Repository ansible/awx, pull requests merged in 2018-06, with the labels that each got.

#1953 Let create_oauth2_token print errors from std_err.
  awx/main/management/commands/create_oauth2_token.py
  awx/main/tests/functional/commands/test_oauth2_token_create.py
Labels: component:api, state:needs_review

#1994 Update INSTALL.md
  INSTALL.md
Labels: component:api, component:installer, component:ui, state:needs_triage, type:enhancement

#1876 Enable source variables for Azure inventory
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
  awx/ui/client/src/inventories-hosts/inventories/related/sources/add/sources-add.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
Labels: component:api, component:ui, state:needs_review, type:enhancement

#2014 Fix issue with table of contents(CONTRIBUTING.md)
  CONTRIBUTING.md
Labels: component:docs, state:needs_triage

#1629 Updates to callback scripts
  tools/scripts/request_tower_configuration.ps1
  tools/scripts/request_tower_configuration.sh
Labels: component:installer, state:needs_triage, type:enhancement
