Repository ansible/awx, pull requests merged in 2018-09, with the labels that each got.

#2113 Upgrade Node and NPM to LTS
  INSTALL.md
  awx/ui/package-lock.json
  awx/ui/package.json
  installer/roles/image_build/files/Dockerfile.sdist
  tools/docker-compose/Dockerfile
Labels: component:ui, state:needs_triage, type:enhancement

#2197 CONTRIBUTING.md: Fixing ToC indendation and wrong links
  CONTRIBUTING.md
Labels: component:docs, state:needs_triage

#2298 properly support deprecated `Authorization: Token xyz`
  awx/main/middleware.py
  awx/main/tests/functional/api/test_oauth.py
Labels: state:needs_triage

#2302 create_preload_data: log no-op operation, remove unnecessary credential
  awx/main/management/commands/create_preload_data.py
Labels: component:api, state:needs_triage, type:enhancement
