Repository ansible/awx, pull requests merged in 2018-11, with the labels that each got.

#2566 Bump version to 2.0.2
  VERSION
Labels: mergeit

#2569 Bump version to 2.1.0
  VERSION
Labels: mergeit

#2571 Merge remote-tracking branch 'release_3.3.1' into devel
  Makefile
  awx/api/views/__init__.py
  awx/conf/migrations/0006_v331_ldap_group_type.py
  awx/conf/migrations/_ldap_group_type.py
  awx/main/management/commands/cleanup_facts.py
  awx/main/queue.py
  awx/ui/client/src/instance-groups/instances/instances.controller.js
  awx/ui/client/src/scheduler/schedulerEdit.controller.js
  awx/ui/client/src/shared/paginate/paginate.controller.js
  awx/ui/client/src/templates/main.js
  tools/sosreport/tower.py
Labels: mergeit

#2547 Get rid of decorator dependency
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit, state:needs_triage

#2577 Fix bug where grandparent groups were excluded
  awx/main/models/inventory.py
  awx/main/tests/functional/models/test_inventory.py
Labels: mergeit

#2550 Add support for runner_on_start
  awx/lib/awx_display_callback/module.py
Labels: mergeit, state:needs_triage

#2543 Using new Helm parameters for PostgreSQL access.
  installer/roles/kubernetes/tasks/main.yml
Labels: component:installer, mergeit, state:needs_triage, type:bug

#2587 remove admin and member roles from team->organizations role assignment options
  awx/ui/client/src/access/add-rbac-user-team/rbac-user-team.controller.js
Labels: component:ui, mergeit

#1894 Remove unused project field
  awx/api/serializers.py
  awx/main/migrations/0052_v340_remove_project_scm_delete_on_next_update.py
  awx/main/models/projects.py
Labels: component:api, mergeit

#2457 dont render blank output lines for some event types + adjust line wrapping
  awx/ui/client/features/output/_index.less
  awx/ui/client/features/output/index.controller.js
  awx/ui/client/features/output/render.service.js
  awx/ui/client/features/output/slide.service.js
Labels: component:ui, mergeit, type:bug

#2595 move from GCE_PEM_FILE_PATH to GCE_CREDENTIALS_FILE_PATH
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: mergeit, state:needs_triage

#2596 fix permission issue with regular user jt admins
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.partial.html
  awx/ui/client/src/access/rbac-multiselect/permissionsUsers.list.js
  awx/ui/client/src/access/rbac-multiselect/rbac-multiselect-list.directive.js
Labels: mergeit

#2605 remove admin and member roles from organization->team permissions
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.controller.js
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.partial.html
Labels: component:ui, mergeit, type:bug

#2618 send activity stream changes as raw JSON, not a JSON-ified string
  awx/main/utils/formatters.py
Labels: mergeit

#2591 Implement deprecation of duplicated ask_ fields in job view
  awx/api/serializers.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#2620 Update saml.md
  docs/auth/saml.md
Labels: mergeit

#2623 properly validate cert data that happens to contain an END substring
  awx/main/tests/functional/api/test_settings.py
  awx/main/validators.py
Labels: mergeit

#2624 Implements workflow convergence without proper layout
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/templates/workflows/workflow.service.js
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
Labels: state:needs_triage

#2583 Do not block superusers with MANAGE_ORGANIZATION_AUTH setting
  awx/main/access.py
  awx/main/tests/functional/test_rbac_user.py
Labels: component:api, mergeit, state:needs_review, type:bug

#2627 fix project and adhoc command form lookups when many credential types exist
  awx/ui/client/src/inventories-hosts/inventories/adhoc/adhoc.controller.js
  awx/ui/client/src/inventories-hosts/inventories/adhoc/adhoc.route.js
  awx/ui/client/src/projects/add/projects-add.controller.js
  awx/ui/client/src/projects/edit/projects-edit.controller.js
  awx/ui/client/src/projects/main.js
Labels: component:ui, mergeit, type:bug

#2625 update to latest vmware_inventory.py support for groupby_custom_field_excludes
  awx/plugins/inventory/vmware_inventory.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#2344 organization views
  awx/api/generics.py
  awx/api/views/__init__.py
  awx/api/views/organization.py
Labels: component:api

#2629 Org view ui tests
  awx/ui/test/e2e/commands/findThenClick.js
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-org-permissions.js
Labels: mergeit

#2634 inventory views
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/api/views/mixin.py
Labels: mergeit

#2044 Add command to revoke tokens (https://github.com/ansible/awx/issues/2030)
  awx/main/management/commands/revoke_oauth2_tokens.py
  awx/main/tests/functional/commands/test_oauth2_token_revoke.py
Labels: component:api, mergeit, priority:low, type:enhancement

#2352 [Feature] Allow use of workflows inside of workflows
  awx/api/filters.py
  awx/api/serializers.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/models/test_workflow.py
  awx/ui/client/features/output/_index.less
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/theme/_variables.less
  awx/ui/client/src/bread-crumb/bread-crumb.block.less
  awx/ui/client/src/partials/job-template-details.html
  awx/ui/client/src/shared/generator-helpers.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.block.less
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/workflow-results/workflow-results.block.less
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
  docs/workflow.md
Labels: mergeit, state:needs_review

#2643 Fix DETAILS link in WF viz not working until after job has ran
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
Labels: mergeit

#2645 fix an unbound variable
  awx/main/models/unified_jobs.py
Labels: mergeit

#2639 Update UJT with inv summary field and update schedule base route to include object to be scheduled
  awx/api/serializers.py
  awx/ui/client/src/scheduler/scheduled-jobs.list.js
  awx/ui/client/src/scheduler/schedulerList.controller.js
Labels: mergeit

#2572 Coalesce host and group Activity Stream deletion entries
  awx/main/signals.py
Labels: mergeit, state:needs_revision

#2646 Fix credential kind translation
  awx/ui/client/src/inventories-hosts/inventories/main.js
  awx/ui/client/src/job-submission/job-submission-factories/check-passwords.factory.js
  awx/ui/client/src/job-submission/job-submission.directive.js
  awx/ui/client/src/job-submission/lists/credential/job-sub-cred-list.controller.js
  awx/ui/client/src/shared/credentialTypesLookup.factory.js
  awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
Labels: mergeit

#2656 Fix default Postgresql version to 9.6
  installer/roles/kubernetes/tasks/main.yml
Labels: mergeit

#2662 move root views new file
  awx/api/views/__init__.py
  awx/api/views/root.py
Labels: mergeit

#2663 Get rid of star import in unified_jobs.py
  awx/main/models/unified_jobs.py
Labels: mergeit

#2669 Updated JT project-related error message
  awx/api/serializers.py
  awx/main/models/jobs.py
Labels: mergeit

#2671 Fix tooltip referring to PROJECTS_ROOT.
  awx/ui/client/src/projects/projects.form.js
Labels: mergeit

#2682 include M2M labels and credentials in Job creation activity stream
  awx/main/models/unified_jobs.py
  awx/main/signals.py
Labels: mergeit

#2690 truncate user first/last name if it exceeds 30 chars on LDAP auth
  awx/sso/backends.py
Labels: mergeit

#2686 Add task manager rescheduling hooks, de-duplication, lifecycle tests
  awx/api/views/__init__.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/tasks.py
  awx/main/tasks.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/utils/common.py
Labels: mergeit

#2665 add support for running awx w/ FIPS enabled
  awx/__init__.py
  awx/main/tests/functional/test_credential.py
  awx/main/validators.py
Labels: mergeit

#2696 Pre-delete bulk delete related, fix parallel request conflicts
  awx/api/generics.py
  awx/api/views/__init__.py
Labels: mergeit

#2672 Fix bug with non-sliced JT job spawn
  awx/main/models/jobs.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/models/test_job.py
Labels: mergeit

#2707 prevent the dispatcher from using a nonsensical max_workers value
  awx/main/dispatch/pool.py
Labels: mergeit

#2713 Minor cleanup of task environment vars
  awx/main/tasks.py
  awx/settings/defaults.py
Labels: component:docs, mergeit

#2716 add a user agent for requests to Insights
  awx/api/views/__init__.py
  awx/main/tests/unit/api/test_views.py
  awx/settings/defaults.py
Labels: mergeit

#2717 Add ncclient for use by networking modules.
  docs/licenses/ncclient.txt
  docs/licenses/selectors2.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: mergeit

#2732 Include migration middleware in timings and profiling
  awx/settings/defaults.py
Labels: mergeit

#2730 License check for slicing >1
  awx/api/serializers.py
Labels: mergeit

#2738 don't send activity stream create for unregistered models
  awx/main/models/unified_jobs.py
Labels: mergeit

#2737 Implement deprecation of groups_with_active_failures
  awx/api/serializers.py
Labels: mergeit

#2741 Fix a bug that did not allow project_admin's to create a project.
  awx/main/access.py
  awx/main/dispatch/pool.py
  awx/main/tests/functional/test_rbac_project.py
Labels: mergeit

#2742 fix scroll top
  awx/ui/client/src/app.js
Labels: mergeit

#2743 include survey_spec in activity stream
  awx/api/serializers.py
  awx/main/signals.py
  awx/main/tests/functional/models/test_activity_stream.py
Labels: mergeit

#2342 Workflow level inventory
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0053_v340_workflow_inventory.py
  awx/main/models/jobs.py
  awx/main/models/mixins.py
  awx/main/models/workflow.py
  awx/main/tests/functional/api/test_job_template.py
  awx/main/tests/functional/api/test_schedules.py
  awx/main/tests/functional/test_rbac_workflow.py
  awx/main/tests/unit/models/test_survey_models.py
  awx/main/tests/unit/models/test_workflow_unit.py
  awx/ui/client/features/jobs/routes/inventoryCompletedJobs.route.js
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/features/templates/templatesList.controller.js
  awx/ui/client/features/templates/templatesList.view.html
  awx/ui/client/lib/components/launchTemplateButton/launchTemplateButton.component.js
  awx/ui/client/lib/models/Inventory.js
  awx/ui/client/lib/models/JobTemplate.js
  awx/ui/client/lib/models/WorkflowJobTemplate.js
  awx/ui/client/lib/models/models.strings.js
  awx/ui/client/src/inventories-hosts/inventories/list/host-summary-popover/host-summary-popover.controller.js
  awx/ui/client/src/inventories-hosts/inventories/list/host-summary-popover/host-summary-popover.directive.js
  awx/ui/client/src/scheduler/schedulerAdd.controller.js
  awx/ui/client/src/scheduler/schedulerEdit.controller.js
  awx/ui/client/src/shared/list-generator/list-generator.factory.js
  awx/ui/client/src/shared/stateDefinitions.factory.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/prompt/prompt.controller.js
  awx/ui/client/src/templates/prompt/prompt.partial.html
  awx/ui/client/src/templates/prompt/prompt.service.js
  awx/ui/client/src/templates/prompt/steps/inventory/prompt-inventory.directive.js
  awx/ui/client/src/templates/prompt/steps/inventory/prompt-inventory.partial.html
  awx/ui/client/src/templates/workflows.form.js
  awx/ui/client/src/templates/workflows/add-workflow/workflow-add.controller.js
  awx/ui/client/src/templates/workflows/edit-workflow/workflow-edit.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
  awx/ui/test/e2e/tests/test-org-permissions.js
  awx/ui/test/spec/workflows/workflow-add.controller-test.js
  docs/prompting.md
  docs/workflow.md
Labels: component:api, component:docs, component:ui, mergeit, type:enhancement

#2750 remove the x icon on the session timeout modal (it doesn't work)
  awx/ui/client/legacy/styles/ansible-ui.less
  awx/ui/client/src/login/authenticationServices/timer.factory.js
Labels: mergeit

#2754 Rename schema job to be more clear about its purpose
  CONTRIBUTING.md
  Makefile
  tox.ini
Labels: mergeit

#2703 Fix Organizations TemplateList websockets
  awx/ui/client/features/templates/routes/organizationsTemplatesList.route.js
Labels: mergeit

#2755 Scheduler: Start Date begins 1 day ahead.
  awx/ui/client/src/scheduler/schedulerAdd.controller.js
Labels: mergeit

#2719 Fail job run if project is failed
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
Labels: mergeit

#2764 add dispatcher status to the sosreport
  tools/sosreport/tower.py
Labels: mergeit

#2753 fix instance group lookup in orgs scrolling behavior
  awx/ui/client/src/shared/instance-groups-multiselect/instance-groups.partial.html
  awx/ui/client/src/templates/labels/labelsList.block.less
Labels: mergeit

#2763 Add precheck script.
  awx/ui/package.json
Labels: mergeit

#2772 add package uninstall example to readme
  awx/ui/README.md
Labels: mergeit

#2762 UI WF results relaunch: handle any relaunch errors.
  awx/ui/client/src/workflow-results/workflow-results.service.js
  awx/ui/test/spec/workflow--results/workflow-results.controller-test.js
  awx/ui/test/spec/workflow--results/workflow-results.service-test.js
Labels: mergeit

#2781 fix workflow total jobs header to total nodes
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
Labels: component:ui

#2780 Update README to include saving exact dependencies using npm.
  awx/ui/README.md
Labels: mergeit

#2791 only override django for FIPS in environments where Django is installed
  awx/__init__.py
Labels: mergeit

#2794 Add a note about `—force-with-lease` to contributing documentation.
  CONTRIBUTING.md
Labels: mergeit

#2788 Set fixed container names
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/docker-isolated-override.yml
Labels: mergeit

#2756 Add a message to the resulting login dialog when a user explicitly logs out.
  awx/ui/client/src/login/authenticationServices/authentication.service.js
  awx/ui/client/src/login/loginModal/loginModal.partial.html
Labels: component:ui, mergeit, priority:low, type:enhancement

#2805 raise contrast on a few key page elements to pass WCAG contrast checks
  awx/ui/client/features/output/_index.less
  awx/ui/client/features/output/constants.js
  awx/ui/client/legacy/styles/codemirror.less
  awx/ui/client/lib/components/launchTemplateButton/_index.less
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/panel/_index.less
  awx/ui/client/lib/components/relaunchButton/_index.less
  awx/ui/client/lib/theme/_variables.less
  awx/ui/client/src/instance-groups/instance-group.block.less
  awx/ui/client/src/shared/branding/colors.default.less
Labels: mergeit, state:needs_triage

#2809 fix management job schedule edit link button
  awx/ui/client/src/scheduler/schedulerList.controller.js
Labels: mergeit, state:needs_triage

#2813 Extract latest strings from source code for translations
  awx/locale/django.pot
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/ui/po/ansible-tower-ui.pot
Labels: mergeit

#2389 Workflow convergence
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/migrations/0054_v340_workflow_convergence.py
  awx/main/models/workflow.py
  awx/main/scheduler/dag_simple.py
  awx/main/scheduler/dag_workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/models/test_workflow.py
  awx/main/tests/unit/scheduler/test_dag_simple.py
  awx/main/tests/unit/scheduler/test_dag_workflow.py
  awx/ui/.jshintrc
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/templates.service.js
  awx/ui/client/src/templates/workflows/workflow-chart/main.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.service.js
  awx/ui/client/src/templates/workflows/workflow-controls/workflow-controls.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.block.less
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/templates/workflows/workflow.service.js
  awx/ui/client/src/vendor.js
  awx/ui/client/src/workflow-results/workflow-results.block.less
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
  awx/ui/client/src/workflow-results/workflow-results.route.js
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
  awx/ui/test/spec/workflow--results/workflow-results.controller-test.js
  awx/ui/test/spec/workflows/workflow-maker.controller-test.js
  docs/img/workflow_step0.png
  docs/img/workflow_step1.png
  docs/img/workflow_step2.png
  docs/img/workflow_step3.png
  docs/img/workflow_step4.png
  docs/licenses/ui/dagre.txt
  docs/licenses/ui/graphlib.txt
  docs/workflow.md
Labels: mergeit, state:needs_triage

#2799 don't conditionally hide workflow viz templates list button
  awx/ui/client/features/templates/templatesList.view.html
Labels: mergeit

#2816 update expected color vals of active tab in smoke test
  awx/ui/test/e2e/tests/smoke.js
Labels: mergeit

#2819 mock an HTTP call to fix busted unit tests
  awx/main/tests/unit/api/test_views.py
Labels: component:api, mergeit, type:bug

#2747 Remove MD5 usage and dependency from UI
  awx/ui/.eslintrc.js
  awx/ui/.jshintrc
  awx/ui/README.md
  awx/ui/client/src/app.js
  awx/ui/client/src/shared/form-generator.js
  awx/ui/client/src/templates/job_templates/add-job-template/job-template-add.controller.js
  awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js
  awx/ui/client/src/templates/job_templates/factories/callback-help-init.factory.js
  awx/ui/client/src/templates/job_templates/factories/hash-setup.factory.js
  awx/ui/client/src/templates/job_templates/job-template.form.js
  awx/ui/client/src/templates/job_templates/main.js
  awx/ui/client/src/vendor.js
  awx/ui/package-lock.json
  awx/ui/package.json
  docs/licenses/ui/angular-md5.txt
Labels: component:ui, mergeit, type:enhancement

#2815 fix isolated nodes in the dev environment
  Makefile
  awx/main/expect/.gitignore
  awx/main/expect/authorized_keys
  tools/docker-isolated/Dockerfile
Labels: mergeit, state:needs_triage

#2810 emit job status lifecycle in event replayer
  awx/main/management/commands/replay_job_events.py
  awx/main/tests/unit/commands/test_replay_job_events.py
Labels: mergeit, state:needs_triage

#2821 Clean up unwanted data in activity stream of nodes
  awx/main/models/jobs.py
  awx/main/signals.py
  awx/main/tests/functional/models/test_activity_stream.py
Labels: component:api, mergeit, type:bug

#2807 Do not pass artifacts to non-job nodes
  awx/main/models/workflow.py
  awx/main/tests/functional/models/test_workflow.py
Labels: mergeit, state:needs_test

#2822 Small update to the node order to reflect e2e test workflow changes
  awx/ui/test/e2e/tests/test-templates-list-actions.js
Labels: component:ui, mergeit, state:needs_review, type:bug

#2825 don't reap jobs that aren't running
  awx/main/dispatch/reaper.py
Labels: mergeit, state:needs_triage

#2826 remove the deprecated `awx-manage deprovision_node` command
  awx/main/management/commands/deprovision_instance.py
  awx/main/management/commands/deprovision_node.py
  awx/main/management/commands/register_instance.py
Labels: mergeit, state:needs_triage

#2792 Prohibit relaunching sliced jobs with changed count
  awx/api/views/__init__.py
Labels: mergeit, state:needs_test

#2824 enforce 1 edge between 2 nodes constraint
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_workflow_node.py
Labels: mergeit, state:needs_triage

#2836 add additional DB retry logic to the callback receiver
  awx/main/dispatch/worker/base.py
  awx/main/dispatch/worker/callback.py
  awx/main/dispatch/worker/task.py
Labels: mergeit, state:needs_triage

#2840 resolve a nuanced traceback for JTs that run w/ a failed project
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#2843 Updating e2e tests to match change in order layout
  awx/ui/test/e2e/tests/test-templates-list-actions.js
Labels: component:ui, mergeit, priority:high, state:needs_review, type:bug

#2842 Changes workflow key icon from fa-key to fa-compass
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/workflow-results/workflow-results.partial.html
Labels: component:ui, mergeit, state:needs_triage, type:bug

#2848 Add timeout & slice count to the job field whitelist.
  awx/main/access.py
Labels: mergeit, state:needs_triage

#2849 allow encrypted fields in custom credentials to be empty
  awx/main/models/credential/__init__.py
  awx/main/tests/unit/models/test_credential.py
Labels: mergeit, state:needs_triage
