Repository ansible/awx, pull requests merged in 2018-12, with the labels that each got.

#2846 Fix 3016 missing job events
  awx/ui/client/features/output/stream.service.js
  awx/ui/test/unit/components/index.js
  awx/ui/test/unit/components/stream.unit.js
Labels: component:ui, mergeit, type:bug

#2852 update org cards count when dataset chnages
  awx/ui/client/src/organizations/list/organizations-list.controller.js
Labels: mergeit, state:needs_triage

#2865 point output search doc link to latest
  awx/ui/client/features/output/constants.js
Labels: mergeit, state:needs_triage

#2845 Fix instance group modal selection
  awx/ui/client/src/shared/instance-groups-multiselect/instance-groups-modal/instance-groups-modal.directive.js
Labels: component:ui, mergeit, priority:medium, type:bug

#2869 Do not update project details after sync jobs
  awx/main/models/projects.py
  awx/main/tests/functional/models/test_job.py
  awx/main/tests/functional/models/test_unified_job.py
  docs/clustering.md
Labels: component:api, mergeit, type:bug

#2877 more sane default log handlers
  awx/settings/defaults.py
Labels: mergeit, state:needs_triage

#2873 Show type in related_jobs, link based on type
  awx/api/serializers.py
  awx/main/access.py
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/api/test_job.py
  awx/main/tests/unit/api/serializers/test_job_template_serializers.py
  awx/ui/client/src/smart-status/smart-status.controller.js
Labels: component:api, component:ui, mergeit, type:enhancement

#2880 Fix links to some resources that lack v1 pages
  awx/api/serializers.py
  awx/main/models/__init__.py
  awx/main/models/credential/__init__.py
Labels: component:api, mergeit, type:bug

#2889 Properly POST credentials to workflow nodes
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
Labels: mergeit

#2890 Fixes bug launching jt where first survey question is optional and empty
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.controller.js
Labels: mergeit

#2888 Sanitize username and description in application tokens list
  awx/ui/client/features/applications/list-applications-users.view.html
Labels: component:ui, mergeit, state:needs_triage, type:bug

#2898 Fixes bug where admin/member roles weren't showing up when adding user to org
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.controller.js
Labels: component:ui, mergeit, type:bug

#2907 Bump version to 2.1.2
  VERSION
Labels: mergeit

#2697 stop various async background requests from bumping the session expiry
  awx/main/middleware.py
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/templates/templatesList.controller.js
  awx/ui/client/lib/models/Base.js
  awx/ui/client/src/home/dashboard/graphs/job-status/job-status-graph.service.js
  awx/ui/client/src/home/home.controller.js
Labels: mergeit, state:needs_test

#2919 only allow the task dispatch worker to import and run decorated tasks
  awx/main/dispatch/worker/task.py
  awx/main/tests/functional/test_dispatch.py
Labels: mergeit, state:needs_triage

#2921 tower-cli config: host value needs to be URL
  DATA_MIGRATION.md
Labels: component:docs, mergeit, state:needs_triage

#2924 Catch python error when unable to find user
  awx/settings/local_settings.py.docker_compose
Labels: component:api, mergeit, state:needs_triage, type:bug

#2937 Fixes bug scheduling jt where first survey question is optional
  awx/ui/client/src/templates/prompt/prompt.service.js
Labels: mergeit

#2933 configure an HA policy for openshift/k8s installs
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit, state:needs_triage

#2917 Fx bug where some SJs could not be relaunched
  awx/api/views/__init__.py
Labels: component:api, mergeit, state:needs_test, type:bug

#2938 Updates to workflow node details link
  awx/ui/client/features/output/legacy.route.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.service.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#2947 Fix 'credential' typo.
  awx/locale/django.pot
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/locale/es/LC_MESSAGES/django.po
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/nl/LC_MESSAGES/django.po
  awx/main/models/credential/__init__.py
  awx/ui/client/src/credential-types/credential-types.list.js
  awx/ui/client/src/credentials/factories/become-method-change.factory.js
  awx/ui/client/src/credentials/factories/kind-change.factory.js
  awx/ui/client/src/teams/teams.form.js
  awx/ui/client/src/templates/survey-maker/surveys/init.factory.js
  awx/ui/client/src/templates/workflows.form.js
  awx/ui/client/src/users/users.form.js
  awx/ui/po/ansible-tower-ui.pot
  awx/ui/po/es.po
  awx/ui/po/fr.po
  awx/ui/po/ja.po
  awx/ui/po/nl.po
Labels: mergeit, state:needs_triage

#2801 collect isolated capacity using a cache plugin, not stdout parsing
  awx/main/conf.py
  awx/main/expect/isolated_manager.py
  awx/plugins/isolated/awx_capacity.py
  awx/settings/defaults.py
Labels: mergeit
