Repository ansible/awx, pull requests merged in 2018-02, with the labels that each got.

#1152 Fix UI bugs related to UI Clustering
  awx/ui/client/src/instance-groups/capacity-adjuster/capacity-adjuster.directive.js
  awx/ui/client/src/instance-groups/instances/instance-jobs/instance-jobs.controller.js
  awx/ui/client/src/instance-groups/instances/instance-modal.controller.js
  awx/ui/client/src/instance-groups/instances/instances-list.partial.html
  awx/ui/client/src/instance-groups/instances/instances.controller.js
  awx/ui/client/src/instance-groups/jobs/jobs-list.partial.html
  awx/ui/client/src/instance-groups/jobs/jobs.controller.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.controller.js
  awx/ui/client/src/instance-groups/main.js
Labels: component:ui

#1096 UI support for prompting on job template schedules
  awx/ui/client/features/credentials/add-edit-credentials.view.html
  awx/ui/client/features/templates/list-templates.controller.js
  awx/ui/client/features/templates/list.view.html
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/legacy/styles/forms.less
  awx/ui/client/lib/components/modal/modal.directive.js
  awx/ui/client/lib/components/tabs/group.directive.js
  awx/ui/client/lib/components/tabs/tab.directive.js
  awx/ui/client/lib/models/Job.js
  awx/ui/client/lib/models/JobTemplate.js
  awx/ui/client/lib/models/WorkflowJob.js
  awx/ui/client/lib/models/index.js
  awx/ui/client/lib/services/base-string.service.js
  awx/ui/client/lib/theme/index.less
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-groups-labels/relatedGroupsLabelsList.partial.html
  awx/ui/client/src/job-submission/job-submission.controller.js
  awx/ui/client/src/job-submission/job-submission.partial.html
  awx/ui/client/src/scheduler/factories/add-schedule.factory.js
  awx/ui/client/src/scheduler/factories/edit-schedule.factory.js
  awx/ui/client/src/scheduler/factories/schedule-post.factory.js
  awx/ui/client/src/scheduler/main.js
  awx/ui/client/src/scheduler/schedulerAdd.controller.js
  awx/ui/client/src/scheduler/schedulerEdit.controller.js
  awx/ui/client/src/scheduler/schedulerForm.block.less
  awx/ui/client/src/scheduler/schedulerForm.partial.html
  awx/ui/client/src/shared/instance-groups-multiselect/instance-groups.partial.html
  awx/ui/client/src/shared/list-generator/list-generator.factory.js
  awx/ui/client/src/shared/parse/parse-type-change.factory.js
  awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.partial.html
  awx/ui/client/src/templates/job_templates/multi-credential/multi-credential.block.less
  awx/ui/client/src/templates/job_templates/multi-credential/multi-credential.partial.html
  awx/ui/client/src/templates/labels/labelsList.block.less
  awx/ui/client/src/templates/labels/labelsList.partial.html
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/prompt/main.js
  awx/ui/client/src/templates/prompt/prompt.block.less
  awx/ui/client/src/templates/prompt/prompt.controller.js
  awx/ui/client/src/templates/prompt/prompt.directive.js
  awx/ui/client/src/templates/prompt/prompt.partial.html
  awx/ui/client/src/templates/prompt/prompt.service.js
  awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.controller.js
  awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.directive.js
  awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.partial.html
  awx/ui/client/src/templates/prompt/steps/inventory/prompt-inventory.controller.js
  awx/ui/client/src/templates/prompt/steps/inventory/prompt-inventory.directive.js
  awx/ui/client/src/templates/prompt/steps/inventory/prompt-inventory.partial.html
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.controller.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.directive.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.partial.html
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.controller.js
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.directive.js
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.partial.html
  awx/ui/client/src/templates/prompt/steps/survey/prompt-survey.controller.js
  awx/ui/client/src/templates/prompt/steps/survey/prompt-survey.directive.js
  awx/ui/client/src/templates/prompt/steps/survey/prompt-survey.partial.html
Labels: component:ui

#1189 fix recent multi-vault select breakage
  awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
Labels: component:ui, state:needs_review, type:bug

#1196 adding keybinding FSM
  awx/network_ui/designs/keybindings.png
  awx/network_ui/designs/keybindings.yml
  awx/ui/client/features/networking/_index.less
  awx/ui/client/features/networking/networking.controller.js
  awx/ui/client/features/networking/networking.view.html
  awx/ui/client/src/network-ui/animations.js
  awx/ui/client/src/network-ui/hotkeys.fsm.js
  awx/ui/client/src/network-ui/keybindings.fsm.js
  awx/ui/client/src/network-ui/move.js
  awx/ui/client/src/network-ui/network.ui.controller.js
Labels: component:ui, state:needs_review, type:enhancement

#1211 host edit form, plus saving changes to a device
  awx/ui/client/src/network-ui/network-details/details.block.less
  awx/ui/client/src/network-ui/network-details/details.controller.js
  awx/ui/client/src/network-ui/network-details/details.directive.js
  awx/ui/client/src/network-ui/network-details/details.partial.html
  awx/ui/client/src/network-ui/network-details/main.js
  awx/ui/client/src/network-ui/network-nav/main.js
  awx/ui/client/src/network-ui/network-nav/network.nav.block.less
  awx/ui/client/src/network-ui/network-nav/network.nav.controller.js
  awx/ui/client/src/network-ui/network-nav/network.nav.view.html
  awx/ui/client/src/network-ui/network.ui.app.js
  awx/ui/client/src/network-ui/network.ui.controller.js
  awx/ui/client/src/network-ui/style.less
Labels: component:ui, state:needs_triage, type:enhancement

#1217 Tweak celery-related messages.
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/task_management/test_scheduler.py
Labels: component:api, state:needs_triage, type:bug

#1201 api-backed copy ui
  awx/ui/client/features/templates/list-templates.controller.js
  awx/ui/client/features/templates/list.route.js
  awx/ui/client/features/templates/list.view.html
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/lib/models/Base.js
  awx/ui/client/lib/models/NotificationTemplate.js
  awx/ui/client/lib/models/index.js
  awx/ui/client/lib/services/base-string.service.js
  awx/ui/client/src/credentials/credentials.list.js
  awx/ui/client/src/credentials/list/credentials-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/inventory.list.js
  awx/ui/client/src/inventories-hosts/inventories/list/inventory-list.controller.js
  awx/ui/client/src/inventory-scripts/inventory-scripts.list.js
  awx/ui/client/src/inventory-scripts/list/list.controller.js
  awx/ui/client/src/notifications/notification-templates-list/list.controller.js
  awx/ui/client/src/notifications/notificationTemplates.list.js
  awx/ui/client/src/projects/list/projects-list.controller.js
  awx/ui/client/src/projects/projects.list.js
  awx/ui/client/src/templates/copy-template/template-copy.service.js
  awx/ui/client/src/templates/main.js
  awx/ui/test/e2e/api.js
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-auditor-read-only-forms.js
  awx/ui/test/e2e/tests/test-credentials-list-actions.js
  awx/ui/test/e2e/tests/test-inventories-list-actions.js
  awx/ui/test/e2e/tests/test-inventory-scripts-list-actions.js
  awx/ui/test/e2e/tests/test-notifications-list-actions.js
  awx/ui/test/e2e/tests/test-projects-list-actions.js
  awx/ui/test/e2e/tests/test-templates-copy-delete-warnings.js
  awx/ui/test/e2e/tests/test-templates-list-actions.js
  awx/ui/test/e2e/tests/test-xss.js
  awx/ui/test/unit/index.js
  awx/ui/test/unit/models/base.unit.js
  awx/ui/test/unit/models/index.js
Labels: component:ui, type:enhancement

#1242 adding details panel FSM and updates to keybindings FSM
  awx/network_ui/designs/details_panel.png
  awx/network_ui/designs/details_panel.yml
  awx/network_ui/designs/keybindings.png
  awx/network_ui/designs/keybindings.yml
  awx/network_ui/designs/move.png
  awx/network_ui/designs/move.yml
  awx/ui/client/src/network-ui/details.panel.fsm.js
  awx/ui/client/src/network-ui/host.partial.svg
  awx/ui/client/src/network-ui/keybindings.fsm.js
  awx/ui/client/src/network-ui/models.js
  awx/ui/client/src/network-ui/move.js
  awx/ui/client/src/network-ui/network-details/details.controller.js
  awx/ui/client/src/network-ui/network-nav/network.nav.controller.js
  awx/ui/client/src/network-ui/network.ui.controller.js
  awx/ui/client/src/network-ui/network_ui.partial.svg
  awx/ui/client/src/network-ui/rack.fsm.js
  awx/ui/client/src/network-ui/router.partial.svg
  awx/ui/client/src/network-ui/site.fsm.js
  awx/ui/client/src/network-ui/switch.partial.svg
Labels: component:ui, state:needs_triage, type:enhancement

#1241 six.string_types in mixins.py
  awx/main/models/mixins.py
Labels: component:api, component:installer, component:ui, state:needs_triage, type:enhancement

#1253 Use --export option for ansible-inventory
  awx/main/tasks.py
Labels: state:blocked

#1123 New RBAC Roles
  awx/api/views.py
  awx/main/access.py
  awx/main/migrations/0021_v330_declare_new_rbac_roles.py
  awx/main/migrations/0022_v330_create_new_rbac_roles.py
  awx/main/models/credential/__init__.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/organization.py
  awx/main/models/projects.py
  awx/main/models/rbac.py
  awx/main/models/workflow.py
  awx/main/tests/functional/test_rbac_credential.py
  awx/main/tests/functional/test_rbac_inventory.py
  awx/main/tests/functional/test_rbac_job_templates.py
  awx/main/tests/functional/test_rbac_notifications.py
  awx/main/tests/functional/test_rbac_workflow.py
  awx/main/tests/unit/test_access.py
Labels: component:api, flag:qe, type:enhancement

#1270 Networking
  awx/ui/client/src/network-ui/animations.js
  awx/ui/client/src/network-ui/models.js
  awx/ui/client/src/network-ui/network-nav/network.nav.block.less
  awx/ui/client/src/network-ui/network-nav/network.nav.controller.js
  awx/ui/client/src/network-ui/network-nav/network.nav.view.html
  awx/ui/client/src/network-ui/network.ui.app.js
  awx/ui/client/src/network-ui/network.ui.controller.js
  awx/ui/client/src/network-ui/style.less
  awx/ui/client/src/network-ui/view.js
  awx/ui/client/src/network-ui/zoom-widget/main.js
  awx/ui/client/src/network-ui/zoom-widget/zoom.block.less
  awx/ui/client/src/network-ui/zoom-widget/zoom.directive.js
  awx/ui/client/src/network-ui/zoom-widget/zoom.partial.html
Labels: component:ui, state:needs_triage, type:enhancement

#1116 [bugfix-pem-validation]
  awx/main/tests/data/ssh.py
  awx/main/tests/unit/test_validators.py
  awx/main/validators.py
Labels: component:api, state:needs_review, type:bug

#1298 add import_playbook as a top-level playbook indicator
  awx/main/utils/ansible.py
Labels: component:ui, state:needs_triage, type:bug

#1308 Py3 Syntax Errors: 0700 -> 0x700 and 0600 -> 0x600
  awx/main/models/jobs.py
Labels: state:needs_triage, type:bug

#1307 fix the device partials to show icons while in Process mode
  awx/ui/client/src/network-ui/host.partial.svg
  awx/ui/client/src/network-ui/network_ui.partial.svg
  awx/ui/client/src/network-ui/router.partial.svg
  awx/ui/client/src/network-ui/switch.partial.svg
Labels: component:ui, state:needs_triage, type:bug

#1231 Add support for TZID in schedule rrules
  awx/ui/client/src/scheduler/factories/r-rule-to-api.factory.js
  awx/ui/client/src/scheduler/factories/schedule-post.factory.js
  awx/ui/client/src/scheduler/schedulerAdd.controller.js
  awx/ui/client/src/scheduler/schedulerEdit.controller.js
  awx/ui/client/src/scheduler/schedulerForm.partial.html
Labels: component:ui

#1319 adding functionality for breadcrumb
  awx/ui/client/src/network-ui/models.js
  awx/ui/client/src/network-ui/network-nav/network.nav.block.less
  awx/ui/client/src/network-ui/network-nav/network.nav.controller.js
  awx/ui/client/src/network-ui/network-nav/network.nav.view.html
  awx/ui/client/src/network-ui/network.ui.controller.js
  awx/ui/client/src/network-ui/view.fsm.js
Labels: component:ui, state:needs_triage, type:enhancement

#1070 Allow authenticating with Openshift via a token
  installer/check_vars/tasks/check_openshift.yml
  installer/openshift/tasks/main.yml
Labels: state:needs_revision

#1327 Bump angular-scheduler version to 0.3.2
  awx/ui/package.json
Labels: component:ui

#904 Implement session-based and OAuth 2 authentications
  awx/api/authentication.py
  awx/api/conf.py
  awx/api/fields.py
  awx/api/generics.py
  awx/api/permissions.py
  awx/api/serializers.py
  awx/api/templates/api/api_o_auth_authorization_root_view.md
  awx/api/templates/api/auth_token_view.md
  awx/api/urls/oauth.py
  awx/api/urls/urls.py
  awx/api/urls/user.py
  awx/api/urls/user_oauth.py
  awx/api/views.py
  awx/conf/apps.py
  awx/main/access.py
  awx/main/consumers.py
  awx/main/management/commands/cleanup_authtokens.py
  awx/main/middleware.py
  awx/main/migrations/0024_v330_add_oauth_activity_stream_registrar.py
  awx/main/migrations/0024_v330_create_user_session_membership.py
  awx/main/models/__init__.py
  awx/main/models/activity_stream.py
  awx/main/models/oauth.py
  awx/main/models/organization.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_oauth.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/test_auth_token_limit.py
  awx/main/tests/functional/test_ldap.py
  awx/main/tests/functional/test_rbac_oauth.py
  awx/main/tests/functional/test_session.py
  awx/main/tests/unit/api/test_views.py
  awx/settings/defaults.py
  awx/sso/middleware.py
  awx/sso/views.py
  awx/templates/rest_framework/api.html
  awx/templates/rest_framework/login.html
  awx/ui/build/webpack.watch.js
  awx/ui/client/src/app.js
  awx/ui/client/src/login/authenticationServices/authentication.service.js
  awx/ui/client/src/login/loginModal/loginModal.controller.js
  awx/ui/client/src/rest/restServices.factory.js
  awx/ui/client/src/shared/Utilities.js
  awx/ui/test/e2e/api.js
  docs/auth/oauth.md
  docs/auth/session.md
  docs/img/auth_session_1.png
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, type:enhancement

#1357 Fixed bug preventing users from selecting non-default inventory on job launch
  awx/ui/client/features/templates/list-templates.controller.js
Labels: component:ui

#1361 Put credentials on their own line in the launch preview
  awx/ui/client/src/templates/prompt/prompt.block.less
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.partial.html
Labels: component:ui

#1383 issue a 401 on invalid login
  awx/api/generics.py
  awx/main/tests/functional/api/test_auth.py
Labels: component:api
