Repository ansible/awx, pull requests merged in 2018-05, with the labels that each got.

#1848 Adds data migration docs for upgrades
  docs/DATA_MIGRATION.md
Labels: component:api, component:docs, component:installer, state:needs_triage

#1878 Fix checkout of role requirements.
  awx/playbooks/project_update.yml
Labels: state:needs_triage

#1882 add variables to inventory mentioned in docs
  installer/inventory
  installer/roles/kubernetes/tasks/openshift.yml
Labels: state:needs_triage

#1895 Support for expect ansible module
  requirements/requirements_ansible.in
Labels: component:installer, state:needs_triage, type:enhancement

#1938 Fix bad path in installation doc
  INSTALL.md
Labels: component:api, component:installer, component:ui, state:needs_triage, type:enhancement

#1942 Added an awx-manage command for generating OAuth2 token.
  awx/api/serializers.py
  awx/main/management/commands/create_oauth2_token.py
  awx/main/tests/functional/commands/test_oauth2_token_create.py
Labels: component:api, state:needs_review
