Repository ansible/awx, pull requests merged in 2018-10, with the labels that each got.

#2341 Views breakout
  awx/api/views/__init__.py
  awx/api/views/mixin.py
  awx/main/tests/functional/api/test_fact_versions.py
  awx/main/tests/functional/api/test_fact_view.py
  awx/main/tests/functional/api/test_job.py
Labels: component:api, state:needs_review

#2332 Updates to versioning system.
  .gitignore
  Makefile
  VERSION
  installer/roles/image_build/files/Dockerfile.sdist
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/Dockerfile.j2
  setup.py
Labels: state:needs_triage

#2369 Fix flake8 errors in setup.py
  setup.py
Labels: state:needs_triage

#2368 Fixed typo Ansbile->Ansible
  awx/ui/client/src/inventories-hosts/inventories/adhoc/adhoc.form.js
Labels: component:ui, state:needs_triage, type:bug

#2348 Ensure workflow graph width is 100% of container
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
Labels: component:ui

#2381 trivial: update teardown command
  DATA_MIGRATION.md
Labels: component:docs, component:installer, mergeit

#2363 Validate ANSIBLE_ injectors on save and increase verbosity
  awx/main/constants.py
  awx/main/fields.py
  awx/main/models/credential/__init__.py
  awx/main/tests/functional/api/test_credential_type.py
  awx/main/tests/unit/test_fields.py
Labels: component:api, mergeit, type:enhancement

#2392 Port downstream installer changes
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/tasks/backup.yml
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/restore.yml
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/management-pod.yml.j2
Labels: mergeit

#2391 use latest asgi_amqp version
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#2394 update node requirements in CONTRIBUTING.md to match INSTALL.md
  CONTRIBUTING.md
Labels: mergeit, state:needs_triage

#2393 Run tests in Docker as non-root user
  Makefile
  installer/inventory
  tools/docker-compose/Dockerfile
  tools/docker-compose/start_development.sh
  tools/docker-compose/start_tests.sh
Labels: mergeit

#2396 don't update package lock file by default, update readmes
  Makefile
  awx/ui/README.md
  awx/ui/test/e2e/README.md
Labels: mergeit

#2400 build swagger docs as part of CI
  Makefile
  tools/docker-compose/start_tests.sh
  tox.ini
Labels: mergeit

#2395 Fix fallout from #2392
  installer/inventory
  installer/roles/image_build/files/launch_awx.sh
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#2372 update awx version to 2.0.1
  VERSION
Labels: mergeit

#2125 Purge inventory script requirements from the AWX virtual environment.
  Makefile
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_tower_uninstall.txt
Labels: mergeit

#2410 update Azure inventory script to latest from Ansible
  awx/plugins/inventory/azure_rm.py
Labels: mergeit

#1911 Much more comprehensive validation of survey specs
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_survey_spec.py
  awx/main/tests/unit/api/test_views.py
Labels: mergeit, state:needs_review

#2411 Add serviceName to Kubernetes StatefulSet spec
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit, type:bug

#2281 Always allow resource creation via global list
  awx/api/views/__init__.py
  awx/main/tests/unit/test_views.py
Labels: component:api, mergeit

#2091 force boolean evaluation
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_push/tasks/main.yml
Labels: component:installer, mergeit, type:bug

#2131 Add inventory vars to set docker install hostnames
  installer/inventory
  installer/roles/local_docker/tasks/standalone.yml
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, type:enhancement

#2164 Fix token based openshift logins during installation - fixes #489
  installer/inventory
  installer/roles/kubernetes/tasks/openshift_auth.yml
Labels: component:installer, mergeit, type:bug

#2351 add views for organization permissions and roles
  awx/ui/client/src/access/add-rbac-user-team/rbac-user-team.partial.html
  awx/ui/client/src/organizations/organizations.form.js
Labels: component:ui, flag:qe, mergeit, type:enhancement

#2414 some minor README updates
  README.md
Labels: mergeit, state:needs_triage

#2416 Fix openshift auth broken by undefined vars
  installer/roles/kubernetes/tasks/openshift_auth.yml
Labels: mergeit

#2235 Extracted more variables which a related to rabbitmq/postgresql from tasks to defaults
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/standalone.yml
Labels: mergeit

#1956 allow nginx config extension
  installer/inventory
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/nginx.conf
Labels: component:installer, mergeit, type:enhancement

#2424 update to the latest stable 1.1 django-oauth-toolkit
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
Labels: mergeit, state:needs_triage

#2266 replace the celery-based task queue with a kombu-based implementation
  CONTRIBUTING.md
  INSTALL.md
  Makefile
  awx/__init__.py
  awx/api/views/__init__.py
  awx/api/views/mixin.py
  awx/celery.py
  awx/main/dispatch/__init__.py
  awx/main/dispatch/control.py
  awx/main/dispatch/pool.py
  awx/main/dispatch/publish.py
  awx/main/dispatch/reaper.py
  awx/main/dispatch/worker/__init__.py
  awx/main/dispatch/worker/base.py
  awx/main/dispatch/worker/callback.py
  awx/main/dispatch/worker/task.py
  awx/main/exceptions.py
  awx/main/management/commands/inventory_import.py
  awx/main/management/commands/run_callback_receiver.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/management/commands/watch_celery.py
  awx/main/models/ha.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/tasks.py
  awx/main/tasks.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_unified_job.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/tests/functional/test_dispatch.py
  awx/main/tests/unit/test_task_manager.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_reload.py
  awx/main/utils/autoscale.py
  awx/main/utils/ha.py
  awx/main/utils/reload.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  awx/settings/local_settings.py.example
  awx/settings/production.py
  docs/resource_copy.md
  docs/task_manager_system.md
  docs/tasks.md
  installer/roles/image_build/files/supervisor_task.conf
  installer/roles/image_build/templates/Dockerfile.j2
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_dev.txt
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/docker-compose/Procfile
  tools/docker-compose/haproxy.cfg
  tools/docker-compose/supervisor.conf
Labels: mergeit, state:needs_triage

#2373 Display WF always nodes in conjunction with success and failure
  awx/api/views/__init__.py
  awx/main/tests/functional/models/test_workflow.py
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/templates/workflows/workflow.service.js
  awx/ui/test/e2e/commands/findThenClick.js
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
  docs/workflow.md
Labels: component:ui, mergeit, type:enhancement

#2437 fix a typo on the JT add page that breaks the custom venv field
  awx/ui/client/src/templates/job_templates/job-template.form.js
Labels: mergeit

#2425 fix issue with ldap queries containing unicode
  awx/sso/ldap_group_types.py
Labels: state:needs_triage

#2438 don't attempt to recover special QUIT messages in the worker pool recovery code
  awx/main/dispatch/pool.py
Labels: mergeit, state:needs_triage

#2440 remove over-eager survey choices validation
  awx/api/views/__init__.py
  awx/main/tests/unit/api/test_views.py
Labels: mergeit

#2141 Removes system tracking code from the UI
  awx/ui/client/lib/theme/index.less
  awx/ui/client/src/app.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-hosts/group-nested-hosts-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/list/host-list.controller.js
  awx/ui/client/src/shared/lodash-as-promised.js
  awx/ui/client/src/shared/main.js
  awx/ui/client/src/system-tracking/compare-facts/fact-template.js
  awx/ui/client/src/system-tracking/compare-facts/flat.js
  awx/ui/client/src/system-tracking/compare-facts/main.js
  awx/ui/client/src/system-tracking/compare-facts/nested-helpers.js
  awx/ui/client/src/system-tracking/compare-facts/nested.js
  awx/ui/client/src/system-tracking/data-services/dedupe-versions.js
  awx/ui/client/src/system-tracking/data-services/fact-scan-data.service.js
  awx/ui/client/src/system-tracking/data-services/get-data-for-comparison.factory.js
  awx/ui/client/src/system-tracking/data-services/get-module-options.factory.js
  awx/ui/client/src/system-tracking/data-services/main.js
  awx/ui/client/src/system-tracking/data-services/resolve-empty-versions.factory.js
  awx/ui/client/src/system-tracking/date-picker/date-picker.block.less
  awx/ui/client/src/system-tracking/date-picker/date-picker.directive.js
  awx/ui/client/src/system-tracking/date-picker/date-picker.partial.html
  awx/ui/client/src/system-tracking/date-picker/main.js
  awx/ui/client/src/system-tracking/fact-data-table/fact-data-table.block.less
  awx/ui/client/src/system-tracking/fact-data-table/fact-data-table.directive.js
  awx/ui/client/src/system-tracking/fact-data-table/fact-data-table.partial.html
  awx/ui/client/src/system-tracking/fact-data-table/main.js
  awx/ui/client/src/system-tracking/fact-module-filter.block.less
  awx/ui/client/src/system-tracking/fact-module-pickers.block.less
  awx/ui/client/src/system-tracking/format-facts.js
  awx/ui/client/src/system-tracking/main.js
  awx/ui/client/src/system-tracking/search-date-range.js
  awx/ui/client/src/system-tracking/system-tracking-container.block.less
  awx/ui/client/src/system-tracking/system-tracking.controller.js
  awx/ui/client/src/system-tracking/system-tracking.partial.html
  awx/ui/client/src/system-tracking/system-tracking.route.js
Labels: component:ui, state:needs_triage

#2439 Change openshift vars path.
  INSTALL.md
Labels: mergeit

#2450 don't call rabbitmqctl forget_cluster_node for isolated instances
  awx/main/management/commands/deprovision_instance.py
Labels: mergeit, state:needs_triage

#2451 Force openshift user behavior for uids over 2500
  awx/main/models/inventory.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/test_dispatch.py
  awx/main/tests/unit/models/test_inventory.py
  tools/docker-compose/start_development.sh
  tools/docker-compose/start_tests.sh
Labels: mergeit, state:needs_triage

#2454 allow users to specify BROKER_URL with passwords that contain : and @
  awx/conf/settings.py
  awx/main/tests/functional/api/test_settings.py
Labels: mergeit, state:needs_triage

#2449 silence the noisy error that's printed w/ `awx-manage check_migrations`
  awx/conf/settings.py
Labels: mergeit

#2461 upgrade to the latest kombu + celery
  awx/main/management/commands/run_dispatcher.py
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#2472 use the proper logger for the callback receiver
  awx/main/dispatch/worker/callback.py
Labels: mergeit

#2037 fixes selinux permissions for awx data.
  installer/roles/local_docker/tasks/standalone.yml
Labels: component:installer, mergeit, type:bug

#2456 Update to latest django subminor to pick up assorted fixes.
  awx/wsgi.py
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit, state:needs_triage

#2476 Remove changelog
  docs/CHANGELOG.md
Labels: mergeit

#2432 Added some Doc for FREEipa
  docs/auth/ldap.md
Labels: component:docs, component:ui, mergeit, state:needs_triage

#2431 Added some Doc for ca_trust_dir
  INSTALL.md
  installer/inventory
Labels: component:docs, component:installer, mergeit, state:needs_triage

#2483 added search for visualizer nodes
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
Labels: mergeit

#2455 Update Azure deps in Ansible venv to match Ansible 2.7 requirements.
  requirements/README.md
  requirements/requirements.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
  requirements/requirements_ansible_git.txt
  requirements/requirements_ansible_uninstall.txt
  requirements/requirements_git.txt
Labels: mergeit, state:needs_triage

#2356 Update project list
  awx/ui/client/features/index.js
  awx/ui/client/features/projects/index.controller.js
  awx/ui/client/features/projects/index.js
  awx/ui/client/features/projects/index.view.html
  awx/ui/client/features/projects/projects.strings.js
  awx/ui/client/features/projects/projectsList.controller.js
  awx/ui/client/features/projects/projectsList.view.html
  awx/ui/client/features/projects/routes/projectsList.route.js
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/list/row-item.directive.js
  awx/ui/client/lib/components/list/row-item.partial.html
  awx/ui/client/src/organizations/linkout/controllers/organizations-projects.controller.js
  awx/ui/client/src/projects/add/projects-add.controller.js
  awx/ui/client/src/projects/list/projects-list.controller.js
  awx/ui/client/src/projects/main.js
  awx/ui/client/src/projects/projects.list.js
  awx/ui/client/src/projects/projects.strings.js
  awx/ui/test/e2e/objects/projects.js
  awx/ui/test/e2e/objects/sections/search.js
  awx/ui/test/e2e/tests/test-projects-list-actions.js
  awx/ui/test/e2e/tests/test-xss.js
Labels: mergeit

#2487 fix a bug that breaks job cancellation on single node jobs
  awx/main/dispatch/control.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
Labels: mergeit

#2493 implement simple retries for wayward inventory deletes
  awx/main/tasks.py
Labels: mergeit

#2492 fix to search for exact search matches
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
Labels: mergeit

#2520 fix flake8
  awx/api/serializers.py
  awx/main/expect/isolated_manager.py
  awx/main/expect/run.py
  awx/main/fields.py
  awx/main/models/schedules.py
  awx/main/tests/docs/test_swagger_generation.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/filters.py
  awx/main/utils/safe_yaml.py
  awx/plugins/library/scan_services.py
  setup.cfg
Labels: mergeit, state:needs_triage

#2508 Fix permissions when running dev container as non-root user
  Makefile
  tools/docker-compose.yml
  tools/docker-compose/Dockerfile
  tools/docker-compose/bootstrap_development.sh
  tools/docker-compose/nginx.conf
  tools/docker-compose/start_development.sh
  tools/docker-compose/start_tests.sh
Labels: mergeit, state:needs_triage

#2517 Let users disable create_preload_data if it isn't necessary
  installer/inventory
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/tasks/main.yml
Labels: component:installer, mergeit, state:needs_triage, type:enhancement

#2513 Allow UI to filter by type again
  awx/api/metadata.py
Labels: component:api, mergeit, type:bug

#2504 Restore Date Picker field in Scheduler template.
  awx/ui/client/lib/theme/index.less
  awx/ui/client/src/scheduler/schedulerDatePicker.block.less
  awx/ui/client/src/scheduler/schedulerDatePicker.directive.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#2497 Fix server error using 2 creds of same type
  awx/api/views/__init__.py
Labels: mergeit, state:needs_triage

#2522 Decouple workflow link editing from workflow node editing
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.block.less
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/workflow-results/workflow-results.block.less
Labels: component:ui, state:needs_triage, type:enhancement

#2498 Fix bug with relaunching with changed JT
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_unified_job.py
  awx/main/tests/functional/test_rbac_job_templates.py
Labels: mergeit, state:needs_triage

#2523 Update variable names for local Docker daemon installation
  installer/roles/local_docker/tasks/standalone.yml
Labels: component:installer, mergeit, type:bug

#2287 automatically delete project files in entire cluster
  awx/main/models/projects.py
  awx/main/tasks.py
Labels: component:api, mergeit

#2486 Remove .cluster.local from service name for rabbitmq
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: component:installer, mergeit, type:bug

#2485 Pass tiller namespace down to helm task
  installer/roles/kubernetes/tasks/main.yml
Labels: mergeit

#2510 Empties /tmp in awx_web Dockerfile
  installer/roles/image_build/templates/Dockerfile.j2
Labels: component:installer, mergeit, type:enhancement

#2430 Fix installer volume definitions
  installer/roles/local_docker/tasks/standalone.yml
Labels: component:installer, mergeit, type:bug

#2529 Apply docker-compose fix to cluster target too
  tools/docker-compose-cluster.yml
Labels: mergeit

#2239 Do 2-pass cancel for workflow jobs
  awx/main/scheduler/dag_workflow.py
  awx/main/scheduler/task_manager.py
Labels: component:api, mergeit

#2542 fix smoke test
  awx/ui/test/e2e/objects/sections/navigation.js
  awx/ui/test/e2e/tests/smoke.js
Labels: mergeit, state:needs_triage

#2544 2340 wf linking
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/main.js
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.block.less
  awx/ui/client/src/templates/workflows/workflow-chart/workflow-chart.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-link-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.partial.html
  awx/ui/client/src/templates/workflows/workflow-maker/main.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.block.less
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
  awx/ui/client/src/workflow-results/workflow-results.block.less
Labels: state:needs_triage

#2548 Re-add markdown, which is used for rendering API help.
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#2555 remove an old, unused migration file
  awx/main/migrations/_old_access.py
Labels: mergeit, state:needs_triage

#2174 Implement Job Template Sharding/Splitting/Slicing
  .gitignore
  awx/api/serializers.py
  awx/api/templates/api/inventory_script_view.md
  awx/api/urls/job_template.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0051_v340_job_slicing.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/projects.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_job.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/models/test_job.py
  awx/main/tests/functional/models/test_unified_job.py
  awx/main/tests/functional/test_rbac_job_start.py
  awx/main/tests/unit/test_tasks.py
  awx/ui/client/features/jobs/index.js
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/jobs/jobsList.view.html
  awx/ui/client/features/jobs/routes/jobs.route.js
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/lib/components/launchTemplateButton/launchTemplateButton.component.js
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/list/row-item.directive.js
  awx/ui/client/lib/components/list/row-item.partial.html
  awx/ui/client/src/templates/job_templates/job-template.form.js
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
  awx/ui/test/unit/components/index.js
  awx/ui/test/unit/components/job-details-split-jobs.unit.js
  awx/ui/test/unit/components/jobs-list-split-jobs.unit.js
  docs/job_slicing.md
Labels: component:api, component:ui, mergeit, type:enhancement

#2558 updated fixtures to use proper organization linking
  awx/ui/test/e2e/fixtures.js
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug
