Repository ansible/awx, pull requests merged in 2019-07, with the labels that each got.

#4184 Delete collection tarball when no longer needed
  awx/main/analytics/core.py
Labels: component:api, mergeit, type:bug

#4190 fix a bug that causes LDAP TLS connection flags to not be set properly
  awx/sso/backends.py
Labels: mergeit

#4196 Release 6.0.0
  VERSION
Labels: mergeit

#4200 run formatting check with ci
  Makefile
  awx/ui_next/CONTRIBUTING.md
  awx/ui_next/package.json
Labels: mergeit

#4199 Show notification type in its own column
  awx/ui_next/src/api/mixins/Notifications.mixin.js
  awx/ui_next/src/components/NotificationsList/NotificationListItem.jsx
  awx/ui_next/src/components/NotificationsList/NotificationListItem.test.jsx
  awx/ui_next/src/components/NotificationsList/__snapshots__/NotificationListItem.test.jsx.snap
  awx/ui_next/src/screens/Organization/OrganizationNotifications/OrganizationNotifications.jsx
  awx/ui_next/src/screens/Organization/OrganizationNotifications/OrganizationNotifications.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationNotifications/__snapshots__/OrganizationNotifications.test.jsx.snap
Labels: component:pf, component:ui, mergeit, type:bug

#4175 fix the hashivault v2 lookup
  awx/main/credential_plugins/hashivault.py
Labels: component:api, mergeit, type:bug

#4250 Fix 254 delete last elem list page
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
Labels: component:pf, component:ui, mergeit, type:bug

#4256 allow data: images in our Content Security Policy
  installer/roles/image_build/templates/nginx.conf.j2
  tools/docker-compose/nginx.vh.default.conf
Labels: mergeit

#4252 fix README snippet
  awx/ui_next/README.md
Labels: component:pf, mergeit

#4118 Failing requirements update when scm_type != git
  awx/playbooks/project_update.yml
Labels: component:api, mergeit, state:needs_test, type:bug

#4260 Change to docker_service for compatibility
  installer/roles/local_docker/tasks/compose.yml
Labels: component:installer, mergeit, type:bug

#4276 fix a bug that breaks OPT_X_TLS_REQUIRE_CERT=0 for LDAP authentication
  awx/sso/backends.py
Labels: mergeit

#4277 add inventory name and id to meta vars
  awx/main/models/unified_jobs.py
  awx/main/tests/unit/models/test_unified_job_unit.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, type:enhancement

#4279 Update Content Security Policy to allow websockets
  installer/roles/image_build/templates/nginx.conf.j2
  tools/docker-compose/nginx.vh.default.conf
Labels: component:ui, mergeit, type:bug

#4282 Fix to use "type" as the condition value for Machine credential to cover I18N
  awx/ui/client/lib/models/Credential.js
Labels: component:ui, mergeit, type:bug

#4283 awx/ui: minor fix on Update on Project Update description
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
  awx/ui/po/ansible-tower-ui.pot
  awx/ui/po/es.po
  awx/ui/po/fr.po
  awx/ui/po/ja.po
  awx/ui/po/nl.po
Labels: component:ui, mergeit, type:bug

#4101 Include defined fields from all parent classes of a HybridDictField
  awx/conf/tests/functional/test_api.py
  awx/sso/fields.py
Labels: component:api, mergeit, state:needs_test, type:bug

#4290 specify a ng-csp attribute so Angular doesn't autodetect
  awx/ui/client/index.template.ejs
Labels: mergeit

#4295 Fix #3857. More informative error message for job templates
  awx/ui/client/src/templates/main.js
Labels: component:ui, mergeit, type:bug

#4123 Fix outdated openstacksdk version and add pip-compile helper script
  requirements/README.md
  requirements/requirements.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
  requirements/updater.sh
Labels: component:api, component:installer, component:ui, mergeit, state:needs_test, type:bug

#4263 Add dynamic custom venv setup
  docs/custom_virtualenvs.md
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: component:installer, mergeit, type:enhancement

#4257 Skeleton template add form
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/index.js
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/Templates.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/index.js
  awx/ui_next/src/types.js
Labels: component:pf, mergeit

#4300 get more events on page down or up when needed
  awx/ui/client/features/output/index.controller.js
Labels: mergeit

#4296 Removed forwardslash that was breaking paginated workflow node requests.
  awx/ui/client/src/templates/templates.service.js
Labels: component:ui, mergeit, type:bug

#4259 Removes duplicated GET request in Org.
  awx/ui_next/src/screens/Organization/Organization.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.test.jsx
Labels: component:pf, mergeit, type:bug

#4251 Add Launch Button to Job Template Details
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
Labels: component:pf, component:ui, mergeit

#4201 Add Helper Method in Serializer for get_summary_fields
  awx/api/serializers.py
  awx/ui/client/src/activity-stream/factories/build-anchor.factory.js
Labels: component:api, mergeit, priority:low, state:needs_review, state:needs_test

#4285 related #4274 - added option to verify server certificate with a specific CA
  awx/main/credential_plugins/aim.py
  awx/main/credential_plugins/conjur.py
  awx/main/credential_plugins/hashivault.py
  awx/main/utils/common.py
Labels: component:api, mergeit, type:bug

#4312 Add some minimal sanity checking before running the updater script.
  requirements/updater.sh
Labels: mergeit

#4313 Remove tooltips from host events in output
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/output/render.service.js
Labels: mergeit

#4315 Remove unused migration methods
  awx/main/migrations/_rbac.py
Labels: mergeit

#4320 Insert signed public key in artifact_dir, fix for issue #4139
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#4319 Ignore Azure templating errors
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/azure_rm/files/azure_rm.yml
Labels: mergeit

#4323 fix listed resources in delete tooltip
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.jsx
Labels: component:pf, mergeit

#4070 Upgrade Django to 2.2
  awx/__init__.py
  awx/api/generics.py
  awx/api/permissions.py
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/conf/migrations/0001_initial.py
  awx/main/consumers.py
  awx/main/fields.py
  awx/main/middleware.py
  awx/main/migrations/0001_initial.py
  awx/main/migrations/0002_squashed_v300_release.py
  awx/main/migrations/0003_squashed_v300_v303_updates.py
  awx/main/migrations/0004_squashed_v310_release.py
  awx/main/migrations/0006_v320_release.py
  awx/main/migrations/0008_v320_drop_v1_credential_fields.py
  awx/main/migrations/0014_v330_saved_launchtime_configs.py
  awx/main/migrations/0018_v330_add_additional_stdout_events.py
  awx/main/migrations/0053_v340_workflow_inventory.py
  awx/main/migrations/0067_v350_credential_plugins.py
  awx/main/migrations/_squashed_30.py
  awx/main/models/__init__.py
  awx/main/models/credential/__init__.py
  awx/main/models/events.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/mixins.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/tests/functional/api/test_instance_group.py
  awx/main/tests/functional/commands/test_commands.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_schedule.py
  awx/main/tests/functional/models/test_workflow.py
  awx/main/tests/functional/task_management/test_capacity.py
  awx/main/tests/functional/test_jobs.py
  awx/main/tests/functional/test_rbac_user.py
  awx/main/tests/unit/api/test_generics.py
  awx/main/tests/unit/conftest.py
  awx/main/tests/unit/models/test_events.py
  awx/main/utils/named_url_graph.py
  awx/main/views.py
  awx/sso/backends.py
  awx/sso/middleware.py
  awx/sso/migrations/0001_initial.py
  awx/sso/pipeline.py
  awx/sso/tests/conftest.py
  awx/sso/tests/functional/test_get_or_set_enterprise_user.py
  awx/sso/tests/unit/test_tacacsplus.py
  awx/sso/views.py
  awx/templates/error.html
  awx/templates/rest_framework/login.html
  awx/wsgi.py
  docs/licenses/django-jsonbfield.txt
  docs/licenses/sqlparse.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
  tools/docker-compose/Dockerfile
Labels: component:api, mergeit, type:enhancement

#4304 Add host description to relevant lists
  awx/ui/client/src/inventories-hosts/hosts/host.list.js
  awx/ui/client/src/inventories-hosts/hosts/hosts.partial.html
  awx/ui/client/src/inventories-hosts/hosts/related/groups/hosts-related-groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-groups/group-nested-groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-hosts/group-nested-hosts.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related/nested-groups/host-nested-groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.list.js
  awx/ui/client/src/shared/list-generator/list-generator.factory.js
Labels: component:ui, mergeit, state:needs_review, type:enhancement

#4332 Roll back the dev environment to CentOS 7 and build a newer sqlite3
  tools/docker-compose/Dockerfile
Labels: mergeit

#4333 Added nightwatch stylesheet to e2e
  awx/ui/test/e2e/nightwatchxsl.xsl
Labels: mergeit

#4324 make lookup toolbar fill width of modal
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/screens/Organization/OrganizationNotifications/__snapshots__/OrganizationNotifications.test.jsx.snap
Labels: component:pf, mergeit

#4328 support nested names for hashivault kv v2 secret engine
  awx/main/credential_plugins/hashivault.py
Labels: component:api, mergeit, type:bug

#4337 fix a 500 error for Activity Stream job records w/ a missing JT
  awx/api/serializers.py
Labels: mergeit

#4072 adding additional environment variables for gcp_compute + gcp modules
  awx/main/models/credential/injectors.py
  awx/main/tests/data/inventory/plugins/azure_rm/env.json
  awx/main/tests/data/inventory/plugins/ec2/env.json
  awx/main/tests/data/inventory/plugins/gce/env.json
  awx/main/tests/data/inventory/plugins/gce/files/file_reference
  awx/main/tests/data/inventory/plugins/openstack/files/file_reference
  awx/main/tests/data/inventory/plugins/satellite6/env.json
  awx/main/tests/data/inventory/plugins/tower/env.json
  awx/main/tests/data/inventory/scripts/azure_rm/env.json
  awx/main/tests/data/inventory/scripts/azure_rm/files/file_reference
  awx/main/tests/data/inventory/scripts/cloudforms/env.json
  awx/main/tests/data/inventory/scripts/cloudforms/files/file_reference
  awx/main/tests/data/inventory/scripts/ec2/env.json
  awx/main/tests/data/inventory/scripts/ec2/files/file_reference
  awx/main/tests/data/inventory/scripts/gce/env.json
  awx/main/tests/data/inventory/scripts/gce/files/file_reference
  awx/main/tests/data/inventory/scripts/gce/files/file_reference_0
  awx/main/tests/data/inventory/scripts/openstack/env.json
  awx/main/tests/data/inventory/scripts/openstack/files/file_reference
  awx/main/tests/data/inventory/scripts/rhv/env.json
  awx/main/tests/data/inventory/scripts/rhv/files/file_reference
  awx/main/tests/data/inventory/scripts/satellite6/env.json
  awx/main/tests/data/inventory/scripts/satellite6/files/file_reference
  awx/main/tests/data/inventory/scripts/tower/env.json
  awx/main/tests/data/inventory/scripts/vmware/env.json
  awx/main/tests/data/inventory/scripts/vmware/files/file_reference
  awx/main/tests/functional/test_inventory_source_injectors.py
Labels: component:api, mergeit, type:bug

#4301 Global collections path
  awx/main/tasks.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/settings/defaults.py
  awx/settings/local_settings.py.docker_compose
  docs/collections.md
Labels: mergeit

#4339 Update the `make clean` command to clear out the parallelized sqlite3 files
  Makefile
Labels: mergeit

#4346 Update collections.md
  docs/collections.md
Labels: mergeit

#4314 Addition of inventory value for memcached image, allows for custom im…
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, type:enhancement

#4345 fix reference to undefined prop for auditors
  awx/ui/client/src/configuration/settings.service.js
Labels: component:ui, mergeit, type:bug

#4316 222 job results details
  awx/ui_next/src/api/models/Jobs.js
  awx/ui_next/src/components/Chip/Chip.test.jsx
  awx/ui_next/src/components/Chip/CredentialChip.jsx
  awx/ui_next/src/components/Chip/CredentialChip.test.jsx
  awx/ui_next/src/components/Chip/index.js
  awx/ui_next/src/components/CodeMirrorInput/CodeMirrorInput.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesInput.jsx
  awx/ui_next/src/components/CodeMirrorInput/index.js
  awx/ui_next/src/components/DetailList/Detail.jsx
  awx/ui_next/src/components/DetailList/DetailList.jsx
  awx/ui_next/src/screens/Job/Job.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
  awx/ui_next/src/screens/Job/JobList/JobListItem.jsx
  awx/ui_next/src/screens/Job/JobTypeRedirect.jsx
  awx/ui_next/src/screens/Job/Jobs.jsx
  awx/ui_next/src/screens/Job/constants.js
  awx/ui_next/src/screens/Organization/OrganizationAccess/__snapshots__/OrganizationAccessItem.test.jsx.snap
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/types.js
  awx/ui_next/src/util/strings.js
  awx/ui_next/src/util/strings.test.js
  awx/ui_next/src/util/yaml.js
Labels: component:pf, mergeit, type:enhancement

#4348 Bump VERSION to 6.1.0
  VERSION
Labels: mergeit

#4360 replace the smart inventory membership lock with a new Django 2.2 flag
  awx/main/tasks.py
Labels: mergeit

#4364 Re-create lost data in Azure_rm imports
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/azure_rm/files/azure_rm.yml
Labels: component:api, mergeit, type:bug

#4372 include instance hostnames in metrics endpoint
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
Labels: mergeit

#4124 Webhook Custom HTTP Method + Basic Auth Support
  awx/api/serializers.py
  awx/main/migrations/0082_v360_webhook_http_method.py
  awx/main/models/notifications.py
  awx/main/notifications/webhook_backend.py
  awx/main/tests/factories/fixtures.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/test_notifications.py
  awx/ui/client/src/notifications/add/add.controller.js
  awx/ui/client/src/notifications/edit/edit.controller.js
  awx/ui/client/src/notifications/main.js
  awx/ui/client/src/notifications/notificationTemplates.form.js
  awx/ui/client/src/notifications/shared/type-change.service.js
  docs/notification_system.md
Labels: component:api, component:ui, mergeit, state:needs_test, type:enhancement

#4375 add pending jobs and system level job status to metrics
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_counts.py
  awx/main/tests/functional/analytics/test_metrics.py
Labels: component:api, priority:low

#4374 Update job status comments
  awx/main/models/unified_jobs.py
Labels: component:api, mergeit

#4377 fix a bug which can cause isolated artifact cleanup to fail
  awx/plugins/isolated/awx_isolated_cleanup.py
Labels: mergeit

#4378 don't filter out schedules that have a null `next_run`
  awx/ui/client/src/scheduler/schedules.route.js
Labels: mergeit

#3851 Remove duplicates from IG list
  awx/main/access.py
  awx/main/tests/functional/test_rbac_instance_groups.py
Labels: component:api, mergeit, type:bug

#4388 awx/ui: fixed minor grammar error in Survey form
  awx/ui/client/src/templates/survey-maker/shared/question-definition.form.js
Labels: component:ui, mergeit, type:bug

#4387 Insights translation
  awx/ui/client/src/inventories-hosts/inventories/insights/insights.controller.js
  awx/ui/client/src/inventories-hosts/inventories/insights/insights.partial.html
  awx/ui/client/src/inventories-hosts/inventories/insights/insights.strings.js
  awx/ui/client/src/inventories-hosts/inventories/insights/main.js
Labels: component:ui, mergeit, type:bug

#4393 Add link to organization inventory list
  awx/ui/client/src/organizations/linkout/controllers/organizations-inventories.controller.js
Labels: component:ui, mergeit, state:needs_review, type:bug

#4385 fake it till you make it!
  tools/docker-compose/Dockerfile
Labels: mergeit

#4391 skip events w/ empty stdout when generating stdout downloads
  awx/main/models/unified_jobs.py
Labels: mergeit

#4396 properly set `is_system_auditor` on initial LDAP login
  awx/main/models/__init__.py
Labels: mergeit

#4380 Add description to template and project list view
  awx/ui/client/features/projects/projects.strings.js
  awx/ui/client/features/projects/projectsList.view.html
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/features/templates/templatesList.view.html
Labels: component:ui, mergeit, state:needs_test, type:enhancement

#4311 Update paramiko to a version that can work with any python-gssapi.
  docs/licenses/paramiko-2.4.2.tar.gz
  docs/licenses/paramiko-2.6.0.tar.gz
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, state:needs_test, type:enhancement

#4363 [4362] git version is old and does not work with x509 certificates
  awx/ui/test/e2e/cluster/Dockerfile
  installer/roles/image_build/files/Dockerfile.sdist
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
Labels: component:installer, mergeit, type:bug

#4398 Prevent clicks outside of prompt modal from closing the modal without saving
  awx/ui/client/lib/components/dialog/dialog.component.js
  awx/ui/client/lib/components/modal/modal.directive.js
Labels: component:ui, mergeit, type:bug

#4399 Show notification menu to users with notification_admin team role
  awx/ui/client/lib/components/layout/layout.directive.js
  awx/ui/test/unit/components/layout.unit.js
Labels: component:ui, mergeit, type:bug

#4401 Update docs to reflect field removals
  docs/multi_credential_assignment.md
  docs/prompting.md
Labels: component:api, mergeit, type:bug

#4317 Remove pexpect, etc, from the ansible venv, that's now runner's problem.
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, state:needs_test
