Repository ansible/awx, pull requests merged in 2019-04, with the labels that each got.

#3564 Management jobs don't produce activity stream entries; don't try and show them
  awx/ui/client/src/management-jobs/card/card.route.js
Labels: mergeit, state:in_progress

#3529 fixes inventory update deadlock
  awx/main/management/commands/inventory_import.py
Labels: mergeit, state:needs_triage

#3528 Add auditor and admin params to user e2e
  awx/ui/test/e2e/objects/users.js
  awx/ui/test/e2e/tests/test-users-crud.js
Labels: component:ui, mergeit, type:enhancement

#3575 Add scm_branch while preloading data
  awx/main/management/commands/create_preload_data.py
Labels: component:installer, mergeit, state:needs_triage, type:bug

#3580 fix a py3 compat issue in the insights action plugin
  awx/playbooks/action_plugins/insights.py
Labels: mergeit

#3569 Use inventory source model, as opposed to organization, for update custom virtualenv
  awx/api/serializers.py
  awx/main/migrations/0066_v350_inventorysource_custom_virtualenv.py
  awx/main/models/inventory.py
  awx/ui/client/src/inventories-hosts/inventories/related/sources/add/sources-add.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/add/sources-add.route.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.route.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
Labels: component:api, component:ui, mergeit, type:enhancement

#3579 Revert "Add scm_branch while preloading data"
  awx/main/management/commands/create_preload_data.py
Labels: mergeit, state:needs_triage

#3573 Change default to allow empty groups from custom sources
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#3597 Don't use the `rsa` python lib.
  requirements/requirements_ansible_uninstall.txt
Labels: mergeit, state:needs_triage

#3546 move wf and jt form launch buttons to the left instead of the right
  awx/ui/client/src/templates/job_templates/job-template.form.js
  awx/ui/client/src/templates/workflows.form.js
Labels: mergeit, state:needs_triage

#3574 Wraps launch template buttons
  awx/ui/client/src/templates/prompt/prompt.block.less
Labels: component:ui, mergeit, type:bug

#3601 fix a bug in isolated OpenSSH key syncing
  awx/plugins/isolated/mkfifo.py
Labels: mergeit, state:needs_triage

#3572 add pagination to user e2e
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-pagination.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3586 Set ansible-inventory verbosity for Ansible 2.8
  awx/main/management/commands/inventory_import.py
Labels: component:api, mergeit, type:enhancement

#3594 Job launch keyboard navigation improvements
  awx/ui/client/src/templates/prompt/prompt.controller.js
  awx/ui/client/src/templates/prompt/prompt.partial.html
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.controller.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.directive.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3592 Code Mirror: prevent console errors when CM parses invalid syntax
  awx/ui/client/lib/components/code-mirror/modal/code-mirror-modal.directive.js
Labels: mergeit, state:needs_triage

#3576 Add sort toolbar to template lists
  awx/ui/client/features/templates/routes/organizationsTemplatesList.route.js
  awx/ui/client/features/templates/routes/projectsTemplatesList.route.js
  awx/ui/client/features/templates/routes/templatesList.route.js
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/features/templates/templatesList.controller.js
  awx/ui/client/features/templates/templatesList.view.html
  awx/ui/client/src/organizations/list/organizations-list.controller.js
  awx/ui/client/src/organizations/list/organizations-list.partial.html
Labels: component:ui, mergeit, type:enhancement

#3598 add index for jobevent created
  awx/main/migrations/0068_v350_index_event_created.py
  awx/main/models/events.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3614 Removes Add Organization Admin Button
  awx/ui/client/src/organizations/linkout/controllers/organizations-admins.controller.js
  awx/ui/client/src/organizations/linkout/organizations-linkout.route.js
Labels: component:ui, mergeit

#3603 Fix some docker standalone bits
  INSTALL.md
  installer/inventory
  installer/roles/local_docker/defaults/main.yml
Labels: component:installer, mergeit, state:needs_triage, type:bug

#3501 Upgrade Old Email Timeout Notifications
  awx/main/models/notifications.py
  awx/ui/client/src/notifications/edit/edit.controller.js
Labels: component:api, mergeit, state:needs_test, state:needs_triage, type:bug

#3618 don't show implicit update jobs in dashboard
  awx/api/views/__init__.py
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug

#3545 include tower header to insights on plan fetch
  awx/main/tasks.py
  awx/playbooks/action_plugins/insights.py
  awx/playbooks/project_update.yml
Labels: mergeit, state:needs_triage

#3619 headless option added
  awx/ui/package.json
  awx/ui/test/e2e/nightwatch.conf.js
Labels: component:ui, mergeit

#3626 fix busted CI
  requirements/requirements_dev.txt
  tools/docker-compose/Dockerfile
  tools/docker-isolated/Dockerfile
Labels: mergeit

#3615 add some additional analytics metrics
  awx/main/analytics/collectors.py
Labels: mergeit, state:needs_triage

#3624 update periodic isolated cleanup to match the new paths post-runner
  awx/main/isolated/manager.py
  awx/plugins/isolated/awx_isolated_cleanup.py
  tools/docker-isolated/README.md
Labels: mergeit, state:needs_triage

#3628 Fix Organization User badge linkout
  awx/ui/client/src/organizations/list/organizations-list.controller.js
Labels: component:ui, mergeit, type:bug

#3510 Use Django's own logic to invalidate sessions of users when changing passwords
  awx/api/serializers.py
  awx/main/management/commands/expire_sessions.py
  awx/main/middleware.py
  awx/main/models/organization.py
  awx/main/tests/functional/api/test_user.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3622 Adjust descriptions of RBAC roles for clarity.
  awx/main/models/rbac.py
Labels: mergeit, state:needs_triage

#3608 Prevents replacing encoded quotes while searching against host filter
  awx/ui/client/src/shared/smart-search/queryset.service.js
  awx/ui/client/src/shared/smart-search/smart-search.controller.js
  awx/ui/client/src/shared/smart-search/smart-search.service.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3617 Prevent on/off toggles from getting inadvertently trigged by enter key presses
  awx/ui/client/src/instance-groups/instances/instances-list.partial.html
  awx/ui/client/src/inventories-hosts/hosts/hosts.partial.html
  awx/ui/client/src/job-submission/job-submission.partial.html
  awx/ui/client/src/partials/survey-maker-modal.html
  awx/ui/client/src/shared/form-generator.js
  awx/ui/client/src/shared/generator-helpers.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.partial.html
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3460 Project admin manual SCM Type creation bug fix
  awx/api/views/root.py
  awx/ui/client/src/projects/edit/projects-edit.controller.js
  awx/ui/client/src/projects/factories/get-project-path.factory.js
Labels: component:api, mergeit, state:needs_triage, type:bug

#3632 don't write playbook stdout to sys.stdout (it's duplicated in log files)
  awx/main/isolated/manager.py
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3587 pickup insights system_id from ansible facts
  awx/main/models/jobs.py
Labels: mergeit, state:needs_triage

#3596 Updated IsolatedManager to take a callback that captures the remote command
  awx/main/isolated/manager.py
  awx/main/tasks.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3634 fix a small bug related to failed inventory counts in the dashboard API
  awx/api/views/__init__.py
Labels: mergeit

#3635 fix a typo
  awx/api/views/__init__.py
Labels: mergeit

#3640 Removes failing symlink to /usr/bin/python3 during the image build
  installer/roles/image_build/files/Dockerfile.sdist
  installer/roles/image_build/templates/Dockerfile.j2
Labels: component:installer, mergeit, type:bug

#3633 Avoid slicing if the inventory only has 1 host
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/tests/functional/models/test_job.py
Labels: component:api, mergeit, type:bug

#3643 Backport fix to run cloudforms script in py3
  awx/plugins/inventory/cloudforms.py
Labels: mergeit

#3637 add a unique UUID for identifying an AWX installation
  awx/conf/registry.py
  awx/conf/settings.py
  awx/main/analytics/collectors.py
  awx/main/conf.py
  awx/main/migrations/0069_v350_generate_unique_install_uuid.py
  awx/main/utils/formatters.py
Labels: mergeit, state:needs_triage

#3647 expose CredentialType.namespace in the API
  awx/api/serializers.py
Labels: mergeit, state:needs_triage

#3631 Refresh the page after pendo flag changes to make change effective immediately
  awx/ui/client/src/configuration/forms/settings-form.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3636 Prometheus Metrics
  Makefile
  awx/api/metrics.py
  awx/api/urls/urls.py
  awx/api/views/metrics.py
  awx/api/views/root.py
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_metrics.py
  docs/licenses/prometheus-client.txt
  docs/prometheus.md
  requirements/requirements.in
  requirements/requirements.txt
  tools/prometheus/.gitignore
  tools/prometheus/prometheus.yml
Labels: component:api, mergeit, priority:medium, type:enhancement

#3657 remove COMPONENT NAME from our issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: mergeit, state:needs_triage

#3658 Fix workflow results layout when extra vars has long line
  awx/ui/client/src/workflow-results/workflow-results.block.less
Labels: mergeit, state:needs_triage

#3653 Fix 403 bug using write PAT and view.always_allow_superuser=True
  awx/api/permissions.py
Labels: component:api, mergeit, type:bug

#3620 Add instance_id for gce imported hosts
  awx/main/migrations/0070_v350_gce_instance_id.py
  awx/main/migrations/_inventory_source.py
  awx/main/tests/functional/test_inventory_source_migration.py
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#3645 Add tool tip to Host Event lines.
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/output/render.service.js
Labels: component:ui, mergeit, state:needs_review, type:enhancement

#3663 Fix job output name in websocket service.
  awx/ui/client/src/shared/socket/socket.service.js
Labels: component:ui, mergeit, type:bug

#3659 add prom permissions test
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_metrics.py
Labels: component:api, mergeit

#3629 Fix RBAC bugs with notification attachment
  awx/main/access.py
  awx/main/tests/functional/test_rbac_notifications.py
  awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
  awx/ui/client/src/notifications/notifications.list.js
  awx/ui/client/src/notifications/shared/notification-list-init.factory.js
  awx/ui/client/src/organizations/edit/organizations-edit.controller.js
  awx/ui/client/src/organizations/main.js
  awx/ui/client/src/projects/edit/projects-edit.controller.js
  awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js
  awx/ui/client/src/templates/workflows/edit-workflow/workflow-edit.controller.js
Labels: component:api, mergeit, type:bug

#3661 Remove stdout wrapper classes that moved to runner
  awx/main/tests/unit/utils/test_event_filter.py
  awx/main/utils/common.py
Labels: component:api, mergeit

#3656 Add applications to e2e
  awx/ui/test/e2e/objects/applications.js
  awx/ui/test/e2e/tests/test-applications.js
Labels: component:ui, mergeit, type:enhancement

#3670 Make root/all groups action bar a bit more responsive
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3669 Ensures extra vars are converted to yaml before being passed along to prompt steps
  awx/ui/client/src/templates/prompt/prompt.service.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3671 Fix comment on awx branding inventory var
  installer/inventory
Labels: component:docs, component:installer, mergeit, state:needs_triage

#3672 remove invalid json renderer from metrics endpoint
  awx/api/views/metrics.py
Labels: mergeit, state:needs_triage

#3674 added ws and pending to user e2e
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-websockets.js
Labels: component:ui, mergeit

#3685 pin ansible runner to 1.3.2
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#3675 Check to make sure the activity stream button should be shown after refresh
  awx/ui/client/src/bread-crumb/bread-crumb.directive.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3625 WIP: specify --forks on isolated health check calls
  awx/main/isolated/manager.py
Labels: mergeit, state:needs_triage

#3692 Fixing flake and waits for spinny that don't need to be there.
  awx/ui/test/e2e/tests/test-websockets.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3683 Leverages awPopOverWatch to generate popover dynamically on workflow node templates help
  awx/ui/client/src/partials/job-template-details.html
  awx/ui/client/src/shared/directives.js
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3678 subscribe to updates for scm revision and and instance group for job …
  awx/ui/client/features/output/details.component.js
Labels: mergeit, state:needs_triage

#3698 Adding selenium stability fix and unpinning se images
  awx/ui/test/e2e/cluster/docker-compose.yml
Labels: component:ui, mergeit, priority:medium, type:bug

#3695 Update wording.
  awx/ui/client/src/license/license.partial.html
  awx/ui/conf.py
Labels: mergeit, state:needs_triage

#3694 remove the old callback plugin import paths
  Makefile
  awx/lib/isolated_callbacks/awx_display.py
  awx/lib/isolated_callbacks/minimal.py
  awx/lib/sitecustomize.py
  awx/lib/tests/__init__.py
  awx/lib/tests/pytest.ini
  awx/main/dispatch/worker/callback.py
  awx/main/management/commands/run_callback_receiver.py
  awx/plugins/callback/awx_display.py
  awx/plugins/callback/minimal.py
  tools/docker-compose/unit-tests/docker-compose.yml
Labels: mergeit, state:needs_triage

#3673 add uuids to ping and metrics
  awx/api/views/root.py
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_metrics.py
  awx/settings/development.py
  tools/prometheus/data/lock
  tools/prometheus/data/wal/00000000
Labels: mergeit, state:needs_triage

#3697 Apply critical dependency upgrades
  awx/__init__.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_common.py
  awx/wsgi.py
  docs/licenses/paramiko-2.4.0.tar.gz
  docs/licenses/paramiko-2.4.2.tar.gz
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_ansible.txt
Labels: component:api, type:bug

#3676 fix tag word wrapping for firefox
  awx/ui/client/lib/components/tag/_index.less
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3704 add prometheus data to gitignore
  .gitignore
  tools/prometheus/data/lock
  tools/prometheus/data/wal/00000000
Labels: component:api, mergeit, state:needs_triage, type:bug

#3702 Revert "Merge pull request #3697 from AlanCoding/conservative_upgrades"
  awx/__init__.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_common.py
  awx/wsgi.py
  docs/licenses/paramiko-2.4.0.tar.gz
  docs/licenses/paramiko-2.4.2.tar.gz
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, state:needs_triage, type:bug

#3707 if runner crashes, attempt to record why
  awx/main/isolated/manager.py
  awx/main/tasks.py
  awx/playbooks/check_isolated.yml
Labels: mergeit, state:needs_triage

#3708 add url to prom docs
  docs/prometheus.md
Labels: mergeit, state:needs_triage

#3703 Bumps Bootstrap to 4.3.1
  awx/ui/package-lock.json
  awx/ui/package.json
Labels: component:ui, mergeit, state:needs_triage

#3712 Do not reset capacity of iso nodes when disabled
  awx/main/isolated/manager.py
Labels: component:api, mergeit

#3709 Apply same pip and setuptools to AWX and Ansible venv
  requirements/requirements.txt
Labels: component:api, mergeit, state:needs_triage, type:bug

#3667 remove system tracking
  awx/api/serializers.py
  awx/api/urls/host.py
  awx/api/views/__init__.py
  awx/main/management/commands/cleanup_facts.py
  awx/main/migrations/0071_v350_remove_system_tracking.py
  awx/main/models/__init__.py
  awx/main/models/fact.py
  awx/main/tests/functional/api/test_fact_versions.py
  awx/main/tests/functional/api/test_fact_view.py
  awx/main/tests/functional/api/test_host_detail.py
  awx/main/tests/functional/commands/conftest.py
  awx/main/tests/functional/commands/test_cleanup_facts.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/fact/test_get_host_fact.py
  awx/main/tests/functional/models/fact/test_get_timeline.py
  awx/main/utils/common.py
Labels: mergeit, state:needs_triage

#3720 Fix memcached configuration in local Docker installs
  installer/roles/image_build/files/settings.py
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/templates/credentials.py.j2
Labels: mergeit

#3723 fix a bug that breaks the isolated heartbeat
  awx/main/isolated/manager.py
Labels: mergeit

#2860 Show entry for system auditor associations
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/fields.py
  awx/main/models/__init__.py
  awx/main/models/activity_stream.py
  awx/main/signals.py
  awx/main/tests/functional/models/test_activity_stream.py
  awx/main/utils/common.py
Labels: component:api, mergeit, type:bug

#3721 Use querset special case to let org members see teams
  awx/main/access.py
  awx/main/tests/functional/test_projects.py
  awx/main/tests/functional/test_rbac_team.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3715 properly set ansible_python_interpreter for local task execution
  awx/main/management/commands/create_preload_data.py
  awx/playbooks/project_update.yml
Labels: mergeit, state:needs_triage

#3711 Apply critical dependency upgrades (try 2)
  awx/__init__.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_common.py
  awx/wsgi.py
  docs/licenses/paramiko-2.4.0.tar.gz
  docs/licenses/paramiko-2.4.2.tar.gz
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3729 rename analytics setting
  awx/main/analytics/core.py
  awx/main/analytics/metrics.py
  awx/main/conf.py
  awx/main/tests/functional/analytics/test_core.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-misc.form.js
  awx/ui/client/src/login/authenticationServices/insightsEnablement.service.js
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug

#3728 instantiate dispatcher once per job run
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: mergeit, state:needs_triage

#3549 Validate virtual environment while running a job/inventory update
  awx-dev
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3733 deprecate /api/v2/dashboard in favor of /api/v2/metrics
  awx/api/views/__init__.py
Labels: mergeit

#3734 remove sqlite db, add it to .gitignore
  .gitignore
  awx-dev
Labels: mergeit

#3736 make deprecation warnings at /api/ much more obvious
  awx/templates/rest_framework/base.html
  awx/ui/context_processors.py
Labels: mergeit

#3739 Update jobs portal list actions e2e
  awx/ui/test/e2e/tests/test-jobs-portal-list-actions.js
Labels: component:ui, mergeit, type:enhancement

#3724 prevent flake for user e2e
  awx/ui/test/e2e/commands/waitForSpinny.js
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/objects/applications.js
  awx/ui/test/e2e/settings.js
  awx/ui/test/e2e/tests/test-applications.js
  awx/ui/test/e2e/tests/test-org-permissions.js
  awx/ui/test/e2e/tests/test-pagination.js
  awx/ui/test/e2e/tests/test-users-crud.js
  awx/ui/test/e2e/tests/test-websockets.js
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
  awx/ui/test/e2e/tests/test-xss.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3737 Deprecate a bunch of inventory computed fields.
  awx/main/migrations/0072_v350_deprecate_fields.py
  awx/main/models/inventory.py
Labels: mergeit, state:needs_triage

#3747 add a loud warning about perf regressions to tasks.py
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3730 Adjust the access logic for settings.MANAGE_ORGANIZATION_AUTH = False
  awx/main/access.py
  awx/main/tests/functional/test_rbac_organization.py
  awx/main/tests/functional/test_rbac_role.py
  awx/main/tests/functional/test_rbac_team.py
  awx/main/tests/functional/test_rbac_user.py
Labels: component:api, mergeit, state:needs_review, type:bug

#3748 pin runner to 1.3.3
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#3755 Adding an option to run all the tests without a retry statement
  awx/ui/package.json
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3696 Fix Django 2.0 deprecation warnings
  awx/api/urls/__init__.py
  awx/api/versioning.py
  awx/conf/tests/functional/conftest.py
  awx/main/fields.py
  awx/main/middleware.py
  awx/main/models/credential/__init__.py
  awx/main/models/ha.py
  awx/main/models/organization.py
  awx/main/models/rbac.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/unit/conftest.py
  awx/settings/defaults.py
  awx/sso/conf.py
  awx/sso/views.py
  requirements/requirements_dev.txt
Labels: component:api, mergeit, type:enhancement

#3749 Use common method for openstack OS_CLIENT_CONFIG_FILE injection
  awx/main/models/credential/injectors.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/data/inventory/plugins/openstack/env.json
  awx/main/tests/data/inventory/plugins/openstack/files/OS_CLIENT_CONFIG_FILE
  awx/main/tests/data/inventory/plugins/openstack/files/openstack.yml
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3758 clean up some old dotfiles
  .dput.cf
  .editorconfig
  .mini-dinstall.cf
  .pylintrc
  nodemon.json
Labels: mergeit, state:needs_triage

#3686 [WIP] Disallow deleting controller or isolated instance groups
  awx/api/serializers.py
  awx/main/models/ha.py
  awx/main/tests/functional/api/test_instance_group.py
  awx/ui/client/src/instance-groups/list/instance-groups-list.controller.js
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug

#3754 Simplify gce inventory plugin injector
  awx/main/models/credential/injectors.py
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/gce/env.json
  awx/main/tests/data/inventory/plugins/gce/files/GCE_CREDENTIALS_FILE_PATH
  awx/main/tests/data/inventory/plugins/gce/files/gcp_compute.yml
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3767 document CORS middleware
  docs/cors.md
Labels: mergeit, state:needs_triage

#3766 merge in downstream changes
  awx/api/views/__init__.py
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/tests/data/insights.json
  awx/main/tests/data/insights.py
  awx/main/tests/data/insights_hosts.json
  awx/main/tests/data/insights_remediations.json
  awx/main/tests/functional/analytics/test_metrics.py
  awx/main/tests/functional/api/test_host_insights.py
  awx/main/tests/unit/api/test_views.py
  awx/main/tests/unit/utils/test_insights.py
  awx/main/utils/insights.py
  awx/playbooks/action_plugins/insights.py
  awx/ui/client/src/inventories-hosts/inventories/insights/insights.controller.js
  awx/ui/client/src/inventories-hosts/inventories/insights/plan-filter.js
  awx/ui/client/src/projects/add/projects-add.controller.js
  awx/ui/client/src/projects/edit/projects-edit.controller.js
  awx/ui/client/src/projects/main.js
  awx/ui/test/e2e/commands/logout.js
  awx/ui/test/e2e/e2e-pipeline.groovy
  awx/ui/test/e2e/objects/applications.js
  awx/ui/test/e2e/tests/test-users-crud.js
  awx/ui/test/e2e/tests/test-websockets.js
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
  docs/licenses/azure-mgmt-authorization.txt
  docs/licenses/azure-mgmt-cdn.txt
  docs/licenses/azure-mgmt-cosmosdb.txt
  docs/licenses/azure-mgmt-devtestlabs.txt
  docs/licenses/azure-mgmt-hdinsight.txt
  docs/licenses/azure-mgmt-loganalytics.txt
  docs/licenses/azure-mgmt-redis.txt
  docs/licenses/azure-mgmt-servicebus.txt
  docs/licenses/configparser.txt
  docs/licenses/keyring.txt
  docs/licenses/secretstorage.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
  tools/sosreport/tower.py
Labels: mergeit, state:needs_review

#3664 Cap page_size in pagination urls
  awx/api/pagination.py
  awx/main/tests/functional/api/test_pagination.py
Labels: component:api, mergeit, type:bug

#3740 Sync docker-compose dockerfile with the actual production image build.
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
Labels: mergeit, state:needs_triage
