Repository ansible/awx, pull requests merged in 2019-01, with the labels that each got.

#2942 add docs for task manager node decider
  docs/capacity.md
  docs/task_manager_system.md
Labels: state:needs_triage

#2972 update to the latest asgi-amqp
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api

#2977 Fix typo in ca_trust_dir
  installer/inventory
Labels: component:installer, mergeit, state:needs_triage, type:bug

#2992 Optimize dashboard using Django annotation for sum
  awx/api/views/__init__.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#2993 catch _all_ types of django.db.utils.Error on CTinT key lookups
  awx/conf/settings.py
Labels: mergeit, state:needs_triage

#2956 swap file order so diff of schema makes more sense
  Makefile
Labels: mergeit, state:needs_triage, type:bug

#2996 adds wait time for postgres setup as a variable
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/tasks/main.yml
Labels: component:installer, mergeit, state:needs_triage, type:enhancement

#3007 Updates to logging, specifically for unit tests
  awx/main/models/inventory.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/common.py
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  awx/settings/local_settings.py.example
Labels: mergeit, state:needs_triage

#3012 enforce key order when writing swagger docs JSON
  awx/main/tests/docs/test_swagger_generation.py
Labels: state:needs_triage

#3006 Documentation of E2E test fixtures, etc.
  awx/ui/test/e2e/README.md
  awx/ui/test/e2e/commands/findThenClick.js
  awx/ui/test/e2e/commands/waitForAngular.js
  awx/ui/test/e2e/fixtures.js
Labels: component:docs, component:ui, mergeit

#3014 skip chromium download when using ui-release make target
  .gitignore
  Makefile
Labels: mergeit

#3002 pg_password should be random 10 character alphanumeric string, when p…
  installer/inventory
Labels: component:docs, component:installer, mergeit, state:needs_triage

#3008 Remove deprecated logic & components from inventory import command
  awx/main/management/commands/inventory_import.py
  awx/main/tests/functional/commands/test_inventory_import.py
  awx/plugins/ansible_inventory/backport.py
Labels: mergeit, state:needs_triage, type:enhancement

#3025 add Django CORS middleware
  awx/settings/defaults.py
  docs/licenses/django-cors-headers.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3024 fix a deadlock when Python garbage collects LDAPBackend objects
  awx/sso/backends.py
Labels: mergeit, state:needs_triage

#3027 correct authorization code expiration help-text
  awx/api/conf.py
Labels: mergeit, state:needs_triage

#3030 add robust handling of non-UTF8 when detecting inventory/playbooks
  awx/main/tests/unit/utils/ansible/__init__.py
  awx/main/tests/unit/utils/ansible/inventories/invalid/bad
  awx/main/tests/unit/utils/ansible/inventories/invalid/bad_encoding
  awx/main/tests/unit/utils/ansible/inventories/invalid/empty.txt
  awx/main/tests/unit/utils/ansible/inventories/valid/executable
  awx/main/tests/unit/utils/ansible/inventories/valid/hosts
  awx/main/tests/unit/utils/ansible/inventories/valid/inventory
  awx/main/tests/unit/utils/ansible/playbooks/invalid/bad
  awx/main/tests/unit/utils/ansible/playbooks/invalid/bad_encoding
  awx/main/tests/unit/utils/ansible/playbooks/invalid/empty
  awx/main/tests/unit/utils/ansible/playbooks/invalid/wrong_file_extension
  awx/main/tests/unit/utils/ansible/playbooks/valid/hello_world.yaml
  awx/main/tests/unit/utils/ansible/playbooks/valid/hello_world.yml
  awx/main/tests/unit/utils/ansible/playbooks/valid/hosts.yml
  awx/main/tests/unit/utils/ansible/playbooks/valid/import.yml
  awx/main/tests/unit/utils/ansible/playbooks/valid/include.yml
  awx/main/tests/unit/utils/ansible/playbooks/valid/vault.yml
  awx/main/tests/unit/utils/ansible/test_ansible.py
  awx/main/utils/ansible.py
Labels: state:needs_triage

#3038 Nginx: Specify X-Frame-Options "DENY" header
  installer/roles/image_build/templates/nginx.conf
Labels: component:installer, mergeit, state:needs_triage, type:enhancement

#2959 Add Grafana notification type
  awx/main/migrations/0055_v340_add_grafana_notification.py
  awx/main/models/notifications.py
  awx/main/notifications/grafana_backend.py
  awx/main/tests/unit/notifications/test_grafana.py
  awx/ui/client/src/notifications/add/add.controller.js
  awx/ui/client/src/notifications/edit/edit.controller.js
  awx/ui/client/src/notifications/notificationTemplates.form.js
  awx/ui/client/src/notifications/shared/type-change.service.js
  docs/notification_system.md
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#2895 Allow SCM overwrite vars in the UI
  awx/ui/client/src/inventories-hosts/inventories/related/sources/add/sources-add.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/edit/sources-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
Labels: component:ui, mergeit, type:enhancement

#3021 add input access methods to credentials
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/models/projects.py
  awx/main/tasks.py
  awx/main/tests/functional/test_credential.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, state:needs_review, type:enhancement

#3034 upgrade social-auth-core to v3.0.0
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3039 Use custom virtual environment in inventory updates
  awx/main/management/commands/inventory_import.py
  awx/main/models/inventory.py
  awx/main/tasks.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3042 fix a py3 bug that breaks the SSO complete endpoint
  awx/api/generics.py
  awx/sso/views.py
Labels: mergeit, state:needs_triage

#3044 detect dead DB connections in the dispatcher when reaping jobs
  awx/main/dispatch/pool.py
Labels: mergeit, state:needs_triage

#3046 AWX 3.0.0
  VERSION
Labels: mergeit

#3045 updating package-lock.json
  awx/ui/package-lock.json
  docs/licenses/ui/popper.js.txt
  docs/licenses/ui/timezone-js.txt
Labels: component:ui, state:needs_triage

#2847 Fix host_filter smart search bug when searching by "or" operator
  awx/ui/client/src/shared/smart-search/queryset.service.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3048 Make schema generator handle alternative iso 8601 datetimes
  awx/main/tests/docs/test_swagger_generation.py
Labels: mergeit, state:needs_triage

#3035 E2E tests for websockets (and other things)
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-org-permissions.js
  awx/ui/test/e2e/tests/test-websockets.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3053 resolved the error message for JT Patch
  awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#2899 Copy WFJT created_by to jobs it spawns
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/tests/functional/models/test_unified_job.py
Labels: component:api, mergeit, type:bug

#3051 record the virtualenv used when a job or inventory sync runs
  awx/api/serializers.py
  awx/main/migrations/0056_v350_custom_venv_history.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3057 Expand and Collapse Jobs List
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/jobs/jobsList.view.html
  awx/ui/client/lib/components/index.js
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/list/list-toolbar.directive.js
  awx/ui/client/lib/components/list/list-toolbar.partial.html
  awx/ui/client/lib/components/tag/_index.less
  awx/ui/client/src/templates/labels/labelsList.block.less
Labels: component:ui, mergeit, state:needs_review, type:enhancement

#3052 explicitly handle .inputs in decrypt_field, encrypt_field
  awx/api/generics.py
  awx/main/models/credential/__init__.py
  awx/main/tests/functional/test_credential.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_encryption.py
  awx/main/utils/encryption.py
Labels: component:api, mergeit

#3050 Job timeout in ui
  awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js
  awx/ui/client/src/templates/job_templates/job-template.form.js
Labels: mergeit

#3067 Adds environment to output details for jts and inv syncs
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/output/status.service.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3065 clean up some unnecessary dispatcher reaping code
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
  awx/main/tests/functional/test_dispatch.py
Labels: mergeit, state:needs_triage

#3061 add linked status indicator for scm inventory project updates
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/tests/unit/api/test_views.py
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/output/status.service.js
Labels: component:api, component:ui, mergeit, state:needs_review, type:enhancement

#3070 clean up unnecessary usage of the six library (awx only supports py3)
  awx/__init__.py
  awx/api/generics.py
  awx/api/parsers.py
  awx/api/renderers.py
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/conf/fields.py
  awx/conf/migrations/_reencrypt.py
  awx/conf/serializers.py
  awx/conf/tests/functional/conftest.py
  awx/conf/tests/unit/test_settings.py
  awx/conf/utils.py
  awx/main/access.py
  awx/main/dispatch/worker/task.py
  awx/main/exceptions.py
  awx/main/fields.py
  awx/main/management/commands/cleanup_activitystream.py
  awx/main/management/commands/cleanup_jobs.py
  awx/main/management/commands/list_instances.py
  awx/main/management/commands/register_queue.py
  awx/main/middleware.py
  awx/main/migrations/_inventory_source.py
  awx/main/migrations/_reencrypt.py
  awx/main/migrations/_scan_jobs.py
  awx/main/models/credential/__init__.py
  awx/main/models/events.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/mixins.py
  awx/main/models/projects.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/task_manager.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/factories/tower.py
  awx/main/tests/functional/api/test_fact_view.py
  awx/main/tests/functional/api/test_settings.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/models/test_job.py
  awx/main/tests/functional/models/test_unified_job.py
  awx/main/tests/unit/expect/test_expect.py
  awx/main/tests/unit/test_fields.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_filters.py
  awx/main/tests/unit/utils/test_formatters.py
  awx/main/utils/common.py
  awx/main/utils/encryption.py
  awx/main/utils/filters.py
  awx/main/utils/formatters.py
  awx/main/utils/handlers.py
  awx/main/utils/named_url_graph.py
  awx/main/utils/safe_yaml.py
  awx/settings/defaults.py
  awx/sso/backends.py
  awx/sso/middleware.py
  awx/sso/pipeline.py
  tools/scripts/pk_to_named_url.py
Labels: mergeit

#3076 move awx.main.utils.ansible tests data into the correct location
  awx/main/tests/data/ansible_utils/inventories/invalid/bad
  awx/main/tests/data/ansible_utils/inventories/invalid/bad_encoding
  awx/main/tests/data/ansible_utils/inventories/invalid/empty.txt
  awx/main/tests/data/ansible_utils/inventories/valid/executable
  awx/main/tests/data/ansible_utils/inventories/valid/hosts
  awx/main/tests/data/ansible_utils/inventories/valid/inventory
  awx/main/tests/data/ansible_utils/playbooks/invalid/bad
  awx/main/tests/data/ansible_utils/playbooks/invalid/bad_encoding
  awx/main/tests/data/ansible_utils/playbooks/invalid/empty
  awx/main/tests/data/ansible_utils/playbooks/invalid/wrong_file_extension
  awx/main/tests/data/ansible_utils/playbooks/valid/hello_world.yaml
  awx/main/tests/data/ansible_utils/playbooks/valid/hello_world.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/hosts.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/import.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/include.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/vault.yml
  awx/main/tests/unit/utils/ansible/playbooks/invalid/empty
  awx/main/tests/unit/utils/ansible/test_ansible.py
  awx/main/tests/unit/utils/test_ansible.py
Labels: mergeit

#3071 Fixed incorrect setting item name for SAML Team Attribute Mapping
  docs/auth/saml.md
Labels: mergeit

#3068 Add expand/collapse toolbar for Job Templates list.
  awx/ui/client/features/templates/templatesList.controller.js
  awx/ui/client/features/templates/templatesList.view.html
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/src/smart-status/smart-status.block.less
Labels: mergeit

#3074 Add expand/collapse toolbar to Projects List.
  awx/ui/client/features/projects/projectsList.controller.js
  awx/ui/client/features/projects/projectsList.view.html
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/truncate/_index.less
Labels: mergeit

#3077 Mark strings for translation
  awx/ui/client/features/applications/add-applications.controller.js
  awx/ui/client/features/applications/list-applications.controller.js
  awx/ui/client/features/credentials/legacy.credentials.js
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/users/tokens/users-tokens-add.controller.js
  awx/ui/client/lib/components/components.strings.js
  awx/ui/client/lib/components/layout/side-nav.partial.html
  awx/ui/client/src/access/permissions-list.controller.js
  awx/ui/client/src/access/rbac-role-column/roleList.directive.js
  awx/ui/client/src/configuration/settings.partial.html
  awx/ui/client/src/credential-types/list/list.controller.js
  awx/ui/client/src/credentials/credentials.form.js
  awx/ui/client/src/credentials/list/credentials-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/list/inventory-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/list/source-summary-popover/source-summary-popover.directive.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/list/host-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-groups-labels/relatedGroupsLabelsList.directive.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/smart-inventory/smart-inventory-host-filter/host-filter-modal/host-filter-modal.directive.js
  awx/ui/client/src/inventory-scripts/list/list.controller.js
  awx/ui/client/src/job-submission/job-submission-factories/create-launch-dialog.factory.js
  awx/ui/client/src/management-jobs/scheduler/schedulerForm.partial.html
  awx/ui/client/src/notifications/notificationTemplates.form.js
  awx/ui/client/src/organizations/edit/organizations-edit.controller.js
  awx/ui/client/src/organizations/linkout/controllers/organizations-admins.controller.js
  awx/ui/client/src/organizations/linkout/controllers/organizations-inventories.controller.js
  awx/ui/client/src/organizations/linkout/controllers/organizations-users.controller.js
  awx/ui/client/src/organizations/linkout/organizations-linkout.route.js
  awx/ui/client/src/organizations/organizations.form.js
  awx/ui/client/src/projects/projects.form.js
  awx/ui/client/src/scheduler/factories/delete-schedule.factory.js
  awx/ui/client/src/scheduler/scheduler.strings.js
  awx/ui/client/src/scheduler/schedulerForm.partial.html
  awx/ui/client/src/shared/form-generator.js
  awx/ui/client/src/shared/list-generator/list-generator.factory.js
  awx/ui/client/src/shared/paginate/paginate.partial.html
  awx/ui/client/src/teams/list/teams-list.controller.js
  awx/ui/client/src/teams/teams.form.js
  awx/ui/client/src/templates/labels/labelsList.directive.js
  awx/ui/client/src/templates/prompt/prompt.controller.js
  awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.directive.js
  awx/ui/client/src/templates/survey-maker/shared/question-definition.form.js
  awx/ui/client/src/users/users.form.js
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.route.js
  awx/ui/client/src/workflow-results/workflow-results.service.js
  awx/ui/client/src/workflow-results/workflow-status-bar/workflow-status-bar.directive.js
  awx/ui/client/src/workflow-results/workflow-status-bar/workflow-status-bar.partial.html
  awx/ui/test/spec/workflow--results/workflow-results.service-test.js
Labels: mergeit

#3078 Fixed role download typo in help text
  awx/locale/django.pot
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/main/conf.py
Labels: component:docs, component:ui, mergeit

#3091 Remove error message for regular logout
  awx/ui/client/src/login/loginModal/loginModal.partial.html
Labels: component:ui, mergeit, state:needs_review, type:bug

#3089 Add execution node field to job details panel
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/features/output/output.strings.js
  awx/ui/client/features/output/status.service.js
Labels: component:ui, mergeit, type:enhancement

#3097 sanitize reflected user input on job details page
  awx/ui/client/features/output/details.component.js
Labels: component:ui, mergeit, type:bug

#3109 fix overindent lint failures
  awx/api/metadata.py
  awx/api/views/__init__.py
  awx/main/managers.py
  awx/main/models/rbac.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/task_management/test_rampart_groups.py
  awx/main/tests/functional/test_rbac_oauth.py
Labels: mergeit

#3087 Some sidebar nav fixes.
  awx/ui/client/lib/components/layout/_index.less
  awx/ui/client/lib/components/layout/side-nav.directive.js
Labels: component:ui, mergeit, type:bug

#3101 increase request page size for credential types in launch prompts
  awx/ui/client/src/templates/prompt/prompt.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3086 Fix expanded view not persisting when a user copies a JT/WF.
  awx/ui/client/features/templates/templatesList.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3118 work around a bug in Django that breaks the stdout HTML view in py3
  awx/api/renderers.py
Labels: mergeit
