Repository ansible/awx, pull requests merged in 2019-05, with the labels that each got.

#3791 Make test_tasks.py durable to changing Ansible versions
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3765 Add Task Overview Details to tasks.md
  docs/tasks.md
Labels: component:api, component:docs, mergeit, state:needs_review, state:needs_revision

#3800 Populate event children list via parent_uuid
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3803 remove references to the (now defunct) fact receiver
  awx/main/constants.py
  awx/settings/defaults.py
  awx/settings/production.py
  installer/roles/image_build/files/settings.py
  installer/roles/kubernetes/templates/configmap.yml.j2
  tools/clusterdevel/roles/minishift/templates/configmap.yml.j2
Labels: mergeit, state:needs_triage

#3802 Include playbook as a default search field
  awx/api/filters.py
  awx/api/views/__init__.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3789 Remove job ask_ fields that reference JT
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/models/jobs.py
Labels: component:api, mergeit, type:bug

#3783 Allow relaunching other user jobs with public vars
  awx/main/access.py
  awx/main/tests/functional/api/test_job.py
  awx/main/tests/functional/test_rbac_job.py
  awx/main/tests/unit/test_access.py
Labels: mergeit, state:needs_test

#3801 Copy credential bug - add owner too
  awx/api/generics.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3714 Show only member users for organization
  awx/ui/client/src/organizations/organizations.form.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3815 sosreport plugin improvements
  tools/sosreport/tower.py
Labels: mergeit, type:bug

#3818 merge in downstream changes
  awx/main/credential_plugins/aim.py
  awx/main/credential_plugins/azure_kv.py
  awx/main/credential_plugins/conjur.py
  awx/main/credential_plugins/hashivault.py
  awx/main/fields.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_credential.py
  awx/ui/client/features/applications/applications.strings.js
  awx/ui/client/features/applications/list-applications-users.controller.js
  awx/ui/client/features/applications/list-applications.controller.js
  awx/ui/client/features/credentials/external-test-modal.component.js
  awx/ui/client/features/credentials/input-source-lookup.component.js
  awx/ui/client/features/jobs/jobs.strings.js
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/output/_index.less
  awx/ui/client/features/output/index.controller.js
  awx/ui/client/features/output/render.service.js
  awx/ui/client/features/projects/projects.strings.js
  awx/ui/client/features/projects/projectsList.controller.js
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/features/templates/templatesList.controller.js
  awx/ui/client/features/users/tokens/tokens.strings.js
  awx/ui/client/features/users/tokens/users-tokens-list.controller.js
  awx/ui/client/lib/services/base-string.service.js
  awx/ui/client/src/home/dashboard/graphs/job-status/job-status-graph.directive.js
  awx/ui/client/src/instance-groups/instance-groups.strings.js
  awx/ui/client/src/instance-groups/instances/instance-modal.controller.js
  awx/ui/client/src/instance-groups/instances/instances.controller.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.controller.js
  awx/ui/client/src/templates/prompt/prompt.controller.js
  requirements/requirements.txt
  requirements/requirements_ansible.txt
  tools/scripts/failure-event-handler
Labels: mergeit, state:needs_triage

#3785 Remove unused output_replacements logic
  awx/main/tasks.py
Labels: component:api, mergeit, state:needs_review, type:bug

#3833 properly record Instance.cpu and Instance.memory for isolated nodes
  awx/main/isolated/manager.py
  awx/plugins/isolated/awx_capacity.py
Labels: mergeit, state:needs_triage

#3810 Raise meaningful error when permission denied to copy JT
  awx/api/generics.py
  awx/main/access.py
  awx/main/tests/functional/test_copy.py
Labels: component:api, mergeit, type:bug

#3850 Make the uwsgi autoreloader reload the dispatcher every time
  Makefile
Labels: component:api, mergeit, state:needs_triage, type:bug

#3855 remove honcho in the dev environment (just use foregrounded supervisor)
  Makefile
  docs/websockets.md
  tools/clusterdevel/bootstrap_minishift.sh
  tools/docker-compose/Dockerfile
  tools/docker-compose/Procfile
  tools/docker-compose/start_development.sh
  tools/docker-compose/supervisor.conf
Labels: mergeit, state:needs_triage

#3839 Add "Disable SSL Verification" checkbox to webhook notification
  awx/main/notifications/webhook_backend.py
  awx/main/tests/functional/test_notifications.py
  awx/ui/client/src/notifications/notificationTemplates.form.js
Labels: component:api, component:ui, mergeit, type:enhancement

#3852 Refactor Dockerfiles
  Makefile
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
Labels: mergeit, state:in_progress

#3848 Move outlier gce cache logic to standard place
  awx/main/models/inventory.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit

#3849 Reduce passing around of passwords dictionary
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit

#3858 Remove --squash option from awx-devel-build
  Makefile
Labels: mergeit, state:needs_triage

#3853 Put variable data permission in its own class
  awx/api/permissions.py
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_inventory.py
Labels: component:api, mergeit, type:enhancement

#3863 use make targets for dev supervisor commands
  tools/docker-compose/supervisor.conf
Labels: mergeit

#3864 more verbose list_instance messaging
  awx/main/management/commands/list_instances.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3842 enforce a stable list order when attaching/detaching instance groups
  awx/main/fields.py
  awx/main/migrations/0073_v360_create_instance_group_m2m.py
  awx/main/migrations/0074_v360_migrate_instance_group_relations.py
  awx/main/migrations/0075_v360_remove_old_instance_group_relations.py
  awx/main/migrations/0076_v360_add_new_instance_group_relations.py
  awx/main/models/ha.py
  awx/main/models/inventory.py
  awx/main/models/organization.py
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/api/test_instance_group.py
  awx/main/tests/functional/test_instance_group_ordering.py
  awx/ui/client/src/instance-groups/instance-groups.service.js
  awx/ui/client/src/templates/job_templates/edit-job-template/job-template-edit.controller.js
Labels: component:api, component:ui, mergeit

#3869 Fix bug in dev supervisor reparenting processes
  tools/docker-compose/supervisor.conf
Labels: component:api, mergeit, state:needs_triage, type:bug

#3868 add docstring and test for instance group service
  awx/ui/client/src/instance-groups/instance-groups.service.js
  awx/ui/test/spec/instance-groups/instance-groups.service-test.js
Labels: mergeit

#3870 Ensure that a root user is always present in development environment
  tools/docker-compose.yml
  tools/docker-compose/Dockerfile
  tools/docker-compose/bootstrap_development.sh
  tools/docker-compose/entrypoint.sh
  tools/docker-compose/start_development.sh
Labels: mergeit, state:needs_triage

#3871 merge in downstream changes
  awx/main/middleware.py
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/src/inventories-hosts/hosts/related/groups/hosts-related-groups.list.js
  awx/ui/client/src/shared/smart-search/queryset.service.js
  awx/ui/test/spec/smart-search/queryset.service-test.js
Labels: mergeit, state:needs_triage

#3861 Update/Edit AWX Docs
  docs/clustering.md
  docs/inventory_plugins.md
  docs/notification_system.md
  docs/task_manager_system.md
Labels: mergeit, state:in_progress, state:needs_docs, state:needs_review

#3854 Update Custom Middleware to New Style
  awx/main/middleware.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/sso/middleware.py
  awx/wsgi.py
Labels: component:api, mergeit, state:needs_test, type:bug

#3904 Bump date.
  awx/templates/rest_framework/api.html
  awx/ui/client/lib/components/components.strings.js
  awx/ui/client/src/about/about.partial.html
Labels: mergeit, state:needs_triage

#3882 add the ability to toggle DEBUG logging on dynamically
  awx/conf/settings.py
  awx/main/constants.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/unit/utils/test_filters.py
  awx/main/utils/db.py
  awx/main/utils/filters.py
  awx/main/utils/handlers.py
  awx/settings/defaults.py
Labels: mergeit, state:needs_triage

#3905 Update INSTALL.md
  INSTALL.md
Labels: component:docs, mergeit, state:needs_triage

#3909 Fix styling bug in Sort Dropdown
  awx/ui/client/lib/components/list/_index.less
Labels: component:ui, mergeit, type:bug

#3908 Correct fr translation for Cancel message
  awx/ui/po/fr.po
Labels: component:docs, component:ui, mergeit, state:needs_triage

#3906 Increasing requests-credssp ver to 1.0.2
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: mergeit, state:needs_triage

#3911 rm extra collection error line
  awx/main/analytics/core.py
  awx/main/management/commands/gather_analytics.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3896 collect events based on last ship, not collection
  awx/main/analytics/core.py
Labels: mergeit, state:needs_triage

#3875 reorder migrations to avoid session error
  awx/settings/defaults.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3874 Expose the content type associated with roles for ActivityStream objects in the API
  awx/api/serializers.py
  awx/ui/client/src/activity-stream/factories/build-description.factory.js
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug

#3820 Resolve default ordering warnings from tests
  awx/api/filters.py
  awx/api/generics.py
  awx/api/views/__init__.py
  awx/api/views/organization.py
  awx/main/migrations/0077_v360_add_default_orderings.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/credential/__init__.py
  awx/main/models/ha.py
  awx/main/models/inventory.py
  awx/main/models/notifications.py
  awx/main/models/oauth.py
  awx/main/models/rbac.py
  awx/main/models/unified_jobs.py
Labels: component:api, mergeit, type:bug

#3918 Fix the middleware ordering
  awx/settings/defaults.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3890 Fix Django debug toolbar after its upgrade
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  awx/urls.py
Labels: component:api, mergeit, type:bug

#3910 Avoid unnecessary user get expiring session memberships
  awx/main/models/organization.py
  awx/main/signals.py
Labels: component:api, mergeit

#3913 Dynamically show instance group name in breadcrumb
  awx/ui/client/src/instance-groups/instance-groups.strings.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.controller.js
  awx/ui/client/src/instance-groups/main.js
Labels: component:ui, mergeit, type:bug

#3914 Update the ports for memcache and rabbitmq to be variablized
  installer/roles/image_build/files/launch_awx.sh
  installer/roles/image_build/files/launch_awx_task.sh
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/local_docker/templates/environment.sh.j2
Labels: component:installer, mergeit, type:enhancement

#3931 Update notification radio button styling to match schedule radiobuttons.
  awx/ui/client/src/notifications/notifications.block.less
Labels: mergeit, state:needs_triage

#3856 Cleanup Sessions & Tokens System Jobs
  awx/api/templates/api/_schedule_detail.md
  awx/api/templates/api/system_job_template_launch.md
  awx/main/management/commands/cleanup_activitystream.py
  awx/main/management/commands/cleanup_sessions.py
  awx/main/management/commands/cleanup_tokens.py
  awx/main/migrations/0078_v360_clear_sessions_tokens_jt.py
  awx/main/migrations/_create_system_jobs.py
  awx/main/models/jobs.py
  awx/ui/client/src/management-jobs/card/card.controller.js
Labels: component:api, component:ui, mergeit, state:needs_test, type:enhancement

#3944 Move dynamic log level logic to filter
  awx/main/utils/filters.py
  awx/main/utils/handlers.py
  awx/settings/defaults.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3933 More precise handling of schedule computed fields no-ops
  awx/main/models/schedules.py
  awx/main/models/unified_jobs.py
  awx/main/tasks.py
  awx/main/tests/functional/models/test_schedule.py
Labels: component:api, mergeit, type:bug

#3900 Remove duplicated type methods and old Django logic
  awx/main/models/activity_stream.py
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/utils/test_common.py
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
  awx/main/utils/polymorphic.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3682 General upgrade of dependencies
  docs/licenses/amqp-2.3.2.tar.gz
  docs/licenses/amqp-2.4.2.tar.gz
  docs/licenses/deprecation.txt
  docs/licenses/lockfile.txt
  docs/licenses/ntlm-auth-1.0.6.tar.gz
  docs/licenses/ntlm-auth-1.3.0.tar.gz
  docs/licenses/websocket-client.txt
  docs/licenses/websocket_client-0.47.0.tar.gz
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, type:enhancement

#3865 disabled instance does not mean offline instance
  awx/api/views/__init__.py
  awx/main/models/ha.py
  awx/main/tasks.py
Labels: mergeit, state:needs_test, state:needs_triage

#3804 Apply optimizations via standard methods
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/api/views/root.py
  awx/main/access.py
Labels: component:api, mergeit, type:enhancement

#3941 Set window size globally on e2e
  awx/ui/test/e2e/nightwatch.conf.js
  awx/ui/test/e2e/tests/smoke.js
  awx/ui/test/e2e/tests/test-404-behavior.js
  awx/ui/test/e2e/tests/test-credentials-list-actions.js
  awx/ui/test/e2e/tests/test-credentials-search-sort.js
  awx/ui/test/e2e/tests/test-form-error-handling.js
  awx/ui/test/e2e/tests/test-inventories-list-actions.js
  awx/ui/test/e2e/tests/test-inventory-scripts-list-actions.js
  awx/ui/test/e2e/tests/test-jobs-portal-list-actions.js
  awx/ui/test/e2e/tests/test-launch-jt.js
  awx/ui/test/e2e/tests/test-notifications-list-actions.js
  awx/ui/test/e2e/tests/test-org-permissions.js
  awx/ui/test/e2e/tests/test-pagination.js
  awx/ui/test/e2e/tests/test-projects-list-actions.js
  awx/ui/test/e2e/tests/test-templates-copy-delete-warnings.js
  awx/ui/test/e2e/tests/test-templates-list-actions.js
  awx/ui/test/e2e/tests/test-websockets.js
  awx/ui/test/e2e/tests/test-workflow-visualizer.js
  awx/ui/test/e2e/tests/test-xss.js
Labels: component:ui, mergeit, priority:medium, state:needs_triage, type:enhancement

#3604 Update SSL support for docker-compose install
  INSTALL.md
  installer/inventory
  installer/roles/image_build/templates/nginx.conf.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, state:needs_triage, type:enhancement

#3873 Avoid DNS timeout in non-Docker for Mac installs
  Makefile
  awx/settings/development.py
  tools/docker-compose.yml
Labels: mergeit, state:needs_review

#3928 Use lockf, not flock.
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: mergeit, state:needs_triage

#3925 Restore old use pattern for gce_ modules, update token_uri URL
  awx/main/models/credential/injectors.py
  awx/main/tests/data/inventory/plugins/gce/files/GCE_CREDENTIALS_FILE_PATH
  awx/main/tests/data/inventory/scripts/gce/files/GCE_CREDENTIALS_FILE_PATH
Labels: mergeit, state:needs_test

#3932 Changes to enable tests in k8s
  Makefile
  awx/main/tests/functional/api/test_settings.py
  tools/docker-compose/Dockerfile
  tools/docker-compose/start_tests.sh
  tox.ini
Labels: mergeit, state:needs_triage

#3947 RFC: add the ability to disable RabbitMQ queue durability
  awx/main/conf.py
  awx/main/dispatch/control.py
  awx/main/dispatch/kombu.py
  awx/main/dispatch/publish.py
  awx/main/management/commands/run_callback_receiver.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/queue.py
  awx/settings/defaults.py
  docs/tasks.md
Labels: mergeit, state:needs_triage

#3961 remove implicit grant type for OAuth 2 apps
  awx/api/serializers.py
  awx/api/templates/api/api_o_auth_authorization_root_view.md
  awx/main/migrations/0079_v360_rm_implicit_oauth2_apps.py
  awx/main/models/oauth.py
  awx/main/tests/functional/api/test_oauth.py
  awx/ui/test/e2e/objects/applications.js
  docs/auth/oauth.md
Labels: component:api, component:installer, component:ui, mergeit, state:needs_triage, type:enhancement

#3930 Upgrade our UI packaging for NodeJS 10.
  INSTALL.md
  awx/ui/README.md
  awx/ui/package-lock.json
  awx/ui/package.json
  tools/docker-compose/Dockerfile
Labels: component:installer, component:ui, mergeit, state:needs_triage, type:enhancement

#3921 #3004 Add proxy support to postgresql, memcached and rabbitmq images
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, state:needs_triage, type:bug

#3965 Updates text of tooltip for Forks in JT.
  awx/ui/client/legacy/styles/ansible-ui.less
  awx/ui/client/src/templates/job_templates/job-template.form.js
Labels: component:ui, mergeit, state:needs_triage

#3974 Fix python3 fallout in translations management script
  tools/scripts/manage_translations.py
Labels: mergeit

#3976 openshift: Ensure char in password are not interpreted
  installer/roles/kubernetes/tasks/openshift_auth.yml
Labels: mergeit

#3893 Replace JobOrigin model with ActivityStream.action_node field
  awx/api/serializers.py
  awx/main/migrations/0080_v360_replace_job_origin.py
  awx/main/models/__init__.py
  awx/main/models/activity_stream.py
  awx/main/models/ha.py
  awx/main/tests/functional/models/test_activity_stream.py
Labels: component:api, mergeit, type:enhancement

#3980 Remove some things that are not first-order dependencies from requirements.in
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#3981 add some debug helpers for tests
  awx/ui/test/e2e/README.md
  awx/ui/test/e2e/cluster/docker-compose.debug-override.yml
  awx/ui/test/e2e/cluster/docker-compose.yml
Labels: mergeit
