Repository ansible/awx, pull requests merged in 2019-03, with the labels that each got.

#3340 Add padding to label list tag.
  awx/ui/client/legacy/styles/bootstrap-custom-overrides.less
  awx/ui/client/legacy/styles/forms.less
  awx/ui/client/src/templates/labels/labelsList.block.less
Labels: component:ui, mergeit, type:bug

#3322 Add SSL suport for docker install
  INSTALL.md
  installer/inventory
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/nginx.conf.j2
  installer/roles/local_docker/tasks/standalone.yml
Labels: mergeit

#3357 Fixes bug where jobs list search was lost on socket message
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/jobs/jobsList.view.html
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3356 Add toolbar sort to projects list
  awx/ui/client/features/projects/projects.strings.js
  awx/ui/client/features/projects/projectsList.controller.js
  awx/ui/client/features/projects/projectsList.view.html
  awx/ui/client/lib/components/components.strings.js
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/list/list-toolbar.directive.js
  awx/ui/client/lib/components/list/list-toolbar.partial.html
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3354 404 validation
  awx/ui/test/e2e/tests/test-404-behavior.js
Labels: component:ui, mergeit, type:enhancement

#3372 Update fields.py to Display Correct Error Message When JT Credential Is Not an Integer
  awx/api/fields.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3376 fix save success modal when adding new application
  awx/ui/client/src/shared/Utilities.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3359 Show yaml comments when possible on launch prompt
  awx/ui/client/src/templates/prompt/prompt.service.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.controller.js
  awx/ui/client/src/templates/prompt/steps/preview/prompt-preview.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3373 add template name to launch prompt modal.
  awx/ui/client/lib/components/launchTemplateButton/launchTemplateButton.component.js
  awx/ui/client/src/templates/prompt/prompt.controller.js
Labels: component:ui, mergeit, state:needs_triage

#3363 Fix dashboard dropdowns after bootstrap upgrade
  awx/ui/client/src/home/dashboard/graphs/dashboard-graphs.block.less
  awx/ui/client/src/home/dashboard/graphs/dashboard-graphs.partial.html
  awx/ui/client/src/home/dashboard/graphs/job-status/job-status-graph.directive.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3382 update docs for development environment
  CONTRIBUTING.md
  awx/ui/README.md
Labels: mergeit

#3381 Revert xlib deps
  tools/docker-compose/Dockerfile
Labels: mergeit

#3375 Fix dev environment when running as root on the host
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
Labels: mergeit

#3360 add unsaved workflow changes flow
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.block.less
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.directive.js
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.partial.html
Labels: mergeit, state:needs_triage

#3367 Add toolbar sort to Jobs lists
  awx/ui/client/features/jobs/jobs.strings.js
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/jobs/jobsList.view.html
  awx/ui/client/features/projects/projectsList.controller.js
  awx/ui/client/lib/components/layout/_index.less
  awx/ui/client/lib/components/list/_index.less
  awx/ui/client/lib/components/list/list-toolbar.partial.html
  awx/ui/client/src/shared/paginate/paginate.controller.js
  awx/ui/client/src/shared/paginate/paginate.directive.js
  awx/ui/client/src/shared/smart-search/smart-search.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3386 Update the error message when exceeding the organization hosts limit
  awx/main/access.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3389 add tooltips for fields prompted on launch
  awx/ui/client/features/templates/templates.strings.js
  awx/ui/client/src/templates/prompt/steps/other-prompts/prompt-other-prompts.partial.html
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3391 bwrap: Add /etc/ssh in bind mounted folder
  awx/main/utils/common.py
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3394 Add the ksu, machinectl, and sesu methods to the builtin list of become methods
  awx/main/constants.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3402 add first name and last name to the headers row of the teams users list
  awx/ui/client/src/teams/teams.form.js
Labels: component:ui, mergeit, type:enhancement

#3377 Adds toggle for all/root groups to inventory groups view
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/inventories-hosts/inventories/main.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/edit/groups-edit.route.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.form.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/list/groups-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/list/groups-list.route.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-groups/group-nested-groups-associate.route.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-groups/group-nested-groups-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-hosts/group-nested-hosts-associate.route.js
  awx/ui/client/src/inventories-hosts/inventories/standard-inventory/inventory.form.js
  awx/ui/client/src/shared/form-generator.js
  awx/ui/client/src/shared/list-generator/list-actions.partial.html
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3404 generate Swagger schemas as if view permissions didn't matter
  awx/api/swagger.py
Labels: mergeit, state:needs_triage

#3403 Working out some python3 kinks
  Makefile
  awx/main/tests/unit/utils/test_common.py
  tools/scripts/awx-python
  tools/scripts/failure-event-handler
Labels: mergeit, state:needs_triage

#3410 fix a failing test in the unit-test target used to generate swagger docs
  tools/docker-compose/unit-tests/docker-compose.yml
Labels: mergeit

#3411 fixes broken documentation link
  awx/ui/client/src/shared/smart-search/smart-search.controller.js
Labels: component:ui, mergeit

#3409 typo in inventory
  installer/inventory
Labels: component:docs, component:installer, mergeit, state:needs_triage

#3412 Run computed fields once for bulk delete requests
  awx/api/views/__init__.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3423 Update reference to test playbooks
  awx/ui/test/e2e/tests/smoke.js
  tools/data_generators/rbac_dummy_data_generator.py
Labels: component:api, component:ui, mergeit, state:needs_triage, type:bug

#3417 Fixes issue with inventory group names that are extremely long.
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
Labels: component:ui, mergeit, type:bug

#3420 docker: yum: use https for postgresql pgdg rpm download
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
Labels: mergeit, state:needs_triage

#3408 Add sort toolbar to instance groups list
  awx/ui/client/src/instance-groups/instance-groups.strings.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.controller.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.partial.html
Labels: component:ui, mergeit, type:enhancement

#3401 Add sort toolbar to applications list
  awx/ui/client/features/applications/applications.strings.js
  awx/ui/client/features/applications/list-applications.controller.js
  awx/ui/client/features/applications/list-applications.view.html
  awx/ui/client/features/jobs/jobsList.controller.js
  awx/ui/client/features/projects/projectsList.controller.js
Labels: component:ui, mergeit, type:enhancement

#3370 UI - scroll to top in pagination
  awx/ui/client/src/shared/paginate/paginate.controller.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3425 send callback receiver log lines to the correct logger
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
Labels: mergeit, state:needs_triage

#3222 Add Timeout Feature to Email Notification Template
  awx/main/notifications/email_backend.py
  awx/ui/client/src/notifications/add/add.controller.js
  awx/ui/client/src/notifications/notification-templates-list/list.controller.js
  awx/ui/client/src/notifications/notificationTemplates.form.js
Labels: component:api, component:ui, mergeit, state:needs_review, type:enhancement

#3416 plugins/tower.py: Use urllib.parse rather than urlparse
  awx/plugins/inventory/tower.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3426 propose the change translation in Japanese
  awx/ui/po/ja.po
Labels: component:ui, state:needs_triage, type:bug

#3435 Fix inventory column width issues to make their contents readable
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
Labels: component:ui, mergeit, type:bug

#3439 Make edit to Notification doc
  docs/notification_system.md
Labels: mergeit

#3424 Makes daphne websocket_timeout infinite.
  installer/roles/image_build/files/supervisor.conf
Labels: component:installer, mergeit, state:needs_triage, type:bug

#3441 makes the card for the workflow display taller
  awx/ui/client/src/workflow-results/workflow-results.block.less
Labels: component:ui, mergeit, type:enhancement

#3449 users e2e
  awx/ui/test/e2e/commands/logout.js
  awx/ui/test/e2e/objects/users.js
  awx/ui/test/e2e/tests/test-users-crud.js
Labels: component:ui, mergeit, type:enhancement

#3452 Add originating address for the failed login message
  awx/api/generics.py
Labels: mergeit, state:needs_triage

#3457 Shows the button the add a JT to users with permissions to make JTs.
  awx/ui/client/src/home/dashboard/lists/job-templates/job-templates-list.directive.js
  awx/ui/client/src/home/dashboard/lists/job-templates/job-templates-list.partial.html
Labels: component:ui, state:needs_review

#3455 e2e fixtures and WS
  awx/ui/test/e2e/commands/findThenClick.js
  awx/ui/test/e2e/commands/navigateTo.js
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-websockets.js
Labels: component:ui, mergeit, state:needs_triage, type:enhancement

#3219 update documentation to include kuberentes initContainers
  docs/custom_virtualenvs.md
Labels: component:docs, mergeit, state:needs_triage

#3451 Host/Inventory vars popout (code mirror)
  awx/ui/client/features/output/details.partial.html
  awx/ui/client/lib/components/code-mirror/code-mirror.directive.js
  awx/ui/client/lib/components/code-mirror/code-mirror.partial.html
  awx/ui/client/lib/components/code-mirror/modal/code-mirror-modal.directive.js
  awx/ui/client/lib/components/code-mirror/modal/code-mirror-modal.partial.html
  awx/ui/client/src/inventories-hosts/hosts/edit/host-edit.controller.js
  awx/ui/client/src/inventories-hosts/hosts/host.form.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/edit/host-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.form.js
  awx/ui/client/src/inventories-hosts/inventories/standard-inventory/edit/inventory-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/standard-inventory/inventory.form.js
  awx/ui/client/src/inventories-hosts/shared/ansible-facts/ansible-facts.controller.js
  awx/ui/client/src/inventories-hosts/shared/ansible-facts/ansible-facts.partial.html
  awx/ui/client/src/shared/form-generator.js
  awx/ui/client/src/shared/parse/parse-type-change.factory.js
Labels: component:ui, state:needs_triage, type:enhancement

#3453 Add sort to application tokens list
  awx/ui/client/features/applications/applications.strings.js
  awx/ui/client/features/applications/index.js
  awx/ui/client/features/applications/list-applications-users.controller.js
  awx/ui/client/features/applications/list-applications-users.view.html
Labels: component:ui, mergeit, type:enhancement

#3433 hide rows from lists where adding would be redundant
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.controller.js
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.directive.js
  awx/ui/client/src/access/add-rbac-resource/rbac-resource.partial.html
  awx/ui/client/src/access/rbac-multiselect/permissionsUsers.list.js
  awx/ui/client/src/access/rbac-multiselect/rbac-multiselect-list.directive.js
  awx/ui/client/src/inventories-hosts/shared/associate-groups/associate-groups.controller.js
  awx/ui/client/src/inventories-hosts/shared/associate-hosts/associate-hosts.controller.js
  awx/ui/client/src/organizations/linkout/addUsers/addUsers.controller.js
  awx/ui/client/src/organizations/linkout/organizations-linkout.route.js
  awx/ui/client/src/shared/stateDefinitions.factory.js
Labels: mergeit, state:needs_review, state:needs_test

#3440 Add sort and pagination to instances list
  awx/ui/client/src/instance-groups/instances/instances-list.partial.html
  awx/ui/client/src/instance-groups/instances/instances.controller.js
  awx/ui/client/src/instance-groups/main.js
Labels: component:ui, mergeit, type:enhancement

#3215 Allow empty default values for numerical survey answers.
  awx/api/views/__init__.py
  awx/main/tests/unit/api/test_views.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3466 pin apache-libcloud to a version that doesn't use PyCrypto
  docs/licenses/libcloud.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
  requirements/requirements_ansible_git.txt
Labels: mergeit

#3471 Install supervisor into the dev environment
  tools/docker-compose/Dockerfile
Labels: mergeit

#3041 ansible-runner integration
  Makefile
  awx/lib/awx_display_callback/__init__.py
  awx/lib/awx_display_callback/cleanup.py
  awx/lib/awx_display_callback/display.py
  awx/lib/awx_display_callback/events.py
  awx/lib/awx_display_callback/minimal.py
  awx/lib/awx_display_callback/module.py
  awx/main/expect/isolated_manager.py
  awx/main/management/commands/test_isolated_connection.py
  awx/main/models/credential/__init__.py
  awx/main/models/jobs.py
  awx/main/tasks.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/expect/test_expect.py
  awx/main/tests/unit/models/test_jobs.py
  awx/main/tests/unit/models/test_survey_models.py
  awx/main/tests/unit/test_tasks.py
  awx/playbooks/check_isolated.yml
  awx/playbooks/clean_isolated.yml
  awx/playbooks/run_isolated.yml
  awx/plugins/isolated/awx_capacity.py
  awx/plugins/isolated/awx_isolated_cleanup.py
  awx/settings/defaults.py
  docs/ansible_runner_integration.md
  docs/custom_virtualenvs.md
  docs/licenses/ansible-runner.txt
  docs/licenses/python-daemon.txt
  docs/process_isolation.md
  requirements/requirements.in
  requirements/requirements.txt
  setup.py
  tools/docker-isolated/Dockerfile
  tools/docker-isolated/README.md
  tools/docker-isolated/awx-expect
Labels: mergeit, state:needs_triage

#3459 Provide Default Email Timeout Value
  awx/api/serializers.py
  awx/main/notifications/email_backend.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3482 do not generate a random ident
  awx/main/expect/isolated_manager.py
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3484 Fix python3 offline installs
  Makefile
Labels: mergeit

#3483 Inventory vars popout round 2 (codemirror)
  awx/ui/client/lib/components/code-mirror/code-mirror.directive.js
  awx/ui/client/lib/components/code-mirror/code-mirror.partial.html
  awx/ui/client/src/inventories-hosts/hosts/edit/host-edit.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/add/host-add.controller.js
  awx/ui/client/src/inventories-hosts/inventories/standard-inventory/add/inventory-add.controller.js
  awx/ui/client/src/workflow-results/workflow-results.controller.js
  awx/ui/client/src/workflow-results/workflow-results.partial.html
  awx/ui/test/e2e/tests/smoke.js
Labels: mergeit, state:needs_triage

#3468 Fix 'Groups' list item styling.
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
Labels: component:ui, mergeit, state:needs_triage, type:bug

#3481 Minor post-runner cleanup
  awx/lib/tests/test_display_callback.py
  awx/main/expect/run.py
  awx/main/tasks.py
  awx/main/tests/unit/expect/test_expect.py
  docs/custom_virtualenvs.md
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
  tools/scripts/awx-expect
Labels: mergeit, state:needs_triage

#3447 WFJT Node Activity Stream Bug Fix
  awx/api/serializers.py
  awx/ui/client/src/activity-stream/factories/build-anchor.factory.js
  awx/ui/client/src/activity-stream/factories/build-description.factory.js
Labels: component:api, component:ui, mergeit, type:bug

#3497 remove an errant console.log
  awx/ui/client/src/activity-stream/factories/build-anchor.factory.js
Labels: mergeit

#3458 Add sort to User Tokens list
  awx/ui/client/features/applications/index.js
  awx/ui/client/features/users/tokens/tokens.strings.js
  awx/ui/client/features/users/tokens/users-tokens-list.controller.js
  awx/ui/client/features/users/tokens/users-tokens-list.partial.html
  awx/ui/client/features/users/tokens/users-tokens-list.route.js
Labels: component:ui, mergeit, type:enhancement

#3494 more iso cleanup and bug fixes
  awx/main/expect/isolated_manager.py
  awx/main/tasks.py
  awx/playbooks/run_isolated.yml
  tools/docker-isolated/Dockerfile
Labels: mergeit, state:needs_triage

#3499 update content-type for oauth2 docs
  awx/api/templates/api/api_o_auth_authorization_root_view.md
Labels: component:api, component:docs, mergeit, state:needs_triage

#3500 bwrap/runner: Add /etc/ssh in bind mounted folder
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3266 Transition to inventory plugins
  awx/main/constants.py
  awx/main/management/commands/inventory_import.py
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/data/inventory/plugins/azure_rm/env.json
  awx/main/tests/data/inventory/plugins/azure_rm/files/azure_rm.yml
  awx/main/tests/data/inventory/plugins/ec2/env.json
  awx/main/tests/data/inventory/plugins/ec2/files/aws_ec2.yml
  awx/main/tests/data/inventory/plugins/gce/files/file_reference
  awx/main/tests/data/inventory/plugins/gce/files/gcp_compute.yml
  awx/main/tests/data/inventory/plugins/openstack/files/file_reference
  awx/main/tests/data/inventory/plugins/openstack/files/openstack.yml
  awx/main/tests/data/inventory/plugins/satellite6/env.json
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
  awx/main/tests/data/inventory/plugins/tower/env.json
  awx/main/tests/data/inventory/plugins/tower/files/tower.yml
  awx/main/tests/data/inventory/scripts/azure_rm/env.json
  awx/main/tests/data/inventory/scripts/azure_rm/files/AZURE_INI_PATH
  awx/main/tests/data/inventory/scripts/cloudforms/env.json
  awx/main/tests/data/inventory/scripts/cloudforms/files/CLOUDFORMS_INI_PATH
  awx/main/tests/data/inventory/scripts/cloudforms/files/cache_dir
  awx/main/tests/data/inventory/scripts/ec2/env.json
  awx/main/tests/data/inventory/scripts/ec2/files/EC2_INI_PATH
  awx/main/tests/data/inventory/scripts/ec2/files/cache_dir
  awx/main/tests/data/inventory/scripts/gce/env.json
  awx/main/tests/data/inventory/scripts/gce/files/GCE_CREDENTIALS_FILE_PATH
  awx/main/tests/data/inventory/scripts/gce/files/GCE_INI_PATH
  awx/main/tests/data/inventory/scripts/openstack/env.json
  awx/main/tests/data/inventory/scripts/openstack/files/OS_CLIENT_CONFIG_FILE
  awx/main/tests/data/inventory/scripts/openstack/files/cache_dir
  awx/main/tests/data/inventory/scripts/rhv/env.json
  awx/main/tests/data/inventory/scripts/rhv/files/OVIRT_INI_PATH
  awx/main/tests/data/inventory/scripts/satellite6/env.json
  awx/main/tests/data/inventory/scripts/satellite6/files/FOREMAN_INI_PATH
  awx/main/tests/data/inventory/scripts/tower/env.json
  awx/main/tests/data/inventory/scripts/vmware/env.json
  awx/main/tests/data/inventory/scripts/vmware/files/VMWARE_INI_PATH
  awx/main/tests/functional/commands/test_inventory_import.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/common.py
  awx/plugins/inventory/openstack_inventory.py
  docs/inventory_plugins.md
  docs/licenses/cachetools.txt
  docs/licenses/futures.txt
  docs/licenses/google-auth.txt
  docs/licenses/rsa.txt
  docs/licenses/shade.txt
  requirements/requirements_ansible.in
  requirements/requirements_ansible.txt
Labels: component:api, mergeit, type:enhancement

#3320 Feature: custom virtual environment directories
  awx/conf/fields.py
  awx/conf/tests/unit/test_fields.py
  awx/main/conf.py
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
  awx/settings/defaults.py
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-misc.form.js
  docs/custom_virtualenvs.md
Labels: component:api, component:ui, mergeit, state:needs_triage, type:enhancement

#3280 Set --playbook-dir in calls to ansible-inventory
  awx/main/management/commands/inventory_import.py
Labels: component:api, mergeit, type:bug

#3502 Feat toolbar sort instance modal list
  awx/ui/client/lib/components/list/row-item.directive.js
  awx/ui/client/lib/components/list/row-item.partial.html
  awx/ui/client/src/instance-groups/instances/instance-modal.controller.js
  awx/ui/client/src/instance-groups/instances/instance-modal.partial.html
  awx/ui/client/src/instance-groups/instances/instances.controller.js
  awx/ui/client/src/instance-groups/list/instance-groups-list.partial.html
  awx/ui/client/src/instance-groups/main.js
Labels: component:ui, mergeit, type:enhancement

#3232 Surface empty groups as children of all group
  awx/main/models/inventory.py
  awx/main/tests/functional/models/test_inventory.py
Labels: component:api, mergeit, type:bug

#3505 Address CVE-2019-3869
  installer/inventory
  installer/roles/image_build/files/launch_awx.sh
  installer/roles/image_build/files/launch_awx_task.sh
  installer/roles/image_build/files/settings.py
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/kubernetes/templates/management-pod.yml.j2
  installer/roles/kubernetes/templates/secret.yml.j2
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/tasks/main.yml
  installer/roles/local_docker/tasks/standalone.yml
  installer/roles/local_docker/templates/credentials.py.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
  installer/roles/local_docker/templates/environment.sh.j2
Labels: mergeit

#3515 Fix permissions of sensitive files in docker-compose installation
  installer/install.yml
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/vars/Darwin.yml
  installer/roles/local_docker/vars/default.yml
Labels: mergeit, state:needs_triage

#3519 runner expects process isolation flags in settings
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3520 pin runner 1.3.1
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#3524 update install docs
  INSTALL.md
Labels: mergeit

#3525 Fix docker-compose installs
  INSTALL.md
  VERSION
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/templates/credentials.py.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
  installer/roles/local_docker/vars/Darwin.yml
  installer/roles/local_docker/vars/default.yml
Labels: mergeit

#3532 Log errors directly from inventory_import.py only if running by hand
  awx/main/management/commands/inventory_import.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3523 properly handle isolated cancellation
  awx/main/expect/isolated_manager.py
  awx/main/tasks.py
Labels: mergeit, state:needs_triage

#3535 Fix bug where init scripts didnt create the admin user correctly
  installer/roles/image_build/files/launch_awx_task.sh
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/local_docker/templates/environment.sh.j2
Labels: mergeit

#3540 ci adjustments
  awx/ui/test/e2e/fixtures.js
  awx/ui/test/e2e/tests/test-org-permissions.js
  awx/ui/test/e2e/tests/test-websockets.js
Labels: component:ui, mergeit, type:bug

#3539 Use option to add back in gce_image hostvar
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/gce/files/gcp_compute.yml
Labels: component:api, mergeit, type:enhancement

#3284 Analytics
  awx/main/analytics/__init__.py
  awx/main/analytics/collectors.py
  awx/main/analytics/core.py
  awx/main/conf.py
  awx/main/management/commands/gather_analytics.py
  awx/main/migrations/0064_v350_analytics_state.py
  awx/main/models/ha.py
  awx/main/models/organization.py
  awx/main/tasks.py
  awx/main/tests/functional/analytics/__init__.py
  awx/main/tests/functional/analytics/test_core.py
  awx/main/tests/functional/analytics/test_counts.py
  awx/main/tests/functional/analytics/test_projects_by_scm_type.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-misc.form.js
  awx/ui/client/src/license/license.block.less
  awx/ui/client/src/license/license.controller.js
  awx/ui/client/src/license/license.partial.html
  awx/ui/client/src/login/authenticationServices/insightsEnablement.service.js
  awx/ui/client/src/login/authenticationServices/main.js
  awx/ui/conf.py
Labels: component:api, mergeit, state:needs_triage, type:enhancement

#3534 replace our usage of pexpect in IsolatedManager with ansible-runner
  awx/main/expect/isolated_manager.py
  awx/main/expect/run.py
  awx/main/management/commands/test_isolated_connection.py
  awx/main/tasks.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/expect/test_expect.py
Labels: mergeit, state:needs_triage

#3503 Format jt details for popover use.
  awx/ui/client/src/partials/job-template-details.html
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.controller.js
Labels: component:ui, mergeit, type:bug

#3555 fix a variety of bugs in isolated support
  awx/main/expect/isolated_manager.py
  awx/main/tasks.py
  awx/playbooks/run_isolated.yml
Labels: mergeit, state:needs_triage

#3518 Make use of user-defined settings for defining the isolated nodes heartbeat
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/production.py
Labels: component:api, mergeit, state:needs_triage, type:bug

#3514 Enable azure_rm inventory plugin
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/azure_rm/files/azure_rm.yml
Labels: component:api, mergeit, type:enhancement

#3552 move awx.main.expect to awx.main.isolated
  Makefile
  awx/main/expect/authorized_keys
  awx/main/isolated/.gitignore
  awx/main/isolated/__init__.py
  awx/main/isolated/manager.py
  awx/main/management/commands/test_isolated_connection.py
  awx/main/tasks.py
  tools/docker-isolated-override.yml
Labels: mergeit, state:needs_triage

#3558 index unified_job.status
  awx/main/migrations/0065_v350_index_job_status.py
  awx/main/models/unified_jobs.py
Labels: mergeit, state:needs_triage

#3563 Move secret key from configmap to secret
  installer/roles/kubernetes/templates/configmap.yml.j2
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/management-pod.yml.j2
  installer/roles/kubernetes/templates/secret.yml.j2
Labels: mergeit

#3559 process host facts for iso runs
  awx/main/isolated/manager.py
  awx/main/tasks.py
  awx/playbooks/check_isolated.yml
Labels: mergeit, state:needs_triage

#2736 Remove python-logstash dependency
  awx/main/utils/formatters.py
  docs/licenses/python-logstash.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, mergeit, type:task
