Repository ansible/awx, pull requests merged in 2019-12, with the labels that each got.

#5418 Pull in downstream changes to k8s installer
  installer/roles/check_vars/tasks/check_openshift.yml
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/restore.yml
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/kubernetes/templates/postgresql-persistent.yml.j2
Labels: mergeit

#5425 Fix memcached_hostname bug in k8s installs
  installer/roles/kubernetes/defaults/main.yml
Labels: mergeit

#5095 Allow some non-superusers to test credential plugins
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_credential.py
  awx/main/tests/functional/api/test_credential_type.py
  awx/main/tests/functional/conftest.py
Labels: mergeit

#5431 keep *-devel package in the dev container
  tools/docker-compose/Dockerfile
Labels: mergeit

#5434 Only show cred type test button to superusers.
  awx/ui/client/features/credentials/add-edit-credentials.controller.js
Labels: mergeit

#4988 Update foreman inventory to use foreman's inventory report
  awx/plugins/inventory/foreman.ini.example
  awx/plugins/inventory/foreman.py
Labels: mergeit, type:bug

#5420 yamllint: Make all files in awx pass yamllint
  .github/BOTMETA.yml
  .yamllint
  awx/main/tests/data/ansible_utils/playbooks/valid/hello_world.yaml
  awx/main/tests/data/ansible_utils/playbooks/valid/hello_world.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/hosts.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/import.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/include.yml
  awx/playbooks/check_isolated.yml
  awx/playbooks/clean_isolated.yml
  awx/playbooks/project_update.yml
  awx/playbooks/run_isolated.yml
  awx/playbooks/scan_facts.yml
  awx/plugins/inventory/openstack.yml
  awx_collection/template_galaxy.yml
  docs/container_groups/service-account.yml
  installer/build.yml
  installer/install.yml
  installer/roles/check_vars/tasks/check_docker.yml
  installer/roles/check_vars/tasks/check_openshift.yml
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_push/tasks/main.yml
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/tasks/backup.yml
  installer/roles/kubernetes/tasks/kubernetes.yml
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/openshift.yml
  installer/roles/kubernetes/tasks/openshift_auth.yml
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/main.yml
  setup.cfg
  tools/clusterdevel/roles/minishift/tasks/main.yml
  tools/clusterdevel/start_minishift_dev.yml
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/docker-credential-plugins-override.yml
  tools/docker-isolated-override.yml
  tools/elastic/docker-compose.elastic-override.yml
  tools/elastic/docker-compose.logstash-link-cluster.yml
  tools/elastic/docker-compose.logstash-link.yml
  tools/elastic/kibana/config/kibana.yml
  tools/prometheus/prometheus.yml
Labels: mergeit

#5437 fix an nuanced bug which can cause OAuth2 migrations to fail
  awx/__init__.py
Labels: mergeit

#5440 'install' was misspelled as 'isntall'
  installer/inventory
Labels: component:docs, mergeit

#5445 Linters: test new linter job
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/restore.yml
Labels: mergeit

#5249 Move to using systemd for service management.
  tools/scripts/ansible-tower-service
Labels: mergeit

#5451 Fix permissions on projects directory by pre-creating it
  Makefile
  tools/docker-compose/Dockerfile
Labels: mergeit

#5436 Upgrades angular and auxiliary deps to 1.7.9
  awx/ui/client/src/shared/multi-select-list/select-list-item.directive.js
  awx/ui/package-lock.json
  awx/ui/package.json
Labels: mergeit

#5379 Workflows pt 1: The Rendering
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/api/models/WorkflowJobTemplates.js
  awx/ui_next/src/components/AppendBody/AppendBody.jsx
  awx/ui_next/src/components/AppendBody/index.js
  awx/ui_next/src/components/FullPage/FullPage.jsx
  awx/ui_next/src/components/FullPage/index.js
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/Template/Templates.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/index.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Graph.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/StartScreen.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Toolbar.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/WorkflowHelp.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/WorkflowHelpDetails.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/index.js
Labels: component:pf, mergeit

#5444 Added cryptography to awxkit deps
  awxkit/setup.py
Labels: mergeit

#5442 Remove outdated Zanata script as part of migration to Memsource
  tools/docker-compose/Dockerfile
  tools/scripts/manage_translations.py
Labels: component:api, component:ui, mergeit, type:enhancement

#5457 Fix situation were error happened before lock was released
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#5447 Update job redirects and tab placement
  awx/ui_next/src/screens/Job/Job.jsx
  awx/ui_next/src/screens/Job/JobTypeRedirect.jsx
Labels: component:pf, mergeit

#5464 fix a bug in isolated check timeout handling
  awx/main/isolated/manager.py
Labels: mergeit

#5460 Fix project sync errors when project branch is commit
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#5468 ansible playbook: move to modern syntax
  awx/playbooks/clean_isolated.yml
  awx/playbooks/project_update.yml
Labels: mergeit

#5466 Migrate organization add to functional component
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
Labels: component:pf, mergeit

#5472 Use total_hosts for task impact for performance
  awx/main/models/jobs.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_unified_job.py
Labels: component:api, mergeit, type:enhancement

#5412 Add dataCy attribute
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/AddRole/SelectableCard.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Team/TeamDetail/TeamDetail.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.jsx
Labels: mergeit

#5450 Add extra_vars Parameter to tower_job_template.py Module
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/test/awx/test_job_template.py
Labels: component:awx_collection, mergeit, state:needs_review, type:enhancement

#5471 Pull in latest version of our angular-scheduler fork to fix Tueday/Tuesday typo
  awx/ui/package-lock.json
  awx/ui/package.json
Labels: component:ui, mergeit

#5477 provide better HTTP responses for certain OAuth2 error scenarios
  awx/main/models/oauth.py
  awx/main/tests/functional/api/test_oauth.py
Labels: mergeit

#5449 Add Inventory Groups and Groups Delete Modal
  awx/ui_next/src/api/index.js
  awx/ui_next/src/api/models/Groups.js
  awx/ui_next/src/api/models/Inventories.js
  awx/ui_next/src/app.scss
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupsDeleteModal.jsx
  awx/ui_next/src/types.js
Labels: component:pf, mergeit

#5413 Enable Approval-Related Email Notifications to Send Properly
  awx/main/notifications/custom_notification_base.py
  awx/main/notifications/email_backend.py
Labels: component:api, mergeit, priority:medium, state:needs_review, type:bug

#5408 Lookup refactor
  awx/ui_next/src/components/AnsibleSelect/AnsibleSelect.jsx
  awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.jsx
  awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.test.jsx
  awx/ui_next/src/components/ContentLoading/ContentLoading.jsx
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/components/Lookup/CredentialLookup.test.jsx
  awx/ui_next/src/components/Lookup/InstanceGroupsLookup.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.jsx
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/components/Lookup/Lookup.test.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.test.jsx
  awx/ui_next/src/components/Lookup/OrganizationLookup.jsx
  awx/ui_next/src/components/Lookup/OrganizationLookup.test.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.test.jsx
  awx/ui_next/src/components/Lookup/README.md
  awx/ui_next/src/components/Lookup/shared/LookupErrorMessage.jsx
  awx/ui_next/src/components/Lookup/shared/OptionsList.jsx
  awx/ui_next/src/components/Lookup/shared/OptionsList.test.jsx
  awx/ui_next/src/components/Lookup/shared/reducer.js
  awx/ui_next/src/components/Lookup/shared/reducer.test.js
  awx/ui_next/src/components/SelectedList/SelectedList.jsx
  awx/ui_next/src/screens/Host/HostAdd/HostAdd.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.test.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SharedFields.jsx
  awx/ui_next/src/screens/Team/TeamAdd/TeamAdd.test.jsx
  awx/ui_next/src/screens/Team/TeamEdit/TeamEdit.test.jsx
  awx/ui_next/src/screens/Team/shared/TeamForm.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/User/UserList/UserList.test.jsx
Labels: component:pf, mergeit

#5479 Configurable login redirect
  awx/api/conf.py
  awx/api/views/root.py
  awx/main/views.py
  awx/settings/defaults.py
  awx/ui/client/src/app.js
  awx/ui/client/src/app.start.js
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-misc.form.js
  awx/ui/client/src/shared/load-config/load-config.factory.js
  awx/urls.py
Labels: mergeit

#5493 add an awx-manage command for re-generating SECRET_KEY
  awx/main/management/commands/regenerate_secret_key.py
  awx/main/tests/functional/commands/test_secret_key_regeneration.py
  awx/main/utils/encryption.py
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/rekey.yml
Labels: mergeit

#5438 adding instance consumed and remaining capacity to metrics
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_metrics.py
Labels: component:api, mergeit, type:enhancement

#5495 Remove some unused stuff from k8s secret
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/kubernetes/templates/secret.yml.j2
Labels: mergeit

#5424 Adds Inventory Groups
  awx/ui_next/src/components/RoutedTabs/RoutedTabs.jsx
  awx/ui_next/src/index.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/index.js
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/InventoryGroupAdd.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/InventoryGroupAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/index.js
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/index.js
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/index.js
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupForm.test.jsx
Labels: component:ui, component:ui_next, mergeit, type:enhancement

#5239 Reduce API response times by 30% by using memcache migration flag
  awx/main/apps.py
  awx/main/middleware.py
  awx/main/scheduler/tasks.py
  awx/main/tasks.py
  awx/main/utils/db.py
Labels: component:api, mergeit, type:enhancement

#5509 Update webpack to 4.41.2
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui_next, mergeit, type:bug

#5391 Don't error on a trailing slash, just fix it up
  awxkit/awxkit/api/client.py
Labels: mergeit

#5510 Fix access list and navigation user link-ins
  awx/ui_next/src/components/PageHeaderToolbar/PageHeaderToolbar.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
Labels: component:ui_next, mergeit, type:bug

#5516 A few downstream changes
  Makefile
  awx/main/utils/encryption.py
Labels: mergeit

#5489 Remove project update blocking
  awx/main/scheduler/dependency_graph.py
  awx/main/tests/functional/task_management/test_scheduler.py
Labels: component:api, mergeit, type:enhancement

#5511 Initialize inventory list with none selected
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
Labels: component:ui_next, mergeit, type:bug

#5505 Use job details status to test status
  awx/ui/client/features/output/details.component.js
  awx/ui/client/features/output/details.partial.html
Labels: mergeit

#5512 Don't reload template panel on tab change
  awx/ui_next/src/screens/Template/Template.jsx
Labels: component:ui_next, mergeit, type:bug

#5529 Set default value for create_preload_data in image_build role
  installer/roles/image_build/defaults/main.yml
Labels: mergeit

#5531 Set a default value for LOGIN_REDIRECT_URL
  awx/api/conf.py
Labels: mergeit

#5517 Move routed organization views to functional components
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationListItem.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.test.jsx
  awx/ui_next/src/screens/Organization/Organizations.test.jsx
Labels: component:ui_next, mergeit

#5467 Fix collection sanity
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_role.py
Labels: component:api, mergeit, type:bug

#5532 Fix inconsistent warning icon sizes
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
Labels: component:ui_next, mergeit, type:bug

#5537 Move organization form to functional component
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.test.jsx
Labels: component:ui_next, mergeit

#5540 Don't complain if LOGIN_REDIRECT_URL is null
  awx/settings/defaults.py
Labels: mergeit

#5543 Add credential_type summarizable fk field
  awx/api/serializers.py
Labels: component:api, mergeit

#5538 Measure unit test coverage of test utils
  awx/ui_next/jest.config.js
  awx/ui_next/testUtils/enzymeHelpers.test.jsx
Labels: component:ui_next, mergeit

#5519 Remove inventory source update blocking
  awx/main/scheduler/dependency_graph.py
  awx/main/tests/functional/task_management/test_scheduler.py
Labels: component:api, mergeit, type:enhancement

#5542 Add Credential List
  awx/ui_next/src/screens/Credential/CredentialAdd/CredentialAdd.jsx
  awx/ui_next/src/screens/Credential/CredentialAdd/index.js
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.test.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.test.jsx
  awx/ui_next/src/screens/Credential/CredentialList/index.js
  awx/ui_next/src/screens/Credential/Credentials.jsx
  awx/ui_next/src/screens/Credential/Credentials.test.jsx
  awx/ui_next/src/screens/Credential/shared/data.credentials.json
  awx/ui_next/src/screens/Credential/shared/index.js
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
Labels: component:ui_next, mergeit

#5560 Fix survey validation to always retun an error code if erroring
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_survey_spec.py
Labels: component:api, mergeit, type:bug

#5563 Edit Makefile for Easier Collections Building/Playbook Testing
  Makefile
Labels: component:awx_collection, mergeit, state:needs_review
