Repository ansible/awx, pull requests merged in 2020-04, with the labels that each got.

#6515 remove some unused code from the redis rewrite
  awx/main/consumers.py
Labels: mergeit

#6513 [DOC] Adds comment about needing to be a pem-file
  INSTALL.md
Labels: component:docs, mergeit

#6491 Second attempt at converting tower_job_template
  awx_collection/README.md
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#6486 JT Launch Prompting (phase 1)
  awx/ui_next/package-lock.json
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/components/LaunchPrompt/CredentialsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/InventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/InventoryStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.test.jsx
  awx/ui_next/src/components/LaunchPrompt/OtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/SurveyStep.jsx
  awx/ui_next/src/components/LaunchPrompt/index.js
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/components/Lookup/InstanceGroupsLookup.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.jsx
  awx/ui_next/src/components/Lookup/OrganizationLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/OptionsList/OptionsList.jsx
  awx/ui_next/src/components/OptionsList/OptionsList.test.jsx
  awx/ui_next/src/components/OptionsList/index.js
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/AssociateModal.jsx
Labels: component:ui_next, mergeit

#6525 get rid of the activity stream middleware
  awx/main/middleware.py
  awx/main/signals.py
  awx/main/tests/functional/api/test_activity_streams.py
  awx/settings/defaults.py
Labels: mergeit

#6482 Adds Survey Functionality to WFJT
  awx/ui_next/src/api/models/JobTemplates.js
  awx/ui_next/src/api/models/WorkflowJobTemplates.js
  awx/ui_next/src/screens/Template/TemplateSurvey.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.test.jsx
Labels: component:ui_next, mergeit, state:needs_test, type:enhancement

#6385 Uses formik hooks for JT Form
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
  awx/ui_next/src/types.js
Labels: component:ui_next, mergeit

#6542 Fix align redis
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#6506 Switch from StatefulSet to Deployment
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/rekey.yml
  installer/roles/kubernetes/tasks/restore.yml
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#6490 Hook up view node button in workflow visualizer
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.jsx
  awx/ui_next/src/components/PromptDetail/index.js
  awx/ui_next/src/components/Workflow/workflowReducer.js
  awx/ui_next/src/components/Workflow/workflowReducer.test.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.test.jsx
Labels: component:ui_next, mergeit

#6548 Mark login button for translation
  awx/ui_next/src/screens/Login/Login.jsx
Labels: component:ui_next, mergeit

#6497 Initial conversion of tower_notification
  awx_collection/README.md
  awx_collection/plugins/modules/tower_notification.py
  awx_collection/test/awx/test_notification.py
  awx_collection/tests/integration/targets/tower_notification/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#6468 add inventory host groups list and host groups lists
  awx/ui_next/src/api/models/Hosts.js
  awx/ui_next/src/screens/Host/HostGroups/HostGroupItem.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupItem.test.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroups.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroups.test.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHost/InventoryHost.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroups.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/index.js
Labels: component:ui_next, mergeit, state:needs_test

#6266 ConfigMap supervisor configs and launch scripts for k8s
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/templates/configmap.yml.j2
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/launch_awx.yml.j2
  installer/roles/kubernetes/templates/supervisor.yml.j2
  installer/roles/kubernetes/vars/openshift.yml
Labels: mergeit, type:enhancement

#6522 add broadcast websocket status command
  awx/main/analytics/broadcast_websocket.py
  awx/main/management/commands/run_wsbroadcast.py
  tools/sosreport/tower.py
Labels: mergeit

#6551 simplify nonce creation and extraction
  awx/main/consumers.py
Labels: mergeit

#6553 remove deprecated manual inventory source support
  awx/api/serializers.py
  awx/main/access.py
  awx/main/management/commands/inventory_import.py
  awx/main/migrations/0114_v370_remove_deprecated_manual_inventory_sources.py
  awx/main/models/inventory.py
  awx/main/signals.py
  awx/main/tests/functional/api/test_credential.py
  awx/main/tests/functional/api/test_unified_jobs_stdout.py
  awx/main/tests/functional/api/test_unified_jobs_view.py
  awx/main/tests/functional/commands/test_inventory_import.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/models/test_notifications.py
  awx/main/tests/functional/test_instances.py
  awx/main/tests/functional/test_named_url.py
  awx/main/tests/functional/test_notifications.py
  awx/main/tests/functional/test_rbac_migration.py
  awx_collection/test/awx/test_workflow_template.py
Labels: mergeit

#6564 Changed column label for plain jobs to "Playbook Run" to align with search
  awx/ui_next/src/components/JobList/JobListItem.jsx
Labels: component:ui_next, mergeit, type:enhancement

#6566 Fix bug where JT is disabled in workflow node form for user with execute permissions on said JT
  awx/ui/client/src/templates/workflows/workflow-maker/forms/workflow-node-form.partial.html
Labels: component:ui, mergeit, type:bug

#6567 Adds workflow job id to header of approval drawer items
  awx/ui/client/lib/components/approvalsDrawer/approvalsDrawer.partial.html
Labels: component:ui, mergeit, type:enhancement

#6565 static identifier in OPTIONS response for workflow job template node
  awx/api/metadata.py
Labels: mergeit

#6421 Adds Survey Preview Functionality
  awx/ui_next/src/components/FormField/PasswordField.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyPreviewModal.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyPreviewModal.test.jsx
  awx/ui_next/src/screens/Template/Survey/index.js
Labels: component:ui_next, mergeit

#6554 Allow disassociating orphaned users from credentials
  awx/api/views/__init__.py
Labels: component:api, mergeit, type:bug

#6572 Allow setting identifier for approval nodes
  awx/api/serializers.py
  awx_collection/test/awx/test_workflow_job_template_node.py
Labels: component:api, component:awx_collection, mergeit, state:needs_review, type:bug

#6582 align with openshift
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#6570 Add Inventory Source workflow node prompt details
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptInventorySourceDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptInventorySourceDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptWFJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/data.inventory_source.json
  awx/ui_next/src/components/PromptDetail/data.project.json
Labels: component:ui_next, mergeit

#6526 Feature memcached socket devel
  awx/settings/defaults.py
  installer/roles/image_build/files/launch_awx.sh
  installer/roles/image_build/templates/launch_awx_task.sh.j2
  installer/roles/kubernetes/defaults/main.yml
  installer/roles/kubernetes/templates/configmap.yml.j2
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/environment.sh.j2
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/templates/credentials.py.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
  installer/roles/local_docker/templates/environment.sh.j2
  tools/clusterdevel/roles/minishift/templates/configmap.yml.j2
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/docker-compose/bootstrap_development.sh
Labels: mergeit

#6585 Tidy up the dev environment a bit
  installer/roles/image_build/files/Dockerfile.sdist
  installer/roles/image_build/files/google-cloud-sdk.repo
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
  tools/docker-compose/google-cloud-sdk.repo
Labels: mergeit

#6588 fix a typo in the credentials UI
  awx/ui/client/src/shared/directives.js
Labels: mergeit

#6592 make awxkit pass through identifier for wfjtn
  awxkit/awxkit/api/pages/workflow_job_template_nodes.py
Labels: mergeit

#6545 Fix adding orphaned user to org
  awx/main/access.py
  awx/main/tests/functional/test_rbac_role.py
Labels: component:api, mergeit, type:bug

#6338 Update logstash docs
  tools/docker-compose/README
  tools/docker-compose/README.md
  tools/elastic/README.md
  tools/elastic/docker-compose.logstash-link.yml
Labels: component:api, component:installer, mergeit, type:enhancement

#6604 Remove state checks from user list test
  awx/ui_next/src/screens/User/UserList/UserList.test.jsx
Labels: component:ui_next, mergeit

#6569 properly serialize external logs that contain decimal.Decimal objects
  awx/main/utils/formatters.py
Labels: mergeit

#6559 association and disassociation of host groups and inventory host groups list.
  awx/ui_next/src/api/models/Hosts.js
  awx/ui_next/src/components/AssociateModal/AssociateModal.jsx
  awx/ui_next/src/components/AssociateModal/AssociateModal.test.jsx
  awx/ui_next/src/components/AssociateModal/data.hosts.json
  awx/ui_next/src/components/AssociateModal/index.js
  awx/ui_next/src/components/DisassociateButton/DisassociateButton.jsx
  awx/ui_next/src/components/DisassociateButton/DisassociateButton.test.jsx
  awx/ui_next/src/components/DisassociateButton/index.js
  awx/ui_next/src/screens/Host/HostGroups/HostGroups.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroups.test.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/InventoryGroupAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.jsx
Labels: component:ui_next, mergeit, state:needs_test, type:bug

#6609 Resolve Name to ID Properly in WFJT Module
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit

#6617 fix memcached in dev env
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/memcached/.dir_placeholder
Labels: mergeit

#6623 Update "Enable Webhooks" option in WFJT
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
Labels: component:ui_next, mergeit

#6472 Remove field properties which are default values anyway
  awx_collection/plugins/modules/tower_credential.py
  awx_collection/plugins/modules/tower_credential_type.py
  awx_collection/plugins/modules/tower_group.py
  awx_collection/plugins/modules/tower_host.py
  awx_collection/plugins/modules/tower_inventory.py
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_job_cancel.py
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/plugins/modules/tower_job_list.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_job_wait.py
  awx_collection/plugins/modules/tower_label.py
  awx_collection/plugins/modules/tower_license.py
  awx_collection/plugins/modules/tower_notification.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_role.py
  awx_collection/plugins/modules/tower_send.py
  awx_collection/plugins/modules/tower_settings.py
  awx_collection/plugins/modules/tower_team.py
  awx_collection/plugins/modules/tower_user.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/plugins/modules/tower_workflow_job_template_node.py
  awx_collection/plugins/modules/tower_workflow_launch.py
  awx_collection/plugins/modules/tower_workflow_template.py
Labels: component:awx_collection, mergeit

#6607 don't send tags to the Grafana annotations API if none are specified
  awx/main/notifications/grafana_backend.py
  awx/main/tests/unit/notifications/test_grafana.py
Labels: mergeit

#6624 Prevent project lookup from firing requests on every render
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui_next, mergeit

#6541 Fix RBAC loose items from reversed decision on JT org permissions
  awx/main/access.py
  awx/main/tests/functional/test_rbac_job_templates.py
Labels: component:api, mergeit, type:bug

#6631 properly respect REFRESH_TOKEN_EXPIRE_SECONDS when generating new tokens
  awx/api/urls/oauth2_root.py
  awx/main/tests/functional/api/test_oauth.py
Labels: mergeit

#6634 Silence deprecation warnings from tower_credential
  awx_collection/test/awx/test_credential.py
Labels: component:awx_collection, mergeit

#6487 fix for CSRF issue in traefik configuration
  installer/roles/image_build/files/settings.py
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#6601 Use a docker volume for the dev env db
  Makefile
  tools/docker-compose.yml
Labels: mergeit

#6635 Remove tower-cli from Zuul CI for AWX collection
  Makefile
  awx_collection/test/awx/conftest.py
Labels: component:awx_collection, mergeit

#6642 Add note to docs about async form behavior
  awx/ui_next/CONTRIBUTING.md
Labels: component:ui_next, mergeit

#6625 Fix JT form playbook select error message and more
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/types.js
Labels: component:ui_next, mergeit

#6629 Document and align the env var for OAuth token
  awx_collection/plugins/doc_fragments/auth.py
  awx_collection/plugins/modules/tower_credential.py
  awx_collection/plugins/modules/tower_credential_type.py
  awx_collection/plugins/modules/tower_group.py
  awx_collection/plugins/modules/tower_host.py
  awx_collection/plugins/modules/tower_inventory.py
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_job_cancel.py
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/plugins/modules/tower_job_list.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_job_wait.py
  awx_collection/plugins/modules/tower_label.py
  awx_collection/plugins/modules/tower_license.py
  awx_collection/plugins/modules/tower_notification.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_role.py
  awx_collection/plugins/modules/tower_settings.py
  awx_collection/plugins/modules/tower_team.py
  awx_collection/plugins/modules/tower_user.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/plugins/modules/tower_workflow_job_template_node.py
  awxkit/awxkit/cli/docs/source/authentication.rst
  awxkit/awxkit/cli/docs/source/usage.rst
  awxkit/awxkit/cli/format.py
  awxkit/awxkit/cli/resource.py
Labels: component:awx_collection, component:cli, mergeit

#6645 more ansible runner isolated cleanup
  awx/main/isolated/manager.py
  awx/main/tasks.py
Labels: mergeit

#6605 update firehose script for bigint migration
  tools/scripts/firehose.py
Labels: mergeit

#6646 Activate no_log for Values in input Parameter of tower_credential Module
  awx_collection/plugins/modules/tower_credential.py
Labels: component:awx_collection, mergeit

#6639 Converts most of our route render prop usage to children
  awx/ui_next/src/components/Breadcrumbs/Breadcrumbs.jsx
  awx/ui_next/src/components/Schedule/Schedule.jsx
  awx/ui_next/src/components/Schedule/Schedules.jsx
  awx/ui_next/src/screens/Credential/Credential.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroups.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroups.jsx
  awx/ui_next/src/screens/Inventory/SmartInventory.jsx
  awx/ui_next/src/screens/Job/Job.jsx
  awx/ui_next/src/screens/Job/Jobs.jsx
  awx/ui_next/src/screens/Organization/Organization.jsx
  awx/ui_next/src/screens/Organization/Organizations.jsx
  awx/ui_next/src/screens/Project/Project.jsx
  awx/ui_next/src/screens/Project/Projects.jsx
  awx/ui_next/src/screens/Team/Team.jsx
  awx/ui_next/src/screens/Template/Templates.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/User/User.jsx
  awx/ui_next/src/screens/User/Users.jsx
Labels: component:ui_next, mergeit

#6652 Update some contributing docs
  CONTRIBUTING.md
  Makefile
  docs/task_manager_system.md
  docs/tasks.md
  tools/clusterdevel/bootstrap_minishift.sh
  tools/clusterdevel/roles/minishift/tasks/main.yml
  tools/clusterdevel/roles/minishift/templates/configmap.yml.j2
  tools/clusterdevel/roles/minishift/templates/hostdev.yml.j2
  tools/clusterdevel/roles/minishift/templates/hostfolderpvc.yml.j2
  tools/clusterdevel/roles/minishift/templates/serviceacct.yml.j2
  tools/clusterdevel/roles/minishift/templates/volumeclaim.yml.j2
  tools/clusterdevel/start_minishift_dev.yml
Labels: mergeit

#6644 Only clear playbook when different project is selected
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui_next, mergeit, type:bug

#6659 Enable tty in dev container
  tools/docker-compose.yml
Labels: mergeit

#6643 Upgrades pf deps to latest
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/DeleteRoleConfirmationModal.test.jsx.snap
  awx/ui_next/src/screens/Template/Survey/SurveyPreviewModal.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyPreviewModal.test.jsx
Labels: component:ui_next, mergeit, state:needs_test

#6660 Pass empty params to launch endpoint rather than null
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
Labels: component:ui_next, mergeit, type:bug

#6658 Fixes issue where job type redirects weren't firing correctly
  awx/ui_next/src/screens/Job/Jobs.jsx
Labels: component:ui_next, mergeit

#6637 Initial commit of tests for tower_workflow_launch
  awx_collection/plugins/modules/tower_workflow_launch.py
  awx_collection/tests/integration/targets/tower_workflow_launch/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#6670 work around redis connection failures in the callback receiver
  awx/main/dispatch/worker/base.py
Labels: mergeit

#6568 Do not set changed=True if the object did not change
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/plugins/modules/tower_credential_type.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_credential.py
  awx_collection/test/awx/test_credential_type.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/test/awx/test_notification.py
  awx_collection/test/awx/test_user.py
Labels: component:awx_collection, mergeit, type:bug

#6677 fix spelling mistake in wsbroadcast status output
  awx/main/management/commands/run_wsbroadcast.py
Labels: mergeit

#6671 Collect task timing, warnings, and deprecations from job events
  awx/main/analytics/collectors.py
Labels: mergeit

#6679 skip non-files when consuming events synced from isolated hosts
  awx/main/isolated/manager.py
Labels: mergeit

#6651 Rename SCM to Source Control
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialAdd/CredentialAdd.test.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.test.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.test.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/GitSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/HgSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/ManualSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SharedFields.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SvnSubForm.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/ProjectsList.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
Labels: component:ui_next, mergeit

#6656 excise withRouter from function components
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupForm.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Team/TeamEdit/TeamEdit.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/InventorySourcesList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/ProjectsList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/WorkflowJobTemplatesList.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/User/UserEdit/UserEdit.jsx
Labels: component:ui_next, mergeit

#6668 Modify Users component to be function based
  awx/ui_next/src/screens/User/Users.jsx
Labels: mergeit

#6176 Send also workflows as part of unified jobs and send all changes to jobs
  awx/main/analytics/collectors.py
  awx/main/tests/functional/analytics/test_collectors.py
Labels: component:analytics, mergeit, type:bug

#6685 Fix route bug in User view
  awx/ui_next/src/screens/User/User.jsx
Labels: component:ui_next, mergeit, type:bug

#6108 Replace our external logging feature with Rsyslog
  .gitignore
  awx/api/templates/api/setting_logging_test.md
  awx/conf/tests/functional/test_api.py
  awx/conf/views.py
  awx/main/conf.py
  awx/main/constants.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_settings.py
  awx/main/tests/unit/api/test_logger.py
  awx/main/tests/unit/utils/test_handlers.py
  awx/main/tests/unit/utils/test_reload.py
  awx/main/utils/external_logging.py
  awx/main/utils/formatters.py
  awx/main/utils/handlers.py
  awx/main/utils/reload.py
  awx/settings/defaults.py
  awx/ui/client/src/configuration/forms/settings-form.controller.js
  awx/ui/client/src/configuration/forms/system-form/configuration-system.controller.js
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-logging.form.js
  awx/ui/client/src/shared/form-generator.js
  docs/licenses/requests-futures.txt
  docs/logging_integration.md
  installer/roles/image_build/files/rsyslog.conf
  installer/roles/image_build/files/rsyslog.repo
  installer/roles/image_build/files/supervisor.conf
  installer/roles/image_build/files/supervisor_task.conf
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/supervisor.yml.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
  tools/docker-compose/Dockerfile
  tools/docker-compose/rsyslog.conf
  tools/docker-compose/rsyslog.repo
  tools/docker-compose/supervisor.conf
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#6697 ensure last comma removed in select
  awx/main/tests/functional/analytics/test_collectors.py
Labels: mergeit

#6688 Remove console.log
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
Labels: mergeit

#6702 rsyslogd: ignore /dev/log when we load imuxsock
  awx/main/utils/external_logging.py
  installer/roles/image_build/files/rsyslog.conf
  tools/docker-compose/rsyslog.conf
Labels: mergeit

#6696 add a few minor logging changes to accomodate Splunk's API
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
  awx/main/utils/formatters.py
Labels: mergeit

#6695 don't wait on memcached TCP
  installer/roles/kubernetes/templates/launch_awx.yml.j2
Labels: mergeit

#6664 Add JT wf node modal prompt details
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/data.job_template.json
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.test.jsx
Labels: component:ui_next, mergeit, type:feature

#6698 Cast the start/end times with timezone.
  awx/main/analytics/collectors.py
Labels: component:api, mergeit, type:bug

#6684 Add note about code style for ui_next
  awx/ui_next/CONTRIBUTING.md
Labels: component:ui_next, mergeit

#6706 make rsyslog service restarts a bit less noisy
  awx/main/utils/reload.py
Labels: mergeit

#6689 Make the module util respect oauth token over username/password
  awx_collection/plugins/module_utils/tower_api.py
Labels: component:awx_collection, mergeit, type:enhancement

#6665 Collect information on inventory sources
  awx/main/analytics/collectors.py
  awx/main/tests/functional/analytics/test_counts.py
Labels: mergeit

#6712 properly implement TCP timeouts for external log aggregation
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
Labels: mergeit

#6716 Remove 'supports_check_mode' Text from Converted Collection Modules
  awx_collection/plugins/modules/tower_credential.py
  awx_collection/plugins/modules/tower_job_cancel.py
  awx_collection/plugins/modules/tower_job_list.py
  awx_collection/plugins/modules/tower_license.py
  awx_collection/plugins/modules/tower_settings.py
  awx_collection/plugins/modules/tower_workflow_launch.py
  awx_collection/tools/templates/tower_module.j2
Labels: component:awx_collection, mergeit

#6717 update custom credential plugin docs to point at an example project
  docs/credentials/credential_plugins.md
Labels: mergeit

#6562 Fixes several things about Survey List
  awx/ui_next/src/components/ErrorDetail/ErrorDetail.jsx
  awx/ui_next/src/components/ErrorDetail/ErrorDetail.test.jsx
  awx/ui_next/src/components/ErrorDetail/getErrorMessage.js
  awx/ui_next/src/components/ErrorDetail/getErrorMessage.test.js
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.test.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarAddButton.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyToolbar.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyToolbar.test.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/TemplateSurvey.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.test.jsx
Labels: component:ui_next, mergeit

#6720 wsbroadcast better logging and behavior
  awx/main/management/commands/run_wsbroadcast.py
  awx/settings/defaults.py
  awx/settings/production.py
Labels: mergeit

#6710 Rename awx rsyslog socket and PID dir
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
  awx/settings/defaults.py
  installer/roles/image_build/files/rsyslog.conf
  installer/roles/image_build/files/supervisor.conf
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/kubernetes/templates/deployment.yml.j2
  installer/roles/kubernetes/templates/supervisor.yml.j2
  installer/roles/local_docker/templates/docker-compose.yml.j2
  tools/docker-compose/Dockerfile
  tools/docker-compose/rsyslog.conf
  tools/docker-compose/supervisor.conf
Labels: component:installer, mergeit, type:bug

#6722 Remove 'rampart' from a user-facing string.
  awx/main/migrations/0006_v320_release.py
  awx/main/migrations/0032_v330_polymorphic_delete.py
  awx/main/models/unified_jobs.py
Labels: mergeit

#6724 reconnect when a vanilla server disconnect happens
  awx/main/wsbroadcast.py
Labels: mergeit

#6704 bump version for 11.0.0
  CHANGELOG.md
  VERSION
Labels: mergeit

#6721 Dockerfile organization
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
Labels: mergeit

#6713 Deprecate Send, Receive, and Workflow Template Collections Modules
  awx_collection/meta/routing.yml
  awx_collection/plugins/modules/tower_receive.py
  awx_collection/plugins/modules/tower_send.py
  awx_collection/plugins/modules/tower_workflow_template.py
  awx_collection/tests/sanity/ignore-2.10.txt
Labels: component:awx_collection, mergeit

#6681 fix copy paste error in docker compose cluster
  tools/docker-compose-cluster.yml
Labels: mergeit

#6723 Fix Page Size toggle does not persist after a search
  awx/ui_next/src/components/ListHeader/ListHeader.jsx
  awx/ui_next/src/components/ListHeader/ListHeader.test.jsx
Labels: component:ui_next, mergeit

#6709 Add workflow details to node view modal
  awx/ui_next/src/api/models/JobTemplates.js
  awx/ui_next/src/components/DetailList/UserDateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptWFJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptWFJobTemplateDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/data.job_template.json
  awx/ui_next/src/components/PromptDetail/data.workflow_template.json
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.test.jsx
Labels: component:ui_next, mergeit, type:feature

#6735 Flip CSRF_COOKIE_SECURE docs.
  docs/auth/session.md
Labels: mergeit

#6732 [fix] Use rsync --blocking-io to work around EAGAIN hazard
  awx/playbooks/check_isolated.yml
  awx/playbooks/run_isolated.yml
Labels: mergeit

#6736 Fix Collection README to Display Properly
  awx_collection/README.md
Labels: component:awx_collection, mergeit

#6678 Fix List Navigation Pagination
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.test.jsx
Labels: component:ui_next, mergeit

#6728 confidence in websocket group logic is high
  awx/main/consumers.py
Labels: mergeit

#6738 Collection: Ignore some sanity errors in ansible 2.9
  awx_collection/tests/sanity/ignore-2.9.txt
Labels: component:awx_collection, mergeit, type:bug

#6687 Update User component to be function based
  awx/ui_next/src/screens/User/User.jsx
  awx/ui_next/src/screens/User/User.test.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/screens/User/Users.jsx
  awx/ui_next/src/screens/User/Users.test.jsx
Labels: component:ui_next, mergeit

#6739 cleanup group membership on disconnect
  awx/main/consumers.py
Labels: mergeit

#6745 don't expose redis port
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#6747 fix redis logs
  awx/main/consumers.py
  awx/main/wsbroadcast.py
  awx/settings/defaults.py
Labels: mergeit

#6737 rsyslogd: set some reasonable limits for disk queues
  awx/main/utils/external_logging.py
Labels: mergeit

#6730 Fix new flake8 from pyflakes 2.2.0 release
  awx/api/serializers.py
  awx/conf/fields.py
  awx/conf/settings.py
  awx/main/analytics/collectors.py
  awx/main/dispatch/periodic.py
  awx/main/dispatch/worker/base.py
  awx/main/dispatch/worker/callback.py
  awx/main/scheduler/dag_simple.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/factories/tower.py
  awxkit/awxkit/api/pages/workflow_job_templates.py
  awxkit/awxkit/api/registry.py
  setup.cfg
Labels: component:api, mergeit, type:bug

#6752 Support adding/removing notifications to job_templates
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#6654 Adds webhooks to Job template form
  awx/ui_next/src/api/models/JobTemplates.js
  awx/ui_next/src/components/Lookup/index.js
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.test.jsx
Labels: component:ui_next, mergeit, type:enhancement

#6766 escape certain log aggregator settings when generating rsyslog config
  awx/main/utils/external_logging.py
Labels: mergeit

#6763 let users configure the destination and max disk size of rsyslogd spool
  awx/main/conf.py
  awx/main/utils/external_logging.py
  awx/settings/defaults.py
Labels: mergeit

#6764 record redis config in the sosreport
  tools/sosreport/tower.py
Labels: mergeit

#6781 update postgres minimum version
  INSTALL.md
Labels: mergeit

#6779 Collection: Fix the tower_project scm_allow_override
  awx_collection/plugins/modules/tower_project.py
  awx_collection/tests/integration/targets/tower_project/tasks/main.yml
Labels: component:awx_collection, mergeit

#6783 update (dead) links to example inv source vars
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
Labels: mergeit

#6765 revert back to the old way of calling flake8 linter
  setup.cfg
Labels: mergeit

#6768 JT Launch Prompting (phase 3) [rebuilt branch]
  awx/ui_next/src/components/CodeMirrorInput/CodeMirrorInput.jsx
  awx/ui_next/src/components/FormField/FieldTooltip.jsx
  awx/ui_next/src/components/FormField/FormField.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/SurveyStep.jsx
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.js
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.test.js
  awx/ui_next/src/components/StatusIcon/StatusIcon.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.jsx
  awx/ui_next/src/util/validators.jsx
  awx/ui_next/src/util/validators.test.js
Labels: component:ui_next, mergeit

#6796 rsyslogd is only needed in the web container
  installer/roles/image_build/files/supervisor_task.conf
Labels: mergeit

#6787 Remove tower_receive and tower_send tests
  awx_collection/tests/integration/targets/tower_receive/tasks/main.yml
  awx_collection/tests/integration/targets/tower_send/tasks/main.yml
Labels: component:awx_collection, mergeit

#6785 Dev env: stop and remove containers before removing volume
  Makefile
Labels: mergeit

#6204 Send job and template nodes to analytics
  awx/main/analytics/collectors.py
  awx/main/tests/functional/analytics/test_collectors.py
Labels: component:analytics, component:api, mergeit, type:enhancement

#6788 include the AWX version as a header in all responses
  awx/api/generics.py
  awx/main/utils/common.py
Labels: component:api, mergeit

#6773 follow symlinks while discovering valid playbooks
  awx/main/models/projects.py
  awx/main/utils/ansible.py
Labels: component:api, mergeit

#6802 bump version to 11.1.0
  CHANGELOG.md
  VERSION
Labels: mergeit

#6804 lie about last time analytics were collected
  awx/main/tests/functional/analytics/test_collectors.py
Labels: mergeit

#6786 Fix searching for a blank string creates a blank search filter
  awx/ui_next/src/components/Search/Search.jsx
  awx/ui_next/src/components/Search/Search.test.jsx
Labels: component:ui_next, mergeit

#6809 Don't use SCLs for openshift.
  installer/roles/kubernetes/vars/openshift.yml
Labels: mergeit

#6814 Change the custom venv vars install line
  docs/custom_virtualenvs.md
Labels: mergeit

#6283 Use vendored collections for inventory imports
  MANIFEST.in
  Makefile
  awx/main/management/commands/inventory_import.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/data/inventory/plugins/azure_rm/files/azure_rm.yml
  awx/main/tests/data/inventory/plugins/ec2/files/aws_ec2.yml
  awx/main/tests/data/inventory/plugins/gce/files/gcp_compute.yml
  awx/main/tests/data/inventory/plugins/openstack/files/openstack.yml
  awx/main/tests/data/inventory/plugins/rhv/env.json
  awx/main/tests/data/inventory/plugins/rhv/files/file_reference
  awx/main/tests/data/inventory/plugins/rhv/files/ovirt.yml
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
  awx/main/tests/data/inventory/plugins/tower/files/tower.yml
  awx/main/tests/data/inventory/plugins/vmware/env.json
  awx/main/tests/data/inventory/plugins/vmware/files/vmware_vm_inventory.yml
  awx/main/tests/data/inventory/scripts/ec2/files/file_reference
  awx/main/tests/data/inventory/scripts/vmware/files/file_reference
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/settings/defaults.py
  awx/settings/local_settings.py.docker_compose
  docs/inventory/inventory_plugins.md
  installer/roles/image_build/files/settings.py
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/kubernetes/templates/configmap.yml.j2
  requirements/collections_requirements.yml
  tools/collections/README.md
  tools/collections/clone_vendor.sh
  tools/docker-compose/Dockerfile
Labels: component:api, mergeit, type:enhancement

#6825 allow users to test log aggregration if `awx` isn't in the loggers list
  awx/conf/views.py
  awx/main/utils/formatters.py
Labels: mergeit

#6820 Show missing detail fields in workflow node view modal
  awx/ui_next/src/components/DetailList/DeletedDetail.jsx
  awx/ui_next/src/components/DetailList/index.js
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptInventorySourceDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptInventorySourceDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.test.jsx
  awx/ui_next/src/components/PromptDetail/PromptWFJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
Labels: component:ui_next, mergeit, type:bug

#6826 Enable VMWare inventory plugin
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/vmware/files/vmware_vm_inventory.yml
  requirements/collections_requirements.yml
Labels: mergeit

#6818 add a setting for enabling high rsyslogd verbosity
  awx/main/conf.py
  awx/main/utils/external_logging.py
  awx/settings/defaults.py
Labels: mergeit

#6832 Improve the ansible-tower-service script
  tools/scripts/ansible-tower-service
Labels: mergeit

#6811 Don't override ANSIBLE_SSH_ARGS for ad-hoc commands.
  awx/main/tasks.py
Labels: mergeit

#5398 If pg_hostname is defined don't try to upgrade PostgreSQL
  installer/roles/local_docker/tasks/main.yml
  installer/roles/local_docker/tasks/upgrade_postgres.yml
Labels: mergeit, type:bug

#6762 Update inventory file
  INSTALL.md
  installer/inventory
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#6005 Add CA trust volume to k8s installer management pod
  installer/roles/kubernetes/templates/management-pod.yml.j2
Labels: component:installer, mergeit, type:bug

#6833 Keystone v3 support for OpenStack Credential
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/tests/data/inventory/plugins/openstack/files/file_reference
  awx/main/tests/data/inventory/scripts/openstack/files/file_reference
  awx/main/tests/unit/test_tasks.py
Labels: mergeit

#6790 Add ability to monitor jobs and workflow_jobs via awx cli, fixes #6165
  awxkit/awxkit/cli/custom.py
Labels: component:cli, mergeit, type:enhancement

#6220 Modified hashivault.py to support approle
  awx/main/credential_plugins/hashivault.py
Labels: component:api, mergeit, type:enhancement

#6848 Updated ingress template for kubernetes to support HTTP and HTTPS when annotations not set
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: component:installer, mergeit, type:bug

#6856 merge in a few downstream fixes
  awx/main/analytics/broadcast_websocket.py
  awx/main/managers.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
  awx/main/tests/unit/analytics/test_broadcast_websocket.py
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
  awx/playbooks/project_update.yml
  awx/ui/client/lib/components/approvalsDrawer/approvalsDrawer.partial.html
  awx/ui/client/src/license/license.partial.html
  awx/ui/po/zh.po
  awx_collection/plugins/modules/tower_credential.py
  awx_collection/plugins/modules/tower_credential_type.py
  awx_collection/plugins/modules/tower_group.py
  awx_collection/plugins/modules/tower_host.py
  awx_collection/plugins/modules/tower_inventory.py
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_notification.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_team.py
  awx_collection/plugins/modules/tower_user.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/plugins/modules/tower_workflow_job_template_node.py
  awx_collection/tests/integration/targets/tower_inventory_source/tasks/main.yml
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
  awx_collection/tools/templates/tower_module.j2
  installer/roles/image_build/files/supervisor.conf
  installer/roles/kubernetes/templates/supervisor.yml.j2
  tools/docker-compose/supervisor.conf
  tools/sosreport/tower.py
Labels: mergeit

#6867 Fixes failing test
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroups.test.jsx
Labels: component:ui_next, mergeit, type:bug

#6860 bump version 11.2.0
  CHANGELOG.md
  VERSION
Labels: mergeit

#6868 Set SDB_NOTIFY_HOST on non-docker OS X
  awx/settings/development.py
Labels: mergeit, type:bug

#6849 Added variable to inventory to add a separate SSL key file
  installer/inventory
  installer/roles/local_docker/templates/docker-compose.yml.j2
  installer/roles/local_docker/templates/nginx.conf.j2
Labels: component:installer, mergeit, type:bug

#6808 Adds webhook fields to job template details
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/shared/data.job_template.json
Labels: component:ui_next, mergeit, state:needs_test
