Repository ansible/awx, pull requests merged in 2020-01, with the labels that each got.

#5499 only restrict OAuth2 tokens for external accounts *at creation time*
  awx/main/models/oauth.py
  awx/main/tests/functional/api/test_oauth.py
Labels: mergeit

#5579 Revert migration flag
  awx/main/apps.py
  awx/main/middleware.py
  awx/main/scheduler/tasks.py
  awx/main/tasks.py
  awx/main/utils/db.py
Labels: mergeit

#5581 Remove incorrect activity stream entries related to managed types
  awx/main/tests/functional/models/test_activity_stream.py
  awx/main/utils/common.py
Labels: component:api, mergeit, type:bug

#5497 fix the saml_admin_attr not working
  awx/sso/pipeline.py
Labels: component:api, mergeit, type:bug

#5577 Add a uwsgi param to prevent SAML error
  installer/roles/kubernetes/templates/configmap.yml.j2
  installer/roles/local_docker/templates/nginx.conf.j2
Labels: component:installer, mergeit, type:bug

#5593 add the ability to generate dot graphs for per-request profiling
  awx/main/middleware.py
  awx/settings/defaults.py
  requirements/requirements_dev.txt
Labels: mergeit

#5553 Inventory Add form fixes
  awx/ui_next/src/components/ContentError/ContentError.jsx
  awx/ui_next/src/screens/Inventory/InventoryAdd/InventoryAdd.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.jsx
  awx/ui_next/src/util/validators.jsx
  awx/ui_next/src/util/validators.test.js
Labels: component:ui_next, mergeit, type:bug

#5580 Upgrades pf deps to latest
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/components/AddRole/SelectResourceStep.jsx
  awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.jsx
  awx/ui_next/src/components/Lookup/shared/OptionsList.jsx
  awx/ui_next/src/components/MultiSelect/MultiSelect.test.jsx
  awx/ui_next/src/components/NotificationList/NotificationListItem.jsx
  awx/ui_next/src/components/NotificationList/__snapshots__/NotificationListItem.test.jsx.snap
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataListItem.jsx
  awx/ui_next/src/components/PaginatedDataList/__snapshots__/ToolbarDeleteButton.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHosts.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
  awx/ui_next/src/screens/Job/JobList/JobList.jsx
  awx/ui_next/src/screens/Job/JobList/JobListItem.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamList.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.jsx
Labels: mergeit

#5605 Adds Promote Delete Modal To InventoryGroupDetails
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.jsx
Labels: component:ui, mergeit, type:bug

#5607 change set-context to use-context
  installer/roles/kubernetes/tasks/kubernetes_auth.yml
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#5589 Generate new uuid for newly registered iso nodes
  awx/main/management/commands/provision_instance.py
  awx/main/migrations/0101_v370_generate_new_uuids_for_iso_nodes.py
Labels: component:api, mergeit

#5611 [awxkit] Raise a more informative error when timeout
  awxkit/awxkit/api/mixins/has_status.py
Labels: mergeit

#5562 Add extra_vars Example to Job Launch Module
  awx_collection/README.md
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/test/awx/test_job_template.py
Labels: component:awx_collection, mergeit, priority:medium

#5613 Log case of duplicate UUIDs
  awx/main/dispatch/pool.py
Labels: component:api, mergeit, type:enhancement

#5616 Update Detail views to use CardActionsRow
  awx/ui_next/src/screens/Host/Host.jsx
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.test.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Project/Project.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Team/Team.jsx
  awx/ui_next/src/screens/Team/TeamDetail/TeamDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/User/User.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.jsx
Labels: component:ui_next, mergeit

#5503 Refactor Inventory Plugin Module to Import from module_utils
  awx_collection/plugins/inventory/tower.py
  awx_collection/plugins/module_utils/ansible_tower.py
Labels: component:awx_collection, mergeit

#5609 Pull in downstream k8s installer changes
  installer/roles/kubernetes/handlers/main.yml
  installer/roles/kubernetes/tasks/ssl_cert_gen.yml
Labels: mergeit

#5635 Introduce CHANGELOG.md
  CHANGELOG.md
Labels: mergeit

#5287 update simple search
  awx/ui_next/SEARCH.md
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/AddRole/SelectResourceStep.jsx
  awx/ui_next/src/components/AddRole/SelectResourceStep.test.jsx
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.test.jsx
  awx/ui_next/src/components/FilterTags/FilterTags.jsx
  awx/ui_next/src/components/FilterTags/FilterTags.test.jsx
  awx/ui_next/src/components/FilterTags/index.js
  awx/ui_next/src/components/ListHeader/ListHeader.jsx
  awx/ui_next/src/components/ListHeader/ListHeader.test.jsx
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/components/Lookup/InstanceGroupsLookup.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.jsx
  awx/ui_next/src/components/Lookup/OrganizationLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/Lookup/shared/OptionsList.jsx
  awx/ui_next/src/components/Lookup/shared/OptionsList.test.jsx
  awx/ui_next/src/components/NotificationList/NotificationList.jsx
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/Search/Search.jsx
  awx/ui_next/src/components/Search/Search.test.jsx
  awx/ui_next/src/components/Sort/Sort.jsx
  awx/ui_next/src/components/Sort/Sort.test.jsx
  awx/ui_next/src/components/VerticalSeparator/VerticalSeparator.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHosts.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Job/JobList/JobList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamList.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/types.js
  awx/ui_next/src/util/qs.js
  awx/ui_next/src/util/qs.test.js
Labels: component:ui_next, mergeit

#5630 Use summary `object_roles` to lookup admin role id
  awx/ui/client/src/organizations/linkout/addUsers/addUsers.controller.js
Labels: component:ui, mergeit, type:bug

#5641 Pin setuptools in requirements_setup_requires.txt
  requirements/requirements_setup_requires.txt
Labels: mergeit

#5643 Fix collection of free_instances from /api/v2/config
  awx/main/analytics/collectors.py
Labels: mergeit

#5644 fix linting failures
  awx/main/views.py
  awx/sso/pipeline.py
  installer/roles/kubernetes/handlers/main.yml
  installer/roles/kubernetes/tasks/ssl_cert_gen.yml
Labels: mergeit

#5645 update the CHANGELOG w/ historical notes from the mailing list
  CHANGELOG.md
Labels: mergeit

#5637 Bump version to 9.1.1
  VERSION
Labels: mergeit

#5618 heavily optimize the write speed of the callback receiver
  awx/api/serializers.py
  awx/conf/settings.py
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
  awx/main/dispatch/worker/callback.py
  awx/main/management/commands/callback_stats.py
  awx/main/management/commands/replay_job_events.py
  awx/main/models/events.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_events.py
  awx/main/tests/functional/api/test_settings.py
  awx/main/tests/functional/commands/test_secret_key_regeneration.py
  awx/main/tests/functional/models/test_events.py
  awx/main/tests/unit/commands/test_replay_job_events.py
  awx/main/tests/unit/models/test_events.py
  awx/settings/defaults.py
Labels: mergeit

#5655 update the CHANGELOG for 9.1.1
  CHANGELOG.md
Labels: mergeit

#5656 remove some unnecessary callback receiver debugging code
  awx/main/dispatch/worker/callback.py
Labels: mergeit

#5639 update select-based search items to utilize labels, not just the api value
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/Search/Search.jsx
  awx/ui_next/src/components/Sort/Sort.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/types.js
Labels: mergeit

#5610 Added canceled_on field to unified_jobs model
  awx/api/serializers.py
  awx/main/migrations/0102_v370_unifiedjob_canceled.py
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/api/test_job.py
Labels: component:api, mergeit, type:bug

#5663 update data migration instructions
  DATA_MIGRATION.md
Labels: mergeit

#5666 fix a bug that breaks inv sync stdout within workflows
  awx/main/models/events.py
Labels: mergeit

#5602 Support AzureCloud choices for azure keyvault
  awx/main/credential_plugins/azure_kv.py
  awx/main/tests/functional/test_credential_plugins.py
Labels: component:api, component:ui, mergeit

#5668 update to latest vmware_inventory.py
  awx/plugins/inventory/vmware_inventory.py
Labels: mergeit

#5604 Add configurable MAX_FORKS for jobs
  awx/main/conf.py
  awx/main/models/jobs.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_job_template.py
  awx/ui/client/src/configuration/forms/jobs-form/configuration-jobs.form.js
  awx/ui/client/src/shared/Utilities.js
Labels: component:api, component:ui, mergeit

#5448 remove computed inventory fields from Host and Group
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0103_v370_remove_computed_fields.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/functional/__init__.py
  awx/main/tests/functional/api/test_oauth.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_context_managers.py
  awx/main/tests/functional/models/test_unified_job.py
  awx/ui/client/legacy/styles/lists.less
  awx/ui/client/src/home/dashboard/counts/dashboard-counts.directive.js
  awx/ui/client/src/inventories-hosts/hosts/related/groups/hosts-related-groups.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/factories/get-hosts-status-msg.factory.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/list/groups-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/list/groups-list.partial.html
  awx/ui/client/src/inventories-hosts/inventories/related/groups/main.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-groups/group-nested-groups-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/groups/related/nested-groups/group-nested-groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related/nested-groups/host-nested-groups-list.controller.js
  awx/ui/client/src/inventories-hosts/inventories/related/hosts/related/nested-groups/host-nested-groups.list.js
  awx/ui/client/src/inventories-hosts/inventories/related/sources/list/sources-list.partial.html
Labels: mergeit

#5665 Only warn when license is exceeded non-fatally
  awx/main/management/commands/inventory_import.py
Labels: mergeit

#5671 remove JobTemplate.job_type = 'scan'
  awx/main/migrations/0104_v370_cleanup_old_scan_jts.py
  awx/main/models/jobs.py
Labels: mergeit

#5597 Add kubectl / oc-specific API server version logic
  installer/roles/kubernetes/tasks/kubernetes.yml
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/tasks/openshift.yml
Labels: mergeit

#5674 Set reasonable default for MAX_FORKS
  awx/main/conf.py
Labels: mergeit

#5661 Warn Louder When ask_extra_vars Should be Set to True But is Not
  awx_collection/README.md
  awx_collection/plugins/modules/tower_job_launch.py
Labels: component:awx_collection, mergeit

#5584 [AWX collection] Add test for deprecated vault_credential
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_job_template.py
Labels: component:api, mergeit, type:bug

#5664 Add Credential Detail view
  awx/main/models/credential/__init__.py
  awx/ui_next/src/screens/Credential/Credential.jsx
  awx/ui_next/src/screens/Credential/Credential.test.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.test.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/index.js
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.test.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.test.jsx
  awx/ui_next/src/screens/Credential/Credentials.jsx
  awx/ui_next/src/screens/Credential/shared/data.credential_type.json
  awx/ui_next/src/screens/Credential/shared/data.credentials.json
  awx/ui_next/src/screens/Credential/shared/index.js
Labels: component:ui_next, mergeit

#5681 Remove form card header close button
  awx/ui_next/src/screens/Inventory/InventoryAdd/InventoryAdd.jsx
  awx/ui_next/src/screens/Inventory/InventoryAdd/InventoryAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.test.jsx
  awx/ui_next/src/screens/Team/TeamAdd/TeamAdd.jsx
  awx/ui_next/src/screens/Team/TeamAdd/TeamAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/User/UserAdd/UserAdd.jsx
  awx/ui_next/src/screens/User/UserAdd/UserAdd.test.jsx
Labels: component:ui_next, mergeit

#5677 do not apply distinct for series of only static fields
  awx/api/filters.py
  awx/main/tests/unit/api/test_filters.py
  awx/main/tests/unit/utils/test_filters.py
Labels: mergeit

#5600 Adds Toggle, Variables, User Link and Delete to Inventory Host/Host Details
  awx/ui_next/src/components/AddRole/SelectResourceStep.jsx
  awx/ui_next/src/components/RoutedTabs/RoutedTabs.jsx
  awx/ui_next/src/screens/Host/Host.jsx
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.jsx
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.test.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.test.jsx
  awx/ui_next/src/screens/Host/Hosts.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHosts.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/index.js
Labels: component:ui_next, mergeit, type:enhancement

#5622 PatternFly select component
  awx/ui_next/src/components/MultiSelect/MultiSelect.jsx
  awx/ui_next/src/components/MultiSelect/MultiSelect.test.jsx
  awx/ui_next/src/components/MultiSelect/TagMultiSelect.jsx
  awx/ui_next/src/components/MultiSelect/TagMultiSelect.test.jsx
  awx/ui_next/src/components/MultiSelect/index.js
  awx/ui_next/src/components/MultiSelect/useSyncedSelectValue.js
  awx/ui_next/src/screens/Template/shared/LabelSelect.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.test.jsx
Labels: component:ui_next, mergeit, type:enhancement

#5688 Upgrade to Formik 2.1.2
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/components/CodeMirrorInput/VariablesField.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesField.test.jsx
  awx/ui_next/src/components/FormField/CheckboxField.jsx
  awx/ui_next/src/components/FormField/FormField.jsx
  awx/ui_next/src/components/FormField/PasswordField.jsx
  awx/ui_next/src/components/FormField/PasswordField.test.jsx
  awx/ui_next/src/screens/Host/shared/HostForm.jsx
  awx/ui_next/src/screens/Host/shared/HostForm.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostAdd/InventoryHostAdd.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryHostForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryHostForm.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/InsightsSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/ManualSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SharedFields.jsx
  awx/ui_next/src/screens/Team/shared/TeamForm.jsx
  awx/ui_next/src/screens/Team/shared/TeamForm.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/User/shared/UserForm.jsx
  awx/ui_next/src/screens/User/shared/UserForm.test.jsx
Labels: component:ui_next, mergeit

#5697 remove an unnecessary settings optimzation
  awx/conf/settings.py
Labels: mergeit

#5654 Fixes navigation bug in InventoryAdd Adds SCM Branch field on JTForm
  awx/ui_next/src/screens/Inventory/InventoryAdd/InventoryAdd.jsx
  awx/ui_next/src/screens/Inventory/InventoryAdd/InventoryAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
Labels: component:ui_next, mergeit, state:needs_review

#5696 Use the default cloud name if one isn't passed to azure plugin
  awx/main/credential_plugins/azure_kv.py
Labels: mergeit, type:bug

#5695 add redirect to login on 401
  awx/ui_next/src/components/ContentError/ContentError.jsx
Labels: component:ui_next, mergeit

#5694 Fail Gracefully on tower_job_launch Module When JT is Not Found
  awx_collection/plugins/modules/tower_job_launch.py
Labels: component:awx_collection, mergeit, type:bug

#5678 Fetch new inventory when location changes
  awx/ui_next/src/app.scss
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/Inventory.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
Labels: component:ui_next, mergeit

#5669 Remove two unused parent relationships from JobEvent model
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0105_v370_remove_jobevent_parent_and_hosts.py
  awx/main/models/events.py
Labels: component:api, mergeit, type:enhancement

#5705 Ensures Variables Details renders even when no value.
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.test.jsx
Labels: component:ui_next, mergeit

#5709 Fixes crontab for gather_analytics to run once every 4 hours
  awx/settings/defaults.py
Labels: mergeit

#5713 Fix some lint
  awx/main/dispatch/worker/callback.py
  awx/main/models/unified_jobs.py
Labels: mergeit

#5723 Scan jobs have been removed, clean up old refs
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/unit/test_access.py
  awx_collection/plugins/modules/tower_job_launch.py
  awxkit/awxkit/api/pages/job_templates.py
  awxkit/awxkit/api/resources.py
Labels: mergeit

#5715 RoutedTabs component - Replace router HOC with hooks
  awx/ui_next/src/components/RoutedTabs/RoutedTabs.jsx
  awx/ui_next/src/components/RoutedTabs/RoutedTabs.test.jsx
  awx/ui_next/src/screens/Credential/Credential.jsx
  awx/ui_next/src/screens/Host/Host.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroup/InventoryGroup.jsx
  awx/ui_next/src/screens/Inventory/SmartInventory.jsx
  awx/ui_next/src/screens/Job/Job.jsx
  awx/ui_next/src/screens/Organization/Organization.jsx
  awx/ui_next/src/screens/Project/Project.jsx
  awx/ui_next/src/screens/Team/Team.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/User/User.jsx
Labels: component:ui_next, mergeit

#5706 Add data-cy attributes for Inventory and Inventory Hosts
  awx/ui_next/src/screens/Inventory/InventoryDetail/InventoryDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupDetail/InventoryGroupDetail.jsx
Labels: component:ui_next, mergeit

#5718 Pin zipp to avoid setuptools upgrade
  requirements/requirements_setup_requires.txt
Labels: component:api, mergeit, type:bug

#5721 Change how analytics is gathered to only gather once per interval
  awx/conf/fields.py
  awx/main/conf.py
  awx/main/tasks.py
  awx/settings/defaults.py
  awx/ui/client/src/configuration/forms/system-form/sub-forms/system-misc.form.js
Labels: mergeit, type:enhancement

#5728 Fix timedelta comparison to account for large intervals
  awx/main/tasks.py
Labels: mergeit

#5714 Use directory alias for imports instead of relative path in our test files
  awx/ui_next/src/api/models/Organizations.test.jsx
  awx/ui_next/src/components/About/About.test.jsx
  awx/ui_next/src/components/AddRole/AddResourceRole.test.jsx
  awx/ui_next/src/components/AddRole/SelectResourceStep.test.jsx
  awx/ui_next/src/components/AddRole/SelectRoleStep.test.jsx
  awx/ui_next/src/components/AnsibleSelect/AnsibleSelect.test.jsx
  awx/ui_next/src/components/BrandLogo/BrandLogo.test.jsx
  awx/ui_next/src/components/CardCloseButton/CardCloseButton.test.jsx
  awx/ui_next/src/components/ContentEmpty/ContentEmpty.test.jsx
  awx/ui_next/src/components/ContentError/ContentError.test.jsx
  awx/ui_next/src/components/ContentLoading/ContentLoading.test.jsx
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.test.jsx
  awx/ui_next/src/components/ExpandCollapse/ExpandCollapse.test.jsx
  awx/ui_next/src/components/FormActionGroup/FormActionGroup.test.jsx
  awx/ui_next/src/components/NotificationList/NotificationListItem.test.jsx
  awx/ui_next/src/components/PageHeaderToolbar/PageHeaderToolbar.test.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarAddButton.test.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.test.jsx
  awx/ui_next/src/components/Pagination/Pagination.test.jsx
  awx/ui_next/src/components/Search/Search.test.jsx
  awx/ui_next/src/components/Sort/Sort.test.jsx
  awx/ui_next/src/components/Sparkline/Sparkline.test.jsx
Labels: component:ui, component:ui_next, mergeit

#5707 Allow CTiT log level to log bulk_create lines
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#5733 Fix overzealous cleanup in awxkit
  awxkit/awxkit/api/pages/job_templates.py
Labels: mergeit

#5699 Make VariablesField detect correct mode on mount
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesField.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesField.test.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesInput.jsx
  awx/ui_next/src/components/CodeMirrorInput/constants.js
Labels: component:ui_next, mergeit, type:bug

#5729 add a script for quickly inserting lots of events
  tools/scripts/firehose.py
Labels: mergeit

#5739 further optimize conf.settings access when logging is enabled
  awx/conf/settings.py
  awx/main/utils/formatters.py
  awx/main/utils/handlers.py
Labels: mergeit

#5732 optimize awx-manage callback_stats for larger datasets
  awx/main/management/commands/callback_stats.py
Labels: mergeit

#5740 Fixes InvGroup Form submission error and TemplateList Missing Resource Bug
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/InventoryGroupAdd.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupAdd/InventoryGroupAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.test.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplatesListItem.test.jsx
Labels: component:ui_next, mergeit, type:bug

#5749 fix a bug that causes __search filters to not properly call .distinct()
  awx/api/filters.py
Labels: mergeit

#5734 Add inventory host edit form
  awx/ui_next/src/screens/Host/Host.jsx
  awx/ui_next/src/screens/Host/Host.test.jsx
  awx/ui_next/src/screens/Host/HostAdd/HostAdd.jsx
  awx/ui_next/src/screens/Host/HostAdd/HostAdd.test.jsx
  awx/ui_next/src/screens/Host/HostEdit/HostEdit.jsx
  awx/ui_next/src/screens/Host/HostEdit/HostEdit.test.jsx
  awx/ui_next/src/screens/Host/Hosts.jsx
  awx/ui_next/src/screens/Host/shared/HostForm.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostAdd/InventoryHostAdd.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostAdd/InventoryHostAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostAdd/index.js
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHosts.jsx
Labels: component:ui_next, mergeit

#5748 Add delete button to Organization and Project Details
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.test.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.test.jsx
Labels: component:ui_next, mergeit

#5753 Fix help for new analytics gather interval
  awx/main/conf.py
Labels: mergeit

#5750 made licensing a warning and not trigger on periodic scheduler
  awx/main/access.py
  awx/main/tasks.py
Labels: component:api, mergeit, type:enhancement

#5751 Inventory details refresh
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.test.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventoryDetail/InventoryDetail.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
Labels: component:ui_next, mergeit, type:bug

#5762 remove another expensive logging lookup in the parent callback process
  awx/main/dispatch/pool.py
Labels: mergeit

#5752 Add delete button to Job Template details
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/index.js
  awx/ui_next/src/screens/Template/shared/data.job_template.json
Labels: component:ui_next, mergeit

#5754 Add delete button to User and Team details
  awx/ui_next/src/screens/Host/HostAdd/HostAdd.test.jsx
  awx/ui_next/src/screens/Team/TeamDetail/TeamDetail.jsx
  awx/ui_next/src/screens/Team/TeamDetail/TeamDetail.test.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.test.jsx
  awx/ui_next/src/screens/User/data.user.json
Labels: component:ui_next, mergeit

#5773 add the ability to enable profiling for the callback receiver workers
  awx/main/dispatch/worker/callback.py
  awx/settings/defaults.py
Labels: mergeit

#5742 Upgrade babel in ui_next
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui_next, mergeit

#5772 JT Form Generate Labels
  awx/ui_next/src/api/models/JobTemplates.js
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.test.jsx
Labels: component:ui_next, mergeit

#5779 some more minor callback cleanup and development tweaks
  awx/conf/settings.py
  awx/main/dispatch/worker/base.py
  awx/main/utils/formatters.py
  awx/settings/development.py
Labels: mergeit

#5781 Reduce logging complexity with setting DB errors
  awx/conf/settings.py
Labels: component:api, mergeit, type:enhancement

#5782 requirements_setup_requires: Top limit wheel to less than 42.0.0
  requirements/requirements_setup_requires.txt
Labels: mergeit

#5784 Fix to handle Str and JSON mix-in data correctly with settings API
  Makefile
  awxkit/awxkit/cli/custom.py
Labels: mergeit

#5786 Fix organization team links
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.test.jsx
  awx/ui_next/src/screens/Team/Team.jsx
  awx/ui_next/src/screens/Team/Team.test.jsx
  awx/ui_next/src/screens/Team/TeamList/index.js
  awx/ui_next/src/screens/Team/Teams.jsx
Labels: component:ui_next, mergeit, type:bug

#5788 Fix host details and list sparkline links
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.jsx
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.test.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.test.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.test.jsx
Labels: component:ui_next, mergeit, type:bug

#5585 Do not allow state where no Galaxy servers are enabled
  awx/main/conf.py
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#5793 Open collection config 'r' for py3 compatibility
  awx_collection/plugins/module_utils/ansible_tower.py
Labels: mergeit

#5801 when a license is installed, only set TOWER_URL_BASE if necessary
  awx/api/views/root.py
Labels: mergeit

#5598 add ability to read ansible_want_ssh_host, rich_params and want_facts to source vars for satellite dynamic inventory
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/scripts/satellite6/files/file_reference
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, type:enhancement
