Repository ansible/awx, pull requests merged in 2020-05, with the labels that each got.

#6910 merge in a few downstream fixes
  awx/api/serializers.py
  awx/main/dispatch/worker/base.py
  awx/main/tasks.py
  awx/ui/client/src/inventories-hosts/inventories/related/sources/sources.form.js
Labels: mergeit

#6909 Allow performing git project updates when Ansible 2.10 (ansible-base) is installed
  awx/playbooks/project_update.yml
  awx/playbooks/project_update_hg_tasks.yml
Labels: component:api, mergeit, type:bug

#6912 Remove defunct entry from view method return tuple
  awx/api/views/__init__.py
Labels: component:api, mergeit

#6900 Adds Sync Functionality to Inventory Source List
  awx/ui_next/src/api/models/InventorySources.js
  awx/ui_next/src/api/models/InventoryUpdates.js
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceSyncButton.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceSyncButton.test.jsx
Labels: component:ui_next, mergeit, state:needs_review

#6846 Copy Feature for Templates and Credentials
  awx/ui_next/src/api/Base.js
  awx/ui_next/src/components/CopyButton/CopyButton.jsx
  awx/ui_next/src/components/CopyButton/CopyButton.test.jsx
  awx/ui_next/src/components/CopyButton/index.js
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.test.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.test.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.test.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.test.jsx
  awx/ui_next/src/util/dates.jsx
Labels: component:ui_next, mergeit, state:needs_test, type:feature

#6915 remove memcached based fact caching plugin
  awx/plugins/fact_caching/awx.py
Labels: mergeit

#6943 merge in a few downstream fixes
  awx/main/consumers.py
  awx/main/migrations/0115_v370_schedule_set_null.py
  awx/main/models/inventory.py
  awx/main/models/unified_jobs.py
  awx/main/tests/data/inventory/plugins/rhv/files/ovirt.yml
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  requirements/collections_requirements.yml
  tools/collections/clone_vendor.sh
  tools/docker-compose/Dockerfile
Labels: mergeit

#6942 Fix tower_job_template module so that params are not overridden (unless specified) in subsequent tasks
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#6948 Fix installer for oc 4.3
  installer/roles/kubernetes/tasks/openshift_auth.yml
  installer/roles/kubernetes/vars/openshift.yml
Labels: mergeit

#6964 Add Notification Association Functionality to tower_workflow_job_template Module
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/test/awx/test_workflow_job_template.py
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#6965 Update JT Integration Test
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit

#6924 Fix Survey, check label 'Required' translation
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.jsx
Labels: component:ui_next, mergeit

#6926 Fix Button 'Create' - to be marked for translation
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
Labels: component:ui_next, mergeit

#6898 Add inventory source create form
  awx/ui_next/src/api/models/Projects.js
  awx/ui_next/src/components/FormField/CheckboxField.jsx
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceAdd/InventorySourceAdd.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceAdd/InventorySourceAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceAdd/index.js
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySources.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySources.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SharedFields.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/index.js
Labels: component:ui_next, mergeit

#6916 Use Webhook Fields in WFJT Form
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
  awx/ui_next/src/types.js
Labels: component:ui_next, mergeit

#6974 Document node and npm installation prerequisites
  INSTALL.md
Labels: mergeit

#6980 merge in a few downstream fixes
  awx/__init__.py
  awx/conf/views.py
  awx/locale/es/LC_MESSAGES/django.po
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/nl/LC_MESSAGES/django.po
  awx/locale/zh/LC_MESSAGES/django.po
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/conftest.py
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
  awx/main/tests/data/inventory/scripts/satellite6/files/file_reference
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/utils/common.py
  awx/main/utils/external_logging.py
  awx/ui/po/es.po
  awx/ui/po/fr.po
  awx/ui/po/ja.po
  awx/ui/po/nl.po
  awx/ui/po/zh.po
  installer/roles/image_build/files/supervisor.conf
  installer/roles/kubernetes/templates/supervisor.yml.j2
  tools/docker-compose/supervisor.conf
Labels: mergeit

#6979 Remove pexpect_timeout setting for ansible-runner
  awx/main/isolated/manager.py
  awx/main/tasks.py
Labels: mergeit

#6937 adds description-based search to templates list
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
Labels: mergeit

#6936 add defaults to qs instead of passing as additional params to api requests
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/screens/Job/Jobs.jsx
Labels: mergeit

#6940 make job id search use number field
  awx/ui_next/src/components/JobList/JobList.jsx
Labels: mergeit

#6993 added try/except to virtual env
  awx/main/utils/common.py
Labels: component:api, mergeit, type:bug

#6994 Remove extraneous re-install of rsyslog
  tools/docker-compose/Dockerfile
Labels: mergeit

#6935 Add `Preview`, `more` and `Show Less` for translation
  awx/ui_next/src/components/ChipGroup/ChipGroup.jsx
  awx/ui_next/src/components/ChipGroup/ChipGroup.test.jsx
  awx/ui_next/src/components/ChipGroup/index.js
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptInventorySourceDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptJobTemplateDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptWFJobTemplateDetail.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/SelectedList/SelectedList.jsx
  awx/ui_next/src/components/SelectedList/SelectedList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryDetail/InventoryDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
Labels: component:ui_next, mergeit

#6955 JT Launch prompt preview & validation
  awx/ui_next/src/components/ErrorDetail/getErrorMessage.js
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.test.jsx
  awx/ui_next/src/components/LaunchPrompt/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/getSurveyValues.js
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.js
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.test.js
  awx/ui_next/src/components/LaunchPrompt/steps/CredentialsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/CredentialsStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/InventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/InventoryStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/StepName.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/SurveyStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useCredentialsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useInventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useOtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/usePreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useSurveyStep.jsx
  awx/ui_next/src/components/LaunchPrompt/useSteps.js
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.test.jsx
  awx/ui_next/src/types.js
Labels: component:ui_next, mergeit

#6975 Add inventory source detail view
  awx/ui_next/src/api/models/Inventories.js
  awx/ui_next/src/api/models/InventorySources.js
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/Inventory.jsx
  awx/ui_next/src/screens/Inventory/InventorySource/InventorySource.jsx
  awx/ui_next/src/screens/Inventory/InventorySource/InventorySource.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySource/index.js
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/index.js
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySources.jsx
  awx/ui_next/src/screens/Inventory/shared/data.inventory_source.json
Labels: component:ui_next, mergeit, state:needs_test

#7001 Adds Teams Access List and tests
  awx/api/serializers.py
  awx/ui_next/src/api/models/Teams.js
  awx/ui_next/src/screens/Team/Team.jsx
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessList.jsx
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessList.test.jsx
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessListItem.jsx
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessListItem.test.jsx
  awx/ui_next/src/screens/Team/TeamAccess/index.js
Labels: component:ui_next, mergeit, state:needs_review

#6952 Adds Copy Button to Inventory List and Project List
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.test.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.test.jsx
Labels: component:ui_next, mergeit, state:needs_review, state:needs_test

#6989 Update strings to follow `sentence capitalization` style
  awx/ui_next/CONTRIBUTING.md
  awx/ui_next/src/components/CodeMirrorInput/VariablesField.jsx
  awx/ui_next/src/components/FieldWithPrompt/FieldWithPrompt.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
Labels: component:ui_next, mergeit

#6992 drastically optimize job host summary creation
  awx/main/models/events.py
  awx/main/models/jobs.py
  awx/main/tasks.py
  awx/main/tests/functional/models/test_events.py
Labels: mergeit

#6949 Vendor collections for isolated jobs to work in ansible 2.10
  awx/main/isolated/manager.py
  awx/main/management/commands/inventory_import.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/playbooks/check_isolated.yml
  awx/playbooks/run_isolated.yml
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  docs/inventory/inventory_plugins.md
  installer/roles/image_build/files/settings.py
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/kubernetes/templates/configmap.yml.j2
  requirements/collections_requirements.yml
  requirements/requirements_dev.txt
  tools/collections/README.md
  tools/docker-compose/Dockerfile
Labels: component:api, component:installer, mergeit, type:bug

#7009 fix websocket stats on kubernetes
  awx/main/wsbroadcast.py
Labels: mergeit

#7013 fix schema check
  awx/main/tests/docs/test_swagger_generation.py
Labels: mergeit

#7003 Fix launch prompt errors when no survey present
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useInventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useSurveyStep.jsx
Labels: component:ui_next, mergeit

#7020 Support adding/removing notifications to multiple awx modules
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
Labels: component:awx_collection, mergeit, type:enhancement

#7029 Remove redundant dev image build make target
  Makefile
Labels: mergeit, type:enhancement

#7026 (docs): enabled syntax highlighting for http patch
  docs/cors.md
  docs/custom_virtualenvs.md
Labels: mergeit

#7014 Update usage of new custom `ChipGroup`
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
Labels: component:ui_next, mergeit

#7017 Rework dev & prod container builds
  .gitignore
  Makefile
  installer/roles/image_build/defaults/main.yml
  installer/roles/image_build/files/google-cloud-sdk.repo
  installer/roles/image_build/files/rsyslog.repo
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/Dockerfile
  tools/docker-compose/ansible_nightly.repo
  tools/docker-compose/google-cloud-sdk.repo
  tools/docker-compose/proot.repo
  tools/docker-compose/rsyslog.conf
  tools/docker-compose/rsyslog.repo
Labels: mergeit

#7030 Clearing Up Linter Errors
  awx/asgi.py
  awx/main/management/commands/callback_stats.py
  awx/main/models/inventory.py
  awx/main/scheduler/dag_simple.py
  awx/main/signals.py
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
  awx/main/tests/factories/tower.py
  awx/main/tests/functional/analytics/test_collectors.py
  awx/main/tests/functional/commands/test_secret_key_regeneration.py
  awx/main/tests/functional/test_dispatch.py
  awx/settings/defaults.py
  requirements/requirements_dev.txt
Labels: mergeit

#7032 stop pre-generating awx.egg-info for the development environment
  Makefile
  installer/roles/image_build/templates/Dockerfile.j2
  tools/docker-compose/awx.egg-info/PKG-INFO
  tools/docker-compose/awx.egg-info/SOURCES.txt
  tools/docker-compose/awx.egg-info/dependency_links.txt
  tools/docker-compose/awx.egg-info/entry_points.txt
  tools/docker-compose/awx.egg-info/not-zip-safe
  tools/docker-compose/awx.egg-info/top_level.txt
  tools/docker-compose/start_tests.sh
Labels: mergeit

#7038 mark the idle dialog continue button for translation
  awx/ui/client/src/login/authenticationServices/timer.factory.js
Labels: mergeit

#7039 merge in a few downstream fixes
  Makefile
  awx/locale/ja/LC_MESSAGES/django.po
  awx/main/models/inventory.py
  awx/main/routing.py
  awx/main/tests/data/inventory/plugins/rhv/files/ovirt.yml
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/settings/defaults.py
  awx/ui/po/ja.po
  requirements/requirements_ansible_uninstall.txt
Labels: mergeit

#7044 foreman: use group_prefix for all groups
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/satellite6/files/foreman.yml
Labels: mergeit

#7046 Remove unneeded dockerfile-sync
  tools/docker-compose/Dockerfile-sync
Labels: component:installer, mergeit

#6950 Adds Inventory Source Sync Button
  awx/ui_next/src/api/models/Inventories.js
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceSyncButton.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceSyncButton.test.jsx
Labels: component:ui_next, mergeit, state:needs_test

#6743 Adding version checking to collection
  Makefile
  awx_collection/plugins/doc_fragments/auth.py
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/template_galaxy.yml
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_credential.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/test/awx/test_module_utils.py
  awx_collection/test/awx/test_project.py
  awx_collection/test/awx/test_send_receive.py
  awx_collection/test/awx/test_user.py
  awx_collection/tools/generate.yml
  awx_collection/tools/roles/generate/tasks/main.yml
  awx_collection/tools/roles/generate/templates/tower_module.j2
  awx_collection/tools/roles/template_galaxy/tasks/main.yml
  awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2
  awx_collection/tools/template_galaxy.yml
Labels: component:awx_collection, mergeit, type:enhancement

#7045 Mark job_explanation strings after they are read from the db
  awx/api/serializers.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/functional/models/test_notifications.py
Labels: component:api, mergeit, type:bug

#7048 Update PO and POT translation files for 11.2.0
  awx/locale/django.pot
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/ui/po/ansible-tower-ui.pot
Labels: component:l10n, mergeit

#7065 Fixes bug where all_parents_must_converge was not being set for new or existing approval nodes
  awx/ui/client/src/templates/workflows/workflow-maker/workflow-maker.controller.js
Labels: component:ui, mergeit, state:needs_review

#7042 Enable management job notications for admins
  awx/ui/client/src/management-jobs/notifications/notification.controller.js
  awx/ui/client/src/management-jobs/notifications/notification.route.js
Labels: component:ui, mergeit

#6699 Adds support for GCE credentials in credential form(s)
  awx/ui_next/src/components/FormField/FormField.jsx
  awx/ui_next/src/screens/Credential/Credential.test.jsx
  awx/ui_next/src/screens/Credential/CredentialAdd/CredentialAdd.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialSubForms/GoogleComputeEngineSubForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialSubForms/SharedFields.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialSubForms/SourceControlSubForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialSubForms/index.js
  awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json
  awx/ui_next/src/screens/Credential/shared/data.gceCredential.json
  awx/ui_next/src/screens/Credential/shared/data.machineCredential.json
  awx/ui_next/src/screens/Credential/shared/data.scmCredential.json
Labels: component:ui_next, mergeit, type:enhancement

#7069 Remove obsolete settings
  awx/main/conf.py
  awx/settings/defaults.py
  awx/settings/production.py
  installer/roles/image_build/files/settings.py
  installer/roles/kubernetes/templates/configmap.yml.j2
Labels: mergeit

#6988 6946 survey form validation error
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionAdd.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionEdit.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.test.jsx
Labels: component:ui_next, mergeit, state:needs_review, type:bug

#7071 AWX installer docker-compose params `host_port` and `host_port_ssl` can also be undefined to prevent exposing a port.
  INSTALL.md
  installer/roles/check_vars/tasks/check_docker.yml
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, type:enhancement

#7087 speed up .egg-info generation on certain systems
  Makefile
  setup.py
Labels: mergeit

#7084 make the run_wsbroadcast command less noisy at startup
  awx/conf/settings.py
  awx/main/management/commands/run_wsbroadcast.py
Labels: mergeit

#7077 Retry chromium download in zuul
  Makefile
  awx/ui/build/zuul_download_chromium.sh
  awx/ui/test/spec/karma.spec.js
  awx/ui/test/unit/karma.unit.js
  installer/roles/image_build/templates/Dockerfile.j2
Labels: component:installer, component:ui, mergeit

#7080 Make consistent usage of `pluralizedItemName` for internationalization
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeams.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
Labels: component:ui_next, mergeit

#7089 Use man pages
  awx/ui/build/zuul_download_chromium.sh
Labels: mergeit

#7023 Modify handleDelete for JobTemplateDetails and WorkflowJobTemplateDetail
  awx/ui_next/src/components/DeleteButton/DeleteButton.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
Labels: component:ui_next, mergeit

#7088 Fix rsyslog in the dev env by using a local dir volume
  tools/docker-compose.yml
  tools/rsyslog/.dir_placeholder
Labels: mergeit

#7082 Narrow function of task to be strictly role install
  awx/playbooks/project_update.yml
Labels: mergeit

#7098 Fix artifact builds
  requirements/requirements_ansible.txt
Labels: mergeit

#7079 Always check configuration before gathering data.
  awx/main/tasks.py
Labels: mergeit

#7106 Revert "follow symlinks while discovering valid playbooks"
  awx/main/models/projects.py
  awx/main/utils/ansible.py
Labels: mergeit

#7108 Make consistent usage of `useRequest` to delete items
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Team/TeamDetail/TeamDetail.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.jsx
Labels: component:ui_next, mergeit

#7035 Add source control branch to prompt launch
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui_next, mergeit

#7075 Remove HipChat Notification Type
  CHANGELOG.md
  awx/main/migrations/0116_v400_remove_hipchat_notifications.py
  awx/main/models/notifications.py
  awx/main/notifications/hipchat_backend.py
  awx/ui/client/src/notifications/notificationTemplates.form.js
  awx_collection/README.md
  awx_collection/plugins/modules/tower_notification.py
  awx_collection/tests/integration/targets/tower_notification/tasks/main.yml
  docs/notification_system.md
Labels: component:api, mergeit

#7028 Add inventory source edit form
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.test.jsx
  awx/ui_next/src/screens/Inventory/Inventories.jsx
  awx/ui_next/src/screens/Inventory/InventorySource/InventorySource.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceAdd/InventorySourceAdd.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceEdit/InventorySourceEdit.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceEdit/InventorySourceEdit.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceEdit/index.js
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
Labels: component:ui_next, mergeit

#7114 don't use symlinks for awxkit VERSION
  Makefile
  awxkit/VERSION
Labels: mergeit

#7027 Add basic output updates with websockets
  awx/ui_next/README.md
  awx/ui_next/package.json
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
  awx/ui_next/src/setupProxy.js
Labels: component:ui_next, mergeit

#6733 Initial version of tower_schedule
  Makefile
  awx_collection/plugins/lookup/tower_schedule_rrule.py
  awx_collection/plugins/modules/tower_schedule.py
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_schedule.py
  awx_collection/tests/integration/targets/tower_schedule/tasks/main.yml
  awx_collection/tests/integration/targets/tower_schedule_rrule/tasks/main.yml
Labels: component:awx_collection, mergeit, state:needs_devel, type:enhancement

#7085 Add inventory source detail sync button
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSyncButton.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSyncButton.test.jsx
Labels: component:ui_next, mergeit

#7117 add some recent changes to the changelog for the next major release
  CHANGELOG.md
Labels: mergeit

#7146 Fixing tower_schedule oauth_token
  awx_collection/plugins/modules/tower_schedule.py
Labels: component:awx_collection, mergeit

#7110 Tower job template webhook service
  awx_collection/plugins/modules/tower_job_template.py
Labels: component:awx_collection, mergeit, type:bug

#7101 make Inventory optional if prompt-on-launch is true
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui_next, mergeit

#7034 Fixes ca_trust_dir mapping for k8s and openshift
  installer/inventory
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: component:api, mergeit, type:bug

#7120 Add option to follow symlinks when scanning for playbooks
  awx/main/conf.py
  awx/main/models/projects.py
  awx/settings/defaults.py
  awx/ui/client/src/configuration/forms/jobs-form/configuration-jobs.form.js
Labels: component:ui, mergeit, type:enhancement

#7068 Upgrade patternfly deps to latest stable versions
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: mergeit, state:needs_test

#7167 fix a typo in the playbook discovery tooling
  awx/main/models/projects.py
Labels: mergeit

#7147 Fix Approval Notifications for PagerDuty
  CHANGELOG.md
  awx/main/notifications/pagerduty_backend.py
Labels: component:api, mergeit, state:needs_review, type:bug

#7113 Fix inventory group host list error modal dismissal
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.test.jsx
Labels: component:ui_next, mergeit, type:bug

#7159 Correctly parse sumologic url paths
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
Labels: mergeit, state:needs_review

#7169 Update Pagerduty and Grafana Approval Notifications
  awx/main/notifications/grafana_backend.py
  awx/main/notifications/pagerduty_backend.py
Labels: component:api, mergeit

#7149 Update meta/routing.yml (to meta/runtime.yml) for AWX Collection
  awx_collection/meta/runtime.yml
Labels: component:awx_collection, mergeit

#7175 remove the usage of create_temporary_fifo from credential plugins
  CHANGELOG.md
  awx/main/credential_plugins/aim.py
  awx/main/credential_plugins/conjur.py
  awx/main/credential_plugins/hashivault.py
  awx/main/credential_plugins/plugin.py
Labels: mergeit

#7178 add a changelog note for the sumologic token fix
  CHANGELOG.md
Labels: mergeit

#7124 vmware_vm_inventory: Replace guest.guestId with config.guestId
  awx/main/models/inventory.py
  awx/main/tests/data/inventory/plugins/vmware/files/vmware_vm_inventory.yml
Labels: mergeit, type:bug

#6265 Add support for importing host/group descriptions
  awx/main/management/commands/inventory_import.py
Labels: mergeit, state:needs_docs, type:enhancement

#7171 Add "of" to "Run on" field in schedule form
  awx/ui_next/src/components/Schedule/shared/FrequencyDetailSubform.jsx
Labels: component:ui_next, mergeit

#7182 Add Wizard buttons as internationalization
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
Labels: component:ui_next, mergeit

#7177 Set event time and date in firehose script
  tools/scripts/firehose.py
Labels: mergeit

#7168 Absent not working for tower_workflow_job_template_node Fix
  awx_collection/plugins/module_utils/tower_api.py
Labels: component:awx_collection, mergeit, type:bug

#7172 Preserve extra_vars when they are not prompted
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.js
  awx/ui_next/src/components/LaunchPrompt/mergeExtraVars.test.js
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.test.jsx
Labels: component:ui_next, mergeit

#7143 [WIP] Allow org admins to remove labels
  awx/main/access.py
Labels: component:api, mergeit, type:enhancement

#7103 Adds support to user and team access add
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/AddRole/CheckboxCard.jsx
  awx/ui_next/src/components/AddRole/SelectResourceStep.jsx
  awx/ui_next/src/components/AddRole/SelectResourceStep.test.jsx
  awx/ui_next/src/components/UserAndTeamAccessAdd/UserAndTeamAccessAdd.jsx
  awx/ui_next/src/components/UserAndTeamAccessAdd/UserAndTeamAccessAdd.test.jsx
  awx/ui_next/src/components/UserAndTeamAccessAdd/getResourceAccessConfig.js
  awx/ui_next/src/components/UserAndTeamAccessAdd/index.js
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessList.jsx
  awx/ui_next/src/screens/Team/TeamAccess/TeamAccessList.test.jsx
  awx/ui_next/src/screens/User/UserAccess/UserAccessList.jsx
  awx/ui_next/src/screens/User/UserAccess/UserAccessList.test.jsx
Labels: component:ui_next, mergeit

#7185 Add subnet configuration to Docker Compose to avoid conflicts.
  installer/inventory
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:installer, mergeit, type:enhancement

#7190 Stop bouncing k8s deployment post-install
  installer/roles/kubernetes/tasks/main.yml
Labels: mergeit

#7189 Hardcode --kubeconfig and therefore only support OpenShift 3.11+
  installer/roles/kubernetes/tasks/openshift_auth.yml
  installer/roles/kubernetes/vars/openshift.yml
Labels: mergeit
