Repository ansible/awx, pull requests merged in 2021-02, with the labels that each got.

#9203 Update with the new logo
  README.md
Labels: mergeit

#9104 Survey logic for awx modules
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/plugins/modules/tower_workflow_launch.py
  awx_collection/tests/integration/targets/tower_job_launch/tasks/main.yml
  awx_collection/tests/integration/targets/tower_workflow_launch/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#6106 Support for Github Enteprise for authentication
  awx/main/tests/functional/api/test_settings.py
  awx/settings/defaults.py
  awx/sso/conf.py
  awx/sso/fields.py
  awx/ui_next/src/screens/Login/Login.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHub.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHub.test.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubDetail/GitHubDetail.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubDetail/GitHubDetail.test.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseEdit/GitHubEnterpriseEdit.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseEdit/GitHubEnterpriseEdit.test.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseEdit/index.js
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseOrgEdit/GitHubEnterpriseOrgEdit.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseOrgEdit/GitHubEnterpriseOrgEdit.test.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseOrgEdit/index.js
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseTeamEdit/GitHubEnterpriseTeamEdit.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseTeamEdit/GitHubEnterpriseTeamEdit.test.jsx
  awx/ui_next/src/screens/Setting/GitHub/GitHubEnterpriseTeamEdit/index.js
  awx/ui_next/src/screens/Setting/Settings.jsx
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
  docs/auth/README.md
Labels: component:api, component:ui, mergeit, state:needs_test, type:enhancement, type:feature

#9185 Add orgs job launch
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/tests/integration/targets/tower_job_launch/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#9094 Adds translation linting and addresses issues the linter found
  awx/ui_next/.eslintrc
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.jsx
  awx/ui_next/src/components/CodeMirrorInput/VariablesDetail.test.jsx
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/components/NotificationList/NotificationListItem.jsx
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeListItem.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateList.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateListItem.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupItem.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupListItem.jsx
  awx/ui_next/src/screens/InstanceGroup/Instances/InstanceListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupListItem.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.jsx
  awx/ui_next/src/screens/NotificationTemplate/shared/CustomMessagesSubForm.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Organization/OrganizationTeams/OrganizationTeamListItem.jsx
  awx/ui_next/src/screens/Project/ProjectJobTemplatesList/ProjectJobTemplatesListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/ArchiveSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/GitSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SvnSubForm.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/LinkModals/LinkDeleteModal.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.jsx
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.jsx
Labels: component:l10n, component:ui, mergeit

#9205 Fix Pylint Error
  awx_collection/test/awx/test_notification_template.py
Labels: flag:qe, mergeit

#9114 Convert TemplateList to PaginatedTable
  awx/ui_next/src/components/CopyButton/CopyButton.jsx
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/TemplateList/TemplateList.jsx
  awx/ui_next/src/components/TemplateList/TemplateList.test.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.test.jsx
  awx/ui_next/src/components/TemplateList/data.job_template.json
  awx/ui_next/src/components/TemplateList/index.js
  awx/ui_next/src/screens/Dashboard/Dashboard.jsx
  awx/ui_next/src/screens/Dashboard/Dashboard.test.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateList.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateList.test.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateListItem.jsx
  awx/ui_next/src/screens/Dashboard/shared/DashboardTemplateListItem.test.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Template/TemplateList/TemplateListItem.test.jsx
  awx/ui_next/src/screens/Template/Templates.jsx
Labels: component:ui, mergeit

#9216 Mark string to translation
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.jsx
Labels: component:ui, mergeit

#8869 Fix prompted values section of schedule details
  awx/ui_next/src/components/PromptDetail/PromptDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:enhancement

#9045 Convert SchedulesList, WorkflowApprovalList to tables
  awx/ui_next/.eslintrc
  awx/ui_next/src/components/PaginatedTable/ActionsTd.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.test.jsx
  awx/ui_next/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.jsx
  awx/ui_next/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.jsx
  awx/ui_next/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.test.jsx
Labels: component:ui, mergeit

#8726 Show job traceback stdout and error details
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9231 Prevent url smashing from prompted inputs
  awx/ui_next/src/components/LaunchPrompt/steps/CredentialPasswordsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/SurveyStep.jsx
Labels: component:ui, mergeit, priority:high, state:needs_test, type:bug

#9130 log job lifecycle
  awx/main/models/jobs.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/dependency_graph.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/utils/formatters.py
  awx/main/utils/handlers.py
  awx/settings/defaults.py
  docs/licenses/JSON-log-formatter.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, mergeit, type:enhancement

#9199 Add ability to cancel running jobs from output view
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
  awx/ui_next/src/screens/Job/JobOutput/shared/OutputToolbar.jsx
  awx/ui_next/src/screens/Job/JobOutput/shared/OutputToolbar.test.jsx
Labels: component:ui, mergeit, state:needs_test

#9123 Update migration page
  awx/settings/defaults.py
  awx/ui_next/apps.py
  awx/ui_next/public/installing.html
  awx/ui_next/public/static/css/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff
  awx/ui_next/public/static/css/assets/fonts/RedHatText/RedHatText-Regular.woff
  awx/ui_next/public/static/css/patternfly.min.css
  awx/ui_next/public/static/css/patternfly.min.css.map
  awx/ui_next/urls.py
Labels: component:ui, mergeit, state:needs_test

#9148 Convert Credentials & Projects lists to PaginatedTable
  awx/ui_next/src/components/PaginatedTable/HeaderRow.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.test.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.test.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.test.jsx
Labels: component:ui, mergeit, type:enhancement

#9240 Update cancel button style to "link"
  awx/ui_next/src/components/AssociateModal/AssociateModal.jsx
  awx/ui_next/src/components/DeleteButton/DeleteButton.jsx
  awx/ui_next/src/components/DisassociateButton/DisassociateButton.jsx
  awx/ui_next/src/components/FormActionGroup/FormActionGroup.jsx
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.jsx
  awx/ui_next/src/components/ResourceAccessList/DeleteRoleConfirmationModal.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/DeleteRoleConfirmationModal.test.jsx.snap
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryGroupsDeleteModal.jsx
  awx/ui_next/src/screens/Setting/shared/RevertAllAlert.jsx
  awx/ui_next/src/screens/Setting/shared/RevertFormActionGroup.jsx
  awx/ui_next/src/screens/Team/TeamRoles/TeamRolesList.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/DeleteAllNodesModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/LinkModals/LinkDeleteModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/LinkModals/LinkModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeDeleteModal.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesList.jsx
Labels: component:ui, mergeit, type:bug

#9264 Handle error state with traceback and no stdout
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
Labels: component:ui, mergeit, state:needs_review, type:bug

#9265 Fix test notifications
  awx/main/tasks.py
Labels: mergeit

#9182 Convert Hosts/Users/Teams list to tables
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.test.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.test.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamList.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.test.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/screens/User/UserList/UserList.test.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.test.jsx
Labels: component:ui, mergeit

#9274 [9273]: Add missing symlinks for awx-manage
  installer/roles/dockerfile/templates/Dockerfile.j2
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#9268 Add version to json-log-formatter in requirements.txt file
  requirements/requirements.txt
Labels: component:api, mergeit, type:bug

#9227 Add project update to project module
  awx_collection/plugins/modules/tower_project.py
  awx_collection/plugins/modules/tower_project_update.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/tower_project/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#8897 Add schedule info from summary fields to allowed notification content.
  awx/main/models/notifications.py
  awx/main/tests/functional/models/test_notifications.py
Labels: component:api, mergeit, type:enhancement

#9179 add container options to EE model
  awx/api/serializers.py
  awx/main/migrations/0126_executionenvironment_container_options.py
  awx/main/models/execution_environments.py
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentAdd/ExecutionEnvironmentAdd.test.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentDetails/ExecutionEnvironmentDetails.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentDetails/ExecutionEnvironmentDetails.test.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentEdit/ExecutionEnvironmentEdit.test.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.test.jsx
  awx_collection/plugins/modules/tower_execution_environment.py
Labels: component:api, component:ui, mergeit, type:enhancement

#9052 Update custom_virtualenvs.md
  docs/custom_virtualenvs.md
Labels: component:docs, component:installer, mergeit

#9170 Add tooltips to inventory sync status
  awx/ui_next/src/components/StatusLabel/StatusLabel.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.test.jsx
Labels: component:ui, mergeit, type:feature

#9288 Show job and skip tags on job detail view
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
  awx/ui_next/src/screens/Job/shared/data.job.json
Labels: component:ui, mergeit

#9290 Relax client-side email validator
  awx/ui_next/src/util/validators.jsx
  awx/ui_next/src/util/validators.test.js
Labels: component:ui, mergeit

#9116 Fixes missing credential types and makes credential type field a type ahead
  awx/ui_next/src/screens/Credential/CredentialAdd/CredentialAdd.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:enhancement

#9263 Update Job Detail container group variable
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
Labels: component:ui, mergeit

#9262 Migrate EE list to tables
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnviromentList.test.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.test.jsx
Labels: component:ui, mergeit

#9284 Fix awx collection docs
  awx_collection/plugins/modules/tower_instance_group.py
  awx_collection/test/awx/test_inventory_source.py
Labels: component:awx_collection, mergeit, type:bug

#9300 Fix #9298 by upgrading pip allowing use of custom_venvs
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: component:api, component:installer, component:ui, mergeit, type:enhancement

#9301 Bump ansible-runner to get the pexpect fix
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:installer, mergeit, type:bug

#9278 Fixes final files in preparation for lingui upgrade
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/components/Lookup/Lookup.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
Labels: component:ui, mergeit, type:task

#9295 add support for diff mode in tower_settings module
  awx_collection/plugins/modules/tower_settings.py
Labels: component:awx_collection, mergeit, type:enhancement

#9287 Disable inventory copy button when inventory has sources
  awx/ui_next/src/components/CopyButton/CopyButton.jsx
  awx/ui_next/src/components/CopyButton/CopyButton.test.jsx
  awx/ui_next/src/components/PaginatedTable/ActionItem.jsx
  awx/ui_next/src/components/PaginatedTable/ActionItem.test.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
Labels: component:ui, mergeit, state:needs_review, state:needs_test, type:feature

#9225 Add relaunch against failed hosts
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/JobList/JobListItem.test.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/components/LaunchButton/ReLaunchDropDown.jsx
  awx/ui_next/src/components/LaunchButton/ReLaunchDropDown.test.jsx
  awx/ui_next/src/components/LaunchButton/index.js
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobOutput/shared/OutputToolbar.jsx
  awx/ui_next/src/screens/Project/ProjectJobTemplatesList/ProjectJobTemplatesListItem.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerToolbar.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9304 Fix Openstack credential region implementation.
  awx/main/models/credential/injectors.py
  awx/main/tests/data/inventory/plugins/openstack/files/file_reference
  awx/main/tests/unit/test_tasks.py
  awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json
Labels: component:api, component:ui, mergeit, type:bug

#9306 Allow dependabot to check python dependencies
  .github/dependabot.yml
Labels: component:api, component:installer, component:ui, dependencies, mergeit

#9277 Update Patternfly to allow access to slider component
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/components/MultiButtonToggle/MultiButtonToggle.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/DeleteRoleConfirmationModal.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
Labels: component:ui, dependencies, mergeit, state:needs_devel, type:task

#9313 Fix defaults that were set to empty string in collections.
  awx_collection/plugins/modules/tower_ad_hoc_command.py
  awx_collection/plugins/modules/tower_credential_input_source.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_project.py
  awx_collection/tests/integration/targets/tower_ad_hoc_command/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#9320 Fix typo
  awx/ui_next/src/components/Lookup/shared/LookupErrorMessage.jsx
Labels: component:ui, mergeit

#9336 Fix bug where credential inputs were not filled on edit
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
Labels: component:ui, mergeit, type:bug

#9332 add a per-request GUID and log as it travels through background services
  awx/main/dispatch/periodic.py
  awx/main/dispatch/pool.py
  awx/main/dispatch/publish.py
  awx/main/dispatch/worker/callback.py
  awx/main/dispatch/worker/task.py
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/filters.py
  awx/main/utils/formatters.py
  awx/settings/defaults.py
  docs/licenses/django-guid.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#9338 fix for issue 4696(tower) , Upstream commit for tower PR 4840
  awx/sso/views.py
Labels: component:api, mergeit, type:bug

#9343 Remove Unused JSON Test Files
  awx/main/tests/functional/ansible.json
  awx/main/tests/functional/packages.json
  awx/main/tests/functional/services.json
Labels: mergeit

#8640 Adds filter by role on Org access lists
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.test.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
Labels: component:ui, mergeit, type:feature

#9340 Add some items to the upcoming changelog
  CHANGELOG.md
Labels: mergeit

#9188 Allow user to remove organization from credentials
  awx/ui_next/src/components/Lookup/OrganizationLookup.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.test.jsx
  awx/ui_next/src/screens/Credential/shared/ExternalTestModal.jsx
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
  awx/ui_next/src/screens/Inventory/shared/InventoryForm.jsx
Labels: component:ui, mergeit, state:needs_test, type:bug

#9347 Don't instrument for coverage by default unless CI
  Makefile
  awx/ui_next/README.md
  awx/ui_next/package.json
Labels: mergeit

#9356 Fix a few unit test console warnings
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.test.jsx
  awx/ui_next/src/components/Sort/Sort.test.jsx
Labels: component:ui, mergeit

#9251 Fixed the Customized Notification returning incorrect values for host_status_counts
  awx/main/models/notifications.py
Labels: mergeit, type:bug

#9369 Fix the broken paths to the favicon and logo in the API browser
  awx/templates/error.html
  awx/templates/rest_framework/api.html
Labels: mergeit

#9210 Prompts on schedules
  awx/ui_next/src/api/models/InventorySources.js
  awx/ui_next/src/api/models/JobTemplates.js
  awx/ui_next/src/api/models/Projects.js
  awx/ui_next/src/api/models/Schedules.js
  awx/ui_next/src/api/models/WorkflowJobTemplates.js
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/usePreviewStep.jsx
  awx/ui_next/src/components/Schedule/Schedule.jsx
  awx/ui_next/src/components/Schedule/Schedule.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleAdd/ScheduleAdd.jsx
  awx/ui_next/src/components/Schedule/ScheduleAdd/ScheduleAdd.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.jsx
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleToggle/ScheduleToggle.jsx
  awx/ui_next/src/components/Schedule/Schedules.jsx
  awx/ui_next/src/components/Schedule/data.schedules.json
  awx/ui_next/src/components/Schedule/shared/ScheduleForm.jsx
  awx/ui_next/src/components/Schedule/shared/ScheduleForm.test.jsx
  awx/ui_next/src/components/Schedule/shared/SchedulePromptableFields.jsx
  awx/ui_next/src/components/Schedule/shared/useSchedulePromptSteps.js
  awx/ui_next/src/screens/Inventory/InventorySource/InventorySource.jsx
  awx/ui_next/src/screens/Project/Project.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/Template.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.test.jsx
Labels: component:ui, mergeit, type:feature

#9334 Add pending approvals badge to application header
  CHANGELOG.md
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.jsx
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.test.jsx
  awx/ui_next/src/components/AppContainer/useWsPendingApprovalCount.js
  awx/ui_next/src/components/AppContainer/useWsPendingApprovalCount.test.jsx
Labels: component:ui, mergeit, type:feature

#9378 Added GUID filters for k8s/OCP environment
  installer/roles/kubernetes/templates/configmap.yml.j2
Labels: component:installer, mergeit, type:bug

#9322 add workflow_job_launch_type in metavars
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/models/test_unified_job.py
Labels: component:api, mergeit, type:enhancement

#9131 Document admin_password in INSTALL.md
  INSTALL.md
Labels: component:docs, component:installer, mergeit

#9382 make sure we use built in credential type
  awxkit/awxkit/api/pages/credentials.py
Labels: mergeit

#9384 Resolve / re-add execution environment list to Organizations
  awx/ui_next/src/api/models/Organizations.js
  awx/ui_next/src/screens/Organization/Organization.jsx
  awx/ui_next/src/screens/Organization/Organization.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationExecEnvList/OrganizationExecEnvList.jsx
  awx/ui_next/src/screens/Organization/OrganizationExecEnvList/OrganizationExecEnvList.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationExecEnvList/OrganizationExecEnvListItem.jsx
  awx/ui_next/src/screens/Organization/OrganizationExecEnvList/OrganizationExecEnvListItem.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationExecEnvList/index.js
  awx/ui_next/src/screens/Organization/Organizations.jsx
Labels: mergeit

#9385 build images using Buildkit
  Makefile
Labels: mergeit

#9381 Make email not required for a user in the UI.
  awx/ui_next/src/screens/User/shared/UserForm.jsx
  awx/ui_next/src/types.js
Labels: component:ui, mergeit, state:needs_test, type:bug

#9392 Add ansible requirement for dev env docs
  tools/docker-compose/README.md
Labels: mergeit

#9346 allow org members to add EEs to an org and superusers to change EEs in an org
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0128_organiaztion_read_roles_ee_admin.py
  awx/main/models/organization.py
Labels: component:api, mergeit, type:bug

#9387 Mount SECRET_KEY into dev env & document it
  awx/settings/defaults.py
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/docs/data_migration.md
Labels: component:installer, mergeit, type:bug

#9395 fix dev env migrate.yml path in docs
  tools/docker-compose/README.md
  tools/docker-compose/docs/data_migration.md
Labels: mergeit

#9391 Collections md update
  docs/collections.md
Labels: component:awx_collection, component:docs, mergeit, state:needs_review

#9402 Minor update EE tables
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.jsx
Labels: component:ui, mergeit

#9303 add copy ability to execution environments
  awx/api/serializers.py
  awx/api/urls/execution_environments.py
  awx/api/views/__init__.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/test_execution_environments.py
  awxkit/awxkit/api/pages/execution_environments.py
Labels: component:api, mergeit, type:enhancement

#9120 Inventory File field and playbook field are both now type ahead.
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
Labels: component:ui, mergeit, type:bug, type:feature

#9400 some more data migration notes
  tools/docker-compose/docs/data_migration.md
Labels: mergeit

#9406 Do not show tooltip with empty content
  awx/ui_next/src/components/StatusLabel/StatusLabel.jsx
  awx/ui_next/src/components/StatusLabel/StatusLabel.test.jsx
Labels: component:ui, mergeit

#9394 Add Execution Environments into a few screens
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.jsx
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.test.jsx
  awx/ui_next/src/components/Lookup/index.js
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.jsx
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.jsx
  awx/ui_next/src/screens/Organization/OrganizationDetail/OrganizationDetail.test.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.jsx
  awx/ui_next/src/screens/Organization/OrganizationEdit/OrganizationEdit.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.test.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.test.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/data.job_template.json
  awx/ui_next/src/types.js
Labels: component:ui, mergeit

#9224 Add system jobs interface w/ configurable data retention
  CHANGELOG.md
  awx/ui_next/src/api/index.js
  awx/ui_next/src/api/models/Jobs.js
  awx/ui_next/src/api/models/SystemJobTemplates.js
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/components/Schedule/Schedule.jsx
  awx/ui_next/src/components/Schedule/ScheduleAdd/ScheduleAdd.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.jsx
  awx/ui_next/src/components/Schedule/Schedules.jsx
  awx/ui_next/src/components/Schedule/shared/ScheduleForm.jsx
  awx/ui_next/src/constants.js
  awx/ui_next/src/screens/ManagementJob/ManagementJob.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/LaunchManagementPrompt.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/ManagementJobList.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/ManagementJobList.test.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/ManagementJobListItem.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/ManagementJobListItem.test.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/index.js
  awx/ui_next/src/screens/ManagementJob/ManagementJobs.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobs.test.jsx
Labels: component:ui, state:needs_test, type:feature

#9196 Convert admin pages lists to tables
  awx/ui_next/src/components/NotificationList/NotificationList.jsx
  awx/ui_next/src/components/NotificationList/NotificationList.test.jsx
  awx/ui_next/src/components/NotificationList/NotificationListItem.jsx
  awx/ui_next/src/components/NotificationList/NotificationListItem.test.jsx
  awx/ui_next/src/components/NotificationList/__snapshots__/NotificationListItem.test.jsx.snap
  awx/ui_next/src/components/PaginatedTable/ActionItem.jsx
  awx/ui_next/src/components/PaginatedTable/HeaderRow.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationList.test.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationListItem.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationListItem.test.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationsList.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeList.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeList.test.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeListItem.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeListItem.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupListItem.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupListItem.test.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.test.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.jsx
Labels: component:ui, mergeit, type:feature

#9037 Update defaults.py RH Satellite settings to use new Foreman plugin variables.
  awx/settings/defaults.py
Labels: mergeit, type:bug

#9417 Adds ouia id's to typeahead select components
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialFormFields/BecomeMethodField.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.jsx
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
Labels: component:ui, mergeit
