Repository ansible/awx, pull requests merged in 2021-07, with the labels that each got.

#10508 Add bug report form for github issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: component:a11y, component:analytics, component:api, component:awx_collection, component:cli, component:docs, component:ee, component:installer, component:l10n, component:ui, component:ux, mergeit

#10564 bumped django version to 2.2.20 in devel
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, mergeit, type:enhancement

#10567 Remove default text from bug title
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: mergeit

#10574 Remove bug template title field
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: mergeit

#10575 Fixes failing test
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
Labels: component:ui, mergeit, state:needs_review

#10589 No result_traceback is blank, not null
  awx/main/tasks.py
Labels: mergeit, type:bug

#10607 Remove unused exception about custom venvs
  awx/main/tasks.py
Labels: mergeit

#10617 Run flake8 on the AWX collection in CI
  awx_collection/plugins/lookup/schedule_rrule.py
  awx_collection/plugins/modules/application.py
  awx_collection/plugins/modules/execution_environment.py
  awx_collection/plugins/modules/export.py
  awx_collection/plugins/modules/import.py
  awx_collection/plugins/modules/job_wait.py
  awx_collection/plugins/modules/project.py
  awx_collection/plugins/modules/project_update.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/plugins/modules/workflow_node_wait.py
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_application.py
  awx_collection/test/awx/test_credential_input_source.py
  awx_collection/test/awx/test_instance_group.py
  awx_collection/test/awx/test_inventory.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/test/awx/test_module_utils.py
  tox.ini
Labels: component:awx_collection, mergeit

#10502 Fix disabled node cover dimensions
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerNode.jsx
Labels: component:ui, mergeit, type:bug

#10504 Encode/decode question variables
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionEdit.jsx
Labels: component:ui, mergeit, type:bug

#10512 Add job status on expand row for hosts
  awx/ui_next/src/screens/Host/HostDetail/HostDetail.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
Labels: component:ui, mergeit, type:enhancement

#10520 Remove custom component
  awx/ui_next/src/components/DataListCell/DataListCell.jsx
  awx/ui_next/src/components/DataListCell/index.js
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
Labels: component:ui, mergeit, type:bug

#10523 Fix Job Settings Page Break on Firefox
  awx/ui_next/src/screens/Setting/SettingList.jsx
Labels: component:ui, mergeit, type:bug

#10543 Update last name for Resource Access List
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.test.jsx
Labels: component:ui, mergeit, type:bug

#10559 Mark string to be translated
  awx/ui_next/src/components/Schedule/ScheduleOccurrences/ScheduleOccurrences.jsx
Labels: component:ui, mergeit, type:bug

#10590 Downstream fixes
  awx/locale/es/LC_MESSAGES/django.po
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/nl/LC_MESSAGES/django.po
  awx/locale/zh/LC_MESSAGES/django.po
  awx/main/migrations/_inventory_source.py
  awx/ui_next/public/static/media/default.strings.json
  awx/ui_next/src/components/About/About.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/screens/Credential/shared/CredentialFormFields/CredentialField.jsx
  awx/ui_next/src/screens/NotificationTemplate/shared/typeFieldNames.js
  awx/ui_next/src/util/getDocsBaseUrl.js
  awx/ui_next/src/util/getDocsBaseUrl.test.js
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#10619 Delete some old code related to the reencryption migration
  awx/conf/migrations/_reencrypt.py
  awx/conf/settings.py
  awx/main/migrations/0015_v330_blank_start_args.py
  awx/main/migrations/_reencrypt.py
Labels: component:api, mergeit, type:bug

#10581 Prevents submission of jtform if name is > 512 characters
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui, mergeit, type:bug

#10631 Wait until inventory is fully deleted in silent_delete
  awxkit/awxkit/api/pages/inventory.py
Labels: component:cli, mergeit

#10633 Conditional polymorphic setnull
  awx/main/migrations/0139_isolated_removal.py
  awx/main/migrations/_inventory_source.py
  awx/main/utils/polymorphic.py
Labels: component:api, mergeit, type:bug

#10525 Update EE lookup title
  awx/ui_next/src/components/AdHocCommands/AdHocExecutionEnvironmentStep.jsx
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.jsx
Labels: component:ui, mergeit, type:bug

#10577 Display error message if schedule does not exist
  awx/ui_next/src/components/Schedule/Schedule.jsx
  awx/ui_next/src/components/Schedule/Schedules.jsx
Labels: component:ui, mergeit, type:bug

#10580 Removes tabs from survey form
  awx/ui_next/src/screens/Template/Template.jsx
Labels: component:ui, mergeit, type:enhancement

#10597 Fixes missing key values in ad hoc credental step advanced search
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.test.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.test.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCredentialStep.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCredentialStep.test.jsx
Labels: component:ui, mergeit

#10656 Update defaults.py
  awx/settings/defaults.py
Labels: mergeit

#10636 Incorporates Minikube to devel environment
  .gitignore
  Makefile
  tools/docker-compose-minikube/deploy.yml
  tools/docker-compose-minikube/minikube/defaults/main.yml
  tools/docker-compose-minikube/minikube/tasks/main.yml
  tools/docker-compose-minikube/minikube/templates/bootstrap_minikube.py.j2
  tools/docker-compose-minikube/minikube/templates/rbac.yml.j2
  tools/docker-compose/README.md
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/bootstrap_development.sh
  tools/docker-compose/receptor.conf
Labels: component:api, mergeit, type:enhancement

#10598 Identify sliced jobs on Job List and Job Details
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/JobList/JobListItem.test.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
Labels: component:ui, mergeit, type:enhancement

#10578 Point REST API favicon at the one the UI uses
  awx/static/favicon.ico
  awx/templates/rest_framework/api.html
Labels: component:api, component:ui, mergeit, state:needs_test, type:bug

#10604 Update RBAC sidebar
  awx/ui_next/src/routeConfig.jsx
  awx/ui_next/src/routeConfig.test.jsx
Labels: component:ui, mergeit, type:enhancement

#10608 Disable remove button if row is being dragged
  awx/ui_next/src/components/Lookup/InstanceGroupsLookup.jsx
  awx/ui_next/src/components/SelectedList/DraggableSelectedList.jsx
  awx/ui_next/src/components/SelectedList/DraggableSelectedList.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
Labels: component:ui, mergeit

#10621 Fix close button alert modal
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
Labels: component:ui, mergeit

#10622 Update login redirect to a be text input field
  awx/ui_next/src/screens/Setting/MiscAuthentication/MiscAuthenticationEdit/MiscAuthenticationEdit.jsx
Labels: component:ui, mergeit

#10640 Add edit icon to SurveyListItem
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyListItem.test.jsx
Labels: component:ui, mergeit

#10623 Adds functionality for expand all
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.test.jsx
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.jsx
  awx/ui_next/src/components/TemplateList/TemplateList.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.test.jsx
  awx/ui_next/src/screens/Application/ApplicationTokens/ApplicationTokenList.jsx
  awx/ui_next/src/screens/Application/ApplicationsList/ApplicationsList.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeList.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
  awx/ui_next/src/screens/InstanceGroup/Instances/InstanceList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/screens/Inventory/SmartInventoryHosts/SmartInventoryHostList.jsx
  awx/ui_next/src/screens/ManagementJob/ManagementJobList/ManagementJobList.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Project/ProjectJobTemplatesList/ProjectJobTemplatesList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.test.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamList.jsx
  awx/ui_next/src/screens/User/UserList/UserList.jsx
  awx/ui_next/src/screens/User/UserTeams/UserTeamList.jsx
  awx/ui_next/src/screens/User/UserTokenList/UserTokenList.jsx
  awx/ui_next/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.jsx
  awx/ui_next/src/util/useExpanded.jsx
  awx/ui_next/src/util/useExpanded.test.jsx
Labels: component:ui, mergeit, type:enhancement

#10606 Display full keys advanced search smart inventory
  awx/ui_next/src/components/Lookup/HostFilterLookup.jsx
Labels: component:ui, mergeit

#10629 Update User screens
  awx/api/serializers.py
  awx/ui_next/src/screens/User/UserDetail/UserDetail.jsx
  awx/ui_next/src/screens/User/UserDetail/UserDetail.test.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.jsx
  awx/ui_next/src/screens/User/data.user.json
  awx/ui_next/src/screens/User/shared/UserForm.jsx
Labels: component:ui, mergeit

#10671 Fix conditional to check that minikube should start
  Makefile
Labels: component:api, mergeit, type:bug

#10684 Properly compile translated API strings
  Makefile
  awx/api/generics.py
  awx/locale/fr/LC_MESSAGES/django.po
Labels: mergeit, type:bug

#10639 Fix inaccurate translation
  awx/ui_next/src/locales/zh/messages.po
Labels: component:api, component:ui, mergeit, type:enhancement

#10576 Adds Ad Hoc Preview step and adds workflow similar to prompt on launch
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.test.js
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.js
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.test.js
  awx/ui_next/src/components/AdHocCommands/AdHocCredentialStep.js
  awx/ui_next/src/components/AdHocCommands/AdHocDetailsStep.js
  awx/ui_next/src/components/AdHocCommands/AdHocPreviewStep.jsx
  awx/ui_next/src/components/AdHocCommands/useAdHocCredentialStep.jsx
  awx/ui_next/src/components/AdHocCommands/useAdHocDetailsStep.jsx
  awx/ui_next/src/components/AdHocCommands/useAdHocExecutionEnvironmentStep.jsx
  awx/ui_next/src/components/AdHocCommands/useAdHocLaunchSteps.js
  awx/ui_next/src/components/AdHocCommands/useAdHocPreviewStep.jsx
Labels: component:ui, mergeit, type:enhancement

#10510 Renders Command Module in job detail view and improves Ad Hoc Commands execution permissions
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.js
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.test.js
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.js
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.test.js
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.js
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.test.js
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.js
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.test.js
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.js
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.test.js
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.js
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.test.js
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.js
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui, mergeit, type:bug

#10672 Reimplement CI jobs in GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/devel_image.yml
  .github/workflows/upload_schema.yml
  .yamllint
  Makefile
Labels: component:api, component:ui

#10660 Bump size of SSO icons login screen
  awx/ui_next/src/screens/Login/Login.js
Labels: component:ui

#10679 Enforces Proper permissions for Host Groups List
  awx/ui_next/src/api/models/Hosts.js
Labels: component:ui

#10675 Workaround Minikube issue on MacOS and enable preflights
  tools/docker-compose-minikube/minikube/defaults/main.yml
  tools/docker-compose-minikube/minikube/tasks/main.yml
  tools/docker-compose-minikube/minikube/tasks/preflight.yml
Labels: component:api, state:needs_review, type:bug

#10664 Update docker-compose
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/awx-1-receptor-standalone.conf
Labels: component:api, size:small, state:needs_review

#10700 Fix misalignment node approval timeout
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
Labels: component:ui

#10665 Disallow network requests in tests
  awx/ui_next/src/components/Search/Search.js
  awx/ui_next/src/components/Sort/Sort.js
  awx/ui_next/src/components/Sort/Sort.test.js
  awx/ui_next/src/components/UserAndTeamAccessAdd/UserAndTeamAccessAdd.test.js
  awx/ui_next/src/screens/InstanceGroup/InstanceGroups.test.js
  awx/ui_next/src/screens/Job/Job.js
  awx/ui_next/src/screens/Job/Job.test.js
  awx/ui_next/src/screens/Setting/SettingList.test.js
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizations.test.js
  awx/ui_next/src/screens/User/UserTokens/UserTokens.test.js
  awx/ui_next/src/setupTests.js
  awx/ui_next/src/util/getRelatedResourceDeleteDetails.test.js
Labels: component:ui, type:enhancement, type:task

#10696 Create map of strings to be translated
  awx/ui_next/src/components/StatusLabel/StatusLabel.js
  awx/ui_next/src/components/StatusLabel/StatusLabel.test.js
Labels: component:ui

#10709 Run prettier and lint
  awx/ui_next/src/setupTests.js
Labels: component:ui, state:needs_review

#10570 Remove mix usage of hooks and HOC for router
  awx/ui_next/src/components/AddRole/SelectResourceStep.js
  awx/ui_next/src/components/Lookup/ApplicationLookup.js
  awx/ui_next/src/components/Lookup/HostFilterLookup.js
  awx/ui_next/src/screens/Job/Job.js
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.js
  awx/ui_next/src/screens/Organization/Organization.js
  awx/ui_next/src/screens/Project/Project.js
Labels: component:ui, state:needs_test, type:task

#10632 Add Thycotic SecretServer support
  awx/main/credential_plugins/tss.py
  awx/main/tests/functional/test_credential.py
  docs/licenses/dataclasses.txt
  docs/licenses/python-tss-sdk.txt
  requirements/requirements.in
  requirements/requirements.txt
  setup.py
Labels: component:api, component:ui, type:enhancement

#10711 Install boto to ci ansible python env
  .github/workflows/upload_schema.yml
Labels: state:needs_review

#10583 wait for database connection
  tools/ansible/roles/dockerfile/files/launch_awx.sh
  tools/ansible/roles/dockerfile/files/launch_awx_task.sh
  tools/ansible/roles/dockerfile/files/wait-for-migrations
Labels: component:api, type:bug

#10511 run dev cluster haproxy container as root
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: component:api, type:bug

#7273 Remove query_parameters from page loop causing 414
  awxkit/awxkit/api/pages/page.py
Labels: component:api, component:cli, state:needs_devel, type:bug

#8023 improve logging migrate or instance not registered
  awx/main/management/commands/run_wsbroadcast.py
Labels: component:api, type:enhancement

#9365 tools/scripts/firehose.py: capture all job ids, attach events to all jobs ids and distribute the events
  tools/scripts/firehose.py
Labels: type:enhancement

#9703 Avoid double LDAP updates
  awx/sso/backends.py
Labels: component:api, type:bug

#10481 Reorder docker compose up options
  Makefile
Labels: type:bug

#10484 only get active long running queries
  docs/debugging/debugging_misc.md
Labels: component:docs

#10566 Headers missing in webhook notification request
  awx/main/notifications/webhook_backend.py
Labels: component:api, type:bug

#10573 Default source_project to organization for inventory source
  awx_collection/plugins/modules/inventory_source.py
  awx_collection/tests/integration/targets/inventory_source_update/tasks/main.yml
Labels: component:awx_collection, state:in_progress, type:bug

#9944 Allow stable use of AWXKIT_PREVENT_TEARDOWN by disabling schedules at the end
  awxkit/awxkit/api/pages/schedules.py
  awxkit/awxkit/api/pages/unified_job_templates.py
Labels: component:api, type:enhancement

#10108 Fix to handle ask_* parameters correctly when set false
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection, state:needs_test, type:bug

#10668 Fix ignoring --no-color for awx-manage list_instances command
  awx/main/management/commands/list_instances.py
Labels: component:api, type:bug

#10634 Updates product name in About modal
  awx/ui_next/public/static/media/default.strings.json
  awx/ui_next/src/components/About/About.js
  awx/ui_next/src/components/About/About.test.js
  awx/ui_next/src/components/AppContainer/AppContainer.test.js
  awx/ui_next/src/hooks/useBrandName.js
Labels: component:ui, type:bug

#10713 Fix multiple accessibility violations
  awx/ui_next/src/components/DetailList/CodeDetail.js
  awx/ui_next/src/components/DetailList/Detail.js
  awx/ui_next/src/components/ExecutionEnvironmentDetail/ExecutionEnvironmentDetail.js
  awx/ui_next/src/components/JobList/JobListItem.js
  awx/ui_next/src/components/LaunchButton/ReLaunchDropDown.js
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.js
  awx/ui_next/src/components/Lookup/InventoryLookup.js
  awx/ui_next/src/components/Lookup/Lookup.js
  awx/ui_next/src/components/Lookup/OrganizationLookup.js
  awx/ui_next/src/screens/Application/ApplicationAdd/ApplicationAdd.test.js
  awx/ui_next/src/screens/Application/ApplicationEdit/ApplicationEdit.test.js
  awx/ui_next/src/screens/Application/shared/ApplicationForm.test.js
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.js
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.js
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.js
  awx/ui_next/src/screens/Template/shared/WebhookSubForm.test.js
Labels: component:ui, state:needs_test

#10716 Return 404 for ad_hoc_command_events list api. Remove api endtpoint
  awx/api/urls/ad_hoc_command_event.py
  awx/api/views/__init__.py
Labels: component:api, type:bug

#10725 Add E2E tests workflow
  .github/workflows/e2e_test.yml
Labels: qe:e2e, state:needs_review, type:task

#10751 Update e2e workflow to use variable for e2e project name
  .github/workflows/e2e_test.yml
Labels: qe:e2e, state:needs_review, type:task

#10756 Set timeout limit for e2e workflow
  .github/workflows/e2e_test.yml
Labels: qe:e2e, type:task

#10662 Updates Several UI Production Dependencies
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/screens/Dashboard/shared/ChartTooltip.js
  awx/ui_next/src/screens/Dashboard/shared/LineChart.js
  awx/ui_next/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.js
  awx/ui_next/src/screens/Job/WorkflowOutput/WorkflowOutputGraph.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerGraph.js
  docs/licenses/ui/d3-collection.txt
  docs/licenses/ui/d3-delaunay.txt
  docs/licenses/ui/d3-voronoi.txt
  docs/licenses/ui/delaunator.txt
  docs/licenses/ui/emotion-stylis.txt
  docs/licenses/ui/internmap.txt
  docs/licenses/ui/memoize-one.txt
  docs/licenses/ui/merge-anything.txt
  docs/licenses/ui/shallowequal.txt
  docs/licenses/ui/stylis-rule-sheet.txt
Labels: component:ui, priority:high, qe:e2e

#10760 [testing branch] Updates prod deps
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/screens/Dashboard/shared/ChartTooltip.js
  awx/ui_next/src/screens/Dashboard/shared/LineChart.js
  awx/ui_next/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.js
  awx/ui_next/src/screens/Job/WorkflowOutput/WorkflowOutputGraph.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerGraph.js
  docs/licenses/ui/d3-collection.txt
  docs/licenses/ui/d3-delaunay.txt
  docs/licenses/ui/d3-voronoi.txt
  docs/licenses/ui/delaunator.txt
  docs/licenses/ui/emotion-stylis.txt
  docs/licenses/ui/internmap.txt
  docs/licenses/ui/memoize-one.txt
  docs/licenses/ui/merge-anything.txt
  docs/licenses/ui/shallowequal.txt
  docs/licenses/ui/stylis-rule-sheet.txt
Labels: qe:e2e

#10761 Add string to be translated
  awx/ui_next/src/components/Pagination/Pagination.js
Labels: component:ui, state:needs_review

#10692 Add auto-populate inventory host form
  awx/ui_next/src/components/HostForm/HostForm.js
  awx/ui_next/src/components/Lookup/InventoryLookup.js
Labels: component:ui

#10768 Remove all groups filter
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.js
Labels: component:ui

#10741 Improves empty state messages for improve UX
  awx/ui_next/src/components/JobList/JobList.js
  awx/ui_next/src/components/PaginatedTable/ToolbarAddButton.js
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.js
Labels: component:ui

#10635 Add extra step to confirm edition of login redirect URL
  awx/ui_next/src/screens/Setting/MiscAuthentication/MiscAuthenticationEdit/MiscAuthenticationEdit.js
  awx/ui_next/src/screens/Setting/MiscAuthentication/MiscAuthenticationEdit/MiscAuthenticationEdit.test.js
  awx/ui_next/src/screens/Setting/shared/SharedFields.js
  awx/ui_next/src/screens/Setting/shared/SharedFields.test.js
  awx/ui_next/src/screens/Setting/shared/index.js
Labels: component:ui

#10572 Add UI support for management jobs in workflows
  awx/ui_next/src/api/models/SystemJobTemplates.js
  awx/ui_next/src/components/PromptDetail/PromptDetail.js
  awx/ui_next/src/components/Workflow/WorkflowLegend.js
  awx/ui_next/src/components/Workflow/WorkflowNodeHelp.js
  awx/ui_next/src/components/Workflow/WorkflowNodeTypeLetter.js
  awx/ui_next/src/screens/ManagementJob/ManagementJob.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/DaysToKeepStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/DaysToKeepStep.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeAddModal.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeEditModal.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/SystemJobTemplatesList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/SystemJobTemplatesList.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useDaysToKeepStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/shared/WorkflowJobTemplateVisualizerUtils.js
  awx/ui_next/src/util/validators.js
Labels: component:ui, state:needs_test, type:enhancement

#10777 Update usage of useBrandName
  awx/ui_next/src/components/AdHocCommands/AdHocDetailsStep.js
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/ManualSubForm.js
  awx/ui_next/src/screens/Setting/SettingList.js
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.js
Labels: component:ui, state:needs_review

#10781 Use cypress base image from a public repo in quay
  .github/workflows/e2e_test.yml
Labels: qe:e2e, type:task

#10757 add a node_type field to the instance model
  awx/api/serializers.py
  awx/main/management/commands/provision_instance.py
  awx/main/managers.py
  awx/main/migrations/0152_instance_node_type.py
  awx/main/models/ha.py
Labels: component:api, state:needs_review, type:enhancement
