Repository ansible/awx, pull requests merged in 2021-04, with the labels that each got.

#9786 Add wheel in venv creation
  Makefile
  docs/licenses/Cython.txt
  docs/licenses/wheel.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#9720 Rename ansible-tower file to automation-controller
  MANIFEST.in
  setup.py
  tools/scripts/ansible-tower-service
  tools/scripts/automation-controller-service
Labels: mergeit

#9737 workflow convergence
  awx/ui_next/src/components/Workflow/workflowReducer.js
  awx/ui_next/src/screens/Job/WorkflowOutput/WorkflowOutputNode.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeAddModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeAddModal.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeEditModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeEditModal.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/useNodeTypeStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerNode.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9797 Make logs more readable in development environment
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/docker-compose/supervisor.conf
Labels: mergeit

#9810 Fix docker-compose up options
  Makefile
Labels: mergeit

#9777 Filter EE also by Organization for JT
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.jsx
  awx/ui_next/src/components/Lookup/ExecutionEnvironmentLookup.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui, mergeit

#9802 Remove invocation of Ansible from launch script
  tools/ansible/roles/dockerfile/files/launch_awx.sh
Labels: mergeit

#9809 Update placeholder image variable in inventory file
  tools/docker-compose/inventory
Labels: mergeit

#9811 Move to webchat.freenode.net.
  CONTRIBUTING.md
  README.md
Labels: mergeit

#9813 Update capitalization for a few screens
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironments.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroups.jsx
Labels: component:ui, mergeit

#9358 Gather job event analytics by last pk instead of created datetime
  awx/main/analytics/__init__.py
  awx/main/analytics/collectors.py
  awx/main/analytics/core.py
  awx/main/conf.py
  awx/main/management/commands/gather_analytics.py
  awx/main/tasks.py
  awx/main/tests/functional/analytics/test_core.py
  awx/main/utils/common.py
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#9818 Configure ace editor to not use blob worker
  awx/ui_next/src/components/CodeEditor/CodeEditor.jsx
Labels: component:ui, mergeit, state:needs_test, type:bug

#9815 Create single source of truth for outgoing Docs link URLs
  awx/ui_next/.eslintrc
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.jsx
  awx/ui_next/src/components/DocsLink/DocsLink.jsx
  awx/ui_next/src/components/DocsLink/index.jsx
  awx/ui_next/src/components/Search/AdvancedSearch.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/AzureSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/EC2SubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/GCESubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/OpenStackSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SatelliteSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/TowerSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/VMwareSubForm.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/VirtualizationSubForm.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
  awx/ui_next/src/screens/NotificationTemplate/shared/CustomMessagesSubForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/GitSubForm.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerToolbar.jsx
  awx/ui_next/src/util/getDocsBaseUrl.js
  awx/ui_next/src/util/getDocsBaseUrl.test.js
Labels: component:ui, mergeit, state:needs_test, type:feature

#9804 instance groups options for modules
  awx_collection/plugins/modules/tower_inventory.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/tests/integration/targets/tower_inventory/tasks/main.yml
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
  awx_collection/tests/integration/targets/tower_organization/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#9710 Make Org a required field for org admins on WFJT
  awx/ui_next/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
Labels: component:ui, mergeit

#9819 Update pod reaper to work with receptor launched pods
  awx/main/management/commands/inventory_import.py
  awx/main/models/mixins.py
  awx/main/models/projects.py
  awx/main/scheduler/kubernetes.py
  awx/main/tasks.py
  awx/main/utils/execution_environments.py
  awx/settings/defaults.py
Labels: mergeit

#9821 replace null unicode with nothing in analytics collection
  awx/main/analytics/collectors.py
Labels: mergeit

#9758 Do not allow user to attempt to delete a running job
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobList.test.jsx
Labels: component:ui, mergeit

#9827 Limit the visible playbook select region
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
Labels: component:ui, mergeit, type:bug

#9673 Fix up request tower ps script
  tools/scripts/request_tower_configuration.ps1
Labels: mergeit, type:bug

#9825 Adjust datetimes to be aware when using awx-manage gather_analytics
  awx/main/analytics/core.py
  awx/main/management/commands/gather_analytics.py
Labels: component:api, mergeit, type:bug

#9803 Cluster dev env: only run migrations on first node
  tools/ansible/roles/dockerfile/files/wait-for-migrations
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/bootstrap_development.sh
Labels: mergeit

#9496 Subscription wizard
  awx/ui_next/.eslintrc
  awx/ui_next/public/static/media/insights-analytics-dashboard.jpeg
  awx/ui_next/src/App.jsx
  awx/ui_next/src/api/models/Config.js
  awx/ui_next/src/api/models/Settings.js
  awx/ui_next/src/components/AppContainer/AppContainer.jsx
  awx/ui_next/src/components/AppContainer/AppContainer.test.jsx
  awx/ui_next/src/contexts/Config.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Setting/License/License.jsx
  awx/ui_next/src/screens/Setting/License/License.test.jsx
  awx/ui_next/src/screens/Setting/License/LicenseDetail/LicenseDetail.jsx
  awx/ui_next/src/screens/Setting/License/LicenseDetail/LicenseDetail.test.jsx
  awx/ui_next/src/screens/Setting/License/LicenseDetail/index.js
  awx/ui_next/src/screens/Setting/License/LicenseEdit/LicenseEdit.jsx
  awx/ui_next/src/screens/Setting/License/LicenseEdit/LicenseEdit.test.jsx
  awx/ui_next/src/screens/Setting/License/LicenseEdit/index.js
  awx/ui_next/src/screens/Setting/License/index.js
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.jsx
  awx/ui_next/src/screens/Setting/SettingList.jsx
  awx/ui_next/src/screens/Setting/Settings.jsx
  awx/ui_next/src/screens/Setting/Subscription/Subscription.jsx
  awx/ui_next/src/screens/Setting/Subscription/Subscription.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionDetail/index.js
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/EulaStep.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/EulaStep.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionModal.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionModal.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionStep.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionStep.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/bootstrapPendo.js
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/index.js
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/pendoUtils.js
  awx/ui_next/src/screens/Setting/Subscription/index.js
  awx/ui_next/src/screens/Setting/UI/UIEdit/UIEdit.jsx
  awx/ui_next/src/setupTests.js
  awx/ui_next/src/util/dates.jsx
  awx/ui_next/src/util/dates.test.jsx
  awx/ui_next/testUtils/enzymeHelpers.jsx
Labels: component:ui, mergeit, type:enhancement, type:feature

#9843 Remove duple // for docs link on PageHeaderToolBar
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.jsx
Labels: component:ui, mergeit

#9836 Use shared logo img and dynamic copyright date
  awx/ui_next/.eslintrc
  awx/ui_next/src/components/About/About.jsx
  awx/ui_next/src/components/About/brand-logo.svg
Labels: component:ui, mergeit

#9844 Fix issue related to plural
  awx/ui_next/src/components/JobList/JobList.jsx
Labels: component:ui, mergeit

#9840 Update version and changelog for version 19
  CHANGELOG.md
  VERSION
  awxkit/VERSION
Labels: mergeit

#9848 Update subscription docs link to use single source of truth
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionStep.jsx
Labels: component:ui, mergeit, state:needs_test, type:bug

#9755 Remove isolated and controller from the UI
  awx/ui_next/src/screens/InstanceGroup/ContainerGroupDetails/ContainerGroupDetails.test.jsx
  awx/ui_next/src/screens/InstanceGroup/ContainerGroupEdit/ContainerGroupEdit.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupAdd/InstanceGroupAdd.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupDetails/InstanceGroupDetails.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupDetails/InstanceGroupDetails.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupEdit/InstanceGroupEdit.test.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupListItem.jsx
  awx/ui_next/src/screens/InstanceGroup/shared/ContainerGroupForm.test.jsx
  awx/ui_next/src/screens/InstanceGroup/shared/InstanceGroupForm.test.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9869 Use validated prop in cred plugin field
  awx/ui_next/src/screens/Credential/shared/CredentialPlugins/CredentialPluginField.jsx
Labels: component:ui, mergeit, type:bug

#9861 Fix non-translatable template string
  awx/ui_next/src/components/About/About.jsx
Labels: component:ui, mergeit

#9814 Do not validate optional survey
  awx/ui_next/src/components/LaunchPrompt/steps/SurveyStep.jsx
  awx/ui_next/src/util/prompt/getSurveyValues.js
Labels: component:ui, mergeit, type:bug

#9586 Add VariablesField YAML/JSON validation
  awx/ui_next/src/components/CodeEditor/CodeEditor.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9858 Add missing template list expanded section details
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.test.jsx
  awx/ui_next/src/components/TemplateList/data.job_template.json
Labels: component:ui, mergeit, type:feature

#9873 Update templates for installer changes
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: mergeit

#9847 Fix elapsed time on job showing incorrect value
  awx/main/models/unified_jobs.py
  awx_collection/test/awx/test_ad_hoc_wait.py
  awx_collection/test/awx/test_job.py
Labels: component:api, mergeit, type:bug

#9885 Change Reference of 'ansible-tower-service' to 'automation-controller-service' in Docs File
  docs/clustering.md
Labels: mergeit

#9886 sprinkle back in some flake8 to catch missing imports
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/migrations/0007_v320_data_migrations.py
  awx/main/migrations/0010_v322_add_ovirt4_tower_inventory.py
  awx/main/migrations/0011_v322_encrypt_survey_passwords.py
  awx/main/migrations/0015_v330_blank_start_args.py
  awx/main/migrations/0016_v330_non_blank_workflow.py
  awx/main/migrations/0021_v330_declare_new_rbac_roles.py
  awx/main/migrations/0026_v330_delete_authtoken.py
  awx/main/migrations/0028_v330_add_tower_verify.py
  awx/main/migrations/0030_v330_modify_application.py
  awx/main/migrations/0038_v330_add_deleted_activitystream_actor.py
  awx/main/migrations/0039_v330_custom_venv_help_text.py
  awx/main/migrations/0069_v350_generate_unique_install_uuid.py
  awx/main/migrations/0076_v360_add_new_instance_group_relations.py
  awx/main/migrations/0084_v360_token_description.py
  awx/main/migrations/0109_v370_job_template_organization_field.py
  awx/main/migrations/0120_galaxy_credentials.py
  awx/main/migrations/_create_system_jobs.py
  awx/main/migrations/_inventory_source.py
  awx/main/scheduler/kubernetes.py
  awx/main/utils/common.py
  awx/ui/fields.py
  tox.ini
Labels: mergeit

#7391 Add tower group for collection modules
  awx_collection/meta/runtime.yml
Labels: component:awx_collection, mergeit

#9892 record the receptor unit ID on the job record for debugging purposes
  awx/main/tasks.py
Labels: mergeit

#9874 Prevent execution environment from being assigned to a new organization
  awx/api/serializers.py
Labels: component:api, mergeit, type:bug

#9889 update django-cors-headers and switch to inclusive settings name
  docs/cors.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#9890 allow schedules to be disabled even if the associated UJT isn't valid
  awx/api/serializers.py
Labels: mergeit

#9683 Pull with credentials from protected registries
  awx/api/serializers.py
  awx/main/models/credential/__init__.py
  awx/main/tasks.py
Labels: component:api, mergeit, type:enhancement

#9862 Use built-in suppress from contextlib
  awxkit/awxkit/api/mixins/has_instance_groups.py
  awxkit/awxkit/api/mixins/has_notifications.py
  awxkit/awxkit/api/pages/instance_groups.py
  awxkit/awxkit/api/pages/inventory.py
  awxkit/awxkit/api/pages/job_templates.py
  awxkit/awxkit/api/pages/notification_templates.py
  awxkit/awxkit/api/pages/organizations.py
  awxkit/awxkit/api/pages/page.py
  awxkit/awxkit/api/pages/schedules.py
  awxkit/awxkit/api/pages/teams.py
  awxkit/awxkit/api/pages/workflow_job_template_nodes.py
  awxkit/awxkit/api/pages/workflow_job_templates.py
  awxkit/awxkit/awx/utils.py
  awxkit/awxkit/utils/__init__.py
  awxkit/test/test_utils.py
Labels: component:api, mergeit

#9903 Remove not used code
  awx/ui_next/src/components/SyncStatusIndicator/SyncStatusIndicator.jsx
  awx/ui_next/src/components/SyncStatusIndicator/index.js
  awx/ui_next/src/util/strings.js
  awx/ui_next/src/util/strings.test.js
Labels: component:ui, mergeit, state:needs_test

#9219 Adding the scm_track_submodules option for project
  awx/api/serializers.py
  awx/main/migrations/0136_scm_track_submodules.py
  awx/main/models/projects.py
  awx/main/tasks.py
  awx/playbooks/project_update.yml
  awx/ui_next/src/components/PromptDetail/PromptProjectDetail.jsx
  awx/ui_next/src/components/PromptDetail/data.project.json
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.test.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.test.jsx
  awx/ui_next/src/screens/Project/data.project.json
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSubForms/SharedFields.jsx
  awx/ui_next/src/types.js
  awx_collection/plugins/modules/tower_project.py
  awxkit/awxkit/api/pages/projects.py
Labels: component:api, component:ui, mergeit, state:needs_test, type:enhancement

#9593 Don't unnecessarily expand YAML expressions
  awx/ui_next/src/components/CodeEditor/VariablesDetail.jsx
  awx/ui_next/src/components/CodeEditor/VariablesDetail.test.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.test.jsx
  awx/ui_next/src/components/MultiButtonToggle/MultiButtonToggle.jsx
Labels: component:ui, mergeit, state:needs_test

#9875 Accessibility fixes
  awx/ui_next/.eslintrc
  awx/ui_next/src/components/AppContainer/AppContainer.jsx
  awx/ui_next/src/components/AppContainer/BrandLogo.jsx
  awx/ui_next/src/components/CodeEditor/CodeEditor.jsx
  awx/ui_next/src/components/CodeEditor/VariablesDetail.jsx
  awx/ui_next/src/components/CodeEditor/VariablesDetail.test.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.test.jsx
  awx/ui_next/src/components/FieldWithPrompt/FieldWithPrompt.jsx
  awx/ui_next/src/components/FieldWithPrompt/FieldWithPrompt.test.jsx
  awx/ui_next/src/components/MultiSelect/TagMultiSelect.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/components/RoutedTabs/RoutedTabs.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.test.jsx
  awx/ui_next/src/components/Search/Search.jsx
  awx/ui_next/src/screens/ActivityStream/ActivityStream.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialFormFields/BecomeMethodField.jsx
  awx/ui_next/src/screens/Dashboard/Dashboard.jsx
  awx/ui_next/src/screens/Dashboard/shared/LineChart.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.test.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyPreviewModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.jsx
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
  awx/ui_next/src/screens/User/UserList/UserListItem.jsx
Labels: component:ui, mergeit

#9922 Always overwrite the contents of .git/hooks/pre-commit
  Makefile
Labels: component:api, mergeit, type:bug

#9884 Do not allow EE to modify Org
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentEdit/ExecutionEnvironmentEdit.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.test.jsx
Labels: component:ui, mergeit

#9776 Observability Metrics
  awx/ui_next/src/App.jsx
  awx/ui_next/src/api/index.js
  awx/ui_next/src/api/models/Metrics.js
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.test.jsx
  awx/ui_next/src/screens/Metrics/LineChart.jsx
  awx/ui_next/src/screens/Metrics/LineChart.test.jsx
  awx/ui_next/src/screens/Metrics/Metrics.jsx
  awx/ui_next/src/screens/Metrics/Metrics.test.jsx
  awx/ui_next/src/screens/Metrics/index.js
Labels: component:ui, state:needs_test, type:feature

#9914 Define variables in the correct Ansible role
  tools/ansible/roles/dockerfile/defaults/main.yml
  tools/ansible/roles/image_build/defaults/main.yml
Labels: mergeit, type:bug

#9942 Dont reap pods when settings.RECEPTOR_RELEASE_WORK = False
  awx/main/tasks.py
Labels: mergeit

#9934 Updating installation documentation
  INSTALL.md
Labels: component:docs, mergeit

#9925 Prevent double-clicking/double-launching jobs
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/components/LaunchButton/ReLaunchDropDown.jsx
  awx/ui_next/src/components/TemplateList/TemplateListItem.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobOutput/shared/OutputToolbar.jsx
  awx/ui_next/src/screens/Project/ProjectJobTemplatesList/ProjectJobTemplatesListItem.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerToolbar.jsx
Labels: component:ui, mergeit

#9940 CredentialPluginField: Fixes bug to display invalid helper text for empty required field.
  awx/ui_next/src/screens/Credential/shared/CredentialPlugins/CredentialPluginField.jsx
Labels: component:ui, mergeit, type:bug

#9933 Add expanded row content to job list
  awx/ui_next/src/components/JobList/JobListItem.jsx
Labels: component:ui, mergeit, type:feature

#9899 metadata: Fixes invalid model classes field.
  awx/api/metadata.py
Labels: mergeit, type:bug

#9950 [Testability] Job template details delete button
  awx/ui_next/src/components/DeleteButton/DeleteButton.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
Labels: component:ui, mergeit

#9954 Add in the missing dry-run check for csv analytics collectors
  awx/main/analytics/core.py
Labels: component:api, mergeit, type:bug

#9907 Add cleanup_images scheduled task
  awx/main/tasks.py
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#9912 Return distinct labels for normal Users
  awx/main/access.py
Labels: component:api, mergeit, type:bug

#9964 Adding ouiaid to RelaunchDropdown.jsx
  awx/ui_next/src/components/LaunchButton/ReLaunchDropDown.jsx
Labels: component:ui, mergeit

#9932 Add expanded row content to project list
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.test.jsx
Labels: component:ui, mergeit, type:feature

#9971 add slow query tracing to docs
  docs/debugging.md
Labels: mergeit

#9689 I18n devel translations
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/zh/LC_MESSAGES/django.po
  awx/ui_next/.linguirc
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:l10n, component:ui, mergeit, state:needs_test, type:enhancement, type:feature

#9600 Initialize variables field/detail with formatted JSON strings
  awx/ui_next/src/components/CodeEditor/VariablesDetail.jsx
  awx/ui_next/src/components/CodeEditor/VariablesDetail.test.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.jsx
  awx/ui_next/src/components/CodeEditor/VariablesField.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9973 Fix issue where ad-hoc commands for multiple hosts ran on single host
  awx/main/tasks.py
Labels: mergeit

#9974 Stop instructing folks to install from devel
  INSTALL.md
Labels: mergeit

#9951 Add option for ignoring tls on Container Registry credentials
  awx/main/models/credential/__init__.py
  awx/main/tasks.py
  awx/main/tests/unit/conftest.py
  awx/main/tests/unit/test_tasks.py
Labels: mergeit

#9883 Remove resource profiling feature
  awx/main/conf.py
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
  awx/settings/defaults.py
  awx/ui_next/src/screens/Setting/Jobs/JobsDetail/JobsDetail.test.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/JobsEdit.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/data.defaultJobSettings.json
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui_next/src/screens/Setting/shared/data.allSettings.json
  awx/ui_next/src/screens/Setting/shared/data.jobSettings.json
  docs/performance_data.md
Labels: mergeit, state:needs_test, type:feature

#9822 Remove custom inventory scripts from the API
  awx/api/serializers.py
  awx/api/urls/inventory_script.py
  awx/api/urls/urls.py
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/api/views/root.py
  awx/main/access.py
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/conf.py
  awx/main/constants.py
  awx/main/management/commands/export_custom_scripts.py
  awx/main/management/commands/inventory_import.py
  awx/main/migrations/0137_custom_inventory_scripts_removal_data.py
  awx/main/migrations/0138_custom_inventory_scripts_removal.py
  awx/main/migrations/_inventory_source.py
  awx/main/migrations/_rbac.py
  awx/main/models/__init__.py
  awx/main/models/activity_stream.py
  awx/main/models/base.py
  awx/main/models/inventory.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/functional/analytics/test_counts.py
  awx/main/tests/functional/analytics/test_metrics.py
  awx/main/tests/functional/api/test_inventory.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/test_copy.py
  awx/main/tests/functional/test_named_url.py
  awx/main/tests/functional/test_rbac_inventory.py
  awx/main/tests/functional/test_rbac_workflow.py
  awx/main/tests/unit/api/serializers/test_inventory_serializers.py
  awx/main/tests/unit/api/test_filters.py
  awx/main/tests/unit/api/test_views.py
  awx/main/tests/unit/test_tasks.py
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_receive.py
  awx_collection/test/awx/test_completeness.py
  awxkit/awxkit/api/pages/inventory.py
  awxkit/awxkit/api/resources.py
  awxkit/awxkit/awx/utils.py
  awxkit/awxkit/cli/custom.py
  awxkit/awxkit/cli/resource.py
Labels: component:api, mergeit

#9958 Fixes object rendered on dom in aria-label
  awx/ui_next/src/components/JobList/JobListCancelButton.jsx
  awx/ui_next/src/components/NotificationList/__snapshots__/NotificationListItem.test.jsx.snap
  awx/ui_next/src/components/PaginatedDataList/__snapshots__/ToolbarDeleteButton.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/DeleteRoleConfirmationModal.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
Labels: component:ui, mergeit

#9975 Fixes bug where users could not delete a single inventory source
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/util/getRelatedResouceDeleteDetails.test.js
  awx/ui_next/src/util/getRelatedResourceDeleteDetails.js
Labels: component:ui, mergeit, type:bug

#9945 Move to fileglob loop for yml requirement locations
  awx/playbooks/project_update.yml
Labels: component:api, mergeit

#9990 Wait for the database migrations before starting
  tools/ansible/roles/dockerfile/files/launch_awx_task.sh
Labels: component:api, mergeit, type:enhancement

#9994 Add bindep.txt file for execution environments
  awx_collection/bindep.txt
Labels: mergeit

#9943 Fixes SSO Redirect
  awx/ui_next/src/screens/Login/Login.jsx
  awx/ui_next/src/screens/Login/Login.test.jsx
Labels: component:ui, mergeit, state:needs_test

#9993 fix running analytics for the first time
  awx/main/tasks.py
Labels: mergeit

#9999 Allow users to set password policies via AUTH_PASSWORD_VALIDATORS
  awx/api/serializers.py
Labels: mergeit

#9996 Removes Snapshot tests
  awx/ui_next/src/components/NotificationList/NotificationListItem.test.jsx
  awx/ui_next/src/components/NotificationList/__snapshots__/NotificationListItem.test.jsx.snap
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.test.jsx
  awx/ui_next/src/components/PaginatedDataList/__snapshots__/ToolbarDeleteButton.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/DeleteRoleConfirmationModal.test.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.test.jsx
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/DeleteRoleConfirmationModal.test.jsx.snap
  awx/ui_next/src/components/ResourceAccessList/__snapshots__/ResourceAccessListItem.test.jsx.snap
Labels: component:ui, mergeit

#10002 Stop installing kubectl/oc
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: mergeit

#9995 Fixes bug deleting the last workflow survey question
  awx/ui_next/src/screens/Template/TemplateSurvey.jsx
  awx/ui_next/src/screens/Template/TemplateSurvey.test.jsx
Labels: component:ui, mergeit, type:bug

#9897 Properly tags Plural-able strings for translation, and removes unnecessary i18n
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobList.test.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.test.jsx
  awx/ui_next/src/components/TemplateList/TemplateList.jsx
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeList.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/screens/Organization/OrganizationList/OrganizationList.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
  awx/ui_next/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.jsx
Labels: component:ui, mergeit

#10011 Remove 'custom' as a Source Option from inventory_source Module
  awx_collection/plugins/modules/tower_inventory_source.py
Labels: component:awx_collection, mergeit

#10013 Upgrade Ansible Runner and AWX EE
  awx/settings/defaults.py
  requirements/requirements.txt
Labels: mergeit

#9895 Tower workflow schema
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#9896 Add workflow approval and node wait modules
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/plugins/modules/tower_workflow_approval.py
  awx_collection/plugins/modules/tower_workflow_node_wait.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/tower_workflow_launch/tasks/main.yml
Labels: component:awx_collection, mergeit, type:enhancement

#10021 Modify formatting in response to black update
  awx/api/generics.py
  awx/api/views/__init__.py
  awx/api/views/metrics.py
  awx/api/views/root.py
  awx/conf/serializers.py
  awx/main/models/base.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/dag_simple.py
  awx/main/tests/functional/api/test_generic.py
  awx/main/tests/unit/api/test_views.py
Labels: mergeit

#9998 Update patternfly packages
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui, mergeit

#10024 Add docs for building and using custom awx image
  INSTALL.md
  docs/build_awx_image.md
Labels: component:docs, mergeit

#9435 Fix misalignment checkbox final build
  awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.jsx
Labels: component:ui, mergeit

#9960 Fixes bug where credential form checkboxes were erroneously checked
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.test.jsx
  awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json
  awx/ui_next/src/screens/Credential/shared/data.towerCredential.json
Labels: component:ui, mergeit

#10003 Log adjustments made to the analytics interval due to the 4-week limit
  awx/main/analytics/collectors.py
  awx/main/analytics/core.py
  awx/main/tests/unit/analytics/test_collection_interval.py
Labels: component:api, mergeit, type:bug

#9965 Hide teams option when adding access role to a team
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
Labels: component:ui, mergeit

#10000 Fix project update
  awx_collection/plugins/modules/tower_project.py
  awx_collection/tests/integration/targets/tower_project/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#10025 Improve error handling / display when Ansible Runner errors
  awx/main/tasks.py
Labels: mergeit

#10033 Fix warning thrown about CodeDetail rows prop
  awx/ui_next/src/components/DetailList/CodeDetail.jsx
Labels: component:ui, mergeit

#10032 Bump timeout for unit-tests
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.test.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.test.jsx
  awx/ui_next/src/setupTests.js
Labels: component:ui, mergeit

#10034 add ouiaId to toolbar delete button
  awx/ui_next/src/components/PaginatedDataList/ToolbarDeleteButton.jsx
Labels: component:ui, mergeit

#10035 Make Workflow Surveys Idempotent
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#10042 Remove inventory-related docs which are outdated or wrong
  docs/credentials/custom_credential_types.md
  docs/inventory/inventory_plugins.md
  docs/inventory/inventory_refresh.md
  docs/inventory/scm_inventory.md
  docs/named_url.md
  docs/resource_copy.md
Labels: component:api, component:docs, mergeit

#10037 Fix a few unit-tests warnings
  awx/ui_next/.eslintrc
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.test.jsx
  awx/ui_next/src/screens/Credential/shared/CredentialForm.jsx
  awx/ui_next/src/screens/Inventory/InventoryDetail/InventoryDetail.test.jsx
  awx/ui_next/src/screens/Login/Login.jsx
  awx/ui_next/src/screens/Metrics/Metrics.test.jsx
Labels: component:ui, mergeit

#10041 Unit test warning cleanup
  awx/ui_next/src/components/JobList/JobListCancelButton.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleListItem.jsx
  awx/ui_next/src/screens/Credential/CredentialEdit/CredentialEdit.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
Labels: component:ui, mergeit

#10036 ProjectList: Fixes columns misalignment.
  awx/ui_next/src/screens/Project/ProjectList/ProjectList.jsx
Labels: component:ui, mergeit, type:bug

#9957 Isolated removal
  Makefile
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/api/views/mixin.py
  awx/conf/registry.py
  awx/conf/serializers.py
  awx/conf/settings.py
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
  awx/main/conf.py
  awx/main/isolated/.gitignore
  awx/main/isolated/__init__.py
  awx/main/isolated/manager.py
  awx/main/management/commands/generate_isolated_key.py
  awx/main/management/commands/list_instances.py
  awx/main/management/commands/provision_instance.py
  awx/main/management/commands/register_queue.py
  awx/main/management/commands/run_wsbroadcast.py
  awx/main/management/commands/test_isolated_connection.py
  awx/main/managers.py
  awx/main/migrations/0139_isolated_removal.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/ha.py
  awx/main/models/jobs.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_instance_group.py
  awx/main/tests/functional/api/test_settings.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/test_tasks.py
  awx/main/wsbroadcast.py
  awx/playbooks/check_isolated.yml
  awx/playbooks/clean_isolated.yml
  awx/playbooks/heartbeat_isolated.yml
  awx/playbooks/run_isolated.yml
  awx/plugins/isolated/awx_capacity.py
  awx/plugins/isolated/awx_isolated_cleanup.py
  awx/plugins/isolated/mkfifo.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/production.py
  docs/clustering.md
  docs/container_groups.md
  docs/container_groups/README.md
  docs/tasks.md
  tools/ansible/roles/dockerfile/files/settings.py
  tools/docker-isolated-override.yml
  tools/docker-isolated/Dockerfile
  tools/docker-isolated/README.md
Labels: component:api, mergeit, type:enhancement

#10004 Adds an execution environment step to the ad hoc commands
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.test.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.test.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocExecutionEnironmentStep.test.jsx
  awx/ui_next/src/components/AdHocCommands/AdHocExecutionEnvironmentStep.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.jsx
  awx/ui_next/src/screens/Inventory/SmartInventoryHosts/SmartInventoryHostList.jsx
Labels: component:ui, mergeit, state:needs_devel
