Repository ansible/awx, pull requests merged in 2021-08, with the labels that each got.

#10788 Fix Collections Errors
  awx_collection/plugins/inventory/controller.py
  awx_collection/plugins/lookup/schedule_rrule.py
  awx_collection/plugins/module_utils/controller_module.py
  awx_collection/test/awx/conftest.py
  awx_collection/test/awx/test_project.py
Labels: component:awx_collection, state:needs_review, type:bug

#10803 WFJT Prompt- Survey- add OUIA locators for testability
  awx/ui/src/components/LaunchPrompt/steps/SurveyStep.js
Labels: component:ui, qe:e2e

#10801 Add Node Type to Instances page and modify "Type" to "Policy Type."
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
Labels: component:ui, qe:e2e, type:enhancement

#10592 Adds support for workflow node aliasing via identifier field
  awx/ui/src/components/Workflow/WorkflowNodeHelp.js
  awx/ui/src/components/Workflow/WorkflowNodeHelp.test.js
  awx/ui/src/components/Workflow/workflowReducer.js
  awx/ui/src/screens/Job/WorkflowOutput/WorkflowOutputGraph.test.js
  awx/ui/src/screens/Job/WorkflowOutput/WorkflowOutputNode.js
  awx/ui/src/screens/Job/WorkflowOutput/useWsWorkflowOutput.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeAddModal.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeEditModal.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/useNodeTypeStep.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerGraph.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerNode.js
  awx/ui/src/util/strings.js
Labels: component:ui, type:enhancement

#10797 Update workflow to use pull_request_target
  .github/CODEOWNERS
  .github/workflows/e2e_test.yml
Labels: qe:e2e, type:task

#10807 Fix Broken Collections Docs
  awx_collection/plugins/doc_fragments/auth_plugin.py
Labels: component:awx_collection, state:needs_review, type:bug

#10722 Ensures that field is on screen behind the confirmation modal
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
  awx/ui/src/screens/Setting/shared/SharedFields.js
  awx/ui/src/screens/Setting/shared/SharedFields.test.js
Labels: component:ui, qe:e2e, type:bug

#10810 Bump npm version inside container
  awx/ui/README.md
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: component:ui, state:needs_review

#10796 Add job id to job details screen
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui, qe:e2e

#10794 Show PAT as part of bulk delete list
  awx/ui/src/components/DeleteButton/DeleteButton.js
  awx/ui/src/screens/Application/shared/ApplicationForm.js
  awx/ui/src/screens/User/UserTokenDetail/UserTokenDetail.js
  awx/ui/src/screens/User/UserTokenList/UserTokenList.js
  awx/ui/src/screens/User/UserTokenList/UserTokenListItem.js
  awx/ui/src/screens/User/shared/UserTokenForm.js
Labels: component:ui, qe:e2e

#10772 Upgrade formik
  awx/ui/package-lock.json
  awx/ui/package.json
Labels: type:task, component:ui

#10819 Remove Clear All button in search when filters cleared
  awx/ui/src/components/Search/Search.js
  awx/ui/src/components/Search/getChipsByKey.js
  awx/ui/src/components/Search/getChipsByKey.test.js
Labels: component:ui

#10789 add minikube to github bug template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: component:docs

#10821 Add Ids to ease tests
  awx/ui/src/components/PaginatedTable/ToolbarDeleteButton.js
  awx/ui/src/screens/User/UserTokenList/UserTokenList.js
  awx/ui/src/screens/User/UserTokenList/UserTokenListItem.js
Labels: component:ui, state:needs_review, qe:e2e

#10826 Point to the Correct Name for AAP Within Collections
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/test/awx/test_module_utils.py
Labels: type:bug, state:needs_review, component:awx_collection

#10828 Addresses permission problem on host group list and adds convergence data to Prompt Detail
  awx/ui/src/api/models/Hosts.js
  awx/ui/src/components/PromptDetail/PromptDetail.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.js
Labels: component:ui, state:needs_review, qe:e2e

#10832 Update inventory source sync button on kebab
  awx/ui/src/components/PaginatedTable/ToolbarSyncSourceButton.js
  awx/ui/src/components/PaginatedTable/ToolbarSyncSourceButton.test.js
  awx/ui/src/components/PaginatedTable/index.js
  awx/ui/src/screens/Inventory/InventorySources/InventorySourceList.js
Labels: component:ui, state:needs_review, qe:e2e

#10703 Marks dashboard chart axis labels for translation
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Dashboard/shared/LineChart.js
Labels: component:ui, qe:e2e

#10809 Remove Collections Module Parameters Deprecated in Controller 4.0.0
  awx_collection/plugins/modules/credential.py
  awx_collection/plugins/modules/job_wait.py
  awx_collection/plugins/modules/notification_template.py
  awx_collection/test/awx/test_credential.py
  awx_collection/tests/integration/targets/credential/tasks/main.yml
  awx_collection/tests/integration/targets/job_wait/tasks/main.yml
  awx_collection/tests/integration/targets/notification_template/tasks/main.yml
Labels: state:in_progress, component:awx_collection

#10856 Update awxkit random_title setting non_ascii to False
  awxkit/awxkit/utils/__init__.py
Labels: type:task, state:needs_review

#10864 Generate a small random title size on awxkit when necessary
  awxkit/awxkit/utils/__init__.py
Labels: type:task

#10869 Fixes several react warnings
  awx/ui/src/components/Lookup/Lookup.js
  awx/ui/src/screens/ActivityStream/ActivityStream.js
  awx/ui/src/screens/InstanceGroup/InstanceGroup.js
  awx/ui/src/screens/InstanceGroup/InstanceGroup.test.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.js
Labels: component:ui, qe:e2e

#10888 Update runtime.yml to Include Ansible Version Requirement
  awx_collection/meta/runtime.yml
Labels: state:needs_review, component:awx_collection

#10783 Fix 10587 managed job time
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/src/components/DetailList/NumberSinceDetail.js
  awx/ui/src/components/Schedule/ScheduleAdd/ScheduleAdd.test.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/Schedule/ScheduleEdit/ScheduleEdit.test.js
  awx/ui/src/components/Schedule/ScheduleList/ScheduleListItem.js
  awx/ui/src/components/Schedule/ScheduleOccurrences/ScheduleOccurrences.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
  awx/ui/src/components/Schedule/shared/buildRuleObj.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionModal.js
  awx/ui/src/util/dates.js
  awx/ui/src/util/dates.test.js
Labels: type:bug, component:ui, qe:e2e

#10885 Update Readme.md
  tools/docker-compose/README.md
Labels: type:enhancement, component:api, component:ui

#10849 Update useBrandName
  awx/ui/public/static/media/default.strings.json
  awx/ui/src/components/About/About.js
  awx/ui/src/components/About/About.test.js
  awx/ui/src/components/AdHocCommands/AdHocDetailsStep.js
  awx/ui/src/components/AppContainer/AppContainer.test.js
  awx/ui/src/hooks/useBrandName.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/ManualSubForm.js
  awx/ui/src/screens/Setting/SettingList.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
Labels: state:needs_devel, component:ui, state:needs_test, qe:e2e

#10903 Fix Test Playbooks, Update README, Make Module Docs More Informative
  awx_collection/README.md
  awx_collection/plugins/modules/credential.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/tests/integration/targets/ad_hoc_command_cancel/tasks/main.yml
  awx_collection/tests/integration/targets/inventory/tasks/main.yml
  awx_collection/tests/integration/targets/inventory_source/tasks/main.yml
  awx_collection/tests/integration/targets/job_launch/tasks/main.yml
  awx_collection/tests/integration/targets/job_template/tasks/main.yml
  awx_collection/tests/integration/targets/project/tasks/main.yml
  awx_collection/tests/integration/targets/project_manual/tasks/create_project_dir.yml
  awx_collection/tests/integration/targets/project_manual/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
  awx_collection/tools/roles/template_galaxy/templates/README.md.j2
Labels: component:awx_collection

#10892 fix typo Bienvenue French logon screen
  awx/ui/src/locales/fr/messages.po
Labels: type:bug, component:api, component:ui, state:needs_review

#10907 properly validates node
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/useNodeTypeStep.js
Labels: component:ui, qe:e2e

#10898 Validate that start/end datetime creates at least 1 schedule.
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
Labels: type:bug, component:ui, qe:e2e

#10859 Remove warning for SSO session when logging in
  awx/ui/src/contexts/Session.js
Labels: component:ui, qe:e2e

#10917 Adds source data to job list and job details view
  awx/ui/src/components/JobList/JobList.js
  awx/ui/src/components/JobList/JobList.test.js
  awx/ui/src/components/JobList/JobListItem.js
  awx/ui/src/components/JobList/JobListItem.test.js
  awx/ui/src/screens/Job/Job.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui, qe:e2e

#10928 Auto fix dep audit
  awx/ui/package-lock.json
Labels: component:ui, qe:e2e

#10727 Code changes to support execution-only nodes in receptor mesh
  Makefile
  awx/api/views/__init__.py
  awx/main/constants.py
  awx/main/managers.py
  awx/main/migrations/0153_instance_last_seen.py
  awx/main/models/ha.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_instance.py
  awx/main/tests/functional/test_jobs.py
  awx/main/tests/unit/models/test_ha.py
  awx/main/utils/common.py
  awx/main/utils/receptor.py
  awx/main/wsbroadcast.py
  awx/settings/defaults.py
  docs/receptor_mesh.md
  tools/docker-compose-cluster.yml
  tools/docker-compose-cluster/awx-1-receptor.conf
  tools/docker-compose-cluster/awx-2-receptor.conf
  tools/docker-compose-cluster/awx-3-receptor.conf
  tools/docker-compose/README.md
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/haproxy.cfg.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-awx.conf.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-hop.conf.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-worker.conf.j2
Labels: type:enhancement, component:api

#10934 Fixes issue where the wrong text appeared in modal
  awx/ui/src/components/ResourceAccessList/DeleteRoleConfirmationModal.js
  awx/ui/src/components/ResourceAccessList/DeleteRoleConfirmationModal.test.js
Labels: type:bug, component:ui, qe:e2e

#10954 Use ansible-runner imports for cpu and memory calculation
  awx/main/models/ha.py
  awx/main/utils/common.py
Labels: component:api, state:needs_review

#10972 Check dynamic_input fields also with has_input()
  awx/main/models/credential/__init__.py
Labels: type:bug

#10949 Always use controlplane as project update backup IG
  awx/main/models/projects.py
  awx/main/tests/conftest.py
  awx/main/tests/functional/task_management/test_rampart_groups.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/tests/functional/test_instances.py
Labels: component:api

#10909 Refactor Job Output component
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/JobOutput/JobOutputSearch.js
  awx/ui/src/screens/Job/JobOutput/PageControls.js
  awx/ui/src/screens/Job/JobOutput/connectJobSocket.js
  awx/ui/src/screens/Job/JobOutput/getEventRequestParams.js
  awx/ui/src/screens/Job/JobOutput/getLineTextHtml.js
  awx/ui/src/screens/Job/JobOutput/isHostEvent.js
  awx/ui/src/screens/Job/JobOutput/loadJobEvents.js
Labels: component:ui, qe:e2e

#10920 Update Workflow Node Convergence
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerNode.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerNode.test.js
Labels: component:ui, qe:e2e

#10959 Fixes misalignment on template list and advanced search Key dropdown bug
  awx/ui/src/api/models/Users.js
  awx/ui/src/components/PaginatedTable/HeaderRow.js
  awx/ui/src/screens/Credential/CredentialList/CredentialList.js
  awx/ui/src/screens/Host/HostList/HostList.js
  awx/ui/src/screens/Host/HostList/HostList.test.js
  awx/ui/src/screens/Inventory/InventoryHosts/InventoryHostList.js
  awx/ui/src/screens/Inventory/InventoryHosts/InventoryHostList.test.js
  awx/ui/src/screens/Inventory/InventorySources/InventorySourceList.js
  awx/ui/src/screens/ManagementJob/ManagementJobList/ManagementJobList.js
  awx/ui/src/screens/User/UserOrganizations/UserOrganizationList.js
  awx/ui/src/screens/User/UserOrganizations/UserOrganizationList.test.js
Labels: component:ui, qe:e2e

#10982 Ensure deterministic order of JSON serializing for misc auth settings
  awx/ui/src/screens/Setting/LDAP/LDAPDetail/LDAPDetail.test.js
  awx/ui/src/screens/Setting/MiscAuthentication/MiscAuthenticationDetail/MiscAuthenticationDetail.test.js
  awx/ui/src/screens/Setting/shared/SettingDetail.js
Labels: type:bug, component:ui, qe:e2e

#10965 Associates ldap_dn on a first User() login
  awx/sso/backends.py
Labels: type:bug, component:api
