Repository ansible/awx, pull requests merged in 2021-05, with the labels that each got.

#10067 Unit test warning cleanup
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.jsx
  awx/ui_next/src/components/MultiSelect/useSyncedSelectValue.js
  awx/ui_next/src/screens/Inventory/InventoryEdit/InventoryEdit.jsx
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/LabelSelect.jsx
  awx/ui_next/src/util/useIsMounted.js
  awx/ui_next/src/util/useRequest.js
Labels: component:ui, mergeit

#10081 Fix unit-test styling warning
  awx/ui_next/src/components/AdHocCommands/AdHocCommandsWizard.jsx
Labels: component:ui, mergeit

#10084 Revert the code that prevents sysadmins from changing managed EEs
  awx/api/views/__init__.py
  awx/main/access.py
Labels: mergeit

#10085 Make the check_migrations command a direct alias of makemigration
  awx/main/management/commands/check_migrations.py
Labels: mergeit

#10089 Fix projects to use the utility function get_default_execution_environment
  awx/main/models/projects.py
Labels: mergeit

#10056 Convert user sub-lists to tables
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizationList.jsx
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizationList.test.jsx
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizationListItem.jsx
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizationListItem.test.jsx
  awx/ui_next/src/screens/User/UserOrganizations/UserOrganizations.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesList.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.test.jsx
  awx/ui_next/src/screens/User/UserTeams/UserTeamList.jsx
  awx/ui_next/src/screens/User/UserTeams/UserTeamListItem.jsx
  awx/ui_next/src/screens/User/UserTeams/UserTeamListItem.test.jsx
Labels: component:ui, mergeit, type:enhancement

#10096 Fix CSP error on Safari
  awx/ui_next/public/installing.html
Labels: mergeit

#10094 add notification error to notification template list view
  awx/api/serializers.py
  awx/main/tests/functional/test_notifications.py
Labels: mergeit

#10047 add org search to labels
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
  awx_collection/tests/integration/targets/tower_workflow_job_template/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#10077 Fix tower_job_launch tags being passed to API
  awx_collection/plugins/modules/tower_job_launch.py
  awx_collection/tests/integration/targets/tower_job_launch/tasks/main.yml
Labels: component:api, component:awx_collection, mergeit, type:bug

#10040 Convert Inventory sub-lists to tables
  awx/ui_next/src/components/PaginatedTable/ActionsTd.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.test.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.test.jsx
  awx/ui_next/src/screens/Host/HostList/HostListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHostGroups/InventoryHostGroupsList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryHosts/InventoryHostList.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.test.jsx
Labels: component:ui, mergeit

#10105 Make date consistent on tooltip display
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
Labels: component:ui, mergeit

#10044 Properly adds survey default values on Schedules
  awx/ui_next/src/components/Schedule/ScheduleAdd/ScheduleAdd.jsx
  awx/ui_next/src/components/Schedule/ScheduleAdd/ScheduleAdd.test.jsx
  awx/ui_next/src/components/Schedule/ScheduleDetail/ScheduleDetail.jsx
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.jsx
  awx/ui_next/src/components/Schedule/ScheduleEdit/ScheduleEdit.test.jsx
Labels: component:ui, mergeit, type:bug

#10100 Rename awx to automation for pod names
  awx/main/scheduler/kubernetes.py
  awx/main/tasks.py
Labels: mergeit

#10106 Docker-compose requires the options to be passed before up
  Makefile
Labels: mergeit

#10116 Update Login page
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/Login/Login.jsx
  awx/ui_next/src/screens/Login/Login.test.jsx
Labels: component:ui, mergeit

#10066 Add testability for e2e tests
  awx/ui_next/src/components/AddDropDownButton/AddDropDownButton.jsx
  awx/ui_next/src/components/AssociateModal/AssociateModal.jsx
  awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx
  awx/ui_next/src/components/PaginatedDataList/ToolbarAddButton.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.jsx
  awx/ui_next/src/components/TemplateList/TemplateList.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentList.jsx
  awx/ui_next/src/screens/Host/HostGroups/HostGroupsList.jsx
  awx/ui_next/src/screens/InstanceGroup/ContainerGroupDetails/ContainerGroupDetails.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupDetails/InstanceGroupDetails.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
Labels: component:ui, mergeit

#10019 Fixes for a couple of credential form bugs
  awx/ui_next/src/screens/Credential/Credential.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx
Labels: component:ui, mergeit, type:bug

#10140 Adds bold to some list items
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.jsx
  awx/ui_next/src/screens/User/UserTeams/UserTeamListItem.jsx
Labels: component:ui, mergeit

#10141 Fix prop typo
  awx/ui_next/src/screens/Template/shared/PlaybookSelect.jsx
Labels: component:ui, mergeit

#10097 add custom_venv for backward compatibility
  awx_collection/plugins/modules/tower_inventory_source.py
  awx_collection/plugins/modules/tower_job_template.py
  awx_collection/plugins/modules/tower_organization.py
  awx_collection/plugins/modules/tower_project.py
Labels: component:awx_collection, component:ee, mergeit, priority:medium, type:enhancement

#9924 Redesign survey multiple choice
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/Template/Survey/MultipleChoiceField.jsx
  awx/ui_next/src/screens/Template/Survey/MultipleChoiceField.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionAdd.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionEdit.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionForm.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:bug

#10131 Converts Teams Roles tab to tables
  awx/ui_next/src/components/AppContainer/NavExpandableGroup.jsx
  awx/ui_next/src/components/Pagination/Pagination.jsx
  awx/ui_next/src/screens/Team/TeamRoles/TeamRoleListItem.jsx
  awx/ui_next/src/screens/Team/TeamRoles/TeamRoleListItem.test.jsx
  awx/ui_next/src/screens/Team/TeamRoles/TeamRolesList.jsx
  awx/ui_next/src/screens/Team/TeamRoles/TeamRolesList.test.jsx
Labels: component:ui, mergeit

#10150 `console.warning` is not exists on browser
  awx/ui_next/src/components/CodeEditor/CodeEditor.jsx
Labels: component:ui, mergeit, type:bug

#10086 Avoid prop reference error when recreating survey
  awx/ui_next/src/screens/Template/Survey/SurveyQuestionAdd.jsx
  awx/ui_next/src/screens/Template/TemplateSurvey.jsx
Labels: component:ui, mergeit, state:needs_test

#10174 Data migration to remove the isolated instances from the database
  awx/main/migrations/0141_remove_isolated_instances.py
Labels: component:api, mergeit, type:enhancement

#10184 Break out the pre-commit hook into an explicit script
  Makefile
  pre-commit.sh
Labels: component:api, mergeit, type:bug

#10145 Allow modify scm branch override
  awx/api/serializers.py
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
  awx/ui_next/src/screens/Job/shared/data.job.json
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.test.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
  awx/ui_next/src/types.js
Labels: component:ui, mergeit, state:needs_test

#9759 Make tower_license module idempotent
  awx_collection/plugins/modules/tower_license.py
Labels: component:awx_collection, mergeit, type:bug

#10113 Adds Job Cancel Button
  awx/ui_next/src/components/JobCancelButton/JobCancelButton.jsx
  awx/ui_next/src/components/JobCancelButton/JobCancelButton.test.jsx
  awx/ui_next/src/components/JobCancelButton/index.js
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSyncButton.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceSyncButton.test.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
  awx/ui_next/src/screens/Job/JobOutput/shared/OutputToolbar.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
Labels: component:ui, mergeit

#10183 Show Error if No Execution Environment is Found on Project Sync or Job Run
  awx/main/tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api, mergeit, type:bug

#10063 Add slider to adjust capacity_adjustment
  awx/ui_next/CONTRIBUTING.md
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/InstanceGroup/Instances/InstanceListItem.jsx
  awx/ui_next/src/screens/InstanceGroup/Instances/InstanceListItem.test.jsx
  awx/ui_next/src/util/useDebounce.jsx
  awx/ui_next/src/util/useDebounce.test.jsx
Labels: component:ui, mergeit

#10161 Display error for boolean fields
  awx/ui_next/src/components/FormField/sortErrorMessages.js
Labels: component:ui, mergeit

#10169 Always resolve launching status
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
Labels: component:ui, mergeit, type:bug

#10187 Warn but still recompile on lint error
  awx/ui_next/package.json
Labels: mergeit

#10175 Add more fields to .only since they get referenced
  awx/main/models/events.py
Labels: component:api, mergeit, type:bug

#10185 Drop the word 'name' from image field, add examples
  awx/main/migrations/0142_update_ee_image_field_description.py
  awx/main/models/execution_environments.py
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.jsx
  awx/ui_next/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.test.jsx
Labels: component:api, component:ui, mergeit, state:needs_test, type:bug

#10190 Remove the shebang line from pre-commit.sh
  pre-commit.sh
Labels: mergeit

#10171 Remove all AWX_ISOLATED* fields
  awx/ui_next/src/screens/Host/data.hostFacts.json
  awx/ui_next/src/screens/Inventory/shared/data.hostFacts.json
  awx/ui_next/src/screens/Job/shared/data.job.json
  awx/ui_next/src/screens/Setting/Jobs/JobsDetail/JobsDetail.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsDetail/JobsDetail.test.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/JobsEdit.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/JobsEdit.test.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/data.defaultJobSettings.json
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui_next/src/screens/Setting/shared/data.allSettings.json
  awx/ui_next/src/screens/Setting/shared/data.jobSettings.json
Labels: component:ui, mergeit, priority:high, type:bug

#10159 Add instance_group to inventory update serializer
  awx/api/serializers.py
Labels: component:api, mergeit, type:enhancement

#10148 Add Variables field validation in launch prompt
  awx/ui_next/src/components/CodeEditor/VariablesField.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/OtherPromptsStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/PreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useInventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useOtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/useLaunchSteps.js
Labels: component:ui, mergeit, type:bug

#9988 Fixes bug where workflow approvals page would crash if deleted username was referenced
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.jsx
Labels: component:ui, mergeit

#10202 Use non-root path links
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.jsx
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.test.jsx
  awx/ui_next/src/components/ContentError/ContentError.jsx
Labels: component:ui, mergeit, type:bug

#10179 Update login message to avoid duplicate brand name
  awx/ui_next/src/index.jsx
  awx/ui_next/src/locales/en/messages.po
  awx/ui_next/src/locales/es/messages.po
  awx/ui_next/src/locales/fr/messages.po
  awx/ui_next/src/locales/ja/messages.po
  awx/ui_next/src/locales/nl/messages.po
  awx/ui_next/src/locales/zh/messages.po
  awx/ui_next/src/locales/zu/messages.po
  awx/ui_next/src/screens/Login/Login.jsx
  awx/ui_next/src/screens/Login/Login.test.jsx
Labels: component:ui, mergeit

#10205 Add an nginx location directive for the favicon
  tools/docker-compose/nginx.vh.default.conf
Labels: component:api, component:ui, mergeit, type:bug

#10182 Use development container when updating dependencies
  Makefile
  awx/ui_next/README.md
  awx/ui_next/package-lock.json
Labels: component:ui, mergeit

#10121 Remove source_script from tower_inventory_source integration test
  awx_collection/tests/integration/targets/tower_inventory_source/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#10134 converts inventory groups related groups and related hosts to tables
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryGroupHosts/InventoryGroupHostListItem.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupList.test.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupListItem.jsx
  awx/ui_next/src/screens/Inventory/InventoryRelatedGroups/InventoryRelatedGroupListItem.test.jsx
Labels: component:ui, mergeit

#10212 created a TransmitterThread class to start transmit jobs within. Surr…
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#10005 Update with force option if branch_override
  awx/main/tasks.py
Labels: component:api, mergeit, type:bug

#10203 Add default error boundary around screens
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
  awx/ui_next/src/App.jsx
Labels: component:ui, mergeit

#10209 Fix failing integration test playbooks
  awx_collection/plugins/module_utils/tower_api.py
  awx_collection/tests/integration/targets/tower_ad_hoc_command_cancel/tasks/main.yml
  awx_collection/tests/integration/targets/tower_instance_group/tasks/main.yml
Labels: component:awx_collection, mergeit, type:bug

#10133 Adds support for pendo initialization across the app
  awx/ui_next/src/components/AppContainer/AppContainer.jsx
  awx/ui_next/src/components/AppContainer/AppContainer.test.jsx
  awx/ui_next/src/contexts/Config.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.test.jsx
  awx/ui_next/src/screens/Setting/UI/UIDetail/UIDetail.jsx
  awx/ui_next/src/screens/Setting/UI/UIEdit/UIEdit.jsx
  awx/ui_next/src/screens/Setting/UI/UIEdit/UIEdit.test.jsx
  awx/ui_next/src/util/bootstrapPendo.js
  awx/ui_next/src/util/issuePendoIdentity.js
Labels: component:ui, mergeit

#10068 Have the project update playbook warn if role/collection syncing is disabled
  awx/playbooks/project_update.yml
Labels: component:api, mergeit, state:needs_review

#10221 Add a check for the existence of pre-commit.sh
  Makefile
Labels: component:api, mergeit, type:bug

#10206 Commits settings.DEFAULT_EXECUTION_ENVIRONMENTS updates into the database
  awx/main/management/commands/create_preload_data.py
Labels: component:api, mergeit, type:bug

#10191 close db and cache connection in new threads
  awx/main/tasks.py
  awx/main/utils/common.py
Labels: component:api, mergeit, type:bug

#10217 Updates LingUI Again
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui, mergeit

#8185 Use inventory and env private_data_dir subfolders
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/models/inventory.py
  awx/main/tasks.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_execution_environments.py
  awx/main/utils/execution_environments.py
Labels: component:api, mergeit, type:enhancement

#9654 Adding host_metrics for customers who don't have automation analytics
  awx/main/management/commands/host_metric.py
  awx/main/migrations/0143_hostmetric.py
  awx/main/models/__init__.py
  awx/main/models/events.py
  awx/main/models/inventory.py
  awx/main/tests/functional/models/test_host_metric.py
Labels: component:api, mergeit, type:enhancement

#10195 Fix null issue for limit
  awx/ui_next/src/components/FieldWithPrompt/FieldWithPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useOtherPromptsStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
Labels: component:ui, mergeit, state:needs_test

#10245 Add testability to the search and pagination fields
  awx/ui_next/src/components/Pagination/Pagination.jsx
  awx/ui_next/src/components/Search/AdvancedSearch.jsx
  awx/ui_next/src/components/Search/Search.jsx
Labels: component:ui, mergeit

#10230 Adding AWX_CONTAINER_GROUP_POD_LAUNCH_TIMEOUT in defaults.py
  awx/main/tasks.py
  awx/settings/defaults.py
Labels: component:api, mergeit, type:enhancement

#10250 Add locators to screen page titles
  awx/ui_next/src/components/ScreenHeader/ScreenHeader.jsx
  awx/ui_next/src/screens/ActivityStream/ActivityStream.jsx
Labels: component:ui, mergeit

#10239 Only initialize pendo if the key is available
  awx/ui_next/src/components/AppContainer/AppContainer.test.jsx
  awx/ui_next/src/util/issuePendoIdentity.js
Labels: component:ui, mergeit

#10251 tweak message about image pull option
  awx/main/migrations/0126_executionenvironment_container_options.py
  awx/main/models/execution_environments.py
Labels: component:api, mergeit

#10261 Bump receptor and receptorctl
  requirements/requirements.txt
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: mergeit

#9904 Document usage of workflow job template nodes with approvals
  awx_collection/plugins/modules/tower_workflow_job_template_node.py
Labels: component:awx_collection, component:docs, mergeit

#10248 Updates PF
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui, mergeit

#10269 Update migration page as per latest name changes
  awx/ui_next/public/installing.html
  awx/ui_next/urls.py
Labels: component:ui, mergeit

#10268 Update branding to match guidelines
  awx/main/analytics/core.py
  awx/main/conf.py
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.test.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.jsx
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
Labels: mergeit

#10271 Enable Export of Galaxy Credentials Associated to Organizations
  awxkit/awxkit/api/pages/credentials.py
  awxkit/awxkit/api/resources.py
Labels: component:awx_collection, component:cli, mergeit, type:bug

#10267 Fixes bug where activity stream changes were displaying as [object object]
  awx/ui_next/src/screens/ActivityStream/ActivityStreamDetailButton.jsx
  awx/ui_next/src/screens/ActivityStream/ActivityStreamDetailButton.test.jsx
Labels: component:ui, mergeit, type:bug

#10289 The list secrets role rule is no longer not needed for container groups
  awx/main/scheduler/kubernetes.py
Labels: mergeit

#10278 Update message about Default Execution Environment
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
Labels: component:ui, mergeit

#10293 Redirect documentation to awx-operator docs
  INSTALL.md
Labels: component:docs, mergeit

#10295 Move irc references to point to irc.libera.chat
  CONTRIBUTING.md
  ISSUES.md
  README.md
Labels: component:docs, mergeit

#10234 Remove explicit eula acceptance
  awx/api/views/root.py
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/EulaStep.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.jsx
  awx/ui_next/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.test.jsx
  awx_collection/plugins/modules/tower_license.py
Labels: component:api, component:ui, mergeit, state:needs_review, type:enhancement

#10102 Add the ability to disable local authentication
  awx/api/conf.py
  awx/conf/signals.py
  awx/main/backends.py
  awx/main/conf.py
  awx/main/management/commands/expire_sessions.py
  awx/main/middleware.py
  awx/settings/defaults.py
  awx/sso/fields.py
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.jsx
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.test.jsx
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemEdit/MiscSystemEdit.jsx
  awx/ui_next/src/screens/Setting/MiscSystem/MiscSystemEdit/MiscSystemEdit.test.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.test.jsx
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui_next/src/screens/Setting/shared/data.allSettings.json
Labels: component:api, component:ui, mergeit, state:needs_review, type:enhancement

#10279 Fixes bug where users were unable to click on text next to checkboxes/radios in modals
  awx/ui_next/src/components/AddRole/SelectResourceStep.jsx
  awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.jsx
  awx/ui_next/src/components/OptionsList/OptionsList.jsx
Labels: component:ui, mergeit, type:bug

#10294 clarify format of date for host_metric
  awx/main/management/commands/host_metric.py
Labels: mergeit
