Repository ansible/awx, pull requests merged in 2021-09, with the labels that each got.

#10985 Exclude control-only nodes from IG policy calculations
  awx/main/tasks.py
  awx/main/tests/functional/test_instances.py
Labels: component:api, state:needs_review

#10929 Validate that control-only Instance nodes cannot change IG membership
  awx/api/views/__init__.py
  awx/api/views/mixin.py
  awx/main/tests/functional/api/test_instance_group.py
Labels: type:enhancement, component:api, state:needs_review

#10927 Disable checkbox for instances with node type control.
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
Labels: state:in_progress, component:ui, qe:e2e

#11007 Remove deprecated lingui add-locale cmd
  awx/ui/CONTRIBUTING.md
  awx/ui/package.json
Labels: component:ui, qe:e2e

#11005 dev environment - change location of receptor socket and sync awx and receptor nodes function
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-awx.conf.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-worker.conf.j2
Labels: component:api, state:needs_review

#10958 Fixes validation issues associated with the Notification Form
  awx/ui/.eslintrc
  awx/ui/src/components/FormField/ArrayTextField.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/NotificationTemplate/shared/TypeInputsSubForm.js
  awx/ui/src/util/validators.js
Labels: component:ui, qe:e2e

#11001 Sort instance by hostname instead of name.
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
Labels: type:bug, component:ui, qe:e2e

#11013 Display finished date once the job is finished
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui, state:needs_review, qe:e2e

#11003 Adds deprecation banner
  awx/ui/src/screens/Setting/RADIUS/RADIUSDetail/RADIUSDetail.js
  awx/ui/src/screens/Setting/RADIUS/RADIUSDetail/RADIUSDetail.test.js
  awx/ui/src/screens/Setting/TACACS/TACACSDetail/TACACSDetail.js
  awx/ui/src/screens/Setting/TACACS/TACACSDetail/TACACSDetail.test.js
Labels: component:ui, qe:e2e

#10994 Add string `Filter By` to be translated
  awx/ui/src/components/Search/Search.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
Labels: component:ui, qe:e2e

#10987 Add websockets to Inventory Source Details
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.js
  awx/ui/src/screens/Inventory/InventorySources/useWsInventorySourcesDetails.js
  awx/ui/src/screens/Inventory/InventorySources/useWsInventorySourcesDetails.test.js
Labels: component:ui, qe:e2e

#11018 Add Node Type Information to /api/v2/ping Endpoint
  awx/api/views/root.py
Labels: component:api, state:needs_review

#11002 Allow manually running a health check, and make other adjustments to the health check trigger
  Makefile
  awx/api/permissions.py
  awx/api/serializers.py
  awx/api/templates/api/instance_health_check.md
  awx/api/urls/instance.py
  awx/api/views/__init__.py
  awx/conf/views.py
  awx/main/migrations/0155_improved_health_check.py
  awx/main/models/ha.py
  awx/main/tasks.py
  awx/main/tests/functional/api/test_instance.py
  awx/main/tests/functional/test_instances.py
  awx/main/utils/receptor.py
  awx/settings/defaults.py
  docs/receptor_mesh.md
Labels: type:enhancement, component:api

#10978 Fixes translation issue on Schedule Form
  awx/ui/src/components/Schedule/shared/DateTimePicker.js
  awx/ui/src/components/Schedule/shared/DateTimePicker.test.js
  awx/ui/src/components/Schedule/shared/FrequencyDetailSubform.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
Labels: component:ui, qe:e2e

#11011 Add strings to be translated
  awx/ui/src/components/LaunchPrompt/steps/SurveyStep.js
  awx/ui/src/components/MultiSelect/TagMultiSelect.js
  awx/ui/src/components/Search/Search.js
  awx/ui/src/screens/ActivityStream/ActivityStream.js
  awx/ui/src/screens/Credential/shared/CredentialForm.js
  awx/ui/src/screens/Credential/shared/CredentialFormFields/BecomeMethodField.js
  awx/ui/src/screens/Dashboard/DashboardGraph.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.js
  awx/ui/src/screens/Metrics/Metrics.js
  awx/ui/src/screens/Template/Survey/SurveyReorderModal.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
  awx/ui/src/screens/Template/shared/LabelSelect.js
  awx/ui/src/screens/Template/shared/PlaybookSelect.js
Labels: component:ui, qe:e2e

#11035 Update image variable name for awx-operator app image docs
  docs/build_awx_image.md
Labels: component:docs

#11034 Assure consistent ordering with default IG first
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/test_instances.py
Labels: type:bug, component:api

#11014 Add instance node type to associate modal.
  awx/ui/src/components/AssociateModal/AssociateModal.js
  awx/ui/src/components/OptionsList/OptionsList.js
Labels: component:ui

#11023 Show button to cancel inventory source sync
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Inventory/InventoryList/InventoryListItem.js
  awx/ui/src/screens/Inventory/InventoryList/InventoryListItem.test.js
  awx/ui/src/screens/Inventory/InventorySources/InventorySourceListItem.js
  awx/ui/src/screens/Inventory/InventorySources/InventorySourceListItem.test.js
  awx/ui/src/screens/Inventory/InventorySources/useWsInventorySources.js
  awx/ui/src/screens/Inventory/InventorySources/useWsInventorySources.test.js
Labels: component:ui

#11065 Minor update linguirc
  awx/ui/.linguirc
Labels: component:ui, qe:e2e

#11062 Collection version change
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/test/awx/test_module_utils.py
Labels: type:enhancement

#11066 UI translation strings for devel branch
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/zh/LC_MESSAGES/django.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
Labels: type:enhancement, component:api, component:ui, state:needs_test, qe:e2e

#11029 Translates the UI strings on the metrics pages
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Metrics/LineChart.js
  awx/ui/src/screens/Metrics/Metrics.js
Labels: component:ui, qe:e2e

#11069 This adds Instance Details view
  awx/ui/src/api/models/Instances.js
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/index.js
  awx/ui/src/screens/InstanceGroup/InstanceGroup.js
  awx/ui/src/screens/InstanceGroup/InstanceGroups.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
  awx/ui/src/screens/InstanceGroup/Instances/Instances.js
  awx/ui/src/screens/InstanceGroup/Instances/index.js
Labels: component:ui, state:needs_review, type:feature, qe:e2e

#11064 Enable Jobs to Run on Execution-Only Nodes Via EEs from Protected Registries
  awx/main/tasks.py
Labels: type:bug, priority:high, component:api, state:needs_review

#11078 Pass --delete flag to worker for execution node cleanup
  awx/main/tasks.py
Labels: type:bug, component:api

#11081 add credentials option to schedules
  awx_collection/plugins/modules/schedule.py
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
Labels: type:enhancement, priority:medium, state:needs_review, component:awx_collection

#10910 Fix overwrite bug where hosts with no instance ID var are re-created
  awx/main/management/commands/inventory_import.py
  awx/main/tests/functional/commands/test_inventory_import.py
Labels: type:bug, component:api

#11097 Fix worfklow node info
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeViewModal.test.js
Labels: component:ui, qe:e2e

#11096 Fixes convergence data value on node edit mode
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
Labels: type:bug, component:ui, qe:e2e

#11090 Adds Health Check functionality to instance list
  awx/ui/src/api/models/Instances.js
  awx/ui/src/components/InstanceToggle/InstanceToggle.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
Labels: component:ui, state:needs_test, qe:e2e

#11102 Adds Popout for extra vars on Job Details view
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui, qe:e2e

#11115 Fix broken link for inventory
  awx/ui/src/components/PromptDetail/PromptJobTemplateDetail.js
  awx/ui/src/components/PromptDetail/PromptJobTemplateDetail.test.js
Labels: component:ui, qe:e2e

#11117 Avoid setting controller_node to an execution node for container jobs
  awx/main/scheduler/task_manager.py
Labels: type:bug, component:api

#11104 Prevents form validation on cancel button click
  awx/ui/src/components/FormActionGroup/FormActionGroup.js
Labels: component:ui, state:needs_review, qe:e2e

#11107 Wrap ExecutionEnv Lookup in SettingGroup component.
  awx/ui/src/components/Lookup/ExecutionEnvironmentLookup.js
  awx/ui/src/components/Lookup/ExecutionEnvironmentLookup.test.js
  awx/ui/src/components/Lookup/Lookup.js
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemEdit/MiscSystemEdit.js
  awx/ui/src/screens/Setting/shared/SharedFields.js
  awx/ui/src/screens/Setting/shared/index.js
Labels: type:enhancement, component:ui, state:needs_review, qe:e2e

#11123 Removes receptor instances from select option on metrics screen
  awx/ui/src/screens/Metrics/Metrics.js
  awx/ui/src/screens/Metrics/Metrics.test.js
Labels: component:ui, state:needs_review, qe:e2e

#11125 Remove unused component VariablesInput
  awx/ui/src/components/CodeEditor/VariablesInput.js
  awx/ui/src/components/CodeEditor/index.js
Labels: component:ui, qe:e2e

#11122 Update empty survey list
  awx/ui/src/screens/Template/Survey/SurveyList.js
  awx/ui/src/screens/Template/Survey/SurveyToolbar.js
Labels: component:ui, state:needs_test, qe:e2e

#11074 prevent duplicate UUIDs from being created and allow users to update hostnames based on uuid
  awx/main/managers.py
  awx/main/models/ha.py
Labels: type:bug, type:enhancement, state:in_progress

#11093 Introduce the control-service TLS support on receptor
  awx/main/tasks.py
  awx/main/utils/receptor.py
Labels: type:enhancement, state:in_progress, component:api

#11120 Filter controller_node selection to online nodes
  awx/main/models/ha.py
Labels: type:bug, component:api

#11118 Project updates must run on controller nodes
  awx/main/tasks.py
Labels: type:bug, priority:high, component:api, state:needs_review

#11132 Break lines for long strings on main lists
  awx/ui/src/components/JobList/JobListItem.js
  awx/ui/src/components/PaginatedTable/TdBreakWord.js
  awx/ui/src/components/PaginatedTable/index.js
  awx/ui/src/components/Schedule/ScheduleList/ScheduleListItem.js
  awx/ui/src/components/TemplateList/TemplateListItem.js
  awx/ui/src/screens/Application/ApplicationsList/ApplicationListItem.js
  awx/ui/src/screens/Credential/CredentialList/CredentialListItem.js
  awx/ui/src/screens/CredentialType/CredentialTypeList/CredentialTypeListItem.js
  awx/ui/src/screens/ExecutionEnvironment/ExecutionEnvironmentList/ExecutionEnvironmentListItem.js
  awx/ui/src/screens/Host/HostList/HostListItem.js
  awx/ui/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupListItem.js
  awx/ui/src/screens/Inventory/InventoryHosts/InventoryHostItem.js
  awx/ui/src/screens/Inventory/InventoryList/InventoryListItem.js
  awx/ui/src/screens/Inventory/InventorySources/InventorySourceListItem.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.js
  awx/ui/src/screens/Organization/OrganizationList/OrganizationListItem.js
  awx/ui/src/screens/Project/ProjectList/ProjectListItem.js
  awx/ui/src/screens/Team/TeamList/TeamListItem.js
  awx/ui/src/screens/User/UserList/UserListItem.js
Labels: component:ui, state:needs_test, qe:e2e

#11134 Do not display EE if a job was canceled
  awx/ui/src/components/JobList/JobListItem.js
  awx/ui/src/components/JobList/JobListItem.test.js
Labels: component:ui, state:needs_test, qe:e2e

#11142 Disable autodiscovery except for docker-compose
  awx/main/tasks.py
  awx/settings/defaults.py
  awx/settings/development.py
Labels: type:enhancement, component:api

#11143 Fixed logic to avoid tracebacks when node_name is invalid
  awx/main/utils/receptor.py
Labels: state:needs_review

#11147 Wrap `setAuthRedirectTo` in useEffect.
  awx/ui/src/App.js
Labels: component:ui, qe:e2e

#11135 add ability to lookup unified job template by org
  awx_collection/plugins/modules/schedule.py
  awx_collection/plugins/modules/workflow_job_template_node.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: type:enhancement, component:api, state:needs_review, component:awx_collection

#11151 simplify module utils python to single file
  awx_collection/plugins/module_utils/awxkit.py
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/plugins/module_utils/controller_module.py
Labels: type:enhancement, component:api, state:needs_review, component:awx_collection

#11161 Fix bug that would run --worker-info health checks on control or hybrid nodes
  awx/main/tasks.py
  awx/main/tests/functional/test_tasks.py
Labels: type:bug, component:api

#11157 Redirect system path to management on jobs URL
  awx/ui/src/screens/Job/Job.js
Labels: component:ui, qe:e2e

#11070 Update Tasks and Clustering Doc Files
  docs/clustering.md
  docs/receptor_mesh.md
  docs/tasks.md
  tools/docker-compose/README.md
Labels: type:task, component:docs

#11156 Fix translation for instance list
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
Labels: component:ui, qe:e2e
