Repository ansible/awx, pull requests merged in 2021-10, with the labels that each got.

#11158 Properly validates Integer Survey Question with min value of 0
  awx/ui/src/components/LaunchPrompt/steps/useSurveyStep.js
  awx/ui/src/screens/Template/Survey/SurveyQuestionForm.js
Labels: component:ui, qe:e2e

#11171 Fix subform for AAP for inventory source
  awx/ui/src/screens/Inventory/shared/InventorySourceForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/ControllerSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/ControllerSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/index.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/InventorySourcesList.js
Labels: component:ui, qe:e2e

#11184 change locator- UserDateDetail
  awx/ui/src/components/DetailList/UserDateDetail.js
  awx/ui/src/screens/Credential/CredentialDetail/CredentialDetail.js
  awx/ui/src/screens/ExecutionEnvironment/ExecutionEnvironmentDetails/ExecutionEnvironmentDetails.js
  awx/ui/src/screens/Host/HostDetail/HostDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/User/UserTokenDetail/UserTokenDetail.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.js
Labels: component:ui, qe:e2e

#11163 Update websockets.md
  docs/websockets.md
Labels: component:docs

#11148 Updates PF dependencies, and Instance Toggle labels
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/src/components/InstanceToggle/InstanceToggle.js
  awx/ui/src/components/PaginatedTable/ActionsTd.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.test.js
Labels: type:bug, component:ui, state:needs_test, qe:e2e

#11192 Fixes delete message
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Organization/OrganizationList/OrganizationList.js
Labels: component:ui

#11183 Fixes Instance Group tooltip
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
Labels: component:ui, qe:e2e

#11204 Always set project sync execution_node to current host
  awx/main/tasks.py
Labels: component:api

#11201 Remove console.log
  awx/ui/src/screens/Job/JobOutput/JobOutput.test.js
Labels: component:ui, state:needs_review

#11200 Update unit-tests
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
Labels: component:ui

#11133 AWX dev environment changes for receptor work signing feature
  awx/main/tasks.py
  awx/main/utils/receptor.py
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-awx.conf.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-worker.conf.j2
Labels: type:enhancement, component:api

#11160 Consolidate cleanup actions under new `ansible-runner worker cleanup` command
  awx/main/constants.py
  awx/main/models/ha.py
  awx/main/signals.py
  awx/main/tasks.py
  awx/main/tests/functional/models/test_execution_environment.py
  awx/main/tests/unit/models/test_ha.py
  awx/main/tests/unit/utils/test_receptor.py
  awx/main/utils/receptor.py
  awx/settings/defaults.py
Labels: type:enhancement, component:api

#11286 Skip additional instance checks on unrecognized hosts
  awx/main/tasks.py
Labels: type:bug, component:api

#11270 Update dependency slackclient to slack_sdk
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/main/notifications/slack_backend.py
  awx/main/tests/unit/notifications/test_slack.py
  docs/licenses/slack-sdk.txt
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: type:bug, state:needs_review
