Repository ansible/awx, pull requests merged in 2021-01, with the labels that each got.

#8980 Simplify image build
  .dockerignore
  Makefile
  awx/main/management/commands/inventory_import.py
  awx/main/tests/functional/models/test_job.py
  awx/main/tests/unit/test_tasks.py
  awx/settings/development.py
  awx/settings/local_settings.py.docker_compose
  awx/ui_next/src/components/AnsibleSelect/AnsibleSelect.test.jsx
  awx/ui_next/src/screens/Host/data.hostFacts.json
  awx/ui_next/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.jsx
  awx/ui_next/src/screens/Inventory/shared/InventorySourceForm.jsx
  awx/ui_next/src/screens/Inventory/shared/data.hostFacts.json
  awx/ui_next/src/screens/Inventory/shared/data.inventory_source.json
  awx/ui_next/src/screens/Job/shared/data.job.json
  awx/ui_next/src/screens/Organization/OrganizationAdd/OrganizationAdd.test.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.jsx
  awx/ui_next/src/screens/Organization/shared/OrganizationForm.test.jsx
  awx/ui_next/src/screens/Project/ProjectAdd/ProjectAdd.test.jsx
  awx/ui_next/src/screens/Project/ProjectEdit/ProjectEdit.test.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.test.jsx
  awx_collection/plugins/modules/tower_project.py
  awx_collection/test/awx/test_inventory_source.py
  installer/build.yml
  installer/inventory
  installer/roles/image_build/files/Dockerfile.sdist
  installer/roles/image_build/tasks/main.yml
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/image_push/tasks/main.yml
  pytest.ini
  tools/scripts/awx-python
Labels: component:installer, mergeit

#8996 Fixed link to Content Hub in Tower module documentation
  awx_collection/tools/roles/template_galaxy/templates/README.md.j2
Labels: mergeit

#8836 Sustaining improve iso logging devel
  awx/main/isolated/manager.py
  awx/playbooks/check_isolated.yml
  awx/playbooks/run_isolated.yml
  awx/settings/defaults.py
Labels: component:api, mergeit

#8658 Move jt/wfjt created/modified details to the end right before the full width details
  awx/ui_next/src/screens/Application/ApplicationDetails/ApplicationDetails.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.jsx
Labels: component:ui_next, mergeit, qe:visual, type:enhancement

#9000 Small docs update
  CONTRIBUTING.md
  awx/ui_next/CONTRIBUTING.md
Labels: mergeit

#8892 Adds searchable keys and related keys to Credentials list
  awx/ui_next/src/components/Lookup/CredentialLookup.jsx
  awx/ui_next/src/screens/Credential/CredentialList/CredentialList.jsx
  awx/ui_next/src/screens/InstanceGroup/ContainerGroupEdit/ContainerGroupEdit.test.jsx
Labels: component:ui_next, mergeit, state:needs_devel

#9001 specify isolated_manager.log path
  awx/settings/production.py
Labels: mergeit

#9006 pin pip-tools for now
  requirements/updater.sh
Labels: mergeit

#9005 Make workflow_job.assert_successful() give specifics
  awxkit/awxkit/api/mixins/has_status.py
  awxkit/awxkit/api/pages/workflow_jobs.py
Labels: mergeit, type:enhancement

#9017 Changed task to job in job timeout description, fixes #9016
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: mergeit

#9008 Update autobahn to address CVE-2020-35678
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:installer, mergeit, type:bug

#8762 Add Google OAuth 2.0 setting edit form
  awx/ui_next/src/screens/Setting/GoogleOAuth2/GoogleOAuth2.test.jsx
  awx/ui_next/src/screens/Setting/GoogleOAuth2/GoogleOAuth2Edit/GoogleOAuth2Edit.jsx
  awx/ui_next/src/screens/Setting/GoogleOAuth2/GoogleOAuth2Edit/GoogleOAuth2Edit.test.jsx
Labels: component:ui_next, mergeit, type:feature

#9003 Adds sync button to project details page
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
  awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.test.jsx
  awx/ui_next/src/screens/Project/ProjectList/ProjectListItem.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSyncButton.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSyncButton.test.jsx
Labels: component:ui_next, mergeit, state:needs_review, state:needs_test

#9009 consolidate settings and delete dead settings
  awx/settings/defaults.py
  awx/settings/local_settings.py.docker_compose
  awx/settings/local_settings.py.example
  awx/settings/production.py
Labels: mergeit

#9002 Update dependencies
  awx/ui_next/package-lock.json
  awx/ui_next/package.json
Labels: component:ui_next, mergeit

#8654 Swap underscores for hyphens in qs namespace strings
  awx/ui_next/src/components/Lookup/InstanceGroupsLookup.jsx
  awx/ui_next/src/screens/CredentialType/CredentialTypeList/CredentialTypeList.jsx
  awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/InventorySourcesList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/WorkflowJobTemplatesList.jsx
Labels: Kebabs, component:ui_next, mergeit, state:needs_test

#8738 Adds vault IDs to Vault credential chips
  awx/ui_next/src/api/models/Jobs.js
  awx/ui_next/src/components/CredentialChip/CredentialChip.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.jsx
  awx/ui_next/src/components/Lookup/MultiCredentialsLookup.test.jsx
  awx/ui_next/src/screens/Job/Job.jsx
  awx/ui_next/src/screens/Project/Project.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/Template.test.jsx
Labels: component:ui_next, mergeit

#9040 When deleting a job sometimes we get this error
  awxkit/awxkit/api/pages/base.py
Labels: mergeit

#8880 Related #5080 openstack region field missing
  awx/locale/django.pot
  awx/locale/en-us/LC_MESSAGES/django.po
  awx/locale/fr/LC_MESSAGES/django.po
  awx/main/models/credential/__init__.py
  awx/main/models/credential/injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/ui_next/src/screens/Credential/shared/data.credentialTypes.json
Labels: component:api, component:ui_next, mergeit, state:needs_test, type:enhancement

#9044 silent_delete also needs to handle Confict
  awxkit/awxkit/api/pages/base.py
Labels: mergeit

#8943 Upgrade PostgreSQL from 10 to 12
  CONTRIBUTING.md
  Makefile
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/kubernetes/tasks/main.yml
  installer/roles/kubernetes/templates/postgresql-persistent.yml.j2
  installer/roles/kubernetes/templates/postgresql-values.yml.j2
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/upgrade_postgres.yml
  tools/docker-compose-cluster.yml
  tools/docker-compose.yml
  tools/scripts/awx-python
Labels: component:installer, mergeit, type:enhancement

#9054 Pin cryptography to pre 3 release
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: mergeit

#8776 Show access tab when credential does not belong to an organization
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/AddRole/AddResourceRole.test.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/SelectableCard/SelectableCard.jsx
  awx/ui_next/src/screens/Credential/Credential.jsx
  awx/ui_next/src/screens/Credential/Credential.test.jsx
  awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx
Labels: component:ui_next, mergeit, state:needs_test, type:feature

#9046 Do not drop inventories marked as has_inventory_sources
  awxkit/awxkit/api/pages/api.py
Labels: mergeit, type:bug

#9063 don't record AUTOMATION_ANALYTICS_LAST_GATHER updates
  awx/main/tasks.py
Labels: mergeit

#8860 Enabled jinja2.ChainableUndefined for custom webhook notifications
  awx/main/models/notifications.py
  awx_collection/test/awx/test_notification_template.py
  requirements/requirements.in
Labels: component:api, mergeit

#8656 Fix Inventory/Project rbac broken on JT form
  awx/ui_next/src/components/AdHocCommands/AdHocCommands.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.jsx
  awx/ui_next/src/components/Lookup/InventoryLookup.test.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.jsx
  awx/ui_next/src/components/Lookup/ProjectLookup.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateAdd/JobTemplateAdd.jsx
  awx/ui_next/src/screens/Template/JobTemplateEdit/JobTemplateEdit.jsx
  awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
Labels: component:ui_next, mergeit, priority:high, type:bug

#8781 Add all LDAP (Default, 1-5) setting forms
  awx/ui_next/src/components/CodeMirrorInput/CodeMirrorInput.jsx
  awx/ui_next/src/screens/Setting/LDAP/LDAP.test.jsx
  awx/ui_next/src/screens/Setting/LDAP/LDAPEdit/LDAPEdit.jsx
  awx/ui_next/src/screens/Setting/LDAP/LDAPEdit/LDAPEdit.test.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
  awx/ui_next/src/screens/Setting/shared/data.ldapSettings.json
Labels: component:ui_next, mergeit, type:feature

#8802 Adds Spinner to Loading state
  awx/ui_next/src/components/AdHocCommands/AdHocCredentialStep.jsx
  awx/ui_next/src/components/ContentLoading/ContentLoading.jsx
  awx/ui_next/src/components/LoadingSpinner/LoadingSpinner.jsx
  awx/ui_next/src/components/LoadingSpinner/index.js
  awx/ui_next/src/components/PaginatedDataList/PaginatedDataList.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/components/Schedule/ScheduleList/ScheduleList.jsx
  awx/ui_next/src/screens/Dashboard/Dashboard.jsx
  awx/ui_next/src/screens/Host/Host.jsx
  awx/ui_next/src/screens/Host/Host.test.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.jsx
  awx/ui_next/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.jsx
  awx/ui_next/src/screens/Template/Survey/SurveyList.jsx
  awx/ui_next/src/screens/Template/Template.jsx
  awx/ui_next/src/screens/Template/TemplateSurvey.jsx
  awx/ui_next/src/screens/Template/TemplateSurvey.test.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplate.jsx
  awx/ui_next/src/screens/Template/shared/data.workflow_job_template.json
Labels: component:ui_next, mergeit, state:needs_devel, type:enhancement

#8580 forcibly close DB and cache socket connection post-fork
  awx/conf/settings.py
Labels: component:api, mergeit

#9099 Remove launch script config mapping for k8s and ocp
  installer/roles/kubernetes/templates/deployment.yml.j2
Labels: mergeit

#9078 Fix Local Docker partial migration and unavailable superuser issues
  installer/roles/image_build/templates/Dockerfile.j2
  installer/roles/local_docker/defaults/main.yml
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/tasks/upgrade_postgres.yml
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: component:api, mergeit, type:bug

#9089 Survey update to workflows
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/test/awx/test_workflow_job_template.py
Labels: component:awx_collection, mergeit, type:bug

#8896 Adds smart inventory button on host list
  awx/ui_next/src/components/Lookup/HostFilterLookup.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.jsx
  awx/ui_next/src/screens/Host/HostList/HostList.test.jsx
  awx/ui_next/src/screens/Host/HostList/SmartInventoryButton.jsx
  awx/ui_next/src/screens/Host/HostList/SmartInventoryButton.test.jsx
  awx/ui_next/src/screens/Inventory/shared/SmartInventoryForm.jsx
  awx/ui_next/src/screens/Inventory/shared/SmartInventoryForm.test.jsx
Labels: component:ui_next, mergeit, type:feature

#9086 further optimize callback receiver buffering for certain situations
  awx/main/dispatch/worker/callback.py
  awx/settings/defaults.py
Labels: mergeit

#9111 Do not set default admin_password
  installer/inventory
  installer/roles/check_vars/tasks/main.yml
Labels: mergeit

#9106 fixed default location for docker_compose_dir variable
  INSTALL.md
Labels: component:docs, mergeit

#9113 Fix bind-mount problem with pg12 upgrades
  installer/roles/local_docker/tasks/compose.yml
  installer/roles/local_docker/tasks/upgrade_postgres.yml
  installer/roles/local_docker/templates/docker-compose.yml.j2
Labels: mergeit

#9028 Add support for credential password prompting on job launch
  awx/ui_next/src/components/FormField/PasswordInput.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.jsx
  awx/ui_next/src/components/LaunchButton/LaunchButton.test.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.jsx
  awx/ui_next/src/components/LaunchPrompt/LaunchPrompt.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/CredentialPasswordsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/CredentialPasswordsStep.test.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/InventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useCredentialPasswordsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useCredentialsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useInventoryStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useOtherPromptsStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/usePreviewStep.jsx
  awx/ui_next/src/components/LaunchPrompt/steps/useSurveyStep.jsx
  awx/ui_next/src/components/LaunchPrompt/useLaunchSteps.js
  awx/ui_next/src/screens/Job/JobTypeRedirect.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/useNodeTypeStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useRunTypeStep.jsx
  awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
Labels: component:ui, mergeit, state:needs_review, type:feature

#9121 Dont fail image builds because of debuginfo repo problems
  installer/roles/image_build/templates/Dockerfile.j2
Labels: mergeit

#8782 Add RADIUS and TACACS+ setting forms
  awx/ui_next/src/screens/Setting/RADIUS/RADIUS.test.jsx
  awx/ui_next/src/screens/Setting/RADIUS/RADIUSEdit/RADIUSEdit.jsx
  awx/ui_next/src/screens/Setting/RADIUS/RADIUSEdit/RADIUSEdit.test.jsx
  awx/ui_next/src/screens/Setting/TACACS/TACACS.test.jsx
  awx/ui_next/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.jsx
  awx/ui_next/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.test.jsx
Labels: component:ui, mergeit, state:needs_test, type:feature

#9011 Updates files to pre lingUI upgrade work
  awx/ui_next/src/components/AddRole/AddResourceRole.jsx
  awx/ui_next/src/components/AddRole/AddResourceRole.test.jsx
  awx/ui_next/src/components/AddRole/SelectRoleStep.jsx
  awx/ui_next/src/components/AnsibleSelect/AnsibleSelect.jsx
  awx/ui_next/src/components/AnsibleSelect/AnsibleSelect.test.jsx
  awx/ui_next/src/components/ExpandCollapse/ExpandCollapse.jsx
  awx/ui_next/src/components/ResourceAccessList/DeleteRoleConfirmationModal.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessList.jsx
  awx/ui_next/src/components/ResourceAccessList/ResourceAccessListItem.jsx
  awx/ui_next/src/components/Sort/Sort.jsx
  awx/ui_next/src/components/Sort/Sort.test.jsx
  awx/ui_next/src/screens/Job/JobOutput/JobOutput.jsx
  awx/ui_next/src/screens/Project/shared/ProjectForm.jsx
  awx/ui_next/src/screens/Project/shared/ProjectSyncButton.jsx
  awx/ui_next/src/screens/Team/TeamList/TeamListItem.jsx
Labels: component:ui, mergeit

#9050 Bump version to 17.0.0
  CHANGELOG.md
  VERSION
  awxkit/VERSION
Labels: mergeit

#9142 stop detecting the need for event data migration
  awx/main/models/__init__.py
  awx/main/tasks.py
Labels: mergeit

#9143 expose active host count on the Organization detail view
  awx/api/views/organization.py
  awx/main/tests/functional/api/test_organization_counts.py
Labels: mergeit

#9149 (docs) update README.md
  README.md
Labels: component:docs, mergeit

#9150 Fixing a small typo
  docs/named_url.md
Labels: component:docs, mergeit, type:bug

#9155 document postgres_data_dir
  installer/inventory
Labels: component:docs, mergeit

#9152 Pre-create pgdocker dir ahead of time with proper permissions
  installer/roles/local_docker/tasks/upgrade_postgres.yml
Labels: component:installer, mergeit, type:bug

#9167 fix workflow url
  awx/main/models/notifications.py
  awx/main/models/workflow.py
  awx/ui_next/src/screens/ActivityStream/ActivityStreamDescription.jsx
Labels: component:api, component:ui, mergeit, type:bug

#9093 Fix setting toggle on click behavior
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.test.jsx
Labels: component:ui, mergeit, priority:high, qe:regression, state:needs_test, type:bug

#9169 Bump version to 17.0.1 & update changelog
  CHANGELOG.md
  VERSION
  awxkit/VERSION
Labels: mergeit

#9048 fixes erroneous render of add button
  awx/ui_next/src/screens/User/UserRoles/UserRolesList.jsx
  awx/ui_next/src/screens/User/UserRoles/UserRolesList.test.jsx
Labels: component:ui, mergeit, state:needs_test

#9156 Minikube-based development environment
  .gitignore
  Makefile
  awx/settings/development.py
  awx/settings/minikube.py
  docs/development/minikube.md
  installer/build.yml
  installer/dockerfile.yml
  installer/roles/dockerfile/defaults/main.yml
  installer/roles/dockerfile/files/RPM-GPG-KEY-ansible-release
  installer/roles/dockerfile/files/launch_awx.sh
  installer/roles/dockerfile/files/launch_awx_task.sh
  installer/roles/dockerfile/files/rsyslog.conf
  installer/roles/dockerfile/files/settings.py
  installer/roles/dockerfile/tasks/main.yml
  installer/roles/dockerfile/templates/Dockerfile.j2
  installer/roles/dockerfile/templates/supervisor.conf.j2
  installer/roles/dockerfile/templates/supervisor_task.conf.j2
  installer/roles/image_build/defaults/main.yml
  installer/roles/image_build/tasks/main.yml
  installer/roles/kubernetes/templates/supervisor.yml.j2
Labels: mergeit

#9035 Display source workflow job when available on job details view
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.test.jsx
Labels: component:ui, mergeit, state:needs_test

#8783 Add SAML and UI setting edit forms
  awx/ui_next/src/screens/Setting/SAML/SAML.test.jsx
  awx/ui_next/src/screens/Setting/SAML/SAMLDetail/SAMLDetail.jsx
  awx/ui_next/src/screens/Setting/SAML/SAMLDetail/SAMLDetail.test.jsx
  awx/ui_next/src/screens/Setting/SAML/SAMLEdit/SAMLEdit.jsx
  awx/ui_next/src/screens/Setting/SAML/SAMLEdit/SAMLEdit.test.jsx
  awx/ui_next/src/screens/Setting/UI/UI.test.jsx
  awx/ui_next/src/screens/Setting/UI/UIEdit/UIEdit.jsx
  awx/ui_next/src/screens/Setting/UI/UIEdit/UIEdit.test.jsx
  awx/ui_next/src/screens/Setting/shared/RevertButton.jsx
  awx/ui_next/src/screens/Setting/shared/SettingDetail.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.test.jsx
  awx/ui_next/src/screens/Setting/shared/data.allSettingOptions.json
Labels: component:ui, mergeit, state:needs_test, type:feature

#9135 Fix the handling of wrong survey spec in awx collection
  awx_collection/plugins/modules/tower_workflow_job_template.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/test/awx/test_workflow_job_template.py
Labels: component:awx_collection, mergeit, type:bug

#9180 Assure that unit_id is always defined
  awx/main/tasks.py
Labels: mergeit

#8970 Convert JobList to PaginatedTable
  awx/ui_next/src/components/DetailList/LaunchedByDetail.jsx
  awx/ui_next/src/components/DetailList/index.js
  awx/ui_next/src/components/JobList/JobList.jsx
  awx/ui_next/src/components/JobList/JobListItem.jsx
  awx/ui_next/src/components/JobList/JobListItem.test.jsx
  awx/ui_next/src/components/PaginatedTable/HeaderRow.jsx
  awx/ui_next/src/components/PaginatedTable/HeaderRow.test.jsx
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
Labels: component:ui, mergeit, type:enhancement

#9069 remove python log rotation in favor of system
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
  awx/settings/defaults.py
Labels: mergeit

#9038 fixes broken link and adds test
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.jsx
  awx/ui_next/src/components/AppContainer/PageHeaderToolbar.test.jsx
Labels: component:ui, mergeit

#9057 Fix inventory list responsive behavior
  awx/ui_next/src/components/PaginatedTable/HeaderRow.jsx
  awx/ui_next/src/components/PaginatedTable/PaginatedTable.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryList.jsx
  awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
Labels: component:ui, mergeit, type:bug

#9192 Fix container group detail link outs
  awx/ui_next/src/screens/Job/JobDetail/JobDetail.jsx
Labels: component:ui, mergeit, state:needs_test

#8661 Add job settings form and unit tests
  awx/ui_next/src/screens/Setting/Jobs/Jobs.test.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/JobsEdit.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/JobsEdit.test.jsx
  awx/ui_next/src/screens/Setting/Jobs/JobsEdit/data.defaultJobSettings.json
  awx/ui_next/src/screens/Setting/shared/SharedFields.jsx
  awx/ui_next/src/screens/Setting/shared/SharedFields.test.jsx
Labels: component:ui, mergeit, type:feature
