Repository ansible/awx, pull requests merged in 2022-07, with the labels that each got.

#12437 [not devel] split into 3 parts - TaskManager, DependencyManager, and WorkflowManager
  awx/api/urls/debug.py
  awx/api/urls/urls.py
  awx/api/views/debug.py
  awx/main/analytics/subsystem_metrics.py
  awx/main/management/commands/inventory_import.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/__init__.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/tasks.py
  awx/main/utils/common.py
  awx/settings/defaults.py
  awx/settings/development.py
Labels: component:api

#12448 Add Help Text with documentation link to Schedules page
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.test.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
  awx/ui/src/screens/Template/Survey/SurveyQuestionForm.js
  awx/ui/src/screens/Template/shared/JobTemplate.helptext.js
Labels: component:ui

#12470 [task_manager_refactor] Time out 3 managers
  awx/main/dispatch/pool.py
  awx/main/scheduler/task_manager.py
Labels: component:api

#12490 [task_manager_refactor] add schedule dependency and workflow managers
  awx/api/views/__init__.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/tasks.py
  awx/main/tasks/system.py
  awx/main/utils/common.py
Labels: component:api

#12325 Fix workflow job template webhook credential bug
  awx_collection/plugins/modules/workflow_job_template.py
Labels: component:awx_collection

#12493 Bump code mirror
  awx/ui/package-lock.json
  awx/ui/package.json
  docs/licenses/ui/codemirror-autocomplete.txt
  docs/licenses/ui/codemirror-commands.txt
  docs/licenses/ui/codemirror-language.txt
  docs/licenses/ui/codemirror-lint.txt
  docs/licenses/ui/codemirror-search.txt
  docs/licenses/ui/codemirror-state.txt
  docs/licenses/ui/codemirror-view.txt
  docs/licenses/ui/crelt.txt
  docs/licenses/ui/lezer-common.txt
  docs/licenses/ui/lezer-highlight.txt
  docs/licenses/ui/lezer-lr.txt
  docs/licenses/ui/style-mod.txt
  docs/licenses/ui/w3c-keyname.txt
Labels: component:ui, component:docs, dependencies

#12468 Updating workflow job template collection test
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection

#12389 Adding GOOGLE_APPLICATION_CREDENTIALS env var
  awx/main/models/credential/injectors.py
  awx/main/tests/data/inventory/plugins/gce/env.json
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#12502 [not devel] Move approval node expiration logic into queryset
  awx/main/migrations/0165_workflowapproval_expires.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/api/test_workflow_node.py
Labels: component:api

#12480 Translate contents of Hosts Automated field as a single string
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.test.js
Labels: component:ui

#12513 fix WorkflowJobTemplate export
  awxkit/awxkit/api/pages/__init__.py
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/api/pages/workflow_approval_templates.py
  awxkit/awxkit/api/resources.py
Labels: component:cli

#12346 Updating pyjwt per dependabot
  requirements/requirements.in
  requirements/requirements.txt
Labels: type:bug

#12255 Adding fields to job_metadata for workflows and approval nodes
  awx/main/models/notifications.py
  awx/main/models/workflow.py
Labels: component:api, component:docs

#12489 Remove external script call to D3.js.
  awx/ui/public/index.html
  awx/ui/public/static/js/d3-collection.v1.min.js
  awx/ui/public/static/js/d3-dispatch.v1.min.js
  awx/ui/public/static/js/d3-force.v1.min.js
  awx/ui/public/static/js/d3-quadtree.v1.min.js
  awx/ui/public/static/js/d3-timer.v1.min.js
  awx/ui/src/util/simulationWorker.js
Labels: component:ui

#12508 Optimize object creation by getting fewer empty relationships
  awx/api/serializers.py
  awx/main/signals.py
  awx/main/tests/unit/api/serializers/test_activity_stream_serializer.py
Labels: component:api

#12541 Pushing updated strings for localization
  awx/locale/ja/LC_MESSAGES/django.po
  awx/locale/ko/LC_MESSAGES/django.po
  awx/locale/zh/LC_MESSAGES/django.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/ko/messages.po
  awx/ui/src/locales/zh/messages.po
Labels: component:api, component:ui

#12432 Enhanced detail component
  awx/ui/src/components/DetailList/Detail.js
  awx/ui/src/components/JobList/JobListItem.js
  awx/ui/src/components/JobList/JobListItem.test.js
  awx/ui/src/components/PromptDetail/PromptInventorySourceDetail.js
  awx/ui/src/components/PromptDetail/PromptInventorySourceDetail.test.js
  awx/ui/src/components/PromptDetail/PromptJobTemplateDetail.js
  awx/ui/src/components/PromptDetail/PromptJobTemplateDetail.test.js
  awx/ui/src/components/PromptDetail/PromptWFJobTemplateDetail.js
  awx/ui/src/components/PromptDetail/PromptWFJobTemplateDetail.test.js
  awx/ui/src/components/ResourceAccessList/ResourceAccessListItem.js
  awx/ui/src/components/ResourceAccessList/ResourceAccessListItem.test.js
  awx/ui/src/components/TemplateList/TemplateListItem.js
  awx/ui/src/components/TemplateList/TemplateListItem.test.js
  awx/ui/src/screens/Credential/CredentialDetail/CredentialDetail.js
  awx/ui/src/screens/Credential/CredentialDetail/CredentialDetail.test.js
  awx/ui/src/screens/Host/HostDetail/HostDetail.js
  awx/ui/src/screens/Host/HostDetail/HostDetail.test.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.test.js
  awx/ui/src/screens/Inventory/InventoryHostDetail/InventoryHostDetail.js
  awx/ui/src/screens/Inventory/InventoryHostDetail/InventoryHostDetail.test.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.js
  awx/ui/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.js
  awx/ui/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.test.js
  awx/ui/src/screens/Inventory/SmartInventoryHostDetail/SmartInventoryHostDetail.js
  awx/ui/src/screens/Inventory/SmartInventoryHostDetail/SmartInventoryHostDetail.test.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.test.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.js
  awx/ui/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
Labels: component:ui

#12544 Suppress 204 No Content results causing an error during import
  awxkit/awxkit/api/pages/api.py
Labels: component:cli

#12528 Remove update_on_project_update
  awx/ui/src/components/PromptDetail/PromptInventorySourceDetail.js
  awx/ui/src/components/PromptDetail/PromptInventorySourceDetail.test.js
  awx/ui/src/components/PromptDetail/data.inventory_source.json
  awx/ui/src/screens/Inventory/InventorySourceAdd/InventorySourceAdd.test.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.js
  awx/ui/src/screens/Inventory/InventorySourceEdit/InventorySourceEdit.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/AzureSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/ControllerSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/EC2SubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/GCESubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/InsightsSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/OpenStackSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SatelliteSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SharedFields.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/VMwareSubForm.test.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/VirtualizationSubForm.test.js
  awx/ui/src/screens/Inventory/shared/data.inventory_source.json
Labels: component:ui

#12551 Block sliced workflow jobs on any job type from their JT
  awx/main/scheduler/dependency_graph.py
Labels: component:api

#12545 Cache task_impact
  awx/main/migrations/0165_task_manager_refactor.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/ha.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/projects.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
Labels: component:api

#12147 Bump Receptorctl to 1.2.3
  requirements/requirements.in
  requirements/requirements.txt
Labels: type:enhancement

#12554 bulk reschedule context should track each of the 3 managers
  awx/main/scheduler/task_manager.py
  awx/main/utils/common.py
Labels: component:api

#12547 [feature-project-integrity] Project signiture verification api change
  awx/api/serializers.py
  awx/main/migrations/0165_added_contentsigning_to_project_model.py
  awx/main/models/projects.py
Labels: component:api

#12559 [task_manager_refactor] ensure system can complete work without periodic scheduler
  awx/main/models/unified_jobs.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks/system.py
  awx/settings/defaults.py
Labels: component:api

#12538 [feature-project-integrity] add new managed credential type for gpg pub key
  awx/main/migrations/0165_added_contentsigning_to_project_model.py
  awx/main/models/credential/__init__.py
  awx/main/tests/functional/test_credential.py
Labels: component:api

#12567 add signature_validation_credential to rel field
  awx/api/serializers.py
Labels: component:api

#12569 [FieldLookupBackend] limit iexact to string fields
  awx/api/filters.py
  awx/main/tests/unit/api/test_filters.py
Labels: component:api

#12566 12483 configure content verification
  awx/ui/src/components/PromptDetail/PromptProjectDetail.js
  awx/ui/src/screens/Project/ProjectAdd/ProjectAdd.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.test.js
  awx/ui/src/screens/Project/ProjectEdit/ProjectEdit.js
  awx/ui/src/screens/Project/shared/Project.helptext.js
  awx/ui/src/screens/Project/shared/ProjectForm.js
  awx/ui/src/screens/Project/shared/ProjectForm.test.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/GitSubForm.js
  awx/ui/src/types.js
Labels: component:ui

#12568 Fix awx collection project module
  awx_collection/plugins/modules/project.py
Labels: component:awx_collection

#12560 Adding subscriptions module and adding pool_id to license
  awx_collection/meta/runtime.yml
  awx_collection/plugins/modules/license.py
  awx_collection/plugins/modules/subscriptions.py
  awx_collection/test/awx/test_completeness.py
Labels: component:awx_collection

#12522 Adding remove_superuser and remove_system_auditors to the SAML user attribute map
  awx/sso/conf.py
  awx/sso/fields.py
  awx/sso/pipeline.py
  awx/sso/tests/functional/test_pipeline.py
  awx/sso/tests/unit/test_fields.py
Labels: component:api

#12555 Fix job output follow mode & scrolling
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/JobOutput/JobOutputSearch.js
Labels: component:ui

#12588 [task_manager_refactor] Optimize task manager with debug toolbar, adjust prefetch
  awx/main/scheduler/task_manager.py
Labels: component:api

#12531 [#12478] Change Inventory "Status" column header to "Sync Status"
  awx/ui/src/screens/Inventory/InventoryList/InventoryList.js
Labels: component:ui
