Repository ansible/awx, pull requests merged in 2022-10, with the labels that each got.

#12728 Adding prevent_instance_group_fallback
  awx/api/serializers.py
  awx/main/migrations/0172_prevent_instance_fallback.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/tests/functional/test_copy.py
  awx/main/tests/functional/test_instances.py
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/shared/Inventory.helptext.js
  awx/ui/src/screens/Inventory/shared/InventoryForm.js
  awx/ui/src/screens/Inventory/shared/data.inventory.json
  awx/ui/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
  awx/ui/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.js
  awx/ui/src/screens/Template/shared/JobTemplate.helptext.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
  awx/ui/src/screens/Template/shared/data.job_template.json
  awx_collection/plugins/modules/inventory.py
  awx_collection/plugins/modules/job_template.py
  awxkit/awxkit/api/pages/inventory.py
  awxkit/awxkit/api/pages/job_templates.py
Labels: component:api, component:ui, component:cli, component:awx_collection

#12996 A few super minor nits in api views/serializers
  awx/api/serializers.py
  awx/api/views/__init__.py
Labels: component:api

#12736 Adding ppc64le support parameters
  tools/ansible/roles/dockerfile/defaults/main.yml
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: community

#12995 Better handle IPv6 in util function `update_scm_url`
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
Labels: component:api

#13009 update instance install bundle requirement
  awx/api/templates/instance_install_bundle/requirements.yml
Labels: component:api

#12969 [tech debt] Remove imports and references that are no longer needed
  awx/api/generics.py
  awx/api/urls/instance.py
  awx/api/urls/inventory.py
  awx/api/urls/inventory_update.py
  awx/api/urls/oauth2_root.py
  awx/api/urls/organization.py
  awx/api/urls/urls.py
  awx/api/urls/webhooks.py
  awx/api/views/__init__.py
  awx/main/tests/unit/api/test_views.py
  awx/sso/views.py
Labels: component:api

#13005 Fix undefined launchConfig error in schedule form
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/screens/ManagementJob/ManagementJob.js
Labels: component:ui, community

#12694 Shortcut Instance.objects.me when possible
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/reaper.py
  awx/main/management/commands/run_wsbroadcast.py
  awx/main/managers.py
  awx/main/tasks/jobs.py
  awx/main/wsbroadcast.py
Labels: component:api

#13022 fix: extend expiration date for receptor certificate for execution node
  awx/api/views/instance_install_bundle.py
Labels: component:api, community

#13025 Moves smart inv vars tooltip to a single line
  awx/ui/src/screens/Inventory/shared/SmartInventoryForm.js
Labels: component:ui

#13027 Fix CSS overflow for legend and tooltip in Topology view.
  awx/ui/src/screens/TopologyView/Legend.js
  awx/ui/src/screens/TopologyView/Tooltip.js
Labels: component:ui

#12997 docs: fix incorrect file extension in execution_nodes.md
  docs/execution_nodes.md
Labels: component:docs, community

#13031 Sending field_name in AttributeError
  awx/main/models/credential/__init__.py
Labels: component:api, community

#13034 Fixes bug re-launching adhoc command with passwords required
  awx/ui/src/components/LaunchButton/LaunchButton.js
  awx/ui/src/components/LaunchPrompt/LaunchPrompt.js
Labels: component:ui

#13040 Add developer documentation for project signing work
  docs/project_signing.md
Labels: component:docs

#12974 Update UI to support pending health checks.
  awx/ui/src/components/HealthCheckButton/HealthCheckButton.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceListItem.js
  awx/ui/src/screens/Instances/InstanceList/InstanceListItem.test.js
Labels: component:ui

#13042 Fix enable/disable node state on browser resize.
  awx/ui/src/screens/TopologyView/MeshGraph.js
  awx/ui/src/screens/TopologyView/TopologyView.js
Labels: component:ui

#13035 Only perform prompts validation if prompts fields are submitted
  awx/api/serializers.py
  awx/main/tests/functional/api/test_schedules.py
Labels: component:api

#13043 add podman config role in instance install bundle
  awx/api/templates/instance_install_bundle/group_vars/all.yml
  awx/api/templates/instance_install_bundle/install_receptor.yml
  awx/api/templates/instance_install_bundle/requirements.yml
Labels: component:api

#13050 Allow entering playbook filename manually in Job Template
  awx/ui/src/screens/Template/shared/PlaybookSelect.js
  awx/ui/src/screens/Template/shared/PlaybookSelect.test.js
Labels: component:ui

#13069 Add back in the uniqueness validation on Instance.hostname
  awx/api/serializers.py
Labels: component:api

#12887 [tech debt] Add new flake8 rules to do some meaningful corrections
  awx/api/permissions.py
  awx/api/views/__init__.py
  awx/main/management/commands/bottleneck.py
  awx/main/migrations/_create_system_jobs.py
  awx/main/migrations/_galaxy.py
  awx/main/models/schedules.py
  awx/main/tests/functional/api/test_instance_group.py
  awx/main/tests/functional/api/test_schedules.py
  awx/main/tests/unit/api/test_views.py
  awx/playbooks/action_plugins/verify_project.py
  awx/settings/defaults.py
  awx/settings/production.py
  awx/sso/conf.py
  awx/sso/migrations/0003_convert_saml_string_to_list.py
  awx/sso/tests/functional/test_pipeline.py
  awx_collection/plugins/modules/project.py
  awx_collection/plugins/modules/workflow_job_template.py
  tox.ini
Labels: component:api, component:awx_collection

#13081 Use raw string to satisfy linter rules
  awx/api/serializers.py
Labels: component:api

#13073 Fix dispatcher connection deadlock w scheduler and cleanup
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
Labels: component:api

#13057 bugfix - allow edit hostname when org.max_hosts == active_count
  awx/main/access.py
Labels: component:api, community

#13068 Allows job output to calculate elapsed time
  awx/main/models/unified_jobs.py
  awx/ui/src/screens/Job/JobOutput/shared/OutputToolbar.js
Labels: component:api, component:ui

#12942 fix: UI host event modal when stdout is an array
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui/src/screens/Job/JobOutput/HostEventModal.test.js
Labels: component:ui, community

#13110 Fixes a broken Host event modal unit test
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
Labels: component:ui

#13104 Pushing updated strings for localization
  awx/locale/translations/es/django.po
  awx/locale/translations/es/messages.po
  awx/locale/translations/fr/django.po
  awx/locale/translations/fr/messages.po
  awx/locale/translations/ja/django.po
  awx/locale/translations/ja/messages.po
  awx/locale/translations/ko/django.po
  awx/locale/translations/ko/messages.po
  awx/locale/translations/nl/django.po
  awx/locale/translations/nl/messages.po
  awx/locale/translations/zh/django.po
  awx/locale/translations/zh/messages.po
  awx/ui/src/locales/translations/es/django.po
  awx/ui/src/locales/translations/es/messages.po
  awx/ui/src/locales/translations/fr/django.po
  awx/ui/src/locales/translations/fr/messages.po
  awx/ui/src/locales/translations/ja/django.po
  awx/ui/src/locales/translations/ja/messages.po
  awx/ui/src/locales/translations/ko/django.po
  awx/ui/src/locales/translations/ko/messages.po
  awx/ui/src/locales/translations/nl/django.po
  awx/ui/src/locales/translations/nl/messages.po
  awx/ui/src/locales/translations/zh/django.po
  awx/ui/src/locales/translations/zh/messages.po
Labels: component:api, component:ui, community

#13097 make job lifecycle Cyan again
  awx/main/utils/handlers.py
Labels: component:api

#13125 UI static files are now directly copied to the proper static dir
  Makefile
  awx/settings/defaults.py
  tools/docker-compose/bootstrap_development.sh
Labels: component:api

#13080 Fixes confusing Error when trying to sync project set to scm_type Manual
  awx_collection/plugins/modules/project_update.py
Labels: component:awx_collection, community

#13041 Allows health checks on only execution nodes
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_instance.py
Labels: component:api

#13082 Include stdout from health check if it is not nothing
  awx/main/tasks/receptor.py
Labels: component:api

#13062 Fix Schedules Form date validation same day different time scenario
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
Labels: component:ui

#13132 Expand the dependencies of the Schedule page type
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/api/pages/schedules.py
Labels: component:cli
