Repository ansible/awx, pull requests merged in 2022-04, with the labels that each got.

#11993 cast bool to str for runner env
  awx/main/tasks/jobs.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#11865 Add user-defined environment variables to ansible-galaxy commands
  awx/main/conf.py
  awx/main/tasks/jobs.py
  awx/playbooks/project_update.yml
  awx/settings/defaults.py
  awx/ui/src/screens/Setting/Jobs/JobsEdit/JobsEdit.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
  awx/ui/src/screens/Setting/shared/data.jobSettings.json
Labels: component:api, component:ui

#11083 Grafana notifications: Fix panel/dashboardId type
  awx/main/notifications/grafana_backend.py
  awx/main/tests/unit/notifications/test_grafana.py
Labels: type:bug, component:api

#11928 Add JobJobEventsChildrenSummary endpoint
  awx/api/templates/api/job_job_events_children_summary.md
  awx/api/urls/job.py
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_events.py
Labels: component:api

#11963 Revert "updated patternfly"
  awx/ui/src/components/SelectedList/DraggableSelectedList.js
  awx/ui/src/components/SelectedList/DraggableSelectedList.test.js
  awx/ui/src/screens/Job/JobOutput/JobOutputSearch.test.js
Labels: component:api, component:ui

#11983 Update cryptography to >=35 for openssl 3 support
  docs/licenses/cryptography.txt
  docs/licenses/semantic-version.txt
  docs/licenses/setuptools-rust.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:docs

#11944 Use new children-summary endpoint data to traverse job event tree
  awx/ui/src/api/models/Jobs.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.test.js
  awx/ui/src/screens/Job/JobOutput/shared/JobEventLine.js
  awx/ui/src/screens/Job/JobOutput/useJobEvents.js
  awx/ui/src/screens/Job/JobOutput/useJobEvents.test.js
Labels: type:bug, component:ui

#12004 Downgrade min required node LTS
  awx/ui/CONTRIBUTING.md
  awx/ui/Dockerfile
  awx/ui/README.md
  awx/ui/package.json
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: component:ui

#11920 Improves UX of workflow approval list
  awx/ui/.eslintrc.json
  awx/ui/src/components/StatusIcon/icons.js
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/components/StatusLabel/StatusLabel.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListApproveButton.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListApproveButton.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListDenyButton.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListDenyButton.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.js
  awx/ui/src/screens/WorkflowApproval/data.workflowApprovals.json
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalControls.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalControls.test.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.test.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalUtils.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalUtils.test.js
Labels: component:api, component:ui

#11964 Escape name__regex and name__iregex
  awx/ui/src/components/Lookup/shared/HostFilterUtils.js
  awx/ui/src/components/Lookup/shared/HostFilterUtils.test.js
Labels: component:api, component:ui

#12007 Add placeholder text when user selects a fuzzy search on labels
  awx/ui/src/components/Search/AdvancedSearch.js
Labels: component:ui

#12009 Do not show inventory for project update on job details
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
Labels: component:ui

#12020 Do not truncate strings on activity stream dropdown
  awx/ui/src/screens/ActivityStream/ActivityStream.js
Labels: component:api, component:ui

#11914 add ID as default filter if no other filtering criteria is provided
  awx/api/filters.py
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_inventory.py
  awx/main/tests/functional/api/test_organizations.py
  awx/main/tests/functional/test_projects.py
Labels: component:api

#12022 change back to Automation Analytics name
  awx/main/analytics/core.py
  awx/main/conf.py
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.test.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionEdit.test.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
Labels: component:api, component:ui

#12045 Only fetch fields we need in task manager
  awx/main/scheduler/task_manager.py
Labels: component:api

#12055 Revert "Only fetch fields we need in task manager"
  awx/main/scheduler/task_manager.py
Labels: component:api

#12021 removed 'check_migrations' condition in _citi_db_wrapper
  awx/conf/settings.py
Labels: component:api

#12056 Update file path in docs/ansible_runner_integration.md
  docs/ansible_runner_integration.md
Labels: component:docs

#12029 Update when deleted is shown on job details
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui

#12048 Disable isCreatable on Advanced Search
  awx/ui/src/components/Search/AdvancedSearch.js
Labels: component:ui

#12063 Remove duplicate CSS rules
  awx/ui/src/components/UserAndTeamAccessAdd/UserAndTeamAccessAdd.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/RunStep.js
Labels: component:api, component:ui

#12041 Mark committed_capacity field for removal
  awx/api/serializers.py
Labels: component:api

#11989 Mark inventory source field for deprecation
  awx/main/migrations/0159_deprecate_inventory_source_UoPU_field.py
  awx/main/models/inventory.py
Labels: component:api

#12068 Fix the job event partition alignment
  awx/main/utils/common.py
Labels: component:api

#12039 Adds popover help text to project details, and unifies those strings …
  awx/ui/src/components/DetailList/Detail.js
  awx/ui/src/components/Popover/Popover.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.test.js
  awx/ui/src/screens/Project/ProjectList/ProjectListItem.test.js
  awx/ui/src/screens/Project/shared/Project.helptext.js
  awx/ui/src/screens/Project/shared/ProjectForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/ArchiveSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/GitSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/ManualSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/SharedFields.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/SvnSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSyncButton.js
  awx/ui/src/screens/Project/shared/ProjectSyncButton.test.js
Labels: component:api, component:ui

#12031 awxkit log which resource failed to import
  awx_collection/plugins/modules/export.py
  awxkit/awxkit/api/pages/api.py
Labels: component:cli, component:collection

#12064 Remove output/stderr tabs from host detail modals when not present
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui/src/screens/Job/JobOutput/HostEventModal.test.js
Labels: component:api, component:ui

#12066 Ship the resolved_role event data to analytics
  awx/main/analytics/collectors.py
Labels: component:api

#12062 Fix notification template details for system auditors
  awx/ui/src/screens/NotificationTemplate/NotificationTemplate.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.test.js
Labels: component:api, component:ui

#12077 Update strings
  awx/ui/src/components/AdHocCommands/useAdHocDetailsStep.js
Labels: component:ui

#12016 Analytics collector should collect full license data
  awx/main/analytics/collectors.py
Labels: component:api

#12050 move static methods used by task manager
  awx/main/models/ha.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/task_manager_models.py
  awx/main/tests/unit/models/test_ha.py
Labels: component:api

#11996 Remove unnecessary blocks from project update playbook
  awx/playbooks/project_update.yml
Labels: component:api

#12083 Updating job execution to use new features in ansible runner
  awx/main/constants.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
  awx/settings/defaults.py
Labels: component:api

#11981 Refactoring release_process docs and updating images
  docs/img/compare-screen.png
  docs/img/galaxy.png
  docs/img/latest-release.png
  docs/img/operator-promote.png
  docs/img/promote-release.png
  docs/img/pypi.png
  docs/release_process.md
Labels: component:docs

#12086 Remove committed_capacity field, delete supporting code
  awx/api/serializers.py
  awx/api/views/mixin.py
  awx/main/managers.py
  awx/main/models/ha.py
  awx/main/scheduler/task_manager.py
  awx/main/scheduler/task_manager_models.py
  awx/main/tests/functional/task_management/test_capacity.py
  awx/main/tests/unit/test_capacity.py
Labels: component:api

#12093 update awx.awx collection to allow archived project.
  awx_collection/plugins/modules/project.py
  awx_collection/tests/integration/targets/project/tasks/main.yml
Labels: component:collection

#12106 Bump Django to 3.2.13
  requirements/requirements.in
  requirements/requirements.txt
Labels: type:bug, component:api

#12104 Adding /etc/supervisord.conf to sosreports
  tools/sosreport/TESTING.md
  tools/sosreport/controller.py
Labels: type:enhancement

#12107 fix off-by-one error in job output pagination
  awx/ui/src/screens/Job/JobOutput/getEventRequestParams.test.js
  awx/ui/src/screens/Job/JobOutput/shared/jobOutputUtils.js
  awx/ui/src/screens/Job/JobOutput/shared/jobOutputUtils.test.js
Labels: component:api, component:ui

#12098 Fix broken job WFJT details when related JT is deleted
  awx/ui/src/components/Workflow/WorkflowNodeHelp.js
Labels: component:ui

#12123 Fix user role association in access modal
  awx/ui/src/components/AddRole/AddResourceRole.js
  awx/ui/src/components/AddRole/AddResourceRole.test.js
Labels: component:ui

#12114 update awx collection workflow module
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:collection

#12115 update workflow nodes to allow workflows and system jobs
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:collection

#12099 Add the X-Content-Type-Options nosniff header
  tools/docker-compose/nginx.vh.default.conf
Labels: type:bug, component:api

#12043 Modifying schedules API to allow for rrulesets #5733
  awx/api/serializers.py
  awx/main/migrations/0160_alter_schedule_rrule.py
  awx/main/models/schedules.py
  awx/main/tests/functional/api/test_schedules.py
  awx/main/tests/functional/models/test_schedule.py
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx_collection/plugins/lookup/schedule_rruleset.py
  awx_collection/plugins/modules/schedule.py
  awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml
  docs/schedules.md
Labels: component:api, component:ui, component:docs, component:collection

#12120 Add dependabot for ui
  .github/dependabot.yml
Labels: type:enhancement

#12128 Add tags/skip tags to the list of things that will cause the Prompt button to be displayed on the schedule form
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
Labels: component:ui

#11998 Adds total host count to inv and smart inv details views
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.test.js
  awx/ui/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.js
  awx/ui/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.test.js
  awx/ui/src/screens/Inventory/shared/data.smart_inventory.json
Labels: component:ui

#12122 Fixing write location of ssh_key-data-cert.pub
  awx/main/tasks/jobs.py
Labels: component:api

#12108 Add organization, host, and credential type detail view help text
  awx/ui/src/screens/CredentialType/CredentialTypeDetails/CredentialTypeDetails.js
  awx/ui/src/screens/Host/HostDetail/HostDetail.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.js
  awx/ui/src/screens/User/UserTokenAdd/UserTokenAdd.js
Labels: component:ui

#12110 Fix notification timing issue by sending in the latter of 2 events
  awx/api/serializers.py
  awx/main/dispatch/worker/callback.py
  awx/main/migrations/0161_unifiedjob_host_status_counts.py
  awx/main/models/events.py
  awx/main/models/notifications.py
  awx/main/models/unified_jobs.py
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tasks/system.py
  awx/main/tests/functional/commands/test_callback_receiver.py
  awx/main/tests/unit/api/serializers/test_job_serializers.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/update_model.py
  awx/settings/defaults.py
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
Labels: component:api, component:ui

#12134 add new locator for deleted inventory in JT detail screen
  awx/ui/src/components/DetailList/DeletedDetail.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
Labels: component:api, component:ui
