Repository ansible/awx, pull requests merged in 2022-06, with the labels that each got.

#12240 Add prometheus and grafana make commands for local environment
  .gitignore
  Makefile
  tools/docker-compose/README.md
  tools/docker-compose/ansible/roles/sources/templates/haproxy.cfg.j2
  tools/grafana/dashboards/awx_dashboard.yml
  tools/grafana/dashboards/demo_dashboard.json
  tools/grafana/datasources/prometheus_source.yml
  tools/prometheus/.gitignore
  tools/prometheus/prometheus.yml
Labels: type:enhancement

#12314 Adding irc bullhorn to release process
  docs/release_process.md
Labels: component:docs

#12307 Upgrade twilio dependency to pick up fix
  requirements/requirements.in
  requirements/requirements.txt
Labels: type:bug, component:api

#12251 Add controller_node to job details page
  awx/api/serializers.py
  awx/main/tests/functional/api/test_job.py
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
Labels: component:api, component:ui

#12229 Persistent list filters
  awx/ui/.eslintrc.json
  awx/ui/src/components/PersistentFilters/PersistentFilters.js
  awx/ui/src/components/PersistentFilters/PersistentFilters.test.js
  awx/ui/src/components/PersistentFilters/index.js
  awx/ui/src/components/RoutedTabs/RoutedTabs.js
  awx/ui/src/components/RoutedTabs/RoutedTabs.test.js
  awx/ui/src/components/Schedule/Schedule.test.js
  awx/ui/src/constants.js
  awx/ui/src/contexts/Session.js
  awx/ui/src/screens/Application/Application/Application.js
  awx/ui/src/screens/Application/Applications.js
  awx/ui/src/screens/Credential/Credential.js
  awx/ui/src/screens/Credential/Credentials.js
  awx/ui/src/screens/CredentialType/CredentialType.js
  awx/ui/src/screens/CredentialType/CredentialTypes.js
  awx/ui/src/screens/ExecutionEnvironment/ExecutionEnvironment.js
  awx/ui/src/screens/ExecutionEnvironment/ExecutionEnvironments.js
  awx/ui/src/screens/Host/Host.js
  awx/ui/src/screens/Host/Hosts.js
  awx/ui/src/screens/InstanceGroup/InstanceGroup.js
  awx/ui/src/screens/InstanceGroup/InstanceGroups.js
  awx/ui/src/screens/Instances/Instance.js
  awx/ui/src/screens/Instances/Instances.js
  awx/ui/src/screens/Inventory/Inventories.js
  awx/ui/src/screens/Inventory/Inventory.js
  awx/ui/src/screens/Inventory/InventoryGroup/InventoryGroup.test.js
  awx/ui/src/screens/Job/Job.js
  awx/ui/src/screens/Job/Jobs.js
  awx/ui/src/screens/ManagementJob/ManagementJob.js
  awx/ui/src/screens/ManagementJob/ManagementJobs.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplate.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplates.js
  awx/ui/src/screens/Organization/Organization.js
  awx/ui/src/screens/Organization/Organizations.js
  awx/ui/src/screens/Project/Project.js
  awx/ui/src/screens/Project/Projects.js
  awx/ui/src/screens/Team/Team.js
  awx/ui/src/screens/Team/Teams.js
  awx/ui/src/screens/Template/Template.js
  awx/ui/src/screens/Template/Templates.js
  awx/ui/src/screens/Template/WorkflowJobTemplate.js
  awx/ui/src/screens/User/User.js
  awx/ui/src/screens/User/Users.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApproval.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovals.js
Labels: component:ui

#11921 Look up the correct top-level resource name when reconstructing foreign keys
  awxkit/awxkit/api/pages/api.py
Labels: component:cli

#12308 Metrics for callback receiver job event lag
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/worker/callback.py
Labels: component:api

#12331 Allow worker files to be loaded as blob objects.
  awx/ui/public/index.html
  awx/ui/src/components/CodeEditor/CodeEditor.js
Labels: component:ui

#12102 Respect optional fully qualified collection name (ansible.builtin.) for playbook identification
  awx/main/tests/data/ansible_utils/playbooks/valid/import_fqcn.yml
  awx/main/tests/data/ansible_utils/playbooks/valid/include_fqcn.yml
  awx/main/utils/ansible.py
Labels: component:api

#12330 Provide feedback when a health check is being performed
  awx/ui/src/components/HealthCheckButton/HealthCheckButton.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
Labels: component:ui

#12315 Job tag characters
  awx/main/migrations/0163_convert_job_tags_to_textfield.py
  awx/main/models/jobs.py
Labels: component:api

#12320 Pre-fill project for job template from query params
  awx/ui/src/components/Lookup/Lookup.js
  awx/ui/src/components/Lookup/ProjectLookup.js
  awx/ui/src/components/RelatedTemplateList/RelatedTemplateList.js
  awx/ui/src/screens/Project/Project.js
  awx/ui/src/screens/Template/JobTemplateAdd/JobTemplateAdd.js
  awx/ui/src/screens/Template/JobTemplateAdd/JobTemplateAdd.test.js
  awx/ui/src/screens/Template/JobTemplateEdit/JobTemplateEdit.test.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
Labels: component:ui

#12187 Fix typo in application module example
  awx_collection/plugins/modules/application.py
Labels: component:awx_collection

#12219 Change Demo Project status to successful
  awx/main/management/commands/create_preload_data.py
  awx/main/models/projects.py
Labels: component:api

#12313 Only do substitutions for container path conversions with resolved paths
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_execution_environments.py
  awx/main/utils/execution_environments.py
Labels: component:api

#12305 Update replies documentation
  .github/triage_replies.md
Labels: component:docs

#12355 Make awx-autoreloader work faster for large code changes
  tools/docker-compose/awx-autoreload
Labels: type:enhancement, component:api

#12341 Hide management job for non system admin as node choice
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeEditModal.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeModal.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.test.js
Labels: component:ui

#12338 Add cancel button to workflow job output
  awx/ui/src/components/JobCancelButton/JobCancelButton.js
  awx/ui/src/screens/Job/WorkflowOutput/WorkflowOutputToolbar.js
  awx/ui/src/screens/Job/WorkflowOutput/WorkflowOutputToolbar.test.js
Labels: component:ui

#12359 Fixing slashes for copy/paste of links
  .github/triage_replies.md
Labels: component:docs

#12327 .github folder maintaince
  .github/BOTMETA.yml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/security_bug_report.md
  .github/LABEL_MAP.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/issue_labeler.yml
  .github/pr_labeler.yml
  .github/workflows/stage.yml
Labels: type:enhancement

#12306 Duplication of PR of Jinga 2 Rendering
  awx/api/serializers.py
Labels: component:api

#12358 Hide add access button based on the user profile for credentials
  awx/ui/src/api/models/Organizations.js
  awx/ui/src/components/ResourceAccessList/ResourceAccessList.js
  awx/ui/src/components/ResourceAccessList/ResourceAccessList.test.js
Labels: component:ui

#12349 Add loading state when saving a visualizer
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.js
Labels: component:ui

#11429 Update README.md
  tools/docker-compose/README.md
Labels: type:enhancement

#12287 detect if job events are tree-like and collapsible
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_events.py
  awx/ui/src/screens/Job/JobOutput/useJobEvents.js
Labels: component:api, component:ui

#12363 Modify position of tooltip for management job list
  awx/ui/src/screens/ManagementJob/ManagementJobList/LaunchManagementPrompt.js
  awx/ui/src/screens/ManagementJob/ManagementJobList/ManagementJobListItem.js
Labels: component:ui

#12235 Subsystem metrics for task manager
  awx/main/analytics/subsystem_metrics.py
  awx/main/queue.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks/system.py
  awx/settings/defaults.py
  tools/grafana/dashboards/demo_dashboard.json
Labels: component:api

#12352 Add docs for subsystem metrics
  docs/subsystem_metrics.md
Labels: component:docs

#12370 Add column org to template list
  awx/ui/src/components/TemplateList/TemplateList.js
  awx/ui/src/components/TemplateList/TemplateListItem.js
  awx/ui/src/components/TemplateList/TemplateListItem.test.js
Labels: component:ui

#12348 Update project status to reflect project sync related to job template
  awx/ui/src/screens/Job/Job.helptext.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
Labels: component:ui

#12246 use haproxy 2.3 with maxconn set to avoid startup failures
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/haproxy.cfg.j2
Labels: type:bug

#12332 Add typeahed for single choice surveys
  awx/ui/src/components/LaunchPrompt/steps/SurveyStep.js
  awx/ui/src/components/MultiSelect/TagMultiSelect.js
  awx/ui/src/screens/Credential/shared/CredentialFormFields/BecomeMethodField.js
  awx/ui/src/screens/Template/Survey/SurveyListItem.js
Labels: component:ui

#12271 return event_status on push, tag push, and merge gitlab webhook events
  awx/api/views/webhooks.py
Labels: component:api

#12360 Add column to display resource related to a schedule
  awx/ui/src/components/Schedule/ScheduleList/ScheduleList.js
  awx/ui/src/components/Schedule/ScheduleList/ScheduleListItem.js
  awx/ui/src/components/Schedule/ScheduleList/ScheduleListItem.test.js
Labels: component:ui

#12382 Update css var
  awx/ui/src/components/CodeEditor/VariablesDetail.js
Labels: component:ui

#12376 work around for 500 on /api/v2/metrics when upgrading
  awx/main/analytics/subsystem_metrics.py
Labels: component:api

#12335 import/export error codes when something bad happens
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/cli/resource.py
Labels: component:cli

#12309 Allow for multiple --extra_vars or --variables flags in awx-cli
  awxkit/awxkit/cli/options.py
Labels: component:cli

#12404 Revert "import/export error codes when something bad happens"
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/cli/resource.py
Labels: component:cli

#12393 Subsystem metrics reset_values should remove all redis keys
  awx/main/analytics/subsystem_metrics.py
Labels: component:api

#12403 Updating release docs
  .github/triage_replies.md
  docs/img/publish-release.png
  docs/img/verify-draft-release.png
  docs/release_process.md
Labels: component:docs

#12408 [new] bubble up an error code when something goes wrong with import/export
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/cli/resource.py
Labels: component:cli

#12421 Bumps Axios and Adds license files
  awx/ui/package-lock.json
  awx/ui/package.json
  docs/licenses/ui/asynckit.txt
  docs/licenses/ui/combined-stream.txt
  docs/licenses/ui/delayed-stream.txt
  docs/licenses/ui/form-data.txt
  docs/licenses/ui/mime-db.txt
  docs/licenses/ui/mime-types.txt
Labels: component:ui, dependencies

#12223 Pass combined artifacts from nested workflows into downstream nodes
  awx/main/models/jobs.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/models/test_workflow.py
Labels: component:api

#12378 Making verbosity list and options a constant and adding WinRM debug
  awx/ui/src/components/AdHocCommands/AdHocCommands.js
  awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.js
  awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.test.js
  awx/ui/src/components/AdHocCommands/AdHocDetailsStep.js
  awx/ui/src/components/AdHocCommands/AdHocPreviewStep.js
  awx/ui/src/components/AdHocCommands/useAdHocDetailsStep.js
  awx/ui/src/components/AdHocCommands/useAdHocLaunchSteps.js
  awx/ui/src/components/AnsibleSelect/AnsibleSelect.js
  awx/ui/src/components/LaunchPrompt/steps/OtherPromptsStep.js
  awx/ui/src/components/LaunchPrompt/steps/OtherPromptsStep.test.js
  awx/ui/src/components/PromptDetail/PromptDetail.js
  awx/ui/src/components/PromptDetail/PromptInventorySourceDetail.js
  awx/ui/src/components/PromptDetail/PromptJobTemplateDetail.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/VerbositySelectField/VerbositySelectField.js
  awx/ui/src/components/VerbositySelectField/index.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/ko/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.test.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
Labels: component:ui

#12366 Remove deprecated field update_on_project_update
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/api/views/mixin.py
  awx/main/migrations/0164_remove_inventorysource_update_on_project_update.py
  awx/main/models/inventory.py
  awx/main/models/unified_jobs.py
  awx/main/tasks/jobs.py
  awx/main/tests/functional/api/test_deprecated_credential_assignment.py
  awx/main/tests/functional/api/test_inventory.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/api/test_views.py
  awx/main/tests/unit/models/test_inventory.py
  awx_collection/plugins/modules/inventory_source.py
  docs/inventory/scm_inventory.md
Labels: component:api, component:docs, component:awx_collection

#12424 Updates irrelevant test
  awx/ui/src/components/LaunchButton/LaunchButton.test.js
Labels: component:ui

#12422 Removes references to Ansible Tower in favor of Ansible Controller
  awx/ui/SEARCH.md
  awx/ui/src/components/LaunchPrompt/steps/OtherPromptsStep.js
  awx/ui/src/components/Lookup/HostFilterLookup.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/ko/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
  awx/ui/src/screens/Credential/shared/CredentialForm.test.js
  awx/ui/src/screens/Credential/shared/data.credentialTypes.json
  awx/ui/src/screens/Credential/shared/data.towerCredential.json
  awx/ui/src/screens/CredentialType/shared/CredentialTypeForm.js
  awx/ui/src/screens/Inventory/shared/SmartInventoryForm.js
  awx/ui/src/screens/NotificationTemplate/shared/CustomMessagesSubForm.js
  awx/ui/src/screens/NotificationTemplate/shared/Notifications.helptext.js
  awx/ui/src/screens/Template/Survey/SurveyQuestionForm.js
  awx/ui/src/screens/Template/shared/WorkflowJobTemplate.helptext.js
Labels: component:ui

#12407 Allow modification of schedule if there are two of the same name
  awx_collection/plugins/modules/schedule.py
  awx_collection/test/awx/test_schedule.py
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
Labels: component:awx_collection

#12412 Adds a failure message to job output when job failed and no events exist
  awx/ui/src/screens/Job/JobOutput/EmptyOutput.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.test.js
Labels: component:ui

#12428 Updated setup.py --version to python3 -m setuptools_scm.
  .github/workflows/ci.yml
  .github/workflows/stage.yml
  Makefile
  awx/__init__.py
  pyproject.toml
  requirements/requirements_dev.txt
  setup.cfg
  setup.py
  tools/ansible/build.yml
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/scripts/egg_info_dev
  tools/scripts/scm_version.py
  tox.ini
Labels: component:api

#12435 Give more specific messages if a job was killed due to SIGTERM or SIGKILL signals
  awx/main/dispatch/reaper.py
  awx/main/dispatch/worker/base.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tasks/signals.py
  awx/main/tasks/system.py
  awx/main/tests/unit/tasks/test_signals.py
  awx/main/utils/update_model.py
Labels: component:api
