Repository ansible/awx, pull requests merged in 2022-02, with the labels that each got.

#11587 Add info popover to WF node list items
  awx/ui/src/components/CheckboxListItem/CheckboxListItem.js
  awx/ui/src/components/CheckboxListItem/CheckboxListItem.test.js
  awx/ui/src/components/DetailList/DetailList.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.test.js
Labels: type:enhancement, component:ui

#10912 Add organization_alias to Org Mapping as intended
  awx/sso/fields.py
  awx/sso/pipeline.py
  awx/sso/tests/functional/test_pipeline.py
  awx/sso/tests/unit/test_fields.py
Labels: type:enhancement, component:api

#11517 Adds expand collapse all functionality on job output page.
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/JobOutput/PageControls.js
  awx/ui/src/screens/Job/JobOutput/PageControls.test.js
  awx/ui/src/screens/Job/JobOutput/useJobEvents.js
  awx/ui/src/screens/Job/JobOutput/useJobEvents.test.js
Labels: component:ui

#11668 Fix typerror cannot read property of null
  awx/ui/src/components/AddDropDownButton/AddDropDownButton.js
Labels: component:ui

#11673 Includes gettext on build-deps for multi-stage builds
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: type:bug, component:api

#11663 Update saml.md
  docs/auth/saml.md
Labels: component:docs

#11681 remove any named pipes before unzipping artifacts
  awx/main/tasks/jobs.py
Labels: component:api

#11675 Fix tooltip documentation in settings
  awx/main/conf.py
  awx/settings/defaults.py
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
Labels: component:api, component:ui, component:docs

#11692 Workflow changes
  .github/workflows/ci.yml
  .github/workflows/devel_image.yml
  .github/workflows/e2e_test.yml
  .github/workflows/stage.yml
  .github/workflows/upload_schema.yml
  Makefile
  pre-commit.sh
Labels: type:enhancement

#11670 Display all job type events in job output
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
Labels: type:bug, component:api, component:ui

#11696 add execution_environment_admin to role module
  awx_collection/plugins/modules/role.py
  awx_collection/tests/integration/targets/role/tasks/main.yml
Labels: component:collection

#11710 Run npm audit fix
  awx/ui/package-lock.json
Labels: component:ui

#11598 Adds credential password step to ad hoc commands wizard
  awx/ui/src/components/AdHocCommands/AdHocCommands.js
  awx/ui/src/components/AdHocCommands/AdHocCommands.test.js
  awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.js
  awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.test.js
  awx/ui/src/components/AdHocCommands/AdHocCredentialStep.js
  awx/ui/src/components/AdHocCommands/AdHocPreviewStep.js
  awx/ui/src/components/AdHocCommands/useAdHocCredentialPasswordStep.js
  awx/ui/src/components/AdHocCommands/useAdHocCredentialStep.js
  awx/ui/src/components/AdHocCommands/useAdHocLaunchSteps.js
Labels: type:bug, component:api, component:ui

#11717 Add metric for number of events emitted over websocket broadcast
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/worker/callback.py
Labels: component:api

#11649 Add await to handleLaunch
  awx/ui/src/components/LaunchButton/LaunchButton.js
Labels: type:bug, component:api, component:ui

#11728 [mesh viz] change the term unhealthy to error
  awx/api/serializers.py
Labels: component:api

#11655 Let an organization admin to add new users to it's tower organization
  awx_collection/plugins/modules/user.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/user/tasks/main.yml
Labels: type:enhancement, component:collection

#11665 Consume control capacity
  Makefile
  awx/main/managers.py
  awx/main/models/ha.py
  awx/main/models/projects.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/conftest.py
  awx/main/tests/factories/fixtures.py
  awx/main/tests/factories/tower.py
  awx/main/tests/functional/api/test_workflow_node.py
  awx/main/tests/functional/task_management/test_rampart_groups.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/tests/functional/test_instances.py
  awx/main/tests/unit/test_capacity.py
  awx/settings/defaults.py
  awx/settings/development.py
  docs/capacity.md
Labels: type:enhancement, component:api, component:docs

#11724 Bump node to LTS version
  Makefile
  awx/ui/CONTRIBUTING.md
  awx/ui/Dockerfile
  awx/ui/README.md
  awx/ui/package.json
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: component:api, component:ui

#11558 Adds Inventory labels
  awx/api/serializers.py
  awx/api/urls/inventory.py
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/main/access.py
  awx/main/migrations/0157_inventory_labels.py
  awx/main/models/inventory.py
  awx/main/models/label.py
  awx/main/tests/unit/models/test_label.py
  awx/ui/src/api/models/Inventories.js
  awx/ui/src/components/LabelSelect/LabelSelect.js
  awx/ui/src/components/LabelSelect/LabelSelect.test.js
  awx/ui/src/components/LabelSelect/index.js
  awx/ui/src/screens/Inventory/InventoryAdd/InventoryAdd.js
  awx/ui/src/screens/Inventory/InventoryAdd/InventoryAdd.test.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/InventoryEdit/InventoryEdit.js
  awx/ui/src/screens/Inventory/InventoryEdit/InventoryEdit.test.js
  awx/ui/src/screens/Inventory/shared/InventoryForm.js
  awx/ui/src/screens/Inventory/shared/InventoryForm.test.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
  awx/ui/src/screens/Template/shared/WorkflowJobTemplateForm.js
Labels: component:api, component:ui, type:feature

#11691 Fixes erroneous disabling of name input field on container and instance group forms
  awx/ui/src/screens/InstanceGroup/ContainerGroup.js
  awx/ui/src/screens/InstanceGroup/ContainerGroupAdd/ContainerGroupAdd.js
  awx/ui/src/screens/InstanceGroup/ContainerGroupEdit/ContainerGroupEdit.js
  awx/ui/src/screens/InstanceGroup/InstanceGroupAdd/InstanceGroupAdd.js
  awx/ui/src/screens/InstanceGroup/InstanceGroups.js
  awx/ui/src/screens/InstanceGroup/shared/ContainerGroupForm.js
  awx/ui/src/screens/InstanceGroup/shared/InstanceGroupForm.js
  awx/ui/src/screens/InstanceGroup/shared/InstanceGroupForm.test.js
  awx/ui/src/util/validators.js
  awx/ui/src/util/validators.test.js
Labels: component:api, component:ui

#11571 Added new class for Ansible Runner Callbacks
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
  awx/main/tests/unit/test_tasks.py
  awx/main/utils/update_model.py
Labels: type:enhancement, component:api

#11725 Fixup conversion of memory and cpu settings to support k8s resource request format
  awx/main/analytics/collectors.py
  awx/main/analytics/core.py
  awx/main/dispatch/pool.py
  awx/main/migrations/0158_make_instance_cpu_decimal.py
  awx/main/models/ha.py
  awx/main/tests/unit/settings/test_k8s_resource_setttings.py
  awx/main/utils/common.py
Labels: component:api

#11746 Fixes validator console error, and routing issue in Instance Groups Branch
  awx/ui/src/screens/InstanceGroup/ContainerGroupEdit/ContainerGroupEdit.js
  awx/ui/src/screens/InstanceGroup/InstanceGroups.js
  awx/ui/src/screens/InstanceGroup/shared/InstanceGroupForm.js
Labels: component:ui

#11766 pep8 E231 fix for awx_collection
  awx_collection/plugins/modules/organization.py
Labels: component:collection

#11734 Fix image push when overriding awx_image_tag
  tools/ansible/roles/image_push/tasks/main.yml
Labels: component:installer

#11767 Allow rekey with an existing key
  awx/main/management/commands/regenerate_secret_key.py
  awx/main/tests/functional/commands/test_secret_key_regeneration.py
Labels: component:api

#11742 drop unused logic in task manager
  awx/main/scheduler/task_manager.py
Labels: component:api

#11776 Use ternary rather than &&
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.js
Labels: component:api, component:ui

#11762 Display roles for organization listed when using non-English web browser
  awx/ui/src/components/ResourceAccessList/ResourceAccessList.js
Labels: component:ui

#11768 Fix TypeError when running a command on a host in a smart inventory
  awx/ui/src/components/AdHocCommands/AdHocCommands.js
  awx/ui/src/components/AdHocCommands/AdHocCommands.test.js
  awx/ui/src/screens/Inventory/SmartInventoryHosts/SmartInventoryHostList.js
  awx/ui/src/screens/Inventory/SmartInventoryHosts/SmartInventoryHostList.test.js
Labels: component:ui

#11759 Fixes broken Link from user to user org
  awx/ui/src/screens/User/UserOrganizations/UserOrganizationList.js
  awx/ui/src/screens/User/UserOrganizations/UserOrganizationList.test.js
  awx/ui/src/screens/User/UserOrganizations/UserOrganizationListItem.js
Labels: component:api, component:ui

#11801 fix missing job lifecycle messages
  awx/main/scheduler/task_manager.py
Labels: component:api

#11794 Allow more than 400 credential types in drop down while adding new credential
  awx/ui/src/screens/Credential/CredentialAdd/CredentialAdd.js
Labels: component:api, component:ui

#11702 Do not mount /etc/redhat-access-insights into EEs
  awx/main/tasks/jobs.py
Labels: component:api

#11756 Enable Podman ipv6 support by default
  awx/settings/defaults.py
Labels: component:api

#11800 set max dispatch workers to same as max forks
  awx/main/dispatch/pool.py
Labels: component:api

#11808 Chaning API version from v1beta1 to v1
  tools/docker-compose-minikube/minikube/templates/rbac.yml.j2
Labels: type:bug

#11679 Changing session cookie name and added a way for clients to know what the name is #11413
  awx/api/generics.py
  awx/settings/defaults.py
  awx/sso/views.py
  awxkit/awxkit/api/client.py
  awxkit/awxkit/awx/utils.py
  awxkit/awxkit/ws.py
  docs/auth/session.md
Labels: component:api, component:docs, component:cli

#11813 Fix bug where translated strings will cause log error to error
  awx/main/utils/handlers.py
Labels: component:api
