Repository ansible/awx, pull requests merged in 2022-08, with the labels that each got.

#12608 Fix Kubernetes dev environment + update docs
  docs/development/minikube.md
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: component:docs

#12587 Allow for adding external execution nodes via API
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/management/commands/register_peers.py
  awx/main/managers.py
  awx/main/migrations/0165_node_and_link_state.py
  awx/main/models/ha.py
  awx/main/scheduler/task_manager_models.py
  awx/main/tasks/system.py
Labels: component:api

#12616 Post new instances to the API on OpenShift
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx_collection/test/awx/test_completeness.py
Labels: component:api, component:awx_collection

#12558 Allow for passing multiple items for values and roles when configuring SAML auth
  awx/sso/conf.py
  awx/sso/fields.py
  awx/sso/migrations/0003_convert_saml_string_to_list.py
  awx/sso/pipeline.py
  awx/sso/tests/functional/test_pipeline.py
  awx/sso/tests/unit/test_fields.py
Labels: component:api

#12618 Add Help Text with documentation link to Notification Templates page
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.test.js
  awx/ui/src/screens/NotificationTemplate/shared/NotificationTemplateForm.test.js
  awx/ui/src/screens/NotificationTemplate/shared/Notifications.helptext.js
  awx/ui/src/screens/NotificationTemplate/shared/TypeInputsSubForm.js
Labels: component:ui

#12459 Easier review workflow output
  awx/ui/src/components/RoutedTabs/RoutedTabs.js
  awx/ui/src/components/WorkflowOutputNavigation/WorkflowOutputNavigation.js
  awx/ui/src/components/WorkflowOutputNavigation/index.js
  awx/ui/src/screens/Job/Job.js
Labels: component:ui

#12623 Adds functionality to provision or add an instance
  awx/ui/src/screens/Instances/InstanceAdd/InstanceAdd.js
  awx/ui/src/screens/Instances/InstanceAdd/InstanceAdd.test.js
  awx/ui/src/screens/Instances/InstanceAdd/index.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.test.js
  awx/ui/src/screens/Instances/Instances.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.test.js
  awx/ui/src/screens/Job/JobOutput/JobOutputSearch.js
Labels: component:ui

#12548 Refactors and redesigns workflow approval to impove UX
  awx/ui/src/components/AppContainer/NavExpandableGroup.js
  awx/ui/src/components/JobCancelButton/JobCancelButton.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApproval.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/index.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalList.test.js
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalButton.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalButton.test.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalControls.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalControls.test.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowDenyButton.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowDenyButton.test.js
Labels: component:ui

#12637 Fixes lack of translation on workflow approval list item actions
  awx/ui/src/screens/WorkflowApproval/WorkflowApprovalList/WorkflowApprovalListItem.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalButton.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowApprovalUtils.js
  awx/ui/src/screens/WorkflowApproval/shared/WorkflowDenyButton.js
Labels: component:ui

#12597 update workflow module for schema node creation to look for type when finding unified job template
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection

#12599 update role module to provide better error message when an object does not exist
  awx_collection/plugins/modules/role.py
  awx_collection/tests/integration/targets/role/tasks/main.yml
Labels: component:awx_collection

#12614 Modifying reaper of administrative work units to allow for change from Controller to Hybrid nodes
  awx/main/tasks/receptor.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#12367 Forcing an unbind for a django-auth-ldap sticky session to the LDAP server
  awx/sso/backends.py
Labels: component:api

#12445 Complex schedules UI
  awx/ui/src/components/ErrorDetail/ErrorDetail.js
  awx/ui/src/components/FormLayout/FormLayout.js
  awx/ui/src/components/Schedule/ScheduleAdd/ScheduleAdd.js
  awx/ui/src/components/Schedule/ScheduleAdd/ScheduleAdd.test.js
  awx/ui/src/components/Schedule/ScheduleDetail/FrequencyDetails.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/Schedule/ScheduleEdit/ScheduleEdit.js
  awx/ui/src/components/Schedule/ScheduleEdit/ScheduleEdit.test.js
  awx/ui/src/components/Schedule/shared/DateTimePicker.js
  awx/ui/src/components/Schedule/shared/FrequencyDetailSubform.js
  awx/ui/src/components/Schedule/shared/FrequencySelect.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
  awx/ui/src/components/Schedule/shared/ScheduleFormFields.js
  awx/ui/src/components/Schedule/shared/SchedulePromptableFields.js
  awx/ui/src/components/Schedule/shared/UnsupportedScheduleForm.js
  awx/ui/src/components/Schedule/shared/buildRuleObj.js
  awx/ui/src/components/Schedule/shared/buildRuleSet.js
  awx/ui/src/components/Schedule/shared/buildRuleSet.test.js
  awx/ui/src/components/Schedule/shared/parseRuleObj.js
  awx/ui/src/components/Schedule/shared/parseRuleObj.test.js
  awx/ui/src/components/Schedule/shared/sortFrequencies.js
  awx/ui/src/util/validators.js
Labels: component:ui

#12619 Dynamic control node receptor config
  awx/main/models/ha.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
  awx/main/tasks/system.py
  docs/licenses/filelock.txt
  requirements/requirements.in
  requirements/requirements.txt
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: component:api, component:docs

#12656 Add metric for task manager on_commit calls
  awx/main/analytics/subsystem_metrics.py
  awx/main/scheduler/task_manager.py
Labels: component:api

#12650 Fixed a bug where the initial form value of verbosity isn't respected
  awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.js
Labels: component:ui

#12593 [feature-project-integrity] configure content verification bug fix
  awx/ui/src/api/models/CredentialTypes.js
  awx/ui/src/screens/Project/ProjectAdd/ProjectAdd.js
  awx/ui/src/screens/Project/ProjectAdd/ProjectAdd.test.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.test.js
  awx/ui/src/screens/Project/ProjectEdit/ProjectEdit.js
  awx/ui/src/screens/Project/ProjectEdit/ProjectEdit.test.js
  awx/ui/src/screens/Project/shared/ProjectForm.js
  awx/ui/src/screens/Project/shared/ProjectForm.test.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/GitSubForm.js
Labels: component:ui

#12642 fix use of distinct on query that UI uses
  awx/api/filters.py
  awx/api/views/__init__.py
Labels: component:api

#12447 Altering events relationship to hosts to increase performance
  awx/main/migrations/0166_alter_jobevent_host.py
  awx/main/models/events.py
Labels: component:api

#12646 JT param everything
  awx/api/serializers.py
  awx/api/urls/job.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/migrations/0167_jt_prompt_everything_on_launch.py
  awx/main/models/ha.py
  awx/main/models/jobs.py
  awx/main/models/unified_jobs.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/models/test_job.py
  awx/main/tests/functional/models/test_job_launch_config.py
  awx/main/tests/functional/test_instances.py
  awx/main/tests/functional/test_jobs.py
  awx/main/tests/functional/test_rbac_job.py
  awx/main/tests/unit/api/serializers/test_job_serializers.py
  awx/main/tests/unit/api/serializers/test_primary_key_related_field.py
  awx/main/utils/common.py
  awx_collection/plugins/modules/job_launch.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/test/awx/test_job_template.py
Labels: component:api, component:awx_collection

#12356 Replace git shallow clone with shutil.copytree
  awx/main/tasks/jobs.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#12527 Further resiliency changes, specifically focused on case of database going offline
  awx/conf/settings.py
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/worker/callback.py
  awx/main/management/commands/run_wsbroadcast.py
  awx/main/tests/functional/utils/test_update_model.py
  awx/main/utils/update_model.py
Labels: component:api

#12494 Register system again if deleted by another pod
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/reaper.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/tasks/system.py
Labels: component:api

#12584 Wait 60 seconds before scaling down a worker
  awx/main/dispatch/pool.py
  awx/settings/defaults.py
Labels: component:api

#12442 Fix false reaper false-positives of waiting jobs that are waiting for worker
  awx/main/dispatch/pool.py
  awx/main/dispatch/reaper.py
  awx/main/tasks/jobs.py
  awx/main/tasks/system.py
  awx/main/tests/functional/test_dispatch.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#12676 Stability fixes, and related logging for slowdowns in dispatcher task processing
  awx/main/dispatch/pool.py
  awx/main/dispatch/publish.py
  awx/main/dispatch/reaper.py
  awx/main/dispatch/worker/base.py
  awx/main/dispatch/worker/callback.py
  awx/main/dispatch/worker/task.py
  awx/main/models/ha.py
  awx/main/tasks/jobs.py
  awx/main/tasks/system.py
  awx/main/utils/common.py
  awx/settings/defaults.py
Labels: component:api

#12289 Correct help text for job idle timeout
  awx/main/conf.py
Labels: component:api

#12679 conditionally show install_bundle link for instances
  awx/api/serializers.py
Labels: component:api

#12671 Avoid dependency manager for jobs with no deps
  awx/main/models/jobs.py
Labels: component:api

#12582 Move reaper logic into worker, avoiding bottlenecks
  awx/main/dispatch/pool.py
  awx/main/dispatch/publish.py
  awx/main/dispatch/reaper.py
  awx/main/tasks/system.py
  awx/main/tests/functional/test_dispatch.py
Labels: component:api

#12090 Avoid parent instance update when status was unchanged
  awx/main/models/unified_jobs.py
Labels: component:api

#11833 Use update_fields for Ansible facts update
  awx/main/models/jobs.py
  awx/main/tests/unit/models/test_jobs.py
Labels: component:api

#12573 Submit job to dispatcher as part of transaction
  awx/main/dispatch/__init__.py
  awx/main/dispatch/worker/base.py
  awx/main/models/unified_jobs.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks/jobs.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#11838 Avoid updating modified_by from None to None
  awx/main/models/base.py
  awx/main/tests/functional/models/test_base.py
Labels: component:api

#12649 Added more context to subscription details and rearrange the order of some of the fields
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.test.js
Labels: component:ui

#12692 Fix errors in websocket code due to missing template
  awx/main/models/unified_jobs.py
Labels: component:api

#12701 Make schedule teardown more reliable
  awxkit/awxkit/api/pages/schedules.py
  awxkit/awxkit/api/pages/unified_job_templates.py
Labels: component:cli

#12706 Revert "Fix errors in websocket code due to missing template"
  awx/main/models/unified_jobs.py
Labels: component:api

#12561 Modifying AWX collection to allow connection to IPv6 hosts.
  awx_collection/plugins/module_utils/controller_api.py
Labels: component:awx_collection

#12704 Consolidate and refactor logging configuration code
  awx/main/models/unified_jobs.py
  awx/settings/defaults.py
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: component:api

#12722 Fix STATIC_ROOT in defaults
  awx/settings/defaults.py
Labels: component:api

#12552 Implement Generic OIDC Provider
  awx/settings/defaults.py
  awx/sso/conf.py
  awx/sso/fields.py
  awx/ui/src/screens/Login/Login.js
  awx/ui/src/screens/Setting/OIDC/OIDC.js
  awx/ui/src/screens/Setting/OIDC/OIDC.test.js
  awx/ui/src/screens/Setting/OIDC/OIDCDetail/OIDCDetail.js
  awx/ui/src/screens/Setting/OIDC/OIDCDetail/OIDCDetail.test.js
  awx/ui/src/screens/Setting/OIDC/OIDCDetail/index.js
  awx/ui/src/screens/Setting/OIDC/OIDCEdit/OIDCEdit.js
  awx/ui/src/screens/Setting/OIDC/OIDCEdit/OIDCEdit.test.js
  awx/ui/src/screens/Setting/OIDC/OIDCEdit/index.js
  awx/ui/src/screens/Setting/OIDC/index.js
  awx/ui/src/screens/Setting/SettingList.js
  awx/ui/src/screens/Setting/Settings.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
  docs/licenses/ecdsa.txt
  docs/licenses/python-jose.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, component:ui, component:docs, community

#12695 [ui] make signature cred. field be project-global
  awx/ui/src/screens/Project/ProjectAdd/ProjectAdd.js
  awx/ui/src/screens/Project/ProjectEdit/ProjectEdit.js
  awx/ui/src/screens/Project/shared/ProjectForm.js
  awx/ui/src/screens/Project/shared/ProjectForm.test.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/GitSubForm.js
Labels: component:ui

#12693 [content signing] 12687 remove enable field
  awx/api/serializers.py
  awx/main/migrations/0167_project_signature_validation_credential.py
  awx/main/models/projects.py
  awx_collection/plugins/modules/project.py
Labels: component:api, component:awx_collection

#12731 Fix make target for compiling api strings
  Makefile
Labels: community

#12655 Adds Instance Peers Tab and update Instance Details view with more data
  awx/api/serializers.py
  awx/api/urls/instance.py
  awx/api/views/__init__.py
  awx/main/access.py
  awx/main/tests/functional/test_tasks.py
  awx/ui/src/api/models/Instances.js
  awx/ui/src/screens/Instances/Instance.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerListItem.js
  awx/ui/src/screens/Instances/InstancePeers/index.js
Labels: component:api, component:ui

#12709 Update node details and legend in Topology View.
  awx/ui/src/screens/TopologyView/Legend.js
  awx/ui/src/screens/TopologyView/MeshGraph.js
  awx/ui/src/screens/TopologyView/Tooltip.js
  awx/ui/src/screens/TopologyView/constants.js
  awx/ui/src/screens/TopologyView/utils/helpers.js
Labels: component:ui

#12760 Fix browsable API in development environment
  awx/settings/development.py
Labels: component:api

#12758 Properly show Peers tab in UI.
  awx/ui/src/screens/Instances/Instance.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js
Labels: component:ui

#12759 Automate bootstrapping of Prometheus in the development environment
  .gitignore
  docs/prometheus.md
  tools/docker-compose/README.md
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/prometheus.yml.j2
Labels: component:docs

#12749 Make error handling less aggressive when checking status of dispatcher task
  awx/main/models/unified_jobs.py
Labels: component:api

#12766 Revert "Merge pull request #12584 from AlanCoding/lazy_workers"
  awx/main/dispatch/pool.py
  awx/settings/defaults.py
Labels: component:api

#12771 Enable work signing for execution node
  awx/main/tasks/receptor.py
Labels: component:api

#12702 Check exit conditions in loop waiting for project flock
  awx/main/tasks/jobs.py
Labels: component:api

#12754 calcuate consumed capacity in same way in metrics
  awx/main/analytics/collectors.py
  awx/main/scheduler/task_manager_models.py
  tools/grafana/dashboards/demo_dashboard.json
Labels: component:api, community

#12780 [mesh-scaling] don't use ordered dict for receptor config
  awx/main/tasks/receptor.py
Labels: component:api

#12769 Fix sanity check to use the relevant active connection
  awx/main/dispatch/__init__.py
  awx/main/dispatch/control.py
Labels: component:api

#12773 Update status labels to reflect node states
  awx/ui/src/components/StatusIcon/StatusIcon.js
  awx/ui/src/components/StatusIcon/icons.js
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceListItem.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceListItem.js
  awx/ui/src/screens/Instances/InstanceList/InstanceListItem.test.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerListItem.js
Labels: component:ui

#12786 Follow up on new execution node creation
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/models/ha.py
  awx/main/tasks/receptor.py
Labels: component:api

#12697 Fix TypeError when config is undefined
  awx/ui/src/screens/Setting/shared/SharedFields.js
Labels: component:ui

#12798 Resolve a deadlock in write_receptor_config()
  awx/main/tasks/receptor.py
Labels: component:api

#12689 poll for events processing completion
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
Labels: component:ui
