Repository ansible/awx, pull requests merged in 2022-01, with the labels that each got.

#11489 Fix relaunch of jobs
  awx/ui/src/components/JobList/JobListItem.js
  awx/ui/src/components/LaunchButton/LaunchButton.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobOutput/shared/OutputToolbar.js
Labels: component:ui

#11485 Fix a problem with the events_table analytics collectors
  awx/main/analytics/collectors.py
Labels: type:bug, component:api

#11324 Reduce duplicate fetches after saving inventory group
  awx/ui/src/screens/Inventory/InventoryGroupEdit/InventoryGroupEdit.js
Labels: type:bug, component:ui, state:needs_test

#11441 Remove unnecessary DEBUG logger level settings
  awx/settings/defaults.py
Labels: type:enhancement, component:api

#11508 Disable awx-config-watcher for k8s images
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
  tools/ansible/roles/dockerfile/templates/supervisor.conf.j2
  tools/ansible/roles/dockerfile/templates/supervisor_task.conf.j2
Labels: state:needs_review

#11504 add better error and documentation on labels
  awx_collection/plugins/modules/job_template.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/tests/integration/targets/job_template/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: type:bug

#11380 add new name to multiple modules
  awx_collection/plugins/modules/application.py
  awx_collection/plugins/modules/credential_type.py
  awx_collection/plugins/modules/execution_environment.py
  awx_collection/plugins/modules/inventory.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/plugins/modules/organization.py
  awx_collection/plugins/modules/project.py
  awx_collection/plugins/modules/user.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/application/tasks/main.yml
  awx_collection/tests/integration/targets/credential_type/tasks/main.yml
  awx_collection/tests/integration/targets/execution_environment/tasks/main.yml
  awx_collection/tests/integration/targets/inventory/tasks/main.yml
  awx_collection/tests/integration/targets/organization/tasks/main.yml
  awx_collection/tests/integration/targets/project/tasks/main.yml
  awx_collection/tests/integration/targets/user/tasks/main.yml
Labels: type:enhancement, state:needs_review, component:awx_collection

#11515 Revert "Remove unnecessary DEBUG logger level settings (#11441)"
  awx/settings/defaults.py
Labels: type:bug, component:api

#11430 SAML user flags 5303
  .gitignore
  Makefile
  awx/settings/defaults.py
  awx/sso/backends.py
  awx/sso/conf.py
  awx/sso/fields.py
  awx/sso/pipeline.py
  awx/sso/tests/functional/test_pipeline.py
  awx/sso/tests/unit/test_fields.py
  awx/ui/src/screens/Setting/SAML/SAML.test.js
  awx/ui/src/screens/Setting/SAML/SAMLDetail/SAMLDetail.test.js
  awx/ui/src/screens/Setting/SAML/SAMLEdit/SAMLEdit.js
  awx/ui/src/screens/Setting/SAML/SAMLEdit/SAMLEdit.test.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
  tools/docker-compose/README.md
  tools/docker-compose/ansible/plumb_keycloak.yml
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/templates/keycloak.awx.realm.json.j2
  tools/docker-compose/ansible/templates/saml_settings.json.j2
Labels: type:enhancement, component:api, component:ui

#11520 In register_peers, only check non-empty flags for the 1-cycle check
  awx/main/management/commands/register_peers.py
Labels: type:bug, component:api

#11375 Fail with specific error message if protected image is not available
  awx/main/management/commands/inventory_import.py
Labels: type:bug, component:api

#11454 Creates end point and beginning of serializer for receptor mesh
  awx/api/serializers.py
  awx/api/templates/api/mesh_visualizer.md
  awx/api/urls/urls.py
  awx/api/views/__init__.py
  awx/api/views/mesh_visualizer.py
  awx/api/views/root.py
Labels: type:enhancement, component:api, state:needs_review, type:feature

#11509 Modify how manual subform is displayed for projects
  awx/ui/src/screens/Project/shared/ProjectForm.js
Labels: component:ui

#11530 Don't expose serviceAccount token on default pod spec
  awx/main/utils/execution_environments.py
Labels: state:needs_review

#11528 Splitting 'tasks.py' file into a module
  awx/api/generics.py
  awx/api/views/__init__.py
  awx/conf/views.py
  awx/main/dispatch/worker/callback.py
  awx/main/dispatch/worker/task.py
  awx/main/management/commands/profile_sql.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/events.py
  awx/main/models/ha.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/notifications.py
  awx/main/models/projects.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/signals.py
  awx/main/tasks/__init__.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
  awx/main/tasks/system.py
  awx/main/tests/functional/api/test_instance.py
  awx/main/tests/functional/task_management/test_container_groups.py
  awx/main/tests/functional/task_management/test_rampart_groups.py
  awx/main/tests/functional/test_copy.py
  awx/main/tests/functional/test_instances.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/tests/functional/test_jobs.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/unit/settings/test_defaults.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_receptor.py
  awx/main/utils/receptor.py
  awx/settings/defaults.py
  docs/debugging/debugging_misc.md
  docs/tasks.md
Labels: component:api

#11503 Remove unused ansible version method
  awx/main/utils/common.py
Labels: type:enhancement, component:api

#11550 Fixing token documentation
  awx_collection/plugins/modules/token.py
Labels: component:docs, component:awx_collection

#11522 Fix null on workflowjobtemplate
  awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.js
  awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js
Labels: component:ui, state:needs_test

#11562 Avoid duplicated entries when calling create_preload_data
  awx/main/management/commands/create_preload_data.py
Labels: type:bug, priority:high

#11556 Bump node and npm versions inside container
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: component:ui, state:needs_review

#11527 Api 4XX error msg customization 1236
  awx/api/generics.py
  awx/main/conf.py
  awx/main/tests/functional/test_api_generics.py
  awx/settings/defaults.py
  awx/ui/src/screens/Setting/Logging/Logging.test.js
  awx/ui/src/screens/Setting/Logging/LoggingDetail/LoggingDetail.js
  awx/ui/src/screens/Setting/Logging/LoggingDetail/LoggingDetail.test.js
  awx/ui/src/screens/Setting/Logging/LoggingEdit/LoggingEdit.js
  awx/ui/src/screens/Setting/Logging/LoggingEdit/LoggingEdit.test.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
  awx/ui/src/screens/Setting/shared/data.logSettings.json
Labels: type:enhancement, component:api, component:ui

#11570 Minor docs tweaks for keycloak setup
  tools/docker-compose/README.md
Labels: component:api, component:docs

#11573 Rename remaining .jsx files to .js
  awx/ui/src/components/AdHocCommands/AdHocPreviewStep.js
  awx/ui/src/components/AdHocCommands/useAdHocCredentialStep.js
  awx/ui/src/components/AdHocCommands/useAdHocDetailsStep.js
  awx/ui/src/components/AdHocCommands/useAdHocExecutionEnvironmentStep.js
  awx/ui/src/components/AdHocCommands/useAdHocPreviewStep.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/DaysToKeepStep.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/DaysToKeepStep.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/SystemJobTemplatesList.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/SystemJobTemplatesList.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useDaysToKeepStep.js
  awx/ui/testUtils/apiReusable.js
  awx/ui/testUtils/enzymeHelpers.js
  awx/ui/testUtils/enzymeHelpers.test.js
Labels: component:ui

#11576 Handeling different types of response.data
  awx/api/generics.py
  awx/main/tests/functional/test_api_generics.py
Labels: type:bug, component:api

#11566 Support user customization of EE mount options and mount paths
  .github/workflows/ci.yml
  awx/conf/fields.py
  awx/main/conf.py
  awx/main/constants.py
  awx/main/tasks/jobs.py
  awx/settings/defaults.py
Labels: type:enhancement, component:api, component:ui, state:needs_docs

#11561 Update status icons
  awx/ui/src/components/StatusIcon/StatusIcon.js
  awx/ui/src/components/StatusIcon/StatusIcon.test.js
  awx/ui/src/components/StatusIcon/icons.js
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.test.js
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui/src/screens/Job/JobOutput/HostEventModal.test.js
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
  awx/ui/src/screens/Job/WorkflowOutput/WorkflowOutputToolbar.js
Labels: type:enhancement, component:ui, state:needs_test

#11602 Avoid Project..get_or_create() in create_preload_data
  awx/main/management/commands/create_preload_data.py
Labels: type:bug, priority:high, state:needs_review

#11591 Turn off the filtering of hop nodes from the Instance endpoints
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/management/commands/list_instances.py
  awx/main/management/commands/register_queue.py
  awx/main/models/ha.py
  awx/main/tasks/system.py
Labels: type:enhancement, component:api

#11608 Mount awx_devel in execution nodes for developer utility
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: type:enhancement, component:api

#11581 Adds more detail to the AWX release notes
  docs/img/compare_release_branch.png
  docs/img/pr_compare_list.png
  docs/release_process.md
Labels: component:docs

#11599 fix deprecated indentation and type
  awx_collection/plugins/doc_fragments/auth_plugin.py
Labels: type:bug

#11569 Update ad_hoc_commands.py
  awx/main/models/ad_hoc_commands.py
Labels: type:enhancement, component:api

#11614 Only do a warning on 2-cycles for the register_peers command
  awx/main/management/commands/register_peers.py
Labels: type:bug, component:api

#11627 Prevent duplicate query in local health check
  awx/main/models/ha.py
Labels: component:api

#11639 Deal properly with comments in requirements_git.txt
  requirements/updater.sh
Labels: type:bug, component:api

#11618 Install ps in dev image
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: type:bug, component:api

#11638 Only display usable inventories for launch prompt
  awx/ui/src/components/LaunchPrompt/steps/InventoryStep.js
Labels: component:ui
