Repository ansible/awx, pull requests merged in 2022-09, with the labels that each got.

#12803 Fix an issue where default cleanup schedules only run once
  awx/main/migrations/_create_system_jobs.py
Labels: component:api

#12790 Common Inventory slicing method for job slices
  awx/main/models/inventory.py
  awx/main/models/jobs.py
Labels: component:api

#12632 Add documentation for running development environment in kind
  docs/development/kind.md
Labels: component:docs

#12819 Make static asset location consistent across all deployments
  awx/settings/development.py
  tools/docker-compose/nginx.vh.default.conf
Labels: component:api

#12791 Clear output follow mode on search
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
Labels: component:ui

#12784 Can deprovision an Instance from Instance List and Instance detail view
  awx/ui/src/api/models/Instances.js
  awx/ui/src/screens/Instances/Instance.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/Shared/RemoveInstanceButton.js
  awx/ui/src/util/getRelatedResourceDeleteDetails.js
Labels: component:ui

#11745 Close database connections while processing job output
  awx/main/dispatch/control.py
  awx/main/dispatch/worker/base.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/models/mixins.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
  awx/main/tasks/signals.py
  awx/main/tests/functional/test_dispatch.py
  awx/main/tests/unit/models/test_unified_job_unit.py
  awx/main/utils/handlers.py
  docs/ansible_runner_integration.md
Labels: component:api, component:docs

#12837 Register pages for the Instance peers and install bundle endpoints
  awx/api/views/instance_install_bundle.py
  awxkit/awxkit/api/pages/instances.py
  awxkit/awxkit/api/pages/page.py
  awxkit/awxkit/api/resources.py
Labels: component:api, component:cli

#12842 Add "cryptography" kind to CredentialType
  awx/main/migrations/0167_project_signature_validation_credential.py
  awx/main/models/credential/__init__.py
Labels: component:api

#12785 Fix list_instances command
  awx/main/management/commands/list_instances.py
Labels: component:api, community

#12826 Fix Instance Detail StatusLabel to show node_state.
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.test.js
Labels: component:ui

#12724 Fix: preserve_existing_hosts flag in awx.awx.group module, while adding a new host to inventory group, retains only 25 existing hosts related #11605
  awx_collection/plugins/modules/group.py
Labels: component:awx_collection, community

#12735 [sig validation] better error for job template run
  awx/api/serializers.py
Labels: component:api

#12856 add firewall rules to control node
  awx/main/tasks/receptor.py
Labels: component:api

#12857 Update install bundle
  awx/api/views/instance_install_bundle.py
Labels: component:api

#12762 fix link of Patternfly style guide
  awx/ui/CONTRIBUTING.md
Labels: component:ui, community

#12848 Account for node state of 'unavailable' in the UI.
  awx/ui/src/components/StatusIcon/StatusIcon.js
  awx/ui/src/components/StatusIcon/icons.js
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/screens/TopologyView/constants.js
  awx/ui/src/screens/TopologyView/utils/helpers.js
Labels: component:ui

#12863 Fix compiler warnings.
  awx/ui/src/screens/TopologyView/Legend.js
Labels: component:ui

#12865 Update Kind Docs
  docs/development/kind.md
Labels: component:docs, community

#12855 Prevents API error on node deprovision request
  awx/ui/src/api/models/Instances.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/Shared/RemoveInstanceButton.js
Labels: component:ui

#12861 Add more helper unit tests.
  awx/ui/src/screens/TopologyView/utils/helpers__RTL.test.js
Labels: component:ui

#12872 Enables search on instance peers list
  awx/ui/src/api/models/Instances.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js
Labels: type:bug, component:ui

#12859 updates CanIUseLite
  awx/ui/package-lock.json
Labels: component:ui

#12788 Ensures that strings in helpText files do not miss being translated
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/Schedule/shared/ScheduleFormFields.js
  awx/ui/src/screens/Application/ApplicationDetails/ApplicationDetails.js
  awx/ui/src/screens/Application/shared/Application.helptext.js
  awx/ui/src/screens/Application/shared/ApplicationForm.js
  awx/ui/src/screens/ExecutionEnvironment/ExecutionEnvironmentDetails/ExecutionEnvironmentDetails.js
  awx/ui/src/screens/ExecutionEnvironment/shared/ExecutionEnvironment.helptext.js
  awx/ui/src/screens/ExecutionEnvironment/shared/ExecutionEnvironmentForm.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/InventorySourceDetail/InventorySourceDetail.js
  awx/ui/src/screens/Inventory/shared/Inventory.helptext.js
  awx/ui/src/screens/Inventory/shared/InventoryForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/AzureSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/ControllerSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/EC2SubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/GCESubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/InsightsSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/OpenStackSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SatelliteSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SharedFields.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/VMwareSubForm.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/VirtualizationSubForm.js
  awx/ui/src/screens/Job/Job.helptext.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.js
  awx/ui/src/screens/NotificationTemplate/shared/Notifications.helptext.js
  awx/ui/src/screens/NotificationTemplate/shared/TypeInputsSubForm.js
  awx/ui/src/screens/Project/ProjectDetail/ProjectDetail.js
  awx/ui/src/screens/Project/shared/Project.helptext.js
  awx/ui/src/screens/Project/shared/ProjectForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/ArchiveSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/GitSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/ManualSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/SharedFields.js
  awx/ui/src/screens/Project/shared/ProjectSubForms/SvnSubForm.js
  awx/ui/src/screens/Project/shared/ProjectSyncButton.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
  awx/ui/src/screens/Template/WorkflowJobTemplateDetail/WorkflowJobTemplateDetail.js
  awx/ui/src/screens/Template/shared/JobTemplate.helptext.js
  awx/ui/src/screens/Template/shared/JobTemplateForm.js
  awx/ui/src/screens/Template/shared/WebhookSubForm.js
  awx/ui/src/screens/Template/shared/WorkflowJobTemplate.helptext.js
  awx/ui/src/screens/Template/shared/WorkflowJobTemplateForm.js
  awx/ui/src/screens/User/UserTokenDetail/UserTokenDetail.js
  awx/ui/src/screens/User/shared/User.helptext.js
Labels: component:ui

#12877 Modify proxy config to allow UI to point to named sites.
  awx/ui/src/setupProxy.js
Labels: component:ui

#12868 Don't add ws events twice to job output
  awx/ui/src/screens/Job/JobOutput/JobOutput.js
Labels: component:ui

#12886 Add new add_label method to the wfjt node and schedules awxkit models
  awxkit/awxkit/api/pages/schedules.py
  awxkit/awxkit/api/pages/workflow_job_template_nodes.py
Labels: component:cli, community

#12889 Complete consolidation of the label views
  awx/api/generics.py
  awx/api/urls/label.py
  awx/api/views/__init__.py
  awx/api/views/inventory.py
  awx/api/views/labels.py
  awx/main/tests/unit/api/test_views.py
Labels: component:api

#12869 UI handle async health checks
  awx/ui/src/components/HealthCheckAlert/HealthCheckAlert.js
  awx/ui/src/components/HealthCheckAlert/index.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceList.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerList.js
  awx/ui/src/screens/Instances/InstancePeers/InstancePeerListItem.js
Labels: component:ui

#12894 Add support for instance_groups and labels on schedule create
  awx/api/serializers.py
  awx/api/views/__init__.py
Labels: component:api

#12893 Changing label functions to account for new relationships
  awx/main/models/label.py
  awx/main/tests/unit/models/test_label.py
Labels: component:api

#12878 Prevent altering certain fields on Instance
  awx/api/serializers.py
Labels: component:api

#12778 Schedule exceptions
  awx/ui/src/components/DetailList/DetailList.js
  awx/ui/src/components/Schedule/ScheduleDetail/FrequencyDetails.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/components/Schedule/shared/FrequencyDetailSubform.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
  awx/ui/src/components/Schedule/shared/ScheduleFormFields.js
  awx/ui/src/components/Schedule/shared/buildRuleObj.js
  awx/ui/src/components/Schedule/shared/buildRuleSet.js
  awx/ui/src/components/Schedule/shared/buildRuleSet.test.js
  awx/ui/src/components/Schedule/shared/parseRuleObj.js
  awx/ui/src/components/Schedule/shared/parseRuleObj.test.js
Labels: component:ui

#12895 Write logic to combing workflow labels, IGs with nodes
  awx/main/models/workflow.py
Labels: component:api

#12896 Correctly summarize label prompts, and add missing EE
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/models/unified_jobs.py
Labels: component:api

#12899 Expand unit tests to apply more fields
  awx/main/tests/functional/api/test_job.py
  awx/main/tests/functional/models/test_job_launch_config.py
Labels: component:api

#12890 Only get receptor.conf lock in k8s environment
  awx/main/tasks/receptor.py
Labels: component:api

#12904 Fix bug where empty workflow job vars blanked node vars
  awx/main/models/jobs.py
  awx/main/models/workflow.py
  awx/main/tests/functional/models/test_workflow.py
Labels: component:api

#12907 Add additional schedule fields for new prompts
  awxkit/awxkit/api/pages/unified_job_templates.py
Labels: component:cli, community

#12849 Adds project revision hash to inventory source views
  awx/api/serializers.py
  awx/main/migrations/0168_inventoryupdate_scm_revision.py
  awx/main/models/inventory.py
  awx/main/tasks/jobs.py
  awx/ui/src/screens/Job/Job.helptext.js
  awx/ui/src/screens/Job/JobDetail/JobDetail.js
Labels: component:api, component:ui

#12897 Changing awxkit --timeout parameter
  awxkit/awxkit/cli/custom.py
  awxkit/awxkit/cli/stdout.py
Labels: component:cli

#12885 Remove extra redirects from the runtime.yml
  awx_collection/meta/runtime.yml
Labels: component:awx_collection

#12866 Add unit tests to remove instance button component
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/src/api/models/Instances.js
  awx/ui/src/screens/Instances/Shared/RemoveInstanceButton.test.js
Labels: component:ui, dependencies

#12916 put install bundle file in templates dir
  awx/api/templates/instance_install_bundle/install_receptor.yml
  awx/api/templates/instance_install_bundle/inventory.yml
  awx/api/templates/instance_install_bundle/requirements.yml
  awx/api/views/instance_install_bundle.py
Labels: component:api

#12923 Bumps migration number from 0168 to 0169
  awx/main/migrations/0169_jt_prompt_everything_on_launch.py
Labels: component:api

#12926 [proj signing] Fix error message, rename action
  awx/playbooks/action_plugins/verify_project.py
  awx/playbooks/library/verify_project.py
  awx/playbooks/project_update.yml
Labels: component:api

#12929 Add instance module to controller action group
  awx_collection/meta/runtime.yml
Labels: component:awx_collection

#12917 Validate job_slice_count in API
  awx/api/serializers.py
  awx/main/models/jobs.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/models/test_job.py
Labels: component:api

#12910 Add doc for adding execution node
  docs/execution_nodes.md
Labels: component:docs

#12937 Set initial value node_type and node_state
  awx/api/serializers.py
Labels: component:api

#12941 Feature prompt on launch on templates collection fixes
  awx_collection/tests/integration/targets/lookup_api_plugin/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection

#12940 Ensure schedule collection test has enough hosts for slices
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
Labels: component:awx_collection, community

#12727 Improves visibility of workflow approval notification bell
  awx/ui/src/components/AppContainer/PageHeaderToolbar.js
  awx/ui/src/components/AppContainer/PageHeaderToolbar.test.js
Labels: component:ui, community

#12844 Prevents test button on credential form from disappearing
  awx/ui/src/screens/Credential/shared/CredentialForm.js
Labels: component:ui

#12947 Fix remove unnecessary comment
  awx/api/views/instance_install_bundle.py
Labels: component:api

#12945 Fix import order partially
  awx/api/views/__init__.py
Labels: component:api, component:ui, component:docs, component:cli, component:awx_collection, dependencies

#12943 Add locators for QE.
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/TopologyView/MeshGraph.js
  awx/ui/src/screens/TopologyView/Tooltip.js
Labels: component:ui

#12915 Add scroll overflow for legend and tooltip in Topology View.
  awx/ui/src/screens/TopologyView/Legend.js
  awx/ui/src/screens/TopologyView/Tooltip.js
Labels: component:ui

#12874 Fixed bug where inventory field was erroneously disabled on WFJT form
  awx/ui/src/components/Lookup/InventoryLookup.js
  awx/ui/src/components/Lookup/InventoryLookup.test.js
  awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js
  awx/ui/src/screens/Template/shared/WorkflowJobTemplateForm.js
Labels: component:ui

#12962 Remove changeOrigin proxy setting.
  awx/ui/src/setupProxy.js
Labels: component:ui

#12955 Normal Users no longer see Instances in side nav
  awx/ui/src/routeConfig.js
  awx/ui/src/routeConfig.test.js
Labels: component:ui

#12964 [collection] Remove instance defaults from docs
  awx_collection/plugins/modules/instance.py
  awx_collection/tests/integration/targets/instance/tasks/main.yml
  docs/development/kind.md
Labels: component:docs, component:awx_collection

#12818 Removes references to current_user
  awx/api/generics.py
  awx/sso/views.py
  awx/ui/src/screens/Login/Login.js
  awx/ui/src/screens/Login/Login.test.js
Labels: component:api, component:ui

#12864 Avoid cache warning for dispatching control type tasks
  awx/main/scheduler/task_manager.py
Labels: component:api

#12912 Add tooltips to Instance form; change `name` field to `host name`.
  awx/ui/src/screens/Instances/Shared/InstanceForm.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.test.js
Labels: component:ui

#12968 Make sure to include field defaults for Instance node_type and node_state
  awx/api/serializers.py
Labels: component:api

#12959 Add a new Instance.health_check_started field
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/migrations/0171_add_health_check_started.py
  awx/main/models/ha.py
  awx/main/tasks/system.py
Labels: component:api

#12973 always display awx_status_total
  awx/main/analytics/metrics.py
  awx/main/tests/functional/analytics/test_metrics.py
Labels: component:api

#12461 Fix notification doc for Workflow Job Template module
  awx_collection/plugins/modules/workflow_job_template.py
Labels: component:awx_collection, community

#12950 [ui] Don't double-entity encode on event stdout
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
Labels: component:ui

#12976 instance install bundle group vars
  awx/api/templates/instance_install_bundle/group_vars/all.yml
  awx/api/templates/instance_install_bundle/inventory.yml
  awx/api/views/instance_install_bundle.py
Labels: component:api
