Repository ansible/awx, pull requests merged in 2022-11, with the labels that each got.

#13139 Fix traceback on timeout with slicing + facts
  awx/main/models/inventory.py
  awx/main/models/jobs.py
Labels: component:api

#13146 de-duplicate default settings
  awx/settings/defaults.py
Labels: component:api

#13083 new machinery for webhook notifications to allow processing of redirects
  awx/main/notifications/webhook_backend.py
  awx/main/tests/functional/test_notifications.py
  awx/main/tests/unit/notifications/test_webhook.py
Labels: component:api, community

#13114 Remove ssh_key_data fix, handled in runner now
  awx/main/tasks/callback.py
Labels: component:api

#12971 Precise migrate.yml path in development docs
  tools/docker-compose/README.md
Labels: community

#13063 No InventoryUpdates when source Project is failed
  awx/api/serializers.py
  awx/api/views/__init__.py
  awx/main/models/projects.py
  awx/main/tasks/jobs.py
Labels: component:api

#13092 Fix error when applying taggit app tags to objects
  awx/main/registrar.py
Labels: component:api

#13170 Conjur cloud and branding
  awx/main/credential_plugins/conjur.py
  awx/ui/src/screens/Credential/CredentialEdit/CredentialEdit.test.js
  awx/ui/src/screens/Credential/shared/CredentialPlugins/CredentialPluginPrompt/CredentialPluginPrompt.test.js
  awx/ui/src/screens/Credential/shared/data.credentialTypes.json
  awx/ui/src/screens/Credential/shared/data.cyberArkCredential.json
  awx_collection/plugins/modules/credential.py
Labels: component:api, component:ui, component:awx_collection, community

#13172 Add proper declaration of secret version if present
  awx/main/credential_plugins/conjur.py
Labels: component:api, community

#13171 Cyberark ccp branding webserviceid
  awx/main/credential_plugins/aim.py
  awx/ui/src/screens/Credential/shared/data.credentialTypes.json
  awx_collection/plugins/modules/credential.py
  awx_collection/tests/integration/targets/credential_input_source/tasks/main.yml
Labels: component:api, component:ui, component:awx_collection, community

#13148 Fix HostEvent modal TypeError
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
  awx/ui/src/screens/Job/JobOutput/HostEventModal.test.js
Labels: component:ui

#13153 Refactor test_get_cleanup_task_kwargs_active_jobs and add new test
  awx/main/models/ha.py
  awx/main/tests/functional/test_instances.py
Labels: component:api

#13174 Avoid adding the 'config' subparser twice
  awxkit/awxkit/cli/resource.py
Labels: component:cli

#12884 [tech debt] Move the IS_TESTING method out of settings
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/publish.py
  awx/main/scheduler/task_manager.py
  awx/main/utils/common.py
  awx/settings/defaults.py
Labels: component:api

#13121 Fixes #13119 #13120 Conjur Cloud support & update brand
  awx/main/credential_plugins/conjur.py
  awx/ui/src/screens/Credential/CredentialEdit/CredentialEdit.test.js
  awx/ui/src/screens/Credential/shared/CredentialPlugins/CredentialPluginPrompt/CredentialPluginPrompt.test.js
  awx/ui/src/screens/Credential/shared/data.credentialTypes.json
  awx/ui/src/screens/Credential/shared/data.cyberArkCredential.json
  awx_collection/plugins/modules/credential.py
Labels: component:api, component:ui, component:awx_collection, community

#13071 Fixes #12846 - Secret version not working for Conjur Credential Plugin
  awx/main/credential_plugins/conjur.py
Labels: component:api, community

#13184 Update conf.py
  awxkit/awxkit/cli/docs/source/conf.py
Labels: component:cli, community

#13181 Replace the querysets provided by django-qsstats-magic
  awx/api/views/__init__.py
  awx/main/dispatch/pool.py
  docs/licenses/django-qsstats-magic.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, component:docs

#13176 Add node_type to instance info and capacity metrics
  awx/main/analytics/collectors.py
  awx/main/analytics/metrics.py
Labels: component:api

#12998 Bulk save facts, and move to before status change
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/tasks/jobs.py
  awx/main/tests/unit/models/test_jobs.py
  awx/main/utils/common.py
Labels: component:api

#13162 update awx collection workflow module schema with new options
  awx_collection/plugins/modules/job_template.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection, community

#13200 Disable work signing by default in dev env
  awx/api/templates/instance_install_bundle/group_vars/all.yml
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-awx.conf.j2
  tools/docker-compose/ansible/roles/sources/templates/receptor-worker.conf.j2
Labels: component:api

#13154 Fix running job showing "waiting" status
  awx/ui/src/screens/Job/useWsJob.js
  licenses/django-qsstats-magic.txt
Labels: component:ui

#13111 Adds an Instance Group component that renders IGs as a PF Label
  awx/ui/src/components/InstanceGroupLabels/InstanceGroupLabels.js
  awx/ui/src/components/InstanceGroupLabels/index.js
  awx/ui/src/components/PromptDetail/PromptDetail.js
  awx/ui/src/components/Schedule/ScheduleDetail/ScheduleDetail.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.js
  awx/ui/src/screens/Inventory/InventoryDetail/InventoryDetail.test.js
  awx/ui/src/screens/Inventory/SmartInventoryDetail/SmartInventoryDetail.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.js
  awx/ui/src/screens/Organization/OrganizationDetail/OrganizationDetail.test.js
  awx/ui/src/screens/Template/JobTemplateDetail/JobTemplateDetail.js
Labels: component:ui

#13213 Fix fallout from turning off work signing in docker-compose
  awx/main/tasks/receptor.py
  tools/docker-compose/ansible/roles/sources/templates/receptor-worker.conf.j2
Labels: component:api

#13198 Pushing updated strings for localization
  awx/locale/es/LC_MESSAGES/django.po
  awx/locale/fr/LC_MESSAGES/django.po
  awx/locale/nl/LC_MESSAGES/django.po
  awx/locale/translations/es/django.po
  awx/locale/translations/es/messages.po
  awx/locale/translations/fr/django.po
  awx/locale/translations/fr/messages.po
  awx/locale/translations/ja/django.po
  awx/locale/translations/ja/messages.po
  awx/locale/translations/ko/django.po
  awx/locale/translations/ko/messages.po
  awx/locale/translations/nl/django.po
  awx/locale/translations/nl/messages.po
  awx/locale/translations/zh/django.po
  awx/locale/translations/zh/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/ko/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/translations/es/django.po
  awx/ui/src/locales/translations/es/messages.po
  awx/ui/src/locales/translations/fr/django.po
  awx/ui/src/locales/translations/fr/messages.po
  awx/ui/src/locales/translations/ja/django.po
  awx/ui/src/locales/translations/ja/messages.po
  awx/ui/src/locales/translations/ko/django.po
  awx/ui/src/locales/translations/ko/messages.po
  awx/ui/src/locales/translations/nl/django.po
  awx/ui/src/locales/translations/nl/messages.po
  awx/ui/src/locales/translations/zh/django.po
  awx/ui/src/locales/translations/zh/messages.po
  awx/ui/src/locales/zh/messages.po
Labels: component:api, component:ui

#12036 Install sosreport controller plugin into proper path
  tools/sosreport/controller.py
Labels: type:bug, component:api, community

#13250 Fix a problem with migration main/0164
  awx/main/migrations/0164_remove_inventorysource_update_on_project_update.py
Labels: component:api
