Repository ansible/awx, pull requests merged in 2023-05, with the labels that each got.

#13930 In collection, allow roles to be added to multiple teams and users
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/plugins/modules/role.py
  awx_collection/tests/integration/targets/role/tasks/main.yml
Labels: component:awx_collection

#13941 Fix for incorrect value for 'Run on' field in frequency details
  awx/ui/src/components/Schedule/ScheduleDetail/FrequencyDetails.js
Labels: component:ui

#13955 Add missing comma in host_status_counts list
  awx/main/models/notifications.py
Labels: component:api

#13957 Fix bug with parent_key filtering
  awx/api/generics.py
Labels: component:api

#13890 Make `state: exists` universal in collection
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/plugins/modules/application.py
  awx_collection/plugins/modules/credential.py
  awx_collection/plugins/modules/credential_input_source.py
  awx_collection/plugins/modules/credential_type.py
  awx_collection/plugins/modules/execution_environment.py
  awx_collection/plugins/modules/group.py
  awx_collection/plugins/modules/host.py
  awx_collection/plugins/modules/instance_group.py
  awx_collection/plugins/modules/inventory.py
  awx_collection/plugins/modules/inventory_source.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/plugins/modules/label.py
  awx_collection/plugins/modules/notification_template.py
  awx_collection/plugins/modules/organization.py
  awx_collection/plugins/modules/project.py
  awx_collection/plugins/modules/schedule.py
  awx_collection/plugins/modules/team.py
  awx_collection/plugins/modules/user.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/plugins/modules/workflow_job_template_node.py
  awx_collection/tests/integration/targets/application/tasks/main.yml
  awx_collection/tests/integration/targets/credential/tasks/main.yml
  awx_collection/tests/integration/targets/credential_input_source/tasks/main.yml
  awx_collection/tests/integration/targets/credential_type/tasks/main.yml
  awx_collection/tests/integration/targets/execution_environment/tasks/main.yml
  awx_collection/tests/integration/targets/group/tasks/main.yml
  awx_collection/tests/integration/targets/host/tasks/main.yml
  awx_collection/tests/integration/targets/instance_group/tasks/main.yml
  awx_collection/tests/integration/targets/inventory/tasks/main.yml
  awx_collection/tests/integration/targets/inventory_source/tasks/main.yml
  awx_collection/tests/integration/targets/job_template/tasks/main.yml
  awx_collection/tests/integration/targets/label/tasks/main.yml
  awx_collection/tests/integration/targets/notification_template/tasks/main.yml
  awx_collection/tests/integration/targets/organization/tasks/main.yml
  awx_collection/tests/integration/targets/project/tasks/main.yml
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
  awx_collection/tests/integration/targets/team/tasks/main.yml
  awx_collection/tests/integration/targets/user/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
Labels: component:awx_collection

#13963 Minor typo fix in docs
  docs/overview.md
Labels: component:docs

#13965 [wsrelay] Switch from psycopg 3 to asyncpg
  awx/main/wsrelay.py
  licenses/asyncpg.txt
  licenses/psycopg-3.1.4.tar.gz
  licenses/psycopg.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api

#13972 Fix incorrect parent_key ref from label to job
  awx/api/views/__init__.py
  awx/main/tests/functional/api/test_job.py
Labels: component:api

#13976 Change the job_wait integration test
  awx_collection/tests/integration/targets/job_wait/tasks/main.yml
Labels: component:awx_collection

#13977 Skip constructed_inventory endpoint in awxkit import
  awxkit/awxkit/api/pages/api.py
Labels: component:cli

#13991 [wsrelay] Handle heartbeet shutdown and redis drop
  awx/main/wsrelay.py
Labels: component:api

#14004 Skip constructed_inventory in a more correct loop
  awxkit/awxkit/api/pages/api.py
Labels: component:cli

#14010 Materialize label page after getting 204 code
  awxkit/awxkit/api/pages/api.py
Labels: component:cli

#13961 Upgrade to Django 4.2 LTS
  awx/main/migrations/0113_v370_event_bigint.py
  awx/main/migrations/0183_pre_django_upgrade.py
  awx/main/migrations/0184_django_indexes.py
  awx/main/migrations/_OrgAdmin_to_use_ig.py
  awx/main/models/credential/__init__.py
  awx/main/models/events.py
  awx/main/models/rbac.py
  awx/main/tests/functional/models/test_inventory.py
  awx/main/tests/unit/models/test_events.py
  awx/settings/defaults.py
  licenses/deprecated.txt
  licenses/jwcrypto-1.4.2.tar.gz
  licenses/jwcrypto.txt
  licenses/wrapt.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api

#13989 Add subsystem metrics for the dispatcher
  awx/main/analytics/subsystem_metrics.py
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
  tools/grafana/dashboards/demo_dashboard.json
Labels: component:api

#13898 Remove unused settings and associated code
  awx/main/tasks/jobs.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/production.py
Labels: component:api

#13992 [dev docs] Re-document websockets infrastructure
  docs/img/websockets-new.png
  docs/img/websockets-old.png
  docs/websockets.md
Labels: component:docs

#14031 Change logging setting for task analytic scheduler
  awx/settings/defaults.py
Labels: component:api

#13852 Adding capability of pretty error pages
  awx/static/RedHatDisplay-Medium.ttf
  awx/static/RedHatDisplay-Regular.ttf
  awx/static/awx-spud-reading.svg
  awx/static/custom_404.html
  awx/static/custom_502.html
  awx/static/custom_504.html
  awx/static/custom_error.css
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/templates/nginx.conf.j2
Labels: component:api

#14041 Rename heartbeet daemon to ws_heartbeat
  Makefile
  awx/main/management/commands/run_ws_heartbeat.py
  awx/main/wsrelay.py
  awx/settings/defaults.py
  docs/websockets.md
  tools/ansible/roles/dockerfile/templates/supervisor_web.conf.j2
  tools/docker-compose/supervisor.conf
Labels: component:api, component:docs

#13524 Related #13336 - DNS resolution is preventing awx_collection to work with http[s]_proxy
  awx_collection/plugins/module_utils/controller_api.py
Labels: component:awx_collection, community

#13966 Prevent manual peering of control plane nodes to hop node
  awx/api/serializers.py
Labels: component:api

#13982 Add instance_group to bulk api
  awx/api/serializers.py
Labels: component:api

#14063 Use PATCH request when updating wf nodes
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Visualizer.test.js
Labels: component:ui

#13994 Adds managed_by_policy checkbox to instances form. Adds warnings when associating or disassociating instances from instance groups.
  awx/ui/src/components/AssociateModal/AssociateModal.js
  awx/ui/src/components/DisassociateButton/DisassociateButton.js
  awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
  awx/ui/src/screens/InstanceGroup/Instances/InstanceList.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.test.js
Labels: component:ui

#13959 Adds missing rel="noopener noreferrer" to each link element with target="_blank"
  awx/ui/.eslintrc.json
  awx/ui/src/components/AppContainer/PageHeaderToolbar.js
  awx/ui/src/components/Search/AdvancedSearch.js
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Inventory/shared/ConstructedInventoryHint.js
  awx/ui/src/screens/NotificationTemplate/shared/Notifications.helptext.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionDetail/SubscriptionDetail.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/AnalyticsStep.js
  awx/ui/src/screens/Setting/Subscription/SubscriptionEdit/SubscriptionStep.js
  awx/ui/src/screens/Template/Survey/SurveyQuestionForm.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerToolbar.js
  awx/ui/src/screens/Template/shared/JobTemplate.helptext.js
  awx/ui/src/screens/TopologyView/Tooltip.js
Labels: component:ui

#12882 Fix ovirt source
  awx/main/models/inventory.py
Labels: component:api, community, community pull request
