Repository ansible/awx, pull requests merged in 2023-09, with the labels that each got.

#14413 Add readthedocs configuration
  .gitignore
  .readthedocs.yaml
  .yamllint
Labels: community

#14409 Added relnotes for 23.0.0
  docs/docsite/rst/release_notes/relnotes.rst
Labels: component:docs, community

#14397 Enable collection integration tests on GHA
  .github/actions/run_awx_devel/action.yml
  .github/actions/upload_awx_devel_logs/action.yml
  .github/workflows/ci.yml
  .github/workflows/e2e_test.yml
  Makefile
  awx_collection/tests/integration/targets/ad_hoc_command_cancel/tasks/main.yml
  awx_collection/tests/integration/targets/demo_data/tasks/main.yml
  awx_collection/tests/integration/targets/group/tasks/main.yml
  awx_collection/tests/integration/targets/job_cancel/tasks/main.yml
  awx_collection/tests/integration/targets/project_update/tasks/main.yml
  awx_collection/tests/integration/targets/user/tasks/main.yml
Labels: component:awx_collection

#14416 Update missing inventory error message
  awx/api/serializers.py
Labels: component:api

#14404 Fix collection metadata license to match intent
  awx_collection/tools/roles/template_galaxy/templates/galaxy.yml.j2
Labels: component:awx_collection

#14385 Avoid activity stream entries for instance going offline
  awx/main/models/ha.py
Labels: component:api

#14370 bump babel dependencies
  awx/ui/package-lock.json
  awx/ui/package.json
Labels: component:ui, dependencies

#14423 rebuild package-lock
  awx/ui/package-lock.json
Labels: component:ui

#14386 Fixes #14377 Ensure Conjur Enterprise JWT token is Base64-encoded
  awx/main/credential_plugins/conjur.py
Labels: component:api, community

#14407 Prevent the user from launching multiple jobs by rapidly clicking on buttons
  awx/ui/src/components/LaunchButton/LaunchButton.js
Labels: component:ui

#14435 Allow saving github creds in user folder
  docs/release_process.md
  tools/scripts/get_next_release.py
Labels: component:docs

#14442 Add link to script for publishing operator on OperatorHub
  docs/release_process.md
Labels: component:docs

#14429 userguide/execution_environments.rst: replace building paragraphs with ref to Get started EE guide
  docs/docsite/rst/userguide/execution_environments.rst
Labels: component:docs, community

#14454 Simplify docs string base generation
  awx/ui/src/util/getDocsBaseUrl.js
  awx/ui/src/util/getDocsBaseUrl.test.js
Labels: component:ui

#14471 Added release notes for version 23.1.0
  docs/docsite/rst/release_notes/relnotes.rst
Labels: component:docs

#14433 AAP-15927 Use ATTACH PARTITION to avoid exclusive table lock for events
  awx/main/utils/common.py
Labels: component:api

#14478 Removed references of IRC and fixed formatting in "Work Items" section.
  docs/docsite/rst/contributor/intro.rst
  docs/docsite/rst/contributor/report_issues.rst
  docs/docsite/rst/contributor/work_items.rst
Labels: component:docs

#14480 Add null value handling in create_partition
  awx/main/utils/common.py
Labels: component:api

#14459 Get rid of names_digest hack no longer needed
  awx/__init__.py
  requirements/README.md
Labels: component:api

#14460 Update django version to address CVE-2023-41164
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies

#14035 Debug log for scheduler commit duration
  awx/main/scheduler/task_manager.py
Labels: component:api

#14403 Add subscription usage page
  awx/ui/src/api/index.js
  awx/ui/src/api/models/SubscriptionUsage.js
  awx/ui/src/routeConfig.js
  awx/ui/src/routeConfig.test.js
  awx/ui/src/screens/SubscriptionUsage/ChartComponents/UsageChart.js
  awx/ui/src/screens/SubscriptionUsage/ChartComponents/UsageChartTooltip.js
  awx/ui/src/screens/SubscriptionUsage/SubscriptionUsage.js
  awx/ui/src/screens/SubscriptionUsage/SubscriptionUsageChart.js
Labels: component:ui

#14485 Simplified release notes for AWX
  docs/docsite/rst/release_notes/relnotes.rst
Labels: component:docs

#14482 Add a section for postgres max_connections value
  docs/docsite/rst/administration/performance.rst
Labels: component:docs

#14489 fix: make type conversions work correctly (related #14487)
  awx_collection/plugins/modules/settings.py
  awx_collection/tests/integration/targets/settings/tasks/main.yml
Labels: component:awx_collection, community
