Repository ansible/awx, pull requests merged in 2023-12, with the labels that each got.

#14702 Fix the bulk Job Launch Integration test in awx collection
  awx_collection/tests/integration/targets/bulk_job_launch/tasks/main.yml
  awx_collection/tests/integration/targets/job_list/tasks/main.yml
  awx_collection/tests/integration/targets/job_wait/tasks/main.yml
  awx_collection/tests/integration/targets/lookup_api_plugin/tasks/main.yml
  awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml
  awx_collection/tests/integration/targets/schedule/tasks/main.yml
  awx_collection/tests/integration/targets/schedule_rrule/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_launch/tasks/main.yml
Labels: component:awx_collection, community

#14534 Add TLS certificate auth for HashiCorp Vault
  Makefile
  awx/main/credential_plugins/hashivault.py
  awx/main/tests/functional/test_credential_plugins.py
  docs/docsite/rst/userguide/credential_plugins.rst
  tools/docker-compose/ansible/plumb_vault.yml
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/vault_tls.yml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
  tools/docker-compose/ansible/roles/vault/defaults/main.yml
  tools/docker-compose/ansible/roles/vault/tasks/initialize.yml
  tools/docker-compose/ansible/roles/vault/tasks/plumb.yml
  tools/docker-compose/ansible/roles/vault/tasks/set_vault_addr.yml
  tools/docker-compose/ansible/roles/vault/tasks/unseal.yml
Labels: component:api, component:docs, community

#14666 remove unnecessary required flags for saml backend
  awx/sso/conf.py
Labels: component:api, community

#14705 Add django-ansible-base
  awx/main/models/mixins.py
  awx/main/models/rbac.py
  awx/settings/defaults.py
  licenses/django-ansible-base.txt
  licenses/django-filter.txt
  licenses/drf-spectacular.txt
  licenses/inflection.txt
  licenses/tabulate.txt
  licenses/uritemplate.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
Labels: component:api, dependencies

#14714 Remove incorrectly formatted line from requirements.txt
  requirements/requirements.txt
Labels: dependencies

#14715 Fix undefined error in settings/logging/edit form
  awx/ui/src/screens/Setting/Logging/LoggingEdit/LoggingEdit.js
Labels: component:ui

#14716 Update setuptools-scm
  Makefile
  requirements/requirements.txt
Labels: dependencies

#14462 Adding hosts bulk deletion feature
  awx/api/serializers.py
  awx/api/templates/api/bulk_host_delete_view.md
  awx/api/urls/urls.py
  awx/api/views/bulk.py
  awx/main/conf.py
  awx/main/tests/functional/test_bulk.py
  awx/settings/defaults.py
  awx_collection/meta/runtime.yml
  awx_collection/plugins/modules/bulk_host_delete.py
  awx_collection/test/awx/test_bulk.py
  awx_collection/test/awx/test_completeness.py
  awx_collection/tests/integration/targets/bulk_host_delete/tasks/main.yml
  awxkit/awxkit/cli/custom.py
  awxkit/awxkit/cli/options.py
  docs/bulk_api.md
Labels: component:api, component:docs, component:cli, component:awx_collection, community

#14710 Simplify RBAC get_roles_on_resource method
  awx/api/serializers.py
  awx/main/models/rbac.py
  docs/rbac.md
Labels: component:api, component:docs

#14709 Narrow the actor types accepted for RBAC evaluations
  awx/api/views/__init__.py
  awx/main/models/mixins.py
  awx/main/models/rbac.py
  awx/main/tests/functional/test_rbac_core.py
  awx/main/tests/functional/test_rbac_team.py
Labels: component:api

#14726 Use filtering/sorting from django-ansible-base
  awx/api/filters.py
  awx/api/generics.py
  awx/api/serializers.py
  awx/conf/models.py
  awx/main/access.py
  awx/main/models/__init__.py
  awx/main/models/ad_hoc_commands.py
  awx/main/models/base.py
  awx/main/models/ha.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/mixins.py
  awx/main/models/notifications.py
  awx/main/models/unified_jobs.py
  awx/main/models/workflow.py
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/api/test_survey_spec.py
  awx/main/tests/unit/api/test_filters.py
  awx/main/tests/unit/utils/test_common.py
  awx/main/tests/unit/utils/test_filters.py
  awx/main/utils/common.py
  awx/main/utils/db.py
  awx/main/utils/filters.py
  awx/settings/defaults.py
Labels: component:api

#14656 Fix twilio_backend.py to send SMS to multiple destinations.
  awx/main/notifications/twilio_backend.py
Labels: component:api, community

#14736 Persist schedule prompt on launch fields when editing
  awx/ui/src/components/Schedule/shared/ScheduleForm.js
  awx/ui/src/components/Schedule/shared/mergeArraysByCredentialType.js
Labels: component:ui
