Repository ansible/awx, pull requests merged in 2023-07, with the labels that each got.

#14201 Rename/relocate receptor crt in install bundle
  awx/api/templates/instance_install_bundle/group_vars/all.yml
Labels: component:api, community

#14081 Add combined roles/collection requirements on project sync
  awx/playbooks/project_update.yml
Labels: component:api

#14062 Added CSRF Origin in settings
  awx/conf/apps.py
  awx/main/conf.py
  awx/settings/defaults.py
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.js
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemDetail/MiscSystemDetail.test.js
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemEdit/MiscSystemEdit.js
  awx/ui/src/screens/Setting/MiscSystem/MiscSystemEdit/MiscSystemEdit.test.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
Labels: component:api, component:ui

#14172 Fix DELETE 500 KeyError due to eventless model events
  awx/main/models/workflow.py
Labels: component:api

#14206 Schedules form - pass time prop as string.
  awx/ui/src/components/Schedule/shared/DateTimePicker.js
  awx/ui/src/components/Schedule/shared/DateTimePicker.test.js
  awx/ui/src/components/Schedule/shared/ScheduleForm.test.js
Labels: component:ui

#14098 Add settings.RECEPTOR_LOG_LEVEL, update work signing key path
  awx/main/tasks/receptor.py
  awx/settings/defaults.py
Labels: component:api

#14196 [hop node] migration peers_from_control_nodes only in k8s
  awx/main/migrations/0186_hop_nodes.py
Labels: component:api

#14221 Refined release documentation
  docs/release_process.md
  tools/scripts/get_next_release.py
Labels: component:docs

#14222 Restore pre-upgrade pg_notify notifcation behavior
  awx/main/dispatch/__init__.py
Labels: component:api

#13998 add organization column notification template list
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateList.test.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.js
  awx/ui/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
Labels: component:ui, community, community pull request

#13999 HostMetricSummaryMonthly command + scheduled task
  awx/api/urls/urls.py
  awx/api/views/__init__.py
  awx/api/views/root.py
  awx/main/conf.py
  awx/main/management/commands/cleanup_host_metrics.py
  awx/main/management/commands/host_metric_summary_monthly.py
  awx/main/models/inventory.py
  awx/main/tasks/__init__.py
  awx/main/tasks/host_metrics.py
  awx/main/tasks/system.py
  awx/main/tests/factories/fixtures.py
  awx/main/tests/functional/commands/test_host_metric_summary_monthly.py
  awx/settings/defaults.py
Labels: component:api, community

#14226 [hop node] fix failing ci checks on feature_hop-node branch
  awx_collection/test/awx/test_instance.py
Labels: component:awx_collection

#14215 [hop node] documentation update in execution_nodes for hop nodes
  docs/execution_nodes.md
Labels: component:docs

#13626 Changing how associations work in awx collection
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/test/awx/test_job_template.py
  awx_collection/test/awx/test_organization.py
Labels: component:awx_collection

#14249 Make dispatcher timeout use SIGUSR1, not SIGTERM
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
  awx/main/scheduler/task_manager.py
Labels: component:api

#14262 Require pyyaml >= 6.0.1
  requirements/requirements.in
  requirements/requirements.txt
Labels: community

#14269 Fix collection module docs for names, IDs, and named URLs
  awx_collection/plugins/modules/ad_hoc_command.py
  awx_collection/plugins/modules/application.py
  awx_collection/plugins/modules/bulk_host_create.py
  awx_collection/plugins/modules/bulk_job_launch.py
  awx_collection/plugins/modules/credential.py
  awx_collection/plugins/modules/credential_input_source.py
  awx_collection/plugins/modules/execution_environment.py
  awx_collection/plugins/modules/export.py
  awx_collection/plugins/modules/group.py
  awx_collection/plugins/modules/host.py
  awx_collection/plugins/modules/instance_group.py
  awx_collection/plugins/modules/inventory.py
  awx_collection/plugins/modules/inventory_source.py
  awx_collection/plugins/modules/inventory_source_update.py
  awx_collection/plugins/modules/job_launch.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/plugins/modules/label.py
  awx_collection/plugins/modules/notification_template.py
  awx_collection/plugins/modules/organization.py
  awx_collection/plugins/modules/project.py
  awx_collection/plugins/modules/project_update.py
  awx_collection/plugins/modules/role.py
  awx_collection/plugins/modules/schedule.py
  awx_collection/plugins/modules/team.py
  awx_collection/plugins/modules/token.py
  awx_collection/plugins/modules/user.py
  awx_collection/plugins/modules/workflow_job_template.py
  awx_collection/plugins/modules/workflow_job_template_node.py
  awx_collection/plugins/modules/workflow_launch.py
Labels: component:awx_collection, community

#14233 Remove host update code which can be non performant
  awx/main/tasks/system.py
Labels: component:api

#13564 Updating release process doc for operator hub instructions
  docs/release_process.md
Labels: component:docs

#13802 Add missing trigger for failed-to-start nodes
  awx/main/scheduler/task_manager.py
Labels: component:api

#14258 Return back chdir to project sync to support project-local roles/coll…
  awx/playbooks/project_update.yml
Labels: component:api, community

#14263 docs/execution_environments.md: add a link to EE getting started guide
  docs/execution_environments.md
Labels: component:docs, community

#14232 Explicitly turn off autocomplete for API login form
  awx/templates/rest_framework/login.html
Labels: component:api

#14287 fixes docs link for controller versions >= 4.3
  awx/ui/src/util/getDocsBaseUrl.js
Labels: component:ui

#14135 Only show the product version header when the requester is authenticated
  awx/api/generics.py
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/test/awx/test_module_utils.py
Labels: component:api, component:awx_collection

#14205 Added support to collection for named urls
  awx_collection/README.md
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/tests/integration/targets/module_utils/tasks/main.yml
  awx_collection/tests/integration/targets/module_utils/tasks/test_named_reference.yml
  awx_collection/tools/roles/template_galaxy/templates/README.md.j2
Labels: component:awx_collection

#13533 Simplifications for DependencyManager
  awx/main/scheduler/task_manager.py
  awx/main/tests/functional/task_management/test_scheduler.py
  docs/task_manager_system.md
Labels: component:api, component:docs

#14080 Adds autoComplete attribute to forms that were missing it
  awx/ui/src/components/AdHocCommands/AdHocCredentialStep.js
  awx/ui/src/components/AdHocCommands/AdHocDetailsStep.js
  awx/ui/src/components/AdHocCommands/AdHocExecutionEnvironmentStep.js
  awx/ui/src/screens/Credential/shared/CredentialPlugins/CredentialPluginPrompt/MetadataStep.js
  awx/ui/src/screens/Credential/shared/ExternalTestModal.js
  awx/ui/src/screens/Inventory/shared/ConstructedInventoryHint.js
  awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/NodeTypeStep.js
Labels: component:ui

#14241 Drop unused django-taggit dependency
  awx/main/migrations/0001_initial.py
  awx/main/migrations/0002_squashed_v300_release.py
  awx/main/migrations/0006_v320_release.py
  awx/main/migrations/0067_v350_credential_plugins.py
  awx/main/migrations/0124_execution_environments.py
  awx/main/migrations/0186_drop_django_taggit.py
  awx/main/models/base.py
  awx/main/registrar.py
  awx/settings/defaults.py
  licenses/django-taggit.txt
  requirements/requirements.in
  requirements/requirements.txt
  tools/docker-compose/README.md
Labels: component:api, dependencies

#14300 optional listener port UI
  awx/api/serializers.py
  awx/main/models/ha.py
  awx/ui/src/screens/Instances/InstanceDetail/InstanceDetail.js
  awx/ui/src/screens/Instances/Shared/InstanceForm.js
Labels: component:api, component:ui
