Repository ansible/awx, pull requests merged in 2023-08, with the labels that each got.

#14302 fix linting
  awx/main/access.py
  awx/main/utils/handlers.py
  awx/settings/development.py
Labels: component:api

#14301 bump python-daemon package
  licenses/future.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies

#14237 Fix trial status and host limit with sub
  awx/main/access.py
  awx/main/utils/licensing.py
Labels: component:api, community

#13479 Update example service-account.yml for container group in documentation
  docs/container_groups/service-account.yml
Labels: component:docs, community

#14290 Fix rbac around credential access add button
  awx/ui/src/components/ResourceAccessList/ResourceAccessList.js
  awx/ui/src/components/ResourceAccessList/ResourceAccessList.test.js
Labels: component:ui

#14283 Wait for new label IDs before setting label prompt values.
  awx/ui/src/components/LaunchPrompt/LaunchPrompt.js
Labels: component:ui

#14157 Add Request time out option for collection
  awx_collection/plugins/doc_fragments/auth.py
  awx_collection/plugins/doc_fragments/auth_plugin.py
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/tests/integration/targets/project/tasks/main.yml
Labels: component:awx_collection, community

#14313 AAP-14538 Only process ansible_facts for successful jobs
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tasks/receptor.py
Labels: component:api

#14296 fix broken link to upgrade docs. related #11313
  DATA_MIGRATION.md
Labels: community

#14326 Allow importing licenses with a missing "usage" attribute
  awx/main/utils/licensing.py
Labels: component:api

#14318 Remove extra quote from Skipped task status string
  awx/ui/src/components/StatusLabel/StatusLabel.js
  awx/ui/src/locales/en/messages.po
  awx/ui/src/locales/es/messages.po
  awx/ui/src/locales/fr/messages.po
  awx/ui/src/locales/ja/messages.po
  awx/ui/src/locales/ko/messages.po
  awx/ui/src/locales/nl/messages.po
  awx/ui/src/locales/zh/messages.po
  awx/ui/src/locales/zu/messages.po
Labels: component:ui, needs_triage, community

#14067 Integrate scheduler into dispatcher main loop
  awx/main/dispatch/__init__.py
  awx/main/dispatch/control.py
  awx/main/dispatch/periodic.py
  awx/main/dispatch/publish.py
  awx/main/dispatch/worker/base.py
  awx/main/management/commands/run_dispatcher.py
  awx/main/tests/functional/test_dispatch.py
  licenses/schedule.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies

#14002 HostMetricSummaryMonthly: Analytics export
  awx/main/analytics/collectors.py
Labels: component:api

#14325 Add a retry to update host facts on deadlocks
  awx/main/tasks/facts.py
  awx/main/tests/functional/test_jobs.py
Labels: component:api

#14336 Fix programming error in facts retry merge
  awx/main/tasks/facts.py
Labels: component:api

#14335 make the default JOB_EVENT_BUFFER_SECONDS 1 seconds
  awx/settings/defaults.py
Labels: component:api, community

#14342 Revert "Improve performance for awx cli export (#13182)"
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/api/pages/page.py
  awxkit/awxkit/api/utils.py
Labels: component:cli

#14347 Fixed typos
  awx/main/dispatch/worker/base.py
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/settings/defaults.py
Labels: component:api, community

#13611 Schedule rruleset fix related #13446
  awx_collection/plugins/lookup/schedule_rruleset.py
  awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml
Labels: component:awx_collection, community

#14207 Update python-tss-sdk dependency
  awx/main/credential_plugins/tss.py
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies, community

#14349 Fix UI_NEXT build process broken by https://github.com/ansible/ansible-ui/pull/766
  awx/ui_next/Makefile
Labels: component:api

#14350 Fixed task and web docs
  docs/development/kind.md
Labels: component:docs, community

#14357 Fix ui-next build step file path issue
  awx/ui_next/Makefile
Labels: component:api

#14343 Fix edit constructed inventory hanging loading state
  awx/ui/src/api/models/ConstructedInventories.js
  awx/ui/src/api/models/ConstructedInventories.test.js
  awx/ui/src/screens/Inventory/ConstructedInventoryAdd/ConstructedInventoryAdd.js
  awx/ui/src/screens/Inventory/ConstructedInventoryAdd/ConstructedInventoryAdd.test.js
  awx/ui/src/screens/Inventory/ConstructedInventoryEdit/ConstructedInventoryEdit.js
  awx/ui/src/screens/Inventory/ConstructedInventoryEdit/ConstructedInventoryEdit.test.js
  awx/ui/src/screens/Inventory/shared/ConstructedInventoryForm.js
  awx/ui/src/screens/Inventory/shared/ConstructedInventoryForm.test.js
Labels: type:bug, component:ui

#14358 Update cryptography for CVE-2023-38325
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies

#14271 AAP-10891 Apply AWX_TASK_ENV when performing credential plugin lookups
  awx/main/models/credential/__init__.py
Labels: component:api

#14363 Enforce mutually exclusive options in credential module of the collection
  awx_collection/plugins/modules/credential.py
Labels: component:awx_collection, community, needs_developer

#14351 Clarify that the license module requires fetching subs prior
  awx_collection/plugins/modules/license.py
Labels: component:awx_collection, community

#14344 Fix default redis url to pass check in redis-py>4.4
  awx/settings/defaults.py
Labels: component:api, community

#14382 Fix typo in description of scm_update_on_launch
  awx_collection/plugins/modules/project.py
Labels: component:awx_collection, community

#14388 Fix CVE-2023-40267
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies

#14255 HostMetrics: Hard auto-cleanup
  awx/main/management/commands/cleanup_host_metrics.py
  awx/main/models/inventory.py
  awx/main/tasks/helpers.py
  awx/main/tasks/host_metrics.py
  awx/main/tasks/system.py
  awx/main/tests/functional/commands/test_cleanup_host_metrics.py
  awx/settings/defaults.py
Labels: component:api

#14225 [DOCS] tools/docker-compose/README.md: add way to solve postgresql issue
  tools/docker-compose/README.md
Labels: community

#14372 Fix undefined property error when task is of type yum/debug and was s…
  awx/ui/src/screens/Job/JobOutput/HostEventModal.js
Labels: component:ui, community

#13482 Consume `job_explanation` from runner, fix error reporting error
  awx/main/tasks/callback.py
  awx/main/tasks/receptor.py
Labels: component:api

#14285 Allow saml_admin_attr to work in conjunction with SAML Org Map
  awx/sso/saml_pipeline.py
  awx/sso/tests/functional/test_saml_pipeline.py
Labels: component:api, component:authentication

#14396 Remove extra scheduler state save that does nothing
  awx/main/tasks/system.py
Labels: component:api
