Repository ansible/awx, pull requests merged in 2023-06, with the labels that each got.

#14044 Manually run subquery for parent event updates
  awx/main/models/events.py
Labels: component:api

#14066 Apply only very conservative database connection reduction changes
  awx/main/dispatch/worker/base.py
  awx/main/management/commands/run_cache_clear.py
  awx/main/management/commands/run_rsyslog_configurer.py
  awx/main/management/commands/run_ws_heartbeat.py
Labels: component:api

#12927 Adds RTL tests to new component, and to Instances List
  awx/ui/.eslintrc.json
  awx/ui/package-lock.json
  awx/ui/package.json
  awx/ui/src/screens/Instances/InstanceList/InstanceList.test.js
  awx/ui/src/screens/Instances/InstanceList/InstanceListItem.js
  licenses/ui/aria-query.txt
  licenses/ui/dom-accessibility-api.txt
  licenses/ui/lz-string.txt
  licenses/ui/pretty-format.txt
  licenses/ui/testing-library-dom.txt
  licenses/ui/types-aria-query.txt
Labels: component:ui, dependencies

#14005 [rsyslog] Enable disk-assisted queuing on output
  awx/main/conf.py
  awx/main/tests/unit/api/test_logger.py
  awx/main/utils/external_logging.py
  awx/settings/defaults.py
  awx/ui/src/screens/Setting/Logging/Logging.test.js
  awx/ui/src/screens/Setting/Logging/LoggingEdit/LoggingEdit.test.js
  awx/ui/src/screens/Setting/shared/data.allSettingOptions.json
  awx/ui/src/screens/Setting/shared/data.allSettings.json
  awx/ui/src/screens/Setting/shared/data.logSettings.json
Labels: component:api, component:ui

#13197 Fix /api/swagger endpoint (available only in development mode)
  awx/api/swagger.py
  awx/api/urls/urls.py
  awx/api/views/root.py
  awx/main/tests/docs/test_swagger_generation.py
  awx/settings/development.py
  requirements/requirements_dev.txt
Labels: component:api

#14020 Update Mesh.js to allow for running AWX at non-root path (URL prefixing)
  awx/ui/src/api/models/JobEvents.js
  awx/ui/src/api/models/Mesh.js
  awx/ui/src/api/models/Root.js
  awx/ui/src/api/models/Root.test.js
Labels: component:ui, community, community pull request

#14076 Add management command to precreate partitioned tables
  awx/main/management/commands/cleanup_jobs.py
  awx/main/management/commands/precreate_partitions.py
  awx/main/utils/common.py
Labels: component:api

#14082 Two silly internal cleanups
  awx/main/management/commands/run_dispatcher.py
  awx/main/management/commands/run_ws_heartbeat.py
Labels: component:api

#14089 Remove random UUIDs from swagger json
  awx/main/tests/docs/test_swagger_generation.py
Labels: component:api

#13913 Fix : awx.awx.group preserve hosts fails when there are no hosts
  awx_collection/plugins/modules/group.py
  awx_collection/tests/integration/targets/group/tasks/main.yml
Labels: component:awx_collection, community

#13985 Awx.credential plugin.tss
  awx/main/credential_plugins/tss.py
Labels: component:api, community

#14091 Rename/relocate receptor cert and keys
  awx/api/templates/instance_install_bundle/group_vars/all.yml
  awx/api/views/instance_install_bundle.py
  awx/main/tasks/receptor.py
Labels: component:api

#14112 Remove whitespace artifacts from black with f-strings
  awx/main/migrations/0144_event_partitions.py
  awx/main/tasks/jobs.py
Labels: component:api

#14086 Update Patternfly and related deps.
  awx/ui/package-lock.json
  awx/ui/package.json
  licenses/ui/aria-query.txt
  licenses/ui/dom-accessibility-api.txt
  licenses/ui/lz-string.txt
  licenses/ui/pretty-format.txt
  licenses/ui/testing-library-dom.txt
  licenses/ui/types-aria-query.txt
Labels: component:ui, dependencies

#14056 [hop_node] Validate listener_port is defined for peers
  awx/api/serializers.py
  awx/api/templates/instance_install_bundle/group_vars/all.yml
  awx/main/management/commands/host_metric.py
  awx/main/migrations/0185_hop_nodes.py
  awx/main/models/ha.py
Labels: component:api

#14092 Remove install bundle download restriction
  awx/api/serializers.py
Labels: component:api

#14119 bugfix collection role module target_teams and instance_groups options
  awx_collection/plugins/modules/role.py
  awx_collection/tests/integration/targets/role/tasks/main.yml
Labels: component:awx_collection

#14046 Check for a list of all option instead of string
  awx_collection/plugins/modules/export.py
Labels: component:awx_collection, community

#13796 Removed automatic failure of job template launch when last project update is failed and update on launch is enabled
  awx/main/models/projects.py
  awx/main/tests/functional/test_projects.py
Labels: component:api

#14079 Add new ANSIBLE_COLLECTIONS_PATH in preparation for deprecation of plural version
  awx/main/tasks/jobs.py
Labels: component:api

#14140 Fixed typo in integration test for group module
  awx_collection/tests/integration/targets/group/tasks/main.yml
Labels: component:awx_collection, community

#14151 Rename work signing private key filename
  awx/main/tasks/receptor.py
Labels: component:api

#13182 Improve performance for awx cli export
  awxkit/awxkit/api/pages/api.py
  awxkit/awxkit/api/pages/page.py
  awxkit/awxkit/api/utils.py
Labels: component:cli, community, community pull request

#14103 Fix for Save on the Jobs settings page not responding
  awx/ui/src/screens/Setting/Jobs/JobsEdit/JobsEdit.js
Labels: component:ui, community

#13928 In collection, give changed status in workflow_job_template when destroying nodes
  awx_collection/plugins/modules/workflow_job_template.py
Labels: component:awx_collection, community

#14146 Add instance_groups on resource_list_param_keys in awx_collection
  awx_collection/plugins/modules/role.py
Labels: component:awx_collection, community

#14156 Rename work signing private key filename
  awx/main/tasks/receptor.py
Labels: component:api

#14068 Add --interval to launch monitor command
  awxkit/awxkit/cli/custom.py
  awxkit/awxkit/cli/stdout.py
Labels: component:cli

#14105 Using execution_environment option in ad_hoc_command module
  awx_collection/plugins/modules/ad_hoc_command.py
  awx_collection/tests/integration/targets/ad_hoc_command/tasks/main.yml
Labels: component:awx_collection, community

#14160 Tooling for running collection tests locally ad hoc
  awx_collection/tools/README.md
  awx_collection/tools/integration_testing.yml
Labels: component:awx_collection

#14097 [wsrelay] Give connection tasks time to clean up
  awx/main/wsrelay.py
Labels: component:api

#14143 Remove reference to unmaintained runner image
  awxkit/awxkit/api/pages/execution_environments.py
Labels: component:cli

#14106 Add example for ad_hoc_command module
  awx_collection/plugins/modules/ad_hoc_command.py
Labels: component:awx_collection, community

#14161 Add hashivault option as docker-compose optional container
  Makefile
  awx/main/credential_plugins/hashivault.py
  tools/docker-compose/README.md
  tools/docker-compose/ansible/roles/sources/tasks/main.yml
  tools/docker-compose/ansible/roles/sources/tasks/vault.yaml
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: component:api

#14166 Use the proper queryset to filter project update events
  awx/api/serializers.py
Labels: component:api

#14182 Fixed bug where a weekly rrule string without a BYDAY would result in the UI throwing a TypeError
  awx/ui/src/components/Schedule/ScheduleDetail/FrequencyDetails.js
Labels: component:ui

#14181 add the bulk api swagger topic for API reference docs
  awx/api/views/bulk.py
Labels: component:api, community

#14189 Fix spelling errors in readme of awx_collection/tools
  awx_collection/tools/README.md
Labels: component:awx_collection, community

#14153 Hop node AWX Collection Updates
  awx_collection/plugins/modules/instance.py
  awx_collection/test/awx/test_instance.py
  awx_collection/tests/integration/targets/instance/tasks/main.yml
Labels: component:awx_collection
