Repository ansible/awx, pull requests merged in 2024-08, with the labels that each got.

#15329 Unpin channels-redis
  awx/main/wsrelay.py
  licenses/aioredis.txt
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies

#15426 Only refresh session if updating own password
  awx/api/serializers.py
  awx/main/tests/functional/api/test_user.py
Labels: component:api

#15427 Fix a test in preparation for syncing description
  awx/main/tests/functional/api/test_immutablesharedfields.py
Labels: component:api

#15432 Remove 'AWX' from setting endpoint
  awx/main/conf.py
Labels: component:api

#15434 Bump DAB version manually because bot is on vacation
  requirements/requirements_git.txt
Labels: dependencies

#15379 Unpin django-split-settings
  requirements/README.md
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies, blocked

#15381 Unpin django-guid and update license
  licenses/django-guid.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: dependencies

#15452 Guard around race condition
  awx/main/utils/licensing.py
Labels: component:api

#15456 SSO login should redirect to new UI index
  awx/sso/views.py
Labels: component:api

#15454 Update django-ansible-base version to 2024.8.19
  requirements/requirements_git.txt
Labels: dependencies

#15328 Replace ansiconv with ansi2html
  awx/api/views/__init__.py
  licenses/ansi2html-1.9.2.tar.gz
  licenses/ansi2html.txt
  licenses/ansiconv.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies, blocked

#15440 fix: avoid calling undefined method for anonymous users
  awx/api/views/__init__.py
Labels: component:api

#15445 Make controller specific team and org roles
  awx/main/migrations/_dab_rbac.py
  awx/main/models/rbac.py
  awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
  awx/main/tests/functional/dab_rbac/test_managed_roles.py
  awx/main/tests/functional/dab_rbac/test_translation_layer.py
  awx/main/tests/functional/test_migrations.py
  awx/settings/defaults.py
  requirements/requirements_git.txt
Labels: component:api, dependencies

#15465 Fix 500 error when ordinary user viewed system JTs
  awx/main/access.py
  awx/main/tests/functional/test_rbac_job.py
  awx/main/tests/unit/test_access.py
Labels: type:bug

#15467 Pin DAB to devel again
  requirements/requirements_git.txt
Labels: dependencies

#15470 Rename System Auditor to Controller System Auditor
  awx/api/generics.py
  awx/api/serializers.py
  awx/main/migrations/_dab_rbac.py
  awx/main/models/__init__.py
  awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
Labels: component:api

#15469 Docs: add Communication guide
  README.md
  docs/docsite/rst/administration/index.rst
  docs/docsite/rst/contributor/communication.rst
  docs/docsite/rst/contributor/index.rst
  docs/docsite/rst/contributor/intro.rst
  docs/docsite/rst/contributor/report_issues.rst
  docs/docsite/rst/contributor/work_items.rst
  docs/docsite/rst/quickstart/index.rst
  docs/docsite/rst/release_notes/index.rst
  docs/docsite/rst/rest_api/index.rst
  docs/docsite/rst/upgrade_migration/index.rst
  docs/docsite/rst/userguide/index.rst
Labels: component:docs, community

#15338 Remove archaic monkey patches
  awx/__init__.py
Labels: component:api

#15477 Cherrypick recent docs prs to docs branch
  .github/triage_replies.md
  README.md
  awx_collection/README.md
  awx_collection/plugins/lookup/controller_api.py
  awx_collection/plugins/modules/job_template.py
  awx_collection/tools/roles/template_galaxy/templates/README.md.j2
  docs/auth/ldap.md
  docs/auth/saml.md
  docs/docsite/conf.py
  docs/docsite/rst/administration/configure_awx.rst
  docs/docsite/rst/administration/index.rst
  docs/docsite/rst/common/logos_branding.rst
  docs/docsite/rst/contributor/communication.rst
  docs/docsite/rst/contributor/index.rst
  docs/docsite/rst/contributor/intro.rst
  docs/docsite/rst/contributor/report_issues.rst
  docs/docsite/rst/contributor/work_items.rst
  docs/docsite/rst/quickstart/create_organization.rst
  docs/docsite/rst/quickstart/create_project.rst
  docs/docsite/rst/quickstart/examine_dashboard.rst
  docs/docsite/rst/quickstart/index.rst
  docs/docsite/rst/release_notes/index.rst
  docs/docsite/rst/rest_api/authentication.rst
  docs/docsite/rst/rest_api/index.rst
  docs/docsite/rst/upgrade_migration/index.rst
  docs/docsite/rst/userguide/index.rst
  docs/docsite/rst/userguide/inventories.rst
  docs/docsite/rst/userguide/job_templates.rst
  docs/docsite/rst/userguide/overview.rst
  docs/docsite/rst/userguide/rbac.rst
  docs/tasks.md
  tools/scripts/post_webhook.py
Labels: component:docs, component:awx_collection, community

#15447 Catch harakiri graceful signal in middlware and log debug info
  awx/settings/defaults.py
  tools/ansible/roles/dockerfile/files/uwsgi.ini
Labels: component:api

#15479 Fallback to use subscription cred for analytic upload
  awx/api/views/analytics.py
  awx/main/analytics/core.py
  awx/main/tests/functional/analytics/test_core.py
  awx/main/tests/functional/api/test_analytics.py
Labels: component:api

#15457 Fix SAMLAuth backend to correctly return social auth pipeline results
  awx/sso/backends.py
Labels: component:api

#15480 Remove references to IRC & Google Groups
  .github/triage_replies.md
  CONTRIBUTING.md
  ISSUES.md
  README.md
Labels: community
