Repository ansible/awx, pull requests merged in 2024-12, with the labels that each got.

#15677 Fix missing dependencies due to extras `-` vs `_`
  requirements/requirements_git.txt
Labels: dependencies

#15669 Add the Sphinx notfound page extension
  docs/docsite/conf.py
  docs/docsite/requirements.in
  docs/docsite/requirements.txt
  docs/docsite/rst/404.rst
Labels: component:docs, community

#15681 use subproject url prefix
  docs/docsite/conf.py
  docs/docsite/rst/404.rst
Labels: component:docs, community

#15660 feat: enable django flags support
  awx/settings/defaults.py
  licenses/django-flags.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies, community

#15679 Fix receptor work unit release after completion
  awx/main/tasks/receptor.py
Labels: component:api

#15683 fix: reset state before evaluating named urls
  awx/main/middleware.py
  awx/main/tests/functional/test_named_url.py
Labels: component:api, community

#15682 Update defaults.py receptor typo
  awx/settings/defaults.py
Labels: component:api, community

#15688 Create a new pytest folder for live system testing with normal services
  .github/workflows/ci.yml
  Makefile
  awx/main/tests/README.md
  awx/main/tests/live/pytest.ini
  awx/main/tests/live/pytest_django_config.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/test_demo_data.py
  tools/docker-compose/ansible/smoke-test.yml
Labels: component:api

#15691 Fix missing exception catch in `create_partition`
  awx/main/tests/live/tests/test_partitions.py
  awx/main/utils/common.py
Labels: component:api

#15690 Fix misused project cache identifier
  awx/main/models/projects.py
  awx/main/tasks/jobs.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/projects/test_requirements.py
Labels: component:api

#15697 bump sqlparse to meet DAB requirement
  requirements/requirements.txt
Labels: dependencies

#15675 Use runtime log utility moved to DAB
  awx/main/dispatch/pool.py
  awx/main/dispatch/worker/base.py
  awx/main/tasks/facts.py
  awx/main/utils/common.py
Labels: component:api

#15696 Do not fast forward rrule if count is set
  awx/main/models/schedules.py
  awx/main/tests/unit/utils/test_schedule_fast_forward.py
Labels: component:api

#15658 Pull the correct collection plugin for the product
  awx/main/apps.py
  awx/main/models/inventory.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/main/utils/common.py
Labels: component:api

#15701 AAP-36536 Send job_lifecycle logs to external loggers
  awx/main/conf.py
  awx/main/models/unified_jobs.py
  awx/main/utils/formatters.py
  awx/settings/defaults.py
  tools/docker-compose/docs/logstash.md
Labels: component:api

#15413 Min value should be Decimal
  awx/main/models/ha.py
Labels: component:api

#15714 Fix test warnings that escaped somehow
  awx/main/tests/functional/models/test_workflow.py
  awx/main/tests/unit/utils/test_common.py
Labels: component:api

#15716 Cleanup in-memory data from test that randomly causes other failures
  awx/main/tests/functional/test_inventory_source_migration.py
Labels: component:api

#15715 AAP-36604 (analytics) Thousands of zombie/orphaned Slow/Stuck DB queries in controller querying active host count
  awx/main/tasks/host_metrics.py
Labels: component:api, community

#15718 Move cred type unite tests to awx-plugins
  awx/main/tests/unit/test_tasks.py
Labels: component:api

#15723 Move RBAC functional tests into folder
  awx/main/tests/functional/rbac/test_rbac_api.py
  awx/main/tests/functional/rbac/test_rbac_credential.py
  awx/main/tests/functional/rbac/test_rbac_execution_environment.py
  awx/main/tests/functional/rbac/test_rbac_instance_groups.py
  awx/main/tests/functional/rbac/test_rbac_inventory.py
  awx/main/tests/functional/rbac/test_rbac_job.py
  awx/main/tests/functional/rbac/test_rbac_job_start.py
  awx/main/tests/functional/rbac/test_rbac_job_templates.py
  awx/main/tests/functional/rbac/test_rbac_label.py
  awx/main/tests/functional/rbac/test_rbac_migration.py
  awx/main/tests/functional/rbac/test_rbac_notifications.py
  awx/main/tests/functional/rbac/test_rbac_organization.py
  awx/main/tests/functional/rbac/test_rbac_project.py
  awx/main/tests/functional/rbac/test_rbac_role.py
  awx/main/tests/functional/rbac/test_rbac_team.py
  awx/main/tests/functional/rbac/test_rbac_user.py
  awx/main/tests/functional/rbac/test_rbac_workflow.py
Labels: component:api
