Repository ansible/awx, pull requests merged in 2024-09, with the labels that each got.

#15493 Fix subscription username password setting name
  awx/main/analytics/core.py
  awx/main/tests/functional/analytics/test_core.py
Labels: component:api

#15490 Translate new RBAC to old RBAC
  awx/main/models/rbac.py
  awx/main/tests/functional/dab_rbac/test_translation_layer_new_to_old.py
Labels: component:api

#15496 Fix analytic ship
  awx/main/analytics/core.py
  awx/main/tests/functional/analytics/test_core.py
Labels: component:api

#15497 Hide AUTOMATION_ANALYTICS_LAST_GATHER
  awx/main/conf.py
Labels: component:api

#15501 Removes collection of unpartitioned_events table
  awx/main/analytics/collectors.py
Labels: component:api, community

#15491 Register any discovered CredentialType after migration
  awx/main/apps.py
  awx/main/management/commands/setup_managed_credential_types.py
  awx/main/models/credential.py
  awx/main/tests/functional/api/test_credential.py
  awx/main/tests/functional/test_apps.py
  awx/main/tests/functional/test_credential.py
  awx/main/tests/unit/models/test_credential.py
  awx/main/utils/common.py
  awx/main/utils/migration.py
Labels: component:api

#15495 fix: avoid race conditions when removing multiple instance
  awx/api/views/mixin.py
  awx/api/views/organization.py
Labels: component:api, community

#15506 Add OPTIONAL_UI_URL_PREFIX
  awx/main/models/ad_hoc_commands.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/projects.py
  awx/settings/defaults.py
Labels: component:api

#15441 Replace `pkg_resources` with `importlib.metadata`
  awx/__init__.py
  awx/main/db/profiled_pg/base.py
  awx/main/models/credential.py
  awx/main/utils/common.py
  awxkit/awxkit/cli/client.py
  docs/docsite/rst/rest_api/_swagger/swagger.py
  tools/scripts/firehose.py
Labels: component:api, component:docs, component:cli

#15518 fix: change to url in platform ui
  awx/main/models/jobs.py
Labels: component:api, community

#15517 Fix instance UI url
  awx/main/management/commands/disable_instance.py
Labels: component:api

#15508 Validate org-user membership from gateway
  awx/main/models/credential.py
  awx/main/models/execution_environments.py
Labels: component:api

#15522 fix workflow job url
  awx/main/models/workflow.py
Labels: component:api, community

#15529 update remaining urls for new UI
  awx/main/models/workflow.py
Labels: component:api, community

#15500 Remove ML remnants from docs
  .github/triage_replies.md
Labels: community

#15505 Plugin removals for docs
  docs/docsite/rst/administration/multi-creds-assignment.rst
  docs/docsite/rst/common/images/credentials-create-aws-secret-credential.png
  docs/docsite/rst/common/images/credentials-create-azure-kms-credential.png
  docs/docsite/rst/common/images/credentials-create-centrify-vault-credential.png
  docs/docsite/rst/common/images/credentials-create-cyberark-ccp-credential.png
  docs/docsite/rst/common/images/credentials-create-cyberark-conjur-credential.png
  docs/docsite/rst/common/images/credentials-create-hashicorp-kv-credential.png
  docs/docsite/rst/common/images/credentials-create-hashicorp-ssh-credential.png
  docs/docsite/rst/common/images/credentials-create-thycotic-devops-credential.png
  docs/docsite/rst/common/images/credentials-create-thycotic-server-credential.png
  docs/docsite/rst/common/images/credentials-link-credential-prompt.png
  docs/docsite/rst/common/images/credentials-link-metadata-prompt.png
  docs/docsite/rst/common/images/credentials-link-metadata-test-error.png
  docs/docsite/rst/common/images/credentials-machine-test-hashicorp-metadata.png
  docs/docsite/rst/common/images/inventories-create-source-AWS-example.png
  docs/docsite/rst/common/images/inventories-create-source-GCE-example.png
  docs/docsite/rst/common/images/inventories-create-source-azurerm-example.png
  docs/docsite/rst/common/images/inventories-create-source-insights-example.png
  docs/docsite/rst/common/images/inventories-create-source-ocpvirt-example.png
  docs/docsite/rst/common/images/inventories-create-source-openstack-example.png
  docs/docsite/rst/common/images/inventories-create-source-rhaap-example.png
  docs/docsite/rst/common/images/inventories-create-source-rhsat6-example.png
  docs/docsite/rst/common/images/inventories-create-source-rhv-example.png
  docs/docsite/rst/common/images/inventories-create-source-terraform-example.png
  docs/docsite/rst/common/images/inventories-create-source-vmware-example.png
  docs/docsite/rst/common/images/key-mgmt-button.png
  docs/docsite/rst/userguide/credential_plugins.rst
  docs/docsite/rst/userguide/credentials.rst
  docs/docsite/rst/userguide/index.rst
  docs/docsite/rst/userguide/insights.rst
  docs/docsite/rst/userguide/inventories.rst
  docs/docsite/rst/userguide/inventory_plugins_templates.rst
Labels: component:docs

#15536 fix: maintain order of insertions into m2m relationship tables
  awx/main/fields.py
Labels: component:api, community

#15502 Docs: change Getting started EE guide reference to point to the relevant location
  docs/docsite/rst/userguide/execution_environments.rst
Labels: component:docs, community

#15533 Make analytics job ts settings hidden
  awx/main/conf.py
Labels: component:api

#15525 🧪 Publish awxkit's coverage to Codecov
  Makefile
  awxkit/tox.ini
Labels: component:cli

#15489 Enable service redirect auth and reverse-sync from DAB
  awx/settings/defaults.py
Labels: component:api

#15558 Filter out ANSIBLE_BASE_ from job env var
  awx/main/tasks/jobs.py
Labels: component:api
