Repository ansible/awx, pull requests merged in 2024-05, with the labels that each got.

#15143 Expose websockets on api prefix v2
  awx/main/routing.py
  tools/docker-compose/ansible/roles/sources/defaults/main.yml
  tools/docker-compose/ansible/roles/sources/templates/local_settings.py.j2
  tools/docker-compose/ansible/roles/sources/templates/nginx.locations.conf.j2
Labels: component:api, community

#15135 Clean up settings file
  awx/settings/defaults.py
Labels: component:api

#15174 Skip 3 expensive calls for jobs saving in 'waiting' status on UnifiedJob
  awx/main/models/unified_jobs.py
Labels: component:api

#15148 Support Django logout redirects
  awx/api/generics.py
  awx/settings/defaults.py
Labels: component:api, community

#15190 add skip authorization option to collection application module
  awx_collection/plugins/modules/application.py
Labels: component:awx_collection, community

#15196 Fix success_url_allowed_hosts set instantiation
  awx/api/generics.py
  awx/settings/defaults.py
Labels: component:api, community

#15150 Added docs for new RBAC changes
  docs/docsite/rst/common/images/rbac_jt_team_access.png
  docs/docsite/rst/common/images/rbac_jt_user_access.png
  docs/docsite/rst/common/images/rbac_team_access_add-roles-review.png
  docs/docsite/rst/common/images/rbac_team_access_add-roles-success.png
  docs/docsite/rst/common/images/rbac_team_access_add-roles.png
  docs/docsite/rst/common/images/rbac_team_access_apply-roles.png
  docs/docsite/rst/common/images/rbac_user_access_add-roles-review.png
  docs/docsite/rst/common/images/rbac_user_access_add-roles.png
  docs/docsite/rst/common/images/rbac_user_access_apply-roles.png
  docs/docsite/rst/userguide/index.rst
  docs/docsite/rst/userguide/rbac.rst
  docs/docsite/rst/userguide/security.rst
Labels: component:docs

#15191 Allow wsrelay to fail without FATAL
  awx/main/management/commands/run_wsrelay.py
  awx/main/wsrelay.py
  tools/ansible/roles/dockerfile/templates/supervisor_task.conf.j2
Labels: component:api

#15203 Update a few dev requirements
  awx/conf/tests/unit/test_settings.py
  awx/main/tests/functional/api/test_create_attach_views.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/api/test_rbac_displays.py
  awx/main/tests/functional/commands/test_commands.py
  awx/main/tests/functional/models/test_context_managers.py
  awx/main/tests/functional/task_management/test_rampart_groups.py
  awx/main/tests/functional/task_management/test_scheduler.py
  awx/main/tests/unit/api/serializers/test_job_template_serializers.py
  awx/main/tests/unit/api/serializers/test_workflow_serializers.py
  awx/main/tests/unit/api/test_generics.py
  awx/main/tests/unit/api/test_views.py
  awx/main/tests/unit/models/test_workflow_unit.py
  awx/main/tests/unit/test_tasks.py
  awx/main/tests/unit/utils/test_reload.py
  awx/sso/tests/unit/test_ldap.py
  requirements/requirements_dev.txt
Labels: component:api, dependencies

#15208 Fix up ansible-test sanity checks due to ansible 2.17 release
  awx_collection/plugins/module_utils/controller_api.py
  awx_collection/plugins/modules/ad_hoc_command.py
  awx_collection/plugins/modules/import.py
  awx_collection/test/awx/conftest.py
  awx_collection/tests/sanity/ignore-2.17.txt
Labels: component:awx_collection

#15170 awxkit: replace deprecated locale.format() with locale.format_string() to fix human output on Python 3.12
  awxkit/awxkit/cli/format.py
Labels: component:cli, community

#15149 Mention in the docs that you can skip `make docker-compose-build`
  tools/docker-compose/README.md
Labels: community

#15222 Update test so that DAB change can merge
  awx/main/tests/functional/test_rbac_api.py
Labels: component:api

#15223 Include Kube credentials in the inventory source picker
  awx/ui/src/components/Lookup/CredentialLookup.js
  awx/ui/src/screens/Inventory/shared/InventorySourceSubForms/SCMSubForm.js
Labels: component:ui

#15114 Make named url work with optional url prefix
  awx/main/middleware.py
  awx/main/tests/functional/test_named_url.py
Labels: component:api

#15237 Use settings fixture in tests
  awx/main/tests/functional/test_named_url.py
Labels: component:api

#15238 Add check_instance_ready management command
  awx/main/management/commands/check_instance_ready.py
Labels: component:api
