Repository ansible/awx, pull requests merged in 2025-01, with the labels that each got.

#15705 General upgrade of dependencies
  awx/main/dispatch/__init__.py
  licenses/aiohappyeyeballs.txt
  licenses/annotated-types.txt
  licenses/azure-common.txt
  licenses/backports-tarfile.txt
  licenses/backports_tarfile-1.2.0.tar.gz
  licenses/docutils.txt
  licenses/durationpy.txt
  licenses/importlib-resources.txt
  licenses/importlib_resources-6.4.5.tar.gz
  licenses/jwcrypto-1.5.6.tar.gz
  licenses/propcache.txt
  licenses/psycopg-3.2.3.tar.gz
  licenses/pydantic-core.txt
  licenses/pydantic.txt
  licenses/uwsgi-2.0.24.tar.gz
  licenses/uwsgi-2.0.28.tar.gz
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies

#15726 Fix API documentation rendering (#15116)
  awx/api/generics.py
  awx/api/swagger.py
  awx/settings/defaults.py
Labels: component:api, community

#15739 Delete test file that should have been removed and fix checks
  awx/main/tests/data/inventory/plugins/insights/env.json
  awx/main/tests/functional/rbac/test_rbac_migration.py
Labels: component:api

#15710 Add input_inventories to ordered_associations
  awx_collection/plugins/module_utils/controller_api.py
Labels: component:awx_collection, community

#15733 Add test to ensure bootstrap reqs are good
  awx/main/tests/functional/test_python_requirements.py
Labels: component:api

#15734 Add client_secret and client_id to credential_input_fields
  awxkit/awxkit/api/pages/credentials.py
Labels: component:cli

#15676 Use advisory_lock from DAB
  awx/main/analytics/core.py
  awx/main/management/commands/deprovision_instance.py
  awx/main/management/commands/inventory_import.py
  awx/main/management/commands/register_queue.py
  awx/main/management/commands/unregister_queue.py
  awx/main/managers.py
  awx/main/models/credential.py
  awx/main/scheduler/task_manager.py
  awx/main/tasks/host_metrics.py
  awx/main/tasks/receptor.py
  awx/main/tasks/system.py
  awx/main/utils/pglock.py
  licenses/django-pglocks.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies

#15749 Add changelog to awx collection
  awx_collection/CHANGELOG.md
Labels: component:awx_collection

#15685 Add new credential entry point discovery
  awx/main/apps.py
  awx/main/models/credential.py
  awx/main/tests/conftest.py
  awx/main/tests/functional/migrations/test_inventory_source_migration.py
  awx/main/tests/live/tests/conftest.py
  awx_collection/test/awx/conftest.py
  awx_collection/tests/integration/targets/credential/tasks/main.yml
  awx_collection/tests/integration/targets/credential_input_source/tasks/main.yml
  awx_collection/tests/integration/targets/inventory/tasks/main.yml
  awx_collection/tests/integration/targets/inventory_source/tasks/main.yml
  awx_collection/tests/integration/targets/workflow_job_template/tasks/main.yml
  requirements/requirements_git.txt
Labels: component:api, component:awx_collection, dependencies

#15742 feat: update insights action plugin to handle oauth
  awx/playbooks/action_plugins/insights.py
  awx/playbooks/project_update.yml
Labels: component:api, community

#15747 feat: support insights service account credentials for project update
  awx/main/tasks/jobs.py
  awx/settings/defaults.py
Labels: component:api, community

#15757 fix: invalid f-string and oidc url for insights plugin
  awx/playbooks/action_plugins/insights.py
  awx/playbooks/project_update.yml
Labels: component:api, community

#15754 Create test for using manual & file projects
  awx/main/tests/data/projects/README.md
  awx/main/tests/data/projects/debug/debug.yml
  awx/main/tests/data/projects/host_query/galaxy.yml
  awx/main/tests/data/projects/host_query/meta/event_query.yml
  awx/main/tests/data/projects/host_query/plugins/modules/example.py
  awx/main/tests/data/projects/role_requirement/meta/main.yml
  awx/main/tests/data/projects/role_requirement/tasks/main.yml
  awx/main/tests/data/projects/test_host_query/collections/requirements.yml
  awx/main/tests/data/projects/test_host_query/run_task.yml
  awx/main/tests/data/projects/with_requirements/roles/requirements.yml
  awx/main/tests/data/projects/with_requirements/use_requirement.yml
  awx/main/tests/factories/fixtures.py
  awx/main/tests/functional/api/test_unified_job_template.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/test_projects.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/projects/conftest.py
  awx/main/tests/live/tests/projects/test_file_projects.py
  awx/main/tests/live/tests/projects/test_indirect_host_counting.py
  awx/main/tests/live/tests/projects/test_manual_project.py
  awx/main/tests/live/tests/projects/test_requirements.py
Labels: component:api

#15759 Establish a feature flag for indirect host counting feature
  awx/settings/defaults.py
Labels: component:api

#15765 AAP-35805 cleanup EE test
  awx/main/tasks/receptor.py
  awx/main/tasks/system.py
  awx/main/tests/functional/test_tasks.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/test_cleanup_task.py
Labels: component:api

#15774 AAP-37282 Add parse JQ data and test it for a `job` object in isolation
  awx/main/tasks/host_indirect.py
  awx/main/tests/data/projects/host_query/meta/event_query.yml
  awx/main/tests/data/projects/host_query/plugins/modules/example.py
  awx/main/tests/live/tests/projects/test_indirect_host_counting.py
  licenses/jq.txt
  requirements/requirements.in
  requirements/requirements.txt
Labels: component:api, dependencies

#15761 Successfully test collection of `event_query.yml` data
  awx/main/tasks/jobs.py
  awx/main/tests/live/tests/projects/test_indirect_host_counting.py
  awx/playbooks/library/indirect_instance_count.py
  awx/settings/development.py
Labels: component:api

#15753 Move some more tests out of root functional folder
  awx/main/tests/functional/api/test_api_generics.py
  awx/main/tests/functional/models/test_db_credential.py
  awx/main/tests/functional/models/test_ha.py
  awx/main/tests/functional/rbac/test_rbac_labels.py
  awx/main/tests/functional/tasks/test_tasks_jobs.py
  awx/main/tests/functional/tasks/test_tasks_system.py
  awx/main/tests/functional/test_linkstate.py
Labels: component:api

#15785 Contract changes for the event_query collection callback plugin
  awx/main/tests/data/projects/host_query/extensions/audit/event_query.yml
  awx/playbooks/library/indirect_instance_count.py
Labels: component:api

#15787 feat: remaining schema changes for indirect host audits
  awx/main/migrations/0202_indirectmanagednodeaudit.py
  awx/main/migrations/0203_job_event_queries_processed.py
  awx/main/models/indirect_managed_node_audit.py
  awx/main/models/jobs.py
  awx/main/tasks/callback.py
Labels: component:api, community

#15784 Re-organize test file and move artifacts processing logic to callback
  awx/main/tasks/callback.py
  awx/main/tasks/jobs.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/projects/conftest.py
  awx/main/tests/live/tests/test_indirect_host_counting.py
Labels: component:api

#15789 fix: compatibility with black v25+
  awx/main/fields.py
  awx/main/migrations/0050_v340_drop_celery_tables.py
  awx/main/tests/functional/api/test_unified_jobs_stdout.py
  awx/main/tests/unit/utils/test_filters.py
  awxkit/awxkit/utils/__init__.py
Labels: component:api, component:cli, community

#15770 Address Lookup Plugins AttributeError
  awx/main/models/credential.py
Labels: component:api

#15790 AAP-37282 Connect host audit model to jq logic via new task
  awx/main/dispatch/worker/callback.py
  awx/main/tasks/host_indirect.py
  awx/main/tasks/jobs.py
  awx/main/tasks/system.py
  awx/main/tests/live/tests/test_indirect_host_counting.py
Labels: component:api

#15792 Add unit tests for indirect host counting
  awx/main/tests/functional/tasks/test_host_indirect.py
Labels: component:api

#15782 Removing some (but not all) dead pytest fixtures
  awx/main/tests/conftest.py
  awx/main/tests/functional/api/test_deprecated_credential_assignment.py
  awx/main/tests/functional/api/test_inventory.py
  awx/main/tests/functional/api/test_job_runtime_params.py
  awx/main/tests/functional/conftest.py
  awx/main/tests/functional/tasks/test_tasks_jobs.py
Labels: component:api

#15781 Put duplicate plugin location in error message
  awx/main/models/credential.py
Labels: component:api

#15794 Do not get django flags from database
  awx/settings/defaults.py
Labels: component:api

#15793 Add helper to proxy analytics requests
  awx/main/tests/unit/utils/test_analytics_proxy.py
  awx/main/utils/analytics_proxy.py
Labels: component:api

#15798 AAP-39559 Wait for all event processing to finish, add fallback task
  awx/main/tasks/callback.py
  awx/main/tasks/host_indirect.py
  awx/main/tests/functional/tasks/test_host_indirect.py
  awx/main/tests/unit/tasks/test_host_indirect_unit.py
  awx/settings/defaults.py
Labels: component:api

#15800 feat: cleanup of old indirect host audit records
  awx/main/tasks/host_indirect.py
  awx/main/tests/functional/tasks/test_host_indirect.py
  awx/main/tests/unit/tasks/test_host_indirect_unit.py
  awx/settings/defaults.py
Labels: component:api, community

#15801 By default, do not count indirect hosts
  awx/main/migrations/0201_indirect_managed_node_audit.py
  awx/main/models/jobs.py
  awx/main/tasks/callback.py
  awx/main/tests/functional/tasks/test_host_indirect.py
Labels: component:api
