Repository ansible/awx, pull requests merged in 2025-03, with the labels that each got.

#15841 update: use singular form ANSIBLE_COLLECTIONS_PATH
  awx/main/tasks/jobs.py
  awx/main/tests/functional/test_inventory_source_injectors.py
  awx/playbooks/project_update.yml
Labels: component:api, community

#15875 Fix test flake due to change enumeration
  awx/main/tests/functional/models/test_events.py
Labels: component:api

#15702 [AAP-34936] Manage Django Settings with Dynaconf
  .coveragerc
  awx/__init__.py
  awx/api/generics.py
  awx/main/tests/unit/test_settings.py
  awx/settings/__init__.py
  awx/settings/application_name.py
  awx/settings/defaults.py
  awx/settings/development.py
  awx/settings/development_defaults.py
  awx/settings/development_kube.py
  awx/settings/development_quiet.py
  awx/settings/functions.py
  awx/settings/kube_defaults.py
  awx/settings/production.py
  awx/settings/production_defaults.py
  awx/settings/quiet_defaults.py
  awx/urls.py
  licenses/django-split-settings.txt
  licenses/dynaconf.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
  tools/docker-compose/ansible/roles/sources/templates/docker-compose.yml.j2
Labels: component:api, dependencies

#15818 Few minor changes in the lookup description
  awx_collection/plugins/lookup/schedule_rrule.py
Labels: component:awx_collection, community

#15887 Pin drf-yasg to make api-test pass
  requirements/requirements_dev.txt
Labels: dependencies

#15869 feat: awx community bug scrub script
  tools/community-bugscrub/README.md
  tools/community-bugscrub/generate-sheet.py
  tools/community-bugscrub/requirements.txt
Labels: community

#15871 Another approach to test race condition
  awx/main/tests/live/tests/test_indirect_host_counting.py
Labels: component:api

#15866 Pass in private_data_dir when project update is on K8S
  awx/api/views/analytics.py
  awx/main/analytics/core.py
  awx/main/models/credential.py
  awx/main/tasks/jobs.py
  awx/main/utils/analytics_proxy.py
Labels: component:api

#15580 BugFix - awx_collection - lookup_organization failed when teams and resources are not in the same org
  awx_collection/plugins/modules/role.py
  awx_collection/tests/integration/targets/role/tasks/main.yml
Labels: component:awx_collection, community

#15863 Add opa_query_path to Organization/Inventory/JobTemplate
  awx/main/migrations/0197_add_opa_query_path.py
  awx/main/migrations/0198_delete_profile.py
  awx/main/migrations/0199_remove_sso_app_content.py
  awx/main/migrations/0200_alter_inventorysource_source_and_more.py
  awx/main/migrations/0201_alter_oauth2application_unique_together_and_more.py
  awx/main/migrations/0202_delete_token_cleanup_job.py
  awx/main/models/inventory.py
  awx/main/models/jobs.py
  awx/main/models/mixins.py
  awx/main/models/organization.py
Labels: component:api

#15893 Aap 41580 indirect host count wildcard query
  awx/main/tasks/host_indirect.py
  awx/main/tests/functional/tasks/test_host_indirect.py
Labels: component:api

#15900 Add notice of paused releases
  README.md
Labels: community

#15908 [dispatcherd] Dispatcher socket-based `--status` demo working
  awx/main/apps.py
  awx/settings/defaults.py
Labels: component:api

#15911 Fix Task Decorator to Work With and Without Feature Flag (AAP-41775)
  awx/main/dispatch/publish.py
  awx/main/tasks/system.py
  awx/settings/defaults.py
Labels: component:api, community
