Repository ansible/awx, pull requests merged in 2025-06, with the labels that each got.

#16006 Remove FEATURE_POLICY_AS_CODE_ENABLED flag
  awx/api/serializers.py
  awx/main/conf.py
  awx/main/tasks/policy.py
  awx/main/tests/functional/test_policy.py
  awx/settings/defaults.py
  awx_collection/test/awx/test_completeness.py
Labels: component:api, component:awx_collection, community

#16008 Combine migration numbers 201-205 into 201 for ease of management
  awx/main/migrations/0201_delete_profile.py
  awx/main/migrations/0201_squashed_deletions.py
  awx/main/migrations/0202_remove_sso_app_content.py
  awx/main/migrations/0203_alter_inventorysource_source_and_more.py
  awx/main/migrations/0204_alter_oauth2application_unique_together_and_more.py
  awx/main/migrations/0205_delete_token_cleanup_job.py
Labels: component:api

#16015 Combine Django bump with other fixes to github checks
  Makefile
  pytest.ini
  requirements/requirements.in
  requirements/requirements.txt
  tools/docker-compose/start_tests.sh
Labels: dependencies

#16027 Fix failing api-test
  Makefile
  awx/main/tests/data/inventory/plugins/controller/env.json
Labels: component:api

#16028 Fix collection whitespace issue
  awx_collection/plugins/module_utils/controller_api.py
Labels: component:awx_collection

#16010 Add placeholder migration
  awx/main/migrations/0201_create_managed_creds.py
  awx/main/migrations/0202_squashed_deletions.py
Labels: component:api

#15962 Do not apply ANSIBLE_STANDARD_SETTINGS_FILES to job environment variables
  awx/main/tasks/jobs.py
Labels: component:api

#16035 AAP-47495 Hide CSRF_TRUSTED_ORIGINS
  awx/main/conf.py
Labels: component:api

#16033 [AAP-48070] Remove ALLOW_LOCAL_RESOURCE_MANAGEMENT setting and enable local resource management
  awx/api/views/__init__.py
  awx/api/views/organization.py
  awx/main/tests/functional/api/test_immutablesharedfields.py
  awx/settings/defaults.py
Labels: component:api
