Repository ansible/awx, pull requests merged in 2025-02, with the labels that each got.

#15786 [AAP-39138] - Add DAB Feature Flag common API
  awx/main/tests/functional/dab_feature_flags/test_feature_flags_api.py
  awx/settings/defaults.py
  requirements/requirements_git.txt
Labels: component:api, dependencies, community

#15805 prevent multiple tasks from processing the same job events, prevent p…
  awx/main/tasks/host_indirect.py
  awx/main/tests/functional/tasks/test_host_indirect.py
Labels: component:api, community

#15809 Fix rrule fast forwarding across DST boundaries
  awx/main/models/schedules.py
  awx/main/tests/unit/utils/test_schedule_fast_forward.py
Labels: component:api

#15717 Fix rsyslog permission error in github ubuntu tests from apparmor
  .github/actions/run_awx_devel/action.yml
  awx/main/tests/live/tests/test_devel_image.py
Labels: component:api

#15815 fix: rely on resolved_action instead of task, adapt to proposed query…
  awx/main/tasks/host_indirect.py
  awx/main/tests/data/projects/host_query/extensions/audit/event_query.yml
  awx/main/tests/functional/tasks/test_host_indirect.py
  awx/main/tests/live/tests/test_indirect_host_counting.py
Labels: component:api, community

#15780 Make awx/main/tests/live dramatically faster
  awx/main/dispatch/publish.py
  awx/main/tests/settings_for_test.py
  awx/main/tests/unit/test_settings.py
  awx/settings/defaults.py
Labels: component:api

#15830 Update feature flag list test
  awx/main/tests/functional/dab_feature_flags/test_feature_flags_api.py
Labels: component:api

#15831 Add ability to provide auth to private repo for requirements_git in container build
  .github/actions/awx_devel_image/action.yml
  .github/actions/run_awx_devel/action.yml
  .github/workflows/ci.yml
  .github/workflows/devel_images.yml
  .gitignore
  MANIFEST.in
  requirements/requirements_git.credentials.txt
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: dependencies

#15839 Fix: do not use current apps in migrations
  awx/main/migrations/_OrgAdmin_to_use_ig.py
Labels: component:api

#15812 Ship analytics data using service account token
  awx/api/views/analytics.py
  awx/main/analytics/core.py
  awx/main/utils/analytics_proxy.py
Labels: component:api

#15807 feat: 38589 GitHub App Authentication
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
Labels: component:api, dependencies, community

#15850 Add Github dep for new cred support if used
  awx/main/tests/functional/test_credential.py
  licenses/PyGithub.txt
  licenses/PyNaCl.txt
  licenses/pygithub-2.6.0.tar.gz
  licenses/pynacl.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
Labels: component:api, dependencies

#15851 revert change made to allow UI to accept x-access-token, just use htt…
  awx/main/tests/unit/utils/test_common.py
  awx/main/utils/common.py
Labels: component:api, community

#15853 More PyGithub dep and license housekeeping
  licenses/pygithub-2.6.0.tar.gz
  licenses/pygithub-2.6.1.tar.gz
  licenses/pynacl.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_git.txt
Labels: dependencies

#15802 Feature indirect host counting
  awx/main/dispatch/worker/callback.py
  awx/main/migrations/0196_indirect_managed_node_audit.py
  awx/main/migrations/0197_delete_profile.py
  awx/main/migrations/0198_remove_sso_app_content.py
  awx/main/migrations/0199_alter_inventorysource_source_and_more.py
  awx/main/migrations/0200_alter_oauth2application_unique_together_and_more.py
  awx/main/migrations/0201_delete_token_cleanup_job.py
  awx/main/models/event_query.py
  awx/main/models/indirect_managed_node_audit.py
  awx/main/models/jobs.py
  awx/main/tasks/callback.py
  awx/main/tasks/host_indirect.py
  awx/main/tasks/jobs.py
  awx/main/tasks/system.py
  awx/main/tests/data/projects/host_query/extensions/audit/event_query.yml
  awx/main/tests/data/projects/host_query/meta/event_query.yml
  awx/main/tests/data/projects/host_query/plugins/modules/example.py
  awx/main/tests/functional/tasks/test_host_indirect.py
  awx/main/tests/live/tests/conftest.py
  awx/main/tests/live/tests/projects/conftest.py
  awx/main/tests/live/tests/projects/test_indirect_host_counting.py
  awx/main/tests/live/tests/test_indirect_host_counting.py
  awx/main/tests/unit/tasks/test_host_indirect_unit.py
  awx/playbooks/library/indirect_instance_count.py
  awx/settings/defaults.py
  awx/settings/development.py
  licenses/jq.txt
  requirements/requirements.in
  requirements/requirements.txt
  requirements/requirements_dev.txt
Labels: component:api, dependencies

#15678 cli: set non-zero return code for `canceled` status
  awxkit/awxkit/cli/custom.py
Labels: component:cli, community

#15862 Remove requirements_git.credentials.txt
  .gitignore
  MANIFEST.in
  requirements/requirements_git.credentials.txt
  tools/ansible/roles/dockerfile/templates/Dockerfile.j2
Labels: dependencies

#15864 fix: audit record name should not be the hostname
  awx/main/tasks/host_indirect.py
  awx/main/tests/data/projects/host_query/extensions/audit/event_query.yml
  awx/main/tests/data/projects/host_query/plugins/modules/example.py
  awx/main/tests/functional/tasks/test_host_indirect.py
  awx/main/tests/live/tests/test_indirect_host_counting.py
Labels: component:api, community
